Massive overhaul to code base to clean up context issues that have been plaguing project, as well as fixing inconscistencies as I went which is helped by the introduction of unit testing.
MAJOR:
- version bump of wovtools to avoid interfering with old projects
- ORIGIN introduced into context so wov-env and related commands work better. No longer will things in production not work because of origin issues and my long-standing confusion of secrets generation is resolved. This was the missing piece.
- wov-env-ops created for standardized context and other params which greatly improves speed for simple commands across all scripts
- changes to config/myconfig format (and naming of files)
- introduced better logging commands of l_, l_error, l_warn, l_verbose and slowly rolling them into scripts
- unit tests created and continue to be built ... needed desperately
- wov-db-connect renamed to wov-db and it assumes db now which will speed up my typing
- a focus on the code and unit tests made it easier to do...
  - many error checks and code fixed
  - many command switches fixed or made more consistent
  - incorporated a way of scribing databases (server vs instance vs Wov Db)

MINOR:
- too many changes to list...

diff --git a/bin/provider-wov-env-aws b/bin/provider-wov-env-aws
--- a/bin/provider-wov-env-aws
+++ b/bin/provider-wov-env-aws
@@ -5,7 +5,11 @@ if [ "${WOV_CLUSTER}" == "" ]; then
   exit 1
 fi
 
-export WOV_cluster_dns_domain=`wov-env --cluster ${WOV_CLUSTER} --var WOV_cluster_dns_domain`
+#export WOV_cluster_dns_domain=`wov-env --cluster ${WOV_CLUSTER} --var WOV_cluster_dns_domain`
+if [ "${WOV_cluster_dns_domain}" == "" ]; then
+  echo "ERROR: provider-wov-env-aws requires variable 'WOV_cluster_dns_domain'."
+  exit 1
+fi
 
 
 # ---------------------------------------------------------------------
@@ -13,13 +17,15 @@ export WOV_cluster_dns_domain=`wov-env --cluster ${WOV_CLUSTER} --var WOV_cluste
 # ---------------------------------------------------------------------
 function fConvertRegionCodeAWS()
 {
+  local retcode=1
   local retval=
   case $1 in
-    va)  retval='us-east-1' ;;
-    iad) retval='us-east-1' ;;
-    *)   printf "\nWARNING: unknown AWS region code of '$1'.\n"
+    va)  retval='us-east-1'; retcode=0 ;;
+    iad) retval='us-east-1'; retcode=0 ;;
+    *)   >&2 printf "WARNING: unknown AWS region code of '$1'.\n"
   esac
   echo "$retval"
+  return $retcode
 }
 
 
@@ -37,5 +43,6 @@ AWS_VPC="$(aws ec2 describe-vpcs --filters "Name=tag:Name,Values=${WOV_CLUSTER}.
 if [ "$?" != "0" ]; then printf "\n\nERROR: failed to connect to AWS to understand VPC.\n\n"; exit 1; fi
 
 export AWS_REGION
+
 export AWS_ZONES
 export AWS_VPC
diff --git a/bin/wov-aws b/bin/wov-aws
--- a/bin/wov-aws
+++ b/bin/wov-aws
@@ -1,46 +1,6 @@
 #!/usr/bin/env bash
 
 # ---------------------------------------------------------------------
-# Import Env
-# ---------------------------------------------------------------------
-wovawsvargs=( "$@" )
-set ""
-. wov-env --provider
-#. <(wov-env --provider --exports)
-. wov-ns-check
-set -- "${wovawsvargs[@]}"
-DOECHO=1
-FOLD=$(tput cols)
-EXIT=1
-
-export WOV_cluster_dns_domain=`wov-env --var WOV_cluster_dns_domain`
-
-
-# TODO: fill this function in, and remove from WIAAS
-#function doCluster()
-#{
-#  RANCLUSTER=1
-#  export CL_REGION="${AWS_REGION}"
-#  export CL_ZONES="${AWS_ZONES}"
-#  export CL_VPC="${AWS_VPC}"
-#}
-
-
-# ---------------------------------------------------------------------
-function fConvertRegionCodeAWS()
-{
-  case $1 in
-    va) cRC='us-east-1' ;;
-    iad) cRC='us-east-1' ;;
-    *)
-      echo
-      echo "***ERROR: unknown AWS region code of '$1'."
-      exit 1
-  esac
-}
-
-
-# ---------------------------------------------------------------------
 # ---------------------------------------------------------------------
 function fDisplayOptions()
 {
@@ -49,6 +9,9 @@ function fDisplayOptions()
 
 usage: `basename $0` [command]
 
+TODO - read the code for now
+
+  convertrc X
   volume-
     describe
     id
@@ -61,21 +24,72 @@ EOF
 
 }
 
+. wov-env-ops fDisplayOptions $* 
+
+# ---------------------------------------------------------------------
+# Import Env
+# ---------------------------------------------------------------------
+. <(wov-env --envs --provider)
+. provider-wov-env-aws
+#wovawsvargs=( "$@" )
+#set ""
+#. <(wov-env --provider)
+##. <(wov-env --provider --exports)
+##. wov-ns-check
+#set -- "${wovawsvargs[@]}"
+
+DOECHO=1
+FOLD=$(tput cols)
+EXIT=1
+
+#export WOV_cluster_dns_domain=`wov-env --var WOV_cluster_dns_domain`
+
+
+# TODO: fill this function in, and remove from WIAAS
+#function doCluster()
+#{
+#  RANCLUSTER=1
+#  export CL_REGION="${AWS_REGION}"
+#  export CL_ZONES="${AWS_ZONES}"
+#  export CL_VPC="${AWS_VPC}"
+#}
+
+
+# NOTE: in provider-wov-env-aws
+# ---------------------------------------------------------------------
+#function fConvertRegionCodeAWS()
+#{
+#  echo "fConvertREgionCodeAWS $1"
+#  case $1 in
+#    va) cRC='us-east-1' ;;
+#    iad) cRC='us-east-1' ;;
+#    *)
+#      echo
+#      echo "***ERROR: unknown AWS region code of '$1'."
+#      exit 1
+#  esac
+#}
+
+
+
 function doVolumeDescribe() 
 {
   local VOLNAME=$1
+  echo "do 1"
   aws ec2 describe-volumes --filter Name="tag:Name",Values=\"${VOLNAME}\" | jq '.Volumes[0]' -r
 }
 
 function doVolumeID() 
 {
   local VOLNAME=$1
+  echo "do 2"
   aws ec2 describe-volumes --filter Name="tag:Name",Values=\"${VOLNAME}\" | jq '.Volumes[0].VolumeId' -r
 }
 
 function doVolumeCheck() 
 {
   local VOLNAME=$1
+  echo "do 3"
   R=$(aws ec2 describe-volumes --filter Name="tag:Name",Values=\"${VOLNAME}\" | jq '.Volumes[0].VolumeId' -r )
   RET=$?
   if [ "${RET}" != "0" ]; then 
@@ -140,33 +154,31 @@ function doVolumeEnsure()
 # ---------------------------------------------------------------------
 # Handle Modifying Params
 # ---------------------------------------------------------------------
-while [[ $1 =~ ^- ]]; do
-
-  if [ "$1" == "-q" ]; then
-    shift
-    DOECHO=0
-
-  elif [ "$1" == "-v" ]; then
-    shift
-    DOECHO=2
-
-  elif [ "$1" == "-h" ] || [ "$1" == "--help" ]; then
-    fDisplayOptions
-    exit 0
-
-  else
-    echo
-    echo "***ERROR: unknown option '$1'."
-    echo
-    fDisplayOptions
-    exit 1
-  fi
-done
+#while [[ $1 =~ ^- ]]; do
+#
+#  if [ "$1" == "--convertrc" ]; then
+#    shift
+#    fConvertRegionCodeAWS $1
+#    r=$?
+#    shift
+#    if [ $r -ne 0 ]; then exit $r; fi
+#
+#  else
+#    echo
+#    echo "***ERROR: unknown option '$1'."
+#    echo
+#    fDisplayOptions
+#    exit 1
+#  fi
+#done
 
 COMMAND=$1
 shift
 
-if   [ "${COMMAND}" == "volume-id" ]; then
+if     [ "${COMMAND}" == "convertrc" ]; then
+  fConvertRegionCodeAWS $*
+  EXIT=$?
+elif   [ "${COMMAND}" == "volume-id" ]; then
   doVolumeID       $*
   EXIT=$?
 elif [ "${COMMAND}" == "volume-describe" ]; then
@@ -190,8 +202,8 @@ elif [ "${COMMAND}" == "cluster" ]; then
   exit 1
 
 else
-  printf "\n\nERROR: unknown command \"${COMMAND}\".\n\n" 1>&2
+  printf "ERROR: unknown command \"${COMMAND}\".\n" 1>&2
 fi
 
 
-return ${EXIT}
+exit ${EXIT}
diff --git a/bin/wov-env b/bin/wov-env
--- a/bin/wov-env
+++ b/bin/wov-env
@@ -1,21 +1,4 @@
 #!/usr/bin/env bash
-FOLD=$(tput cols)
-CLUSTER=
-ECHOMODE=0
-DOALL=1
-SED=`which gsed`
-HAS_SECRET=0
-PROVIDERVARS=()
-RANCLUSTER=0
-
-
-# Default variables to echo
-ECHOVARS=( 'WOV_VERSION' 'WOV_ME' 'WOV_BASEDIR' 'WOV_ARCHIVEREPOSITORY' 'WOV_ARCHIVEENV' 'WOV_CONTEXT' \
-           'WOV_CLUSTER' 'WOV_NS' 'WOV_CLTYPE' 'WOV_PROVIDER' 'WOV_REGION' 'WOV_FLAVOR' 'WOV_PROJECT' \
-           'WOV_KSTAGE' 'WOV_GSTAGE' 'WOV_STAGE' 'WOV_PVER' 'WOV_SVER' 'WOV_USERNAME' 'WOV_USEREMAIL' \
-           'WOV_PROJECT' 'WOV_PROJECTTYPE' 'WOV_PROJECTTITLE' 'WOV_PROJECTDESCRIPTION' 'WOV_KPROJECT' \
-           'WOV_WPROJECT' )
-#CLUSTERVARS=( 'CL_REGION' 'CL_ZONES' 'CL_VPC' )
 
 
 function fWovEnvDisplayOptions()
@@ -28,7 +11,7 @@ usage: `basename $0` [options]
 Export the context as variables for scripts or export specific variables. 
 
 This pulls config data from:
- - Wovtools project config (./wovtools/config.json)
+ - Wovtools project config (./${WOV_CONFIGFILE_MAIN})
  - Wovtools global config ($HOME/.wovtools)
  - K8s config
  - git
@@ -45,7 +28,7 @@ Command Options:
   --vh-label    : vh label in DockerHub repo
  
   Basic Environment Configuration:
-  -g/--global X : target output for another context (not from Kubernetes)  NOTE: must be 1st param
+#  -g/--global X : target output for another context (not from Kubernetes)  NOTE: must be 1st param
   -e            : echo the output with newlines
   -E            : echo the output on one line (bash executable)
   -p/--provider : run cluster config as well (queries cloud provider via wov-env-PROVIDER)
@@ -69,9 +52,14 @@ Command Options:
 
   Kubernetes Generation 
     NOTE: These use Make to run a script... not good... need better way to run
-  -c/--cluster X  : set the cluster to X (required for --cm/--se)
-  --cm X          : only config used by plugin, (sep lines)
-  --se X          : only secrets used by plugin, (sep lines)
+  # --origin X       : read from file
+  #--context X      : set the context (cluster and namespace)
+  -c/--cluster X   : set the cluster to X (required for --cm/--se)
+  -n/--namespace X : set the namespace to X
+  --cm X           : K8S ConfigMap variables for a microservice X (sep lines)
+  --se X           : only secrets used by plugin, (sep lines)
+
+  --clear-cluster-cache : clears out cache files for cluster configurations
 
 Example Usage:
   `basename $0`    : sets all environment variables
@@ -81,129 +69,130 @@ Example Usage:
 
 EOF
 }
+. wov-env-ops fWovEnvDisplayOptions $*
 
-if [ "$1" == '--help' ] || [ "$1" == '-h' ]; then fWovEnvDisplayOptions; exit 0; fi
+
+ECHOMODE=0
+DOALL=1
+SED=`which gsed`
+PROVIDERVARS=()
+RANCLUSTER=0
+CONTEXTSET=0
 
 
-#_ARGS=()
-#shift_globally () {
-#  echo "...shift_globally on : '$@' ${#@}"
-#  shift
-#  _ARGS=$@
-#  echo "  ...shifted_globally: '${_ARGS[@]}' ${#_ARGS[@]}"
-#}
-
+# Default variables to echo
+ECHOVARS=( 'WOV_PROJECTTITLE' 'WOV_VERSION' 'WOV_ME' 'WOV_PVER' 'WOV_SVER' \
+           'WOV_ORIGIN' 'WOV_WORKINGCONTEXT' \
+           'WOV_CONTEXT' 'WOV_CLUSTER' 'WOV_NS' 'WOV_CLTYPE' 'WOV_PROVIDER' 'WOV_REGION' 'WOV_FLAVOR' 'WOV_PROJECT' 'WOV_STAGE' \
+           'WOV_KPROJECT' 'WOV_WPROJECT' 'WOV_KSTAGE' 'WOV_GSTAGE' \
+           'WOV_PROJECTTYPE' 'WOV_PROJECTDESCRIPTION' \
+           'WOV_USERNAME' 'WOV_USEREMAIL' \
+           'WOV_BASEDIR' 'WOV_ARCHIVEREPOSITORY' 'WOV_ARCHIVEENV')
 
 # --------------------------------------------------------------------- 
 # Calls wov-env-build to build the secretfile if it does not exist.
+# NOTE: does not build k8s
 #  if $1 == force, force
 # --------------------------------------------------------------------- 
 function fBuildClusterSecrets
 { 
   if [ ! -f "${WOV_SECRETFILE}" ] || [ "$1" == "force" ]; then 
-    local NS=
-    if [ "${GLOBALCOMMAND}" != "" ]; then
-      NS="--global ${GLOBALCOMMAND} "
-    else
-      NS="--namespace ${WOV_NS}" 
-    fi
-    # echo "wov-env-build ${NS} -q --secrets ${CLUSTER} "
-    wov-env-build ${NS} -q --secrets ${CLUSTER} 
+    # echo "call wov-env-build --context ${WOV_CONTEXT} -q --secrets ${CLUSTER} "
+    wov-env-build --context ${WOV_CONTEXT} -q --config
     if [ "$?" != "0" ]; then exit 1; fi
   fi
 }
 
+function ensureSetContext()
+{
+  if [ ${CONTEXTSET} -eq 0 ]; then doSetContext $1; fi
+}
+
 # --------------------------------------------------------------------- 
+# TODO: UPDATE DOCUMENATION HERE AS IT IS WRONG
 # Sets the cluster we are generating environment vars for. By default,
 # generates using settings in 'local', which is generated by 
-# wov-env-build using the 'localcontext' entry. So, 'local' points to
-# whatever cluster this project considers the localcontext.
+# wov-env-build using the 'curorigin' entry. So, 'local' points to
+# whatever cluster this project considers the curorigin.
 # NOTE: creates the directory, but not file since that would look like 
 #       it was current.
+# NOTE2: Uses WOV_NS so if you change it with --namespace, then it will
+#        be used in setting which stage of the cluster to use.
 # $1 - cluster name
 # $2 - if true, force build
 # --------------------------------------------------------------------- 
-function doSetCluster
+function doSetContext
 {
-  CLUSTER=$1
-  local WOV_SECRETFILE_path=${WOV_BASEDIR}/wovtools/cache/clusters/${CLUSTER}
-  mkdir -m 700 -p ${WOV_SECRETFILE_path}
-  WOV_SECRETFILE=${WOV_SECRETFILE_path}/secrets.json
-  export WOV_SECRETFILE
+  # Load up new context for calls below
+  . wov-env-loader --context ${1}
 
   # ---------------------------------------------------------------------
   # Ensure the SECRET_CACHE_DIR exists and is protected and then merge
-  # files config.json and local.json together in SECRETSMERGED_RAW
+  # files config.json and myconfig.json together in SECRETSMERGED_RAW
   # if they have changed.
   # ---------------------------------------------------------------------
   mkdir -m 700 -p ${WOV_CACHEDIR}
+  mkdir -m 700 -p ${WOV_CLUSTERDIR}
 
   # check files that could impact WOV_SECRETFILE generation
   #  - changes to kube config
-  #  - newly merged wovtools/config.json|local.json
+  #  - newly merged wovtools/config.json|myconfig.json
   #  - wovtools/secrets directory has changes
   if [ ! -f "${WOV_SECRETFILE}" ] || 
+     [ "$2" == 'true' ] ||
      [ "${HOME}/.kube/config"            -nt "${WOV_SECRETFILE}" ] ||
      [ "${WOV_CONFIGFILE_MERGED}"        -nt "${WOV_SECRETFILE}" ] || 
      [ "${WOV_BASEDIR}/wovtools/secrets" -nt "${WOV_SECRETFILE}" ] ||
-     [ "${WOV_BASEDIR}/wovtools/config.json" -nt "${WOV_SECRETFILE}" ] ||
-     [ "${WOV_BASEDIR}/wovtools/local.json" -nt "${WOV_SECRETFILE}" ] ||
+     [ "${WOV_CONFIGFILE_MAIN}"          -nt "${WOV_SECRETFILE}" ] ||
+     [ "${WOV_CONFIGFILE_MINE}"          -nt "${WOV_SECRETFILE}" ] ||
      [ "${WOV_BASEDIR}/.git/config"      -nt "${WOV_SECRETFILE}" ]; then
     
+    # Builds files but does not import
     fBuildClusterSecrets force 
     touch "${WOV_SECRETFILE}"
-    . wov-env-loader
-  fi
-}
-
-
-
-
-
-
-
-
-# --------------------------------------------------------------------- 
-# For dev and prod, check local code and secrets are checked in and pushed.
-# @param {bool} $1 - if true, allows for err msg and exit
-# @return {bool} - 1 if error, 0 if ok
-# --------------------------------------------------------------------- 
-function doGitChecksOnFormalStages()
-{
-  local retval=1
-
-  if [ "$WOV_STAGE" == "prod" ] || [ "$WOV_STAGE" == "dev" ]; then
-
-    local R1=0
-    wov-git-check ${WOV_BASEDIR}
-    R1=$?
-    if [ $R1 -eq 0 ]; then
-      wov-git-check ${WOV_BASEDIR}/wovtools/secrets
-      R2=$?
-      if [ $R2 -eq 0 ]; then
-        retval=0
-      fi
-    fi
-
-    if [ $retval -ne 0 ]; then
-      printf "\n\nERROR: failed git checks.\n\n"
-      exit 1
-    fi
+    # . wov-env-loader -g ${WOV_CLUSTER}-${WOV_NS}"
   fi
 
-  return $retval
+  CONTEXTSET=1
 }
 
 
-# --------------------------------------------------------------------- 
-# Used to generate the path where CLuster configuration would sit in 
-# the archive.
-#  ex. local path="`getRelativeArchivePath MyCluster`"
-# --------------------------------------------------------------------- 
-function getRelativeArchivePath()
-{ 
-  echo "${1}/${WOV_PROJECT}/${WOV_STAGE}/${WOV_PVER}_${WOV_SVER}" 
-}
+
+
+
+
+
+
+## --------------------------------------------------------------------- 
+## For dev and prod, check local code and secrets are checked in and pushed.
+## @param {bool} $1 - if true, allows for err msg and exit
+## @return {bool} - 1 if error, 0 if ok
+## --------------------------------------------------------------------- 
+#function doGitChecksOnFormalStages()
+#{
+#  local retval=1
+#
+#  if [ "$WOV_STAGE" == "prod" ] || [ "$WOV_STAGE" == "dev" ]; then
+#
+#    local R1=0
+#    wov-git-check ${WOV_BASEDIR}
+#    R1=$?
+#    if [ $R1 -eq 0 ]; then
+#      wov-git-check ${WOV_BASEDIR}/wovtools/secrets
+#      R2=$?
+#      if [ $R2 -eq 0 ]; then
+#        retval=0
+#      fi
+#    fi
+#
+#    if [ $retval -ne 0 ]; then
+#      printf "\n\nERROR: failed git checks.\n\n"
+#      exit 1
+#    fi
+#  fi
+#
+#  return $retval
+#}
 
 
 # --------------------------------------------------------------------- 
@@ -315,11 +304,6 @@ function fDoProvider() # Cluster()
 {
   RANPROVIDER=1
 
-  if [ "${CLUSTER}" != "${WOV_CLUSTER}" ]; then
-    #if [ "$ECHOMODE" == "1" ] || [ "${ECHOMODE}" == "2" ]; then printf "  ... setting cluster to '${WOV_CLUSTER}'\n"; fi
-    doSetCluster ${WOV_CLUSTER} true
-  fi
-
   if [ "$WOV_PROVIDER" == "aws" ]; then . provider-wov-env-aws; 
   else
     printf "\n\nERROR: Unknown provider to load env vars from : '${WOV_PROVIDER}'.\n\n"
@@ -355,7 +339,7 @@ function doProviderEcho
 # --------------------------------------------------------------------- 
 function doPrintVarX()
 {
-  if [ "$HAS_SECRET" == "0" ]; then fBuildClusterSecrets; fi
+#  if [ "$HAS_SECRET" == "0" ]; then fBuildClusterSecrets; fi
   R=`doPrintVarsENVS | grep "$1=" | cut -f2 -d"=" | ${SED} -e "s/^'//" -e "s/'$//"`
   if [ "$R" == "" ]; then
     R=${!1}
@@ -363,12 +347,18 @@ function doPrintVarX()
   echo $R
 }
 
+
+# --------------------------------------------------------------------- 
+# This generates a printout of variables, suitable for sourcing
+# BUGS: NOTE: TODO: this loads the environment vars but if the context changes, this is not called again
+# --------------------------------------------------------------------- 
 function doPrintVarsENVS()
 {
-  if [ "$HAS_SECRET" == "0" ]; then fBuildClusterSecrets; fi
+#  if [ "$HAS_SECRET" == "0" ]; then fBuildClusterSecrets; fi
 
   cat ${WOV_SECRETFILE} |
     jq  -r 'walk( if type == "object" then with_entries(select( .key | test("STAGE.+") or test("//*") | not)) else . end) | [leaf_paths as $path | {"key": $path | join("_"), "value": getpath($path)}] | from_entries | keys[] as $k | "WOV_\($k)=" + @sh "\(.[$k])" '
+
 
   if [ "$RANPROVIDER" == "1" ]; then doProviderEcho "\n"; fi
 
@@ -382,7 +372,7 @@ function doPrintVarsCONF()
 
 function doPrintVarsEXPORTS()
 {
-  if [ "$HAS_SECRET" == "0" ]; then fBuildClusterSecrets; fi
+#  if [ "$HAS_SECRET" == "0" ]; then fBuildClusterSecrets; fi
 
   cat ${WOV_SECRETFILE} |
     jq  -r 'walk( if type == "object" then with_entries(select( .key | test("STAGE.+") or test("//*") | not)) else . end) | [leaf_paths as $path | {"key": $path | join("_"), "value": getpath($path)}] | from_entries | keys[] as $k | "export WOV_\($k)=" + @sh "\(.[$k])" '
@@ -414,10 +404,10 @@ function fConfGeneration()
   if [ -e "${WOV_BASEDIR}/${1}/src/${1}config.js" ]; then
     MSCFILE="${WOV_BASEDIR}/${1}/src/${1}config.js"
     if [ "$2" == "cm" ]; then 
-      R=( $(node -e "console.log((new (require('${MSCFILE}'))())._genK8SConfigMap())") ) 
+      R=( "$(node -e "console.log((new (require('${MSCFILE}'))())._genK8SConfigMap())")" ) 
       RR=$?
     elif [ "$2" == "se" ]; then
-      R=( $(node -e "console.log((new (require('${MSCFILE}'))())._genK8SSecrets())") )
+      R=( "$(node -e "console.log((new (require('${MSCFILE}'))())._genK8SSecrets())")" )
       RR=$?
     fi
     if [ "${RR}" != "0" ]; then echo "ERROR: failed to generate '${1}' config from NodeJS source code: ${MSCFILE}"; exit 1 ; fi
@@ -425,10 +415,10 @@ function fConfGeneration()
   elif [ -e "${WOV_BASEDIR}/src/${1}config.js" ]; then
     MSCFILE="${WOV_BASEDIR}/src/${1}config.js"
     if [ "$2" == "cm" ]; then
-      R=( $(node -e "console.log((new (require('${MSCFILE}'))())._genK8SConfigMap())") ) 
+      R=( "$(node -e "console.log((new (require('${MSCFILE}'))())._genK8SConfigMap())")" ) 
       RR=$?
     elif [ "$2" == "se" ]; then 
-      R=( $(node -e "console.log((new (require('${MSCFILE}'))())._genK8SSecrets())") ) 
+      R=( "$(node -e "console.log((new (require('${MSCFILE}'))())._genK8SSecrets())")" ) 
       RR=$?
     fi
     if [ "${RR}" != "0" ]; then echo "ERROR: failed to generate '${1}' config from NodeJS source code: ${MSCFILE}"; exit 1 ; fi
@@ -613,17 +603,39 @@ function doResVerify()
 }
 
 
+# --------------------------------------------------------------------- 
+# --------------------------------------------------------------------- 
+function doClearClusterCache()
+{
+  local ccd="${WOV_BASEDIR}/wovtools/cache/clusters"
+  if [ -e "${ccd}" ]; then
+    if [ $DOECHO -ge 1 ]; then echo "  ... clearing '${ccd}'."; fi
+    rm -Rf "${ccd}"
+  else
+    >&2 echo "WARNING: no cluster cache to clear at '${ccd}'."
+  fi
+}
+
+
+# ---------------------------------------------------------------------
+function doListMicroservices()
+{
+  fGetMicroserviceRecipes
+  if [ ${#RECIPES[@]} -eq 0 ]; then echo 'No microservices'; else echo "${RECIPES[@]}"; fi
+}
 
 # --------------------------------------------------------------------- 
 # Load env
 # --------------------------------------------------------------------- 
-# NOTE: this passes arguments
-. wov-env-loader
+envargswovenv=( "$@" )
+set ""
 . wov-env-common
 . wov-db-common
+set -- "${envargswovenv[@]}"
 
-retreiveLocalContextCluster
-doSetCluster ${LOCALCONTEXT}
+
+#retreiveLocalContextCluster
+#doSetContext ${WOV_CONTEXT}
 
 
 # --------------------------------------------------------------------- 
@@ -635,38 +647,61 @@ while [[ $1 =~ ^- ]]; do
   elif [ "$1" == '-E' ]; then
     ECHOMODE=2
 
-  elif [ "$1" == '-c' ] || [ "$1" == '--cluster' ]; then
+  elif [ "$1" == '--context' ]; then
     shift
-    doSetCluster $1
+    doSetContext "$1"
+    shift
+
+  
+#  elif [ "$1" == '-c' ] || [ "$1" == '--cluster' ]; then
+#    shift
+#    doSetContext "$1-${WOV_NS}"
+#    shift
+#
+#  elif [ "$1" == '-n' ] || [ "$1" == '--namespace' ]; then
+#    shift
+#    doSetContext "${WOV_CLUSTER}-${1}"
+#    shift
 
   elif [ "$1" == '-p' ] || [ "$1" == '--provider' ]; then
+    # build the context, building secrets as needed, and then source the secrets file
+    ensureSetContext ${WOV_CONTEXT}
+    . <(doPrintVarsENVS)
     fDoProvider # Cluster
+    doProviderEcho '\n'
 
   elif [ "$1" == "--conf" ]; then
 #    doLoadConf
+    ensureSetContext ${WOV_CONTEXT}
     doPrintVarsCONF
 
   elif [ "$1" == "--envs" ]; then
 #    doLoadEnv
+    ensureSetContext ${WOV_CONTEXT}
     doPrintVarsENVS
 
   elif [ "$1" == "--secrets" ]; then
+    ensureSetContext ${WOV_CONTEXT}
     printf "\nsecret file (${WOV_SECRETFILE}):\n";
     cat ${WOV_SECRETFILE}
 
     # print one var
   elif [ "$1" == "--env-var" ]; then
+    ensureSetContext ${WOV_CONTEXT}
     shift
     if [ "$CLUSTER" == "" ]; then printf "\n\nERROR($(basename $0)): no cluster set. Use the '--cluster X' option.\n\n"; fi
     command grep -h ${1} ${WOV_BASEDIR}/wovtools/cache/clusters/${CLUSTER}/[cs][me]/*.json | ${SED} -e 's/^.*[=]//' -e 's/^"//' -e 's/"$//'
 
   elif [ "$1" == "--exports" ]; then
 #    doLoadExports
+    ensureSetContext ${WOV_CONTEXT}
     doPrintVarsEXPORTS
 
   elif [ "$1" == "--rcAWS" ]; then
     shift
-    echo $(fConvertRegionCodeAWS $1)
+    ensureSetContext ${WOV_CONTEXT}
+    wov-aws convertrc $1
+    if [ $? != 0 ]; then exit 1; fi
     shift
 
 #  elif [ "$1" == "--CC" ]; then
@@ -676,22 +711,31 @@ while [[ $1 =~ ^- ]]; do
 
   elif [ "$1" == "--cm" ]; then
     shift
+    ensureSetContext ${WOV_CONTEXT}
     fConfGeneration $1 cm 1
 
   elif [ "$1" == "--se" ]; then
     shift
+    ensureSetContext ${WOV_CONTEXT}
     fConfGeneration $1 se 1
 
   elif [ "$1" == "--CM" ]; then
     shift
+    ensureSetContext ${WOV_CONTEXT}
     fConfGeneration $1 cm 0
 
   elif [ "$1" == "--SE" ]; then
     shift
+    ensureSetContext ${WOV_CONTEXT}
     fConfGeneration $1 se 0
+
+  elif [ "$1" == "--clear-cluster-cache" ]; then
+    shift
+    doClearClusterCache
 
   elif [ "$1" == '--var' ]; then
     shift 
+    ensureSetContext ${WOV_CONTEXT}
     V=$(doPrintVarX $1)
     if [ "$ECHOMODE" == "1" ]; then
       printf "$1=\"${V}\"\n"
@@ -701,26 +745,23 @@ while [[ $1 =~ ^- ]]; do
       echo ${V}
     fi
     DOALL=0
-  elif [ "$1" == '-v' ] || [ "$1" == '--version' ]; then
-    echo $WOV_VERSION
-
 
   elif [ "$1" == '--health' ]; then
+    ensureSetContext ${WOV_CONTEXT}
     doHealthChecks
 
   elif [ "$1" == '--health-tls' ]; then
+    ensureSetContext ${WOV_CONTEXT}
     doHealthChecks https
 
   elif [ "$1" == '--health-no-tls' ]; then
+    ensureSetContext ${WOV_CONTEXT}
     doHealthChecks http
 
 
-  elif [ "$1" == '--help' ] || [ "$1" == '-h' ]; then
-    fWovEnvDisplayOptions
-    exit 0
-
   elif [ "$1" == '--res' ]; then
     shift
+    ensureSetContext ${WOV_CONTEXT}
     doResName $@
     A=$?
     if [ $A -ne 0 ]; then exit $A; fi
@@ -729,7 +770,13 @@ while [[ $1 =~ ^- ]]; do
     set - blank "$@"
       # -- pushes 'blank' onto arguments, so next shift can get rid of it
 
+  elif [ "$1" == '--lms' ]; then
+    shift
+    doListMicroservices
+
+
   elif [ "$1" == '--vres' ]; then
+    ensureSetContext ${WOV_CONTEXT}
     R1=$(doResVerify ${2} ${3}) ; RR1=$?
     if [ ${DOECHO} -ge 2 ]; then echo "  ... verify ${2} ${3}"; fi
     if [ "$R1" == "1" ]; then echo "true"; else echo "false"; fi
@@ -738,25 +785,29 @@ while [[ $1 =~ ^- ]]; do
 
   else
     echo
-    echo "***ERROR: unknown option '$1'."
+    echo "***ERROR (`basename $0`): unknown option '$1'."
     echo
     exit 1
   fi
   shift
 
-
 done
 
-# if user never asked to show any individual variables, show all
-if [ "$DOALL" == "1" ]; then
-  if   [ "$ECHOMODE" == "0" ]; then
-    printf "" # do nothing
-  elif [ "$ECHOMODE" == "1" ]; then
-    fDoEcho "\n"
-  elif [ "$ECHOMODE" == "2" ]; then
-    fDoEcho " "
-  else
-    printf "\n\nERROR: Unknown echo mode '$ECHOMODE'.\n\n"
-    exit 1
+if [ $WOV_DODEFAULTCOMMAND -eq 1 ]; then
+
+  ensureSetContext ${WOV_CONTEXT}
+
+  # if user never asked to show any individual variables, show all
+  if [ "$DOALL" == "1" ]; then
+    if   [ "$ECHOMODE" == "0" ]; then
+      printf "" # do nothing
+    elif [ "$ECHOMODE" == "1" ]; then
+      fDoEcho "\n"
+    elif [ "$ECHOMODE" == "2" ]; then
+      fDoEcho " "
+    else
+      printf "\n\nERROR: Unknown echo mode '$ECHOMODE'.\n\n"
+      exit 1
+    fi
   fi
 fi
diff --git a/bin/wov-env-common b/bin/wov-env-common
--- a/bin/wov-env-common
+++ b/bin/wov-env-common
@@ -1,7 +1,9 @@
 #!/usr/bin/env bash
 
 
+# ---------------------------------------------------------------------
 # Echo Undefined if ""
+# ---------------------------------------------------------------------
 function EUndef()
 {
   if [ "$1" != "" ]; then
@@ -13,11 +15,75 @@ function EUndef()
 
 
 # ---------------------------------------------------------------------
+# Sets global RECIPES variable
+# ---------------------------------------------------------------------
+function fGetMicroserviceRecipes()
+{
+  RECIPES=( $(cd ${WOV_BASEDIR}/wovtools/msrecipes && find * -maxdepth 0 -type f 2> /dev/null) )
+
+#  echo "${RECIPES[@]}"
+}
+
+
+# ---------------------------------------------------------------------
+# from: https://stackoverflow.com/a/8574392/2664702
+# Returns: 0 success/found, 1 fail/not found
+# ---------------------------------------------------------------------
+containsElement () {
+  local e match="$1"
+  shift
+  for e; do [[ "$e" == "$match" ]] && return 0; done
+  return 1
+}
+
+# ---------------------------------------------------------------------
+# Used to generate the path where CLuster configuration would sit in
+# the archive.
+#  ex. local path="`getRelativeArchivePath MyCluster`"
+# ---------------------------------------------------------------------
+function getRelativeArchivePath()
+{
+  echo "${1}/${WOV_PROJECT}/${WOV_STAGE}/${WOV_PVER}_${WOV_SVER}"
+}
+
+
+# ---------------------------------------------------------------------
+# ---------------------------------------------------------------------
+function exitIfProd()
+{
+  local R="$(git rev-parse --abbrev-ref HEAD)" ; Re=$?
+  if [ "$Re" != "0" ]; then
+    >&2 printf "ERROR: exiting because could not determine stage. git failed.\n"
+    exit 1
+  fi
+  if [ "${R}" == "prod" ] || [ "${R}" == "dev" ]; then
+    >&2 printf "ERROR: exiting because in stage '${R}'.\n"
+    exit 1
+  fi
+}
+
+# ---------------------------------------------------------------------
+# ---------------------------------------------------------------------
+function exitIfProdOrDev()
+{
+  local R="$(git rev-parse --abbrev-ref HEAD)" ; Re=$?
+  if [ "$Re" != "0" ]; then
+    >&2 printf "ERROR: exiting because could not determine stage. git failed.\n"
+    exit 1
+  fi
+  if [ "${R}" == "prod" ]; then
+    >&2 printf "ERROR: exiting because in stage 'prod'.\n"
+    exit 1
+  fi
+}
+
+
+# ---------------------------------------------------------------------
 # Store the local context cluster (from merged raw file) in $LOCALCONTEXT
 # Only checks wovtools/local.json
 # ---------------------------------------------------------------------
 function retreiveLocalContextCluster()
-{ if [ "${LOCALCONTEXT}" == "" ]; then LOCALCONTEXT=`jq -r ".localcontext" ${WOV_BASEDIR}/wovtools/local.json`; fi }
+{ if [ "${LOCALCONTEXT}" == "" ]; then LOCALCONTEXT=`jq -r ".curorigin" "${WOV_CONFIGFILE_MINERAW}"`; fi }
 
 
 
@@ -72,7 +138,7 @@ function doResName()
       echo "${2}-peerconn"
 
     elif [ "$1" == "DNS" ]; then
-      DBNAME=$(doResName DB ${2})
+      DBNAME=$(doResName DB ${2} ${3})
       echo $(aws rds describe-db-instances --db-instance-identifier ${DBNAME} --query 'DBInstances[0].Endpoint.Address' --output text)
     else
       printf "\n\nERROR: unknown resource of ${1} to doResName.\n"
diff --git a/bin/wov-env-loader b/bin/wov-env-loader
--- a/bin/wov-env-loader
+++ b/bin/wov-env-loader
@@ -2,21 +2,68 @@
 
 # --------------------------------------------------------------------- 
 # This is a light-weight env variable loader. Used by wov-env and wov-env-build.
-#  NOTE: This does not contain secrets variables. 
+#  NOTE: This does not contain secrets variables or do any importing. 
 # --------------------------------------------------------------------- 
-
 
 # --------------------------------------------------------------------- 
 # Versions
 # --------------------------------------------------------------------- 
-export WOV_VERSION=1
+export WOV_VERSION=2
 export WOV_VH_VERSION=0.1
+
 
 # --------------------------------------------------------------------- 
 # Command line
 # --------------------------------------------------------------------- 
-if [ "$1" == '-g' ] || [ "$1" == '--global' ]; then shift; GLOBALCOMMAND=$1; shift; fi
-if [ "$1" == "--vh-label" ]; then echo "${WOV_VH_VERSION}"; exit 0; fi
+#if [ "$1" == '-g' ] || [ "$1" == '--global' ]; then shift;  GLOBALCONTEXT=$1; shift; fi
+#if [ "$1" == '-c' ] || [ "$1" == '--context' ]; then shift; GLOBALCONTEXT=$1; shift; fi
+#>&2 echo "CMDS $*"
+#while [[ $1 =~ ^- ]]; do
+#
+##  >&2 echo "CMD $1"
+#  if [ "$1" == "-q" ]; then
+#    shift
+#    DOECHO=0
+#
+#  elif [ "$1" == "-v" ]; then
+#    shift
+#    DOECHO=2
+#
+#  elif [ "$1" == "--vh-label" ]; then
+#    shift
+#    echo "${WOV_VH_VERSION}";
+#    exit 0
+#
+#  elif [ "$1" == "--origin" ]; then
+#    shift
+#    export WOV_ORIGIN="$1"
+##    >&2 echo "cli switch WOV_ORIGIN ${WOV_ORIGIN}"
+#    shift
+#
+#  elif [ "$1" == '--context' ]; then
+#    shift
+#    export WOV_CONTEXT="$1"
+##    >&2 echo "cli switch WOV_CONTEXT ${WOV_CONTEXT}"
+#    shift
+#
+#  else
+#    echo
+#    echo "***ERROR: wov-env-loader unknown option '$1'."
+#    exit 1
+#  fi
+#
+#  >&2 echo "exit CMD $1"
+#done
+
+#>&2 echo "CMDS left ${*}"
+
+#NOTE: this was a short circuiting piece of code
+#if [ "${WOV_CONTEXT}" != "" ]; then
+#  if [ "${GLOBALCONTEXT}" == "" ]; then
+#    echo "WOV_CONTEXT ${WOV_CONTEXT} set and no GLOBALCONTEXT overridding, exiting b/c no need to call "
+#    exit 0
+#  fi
+#fi
 
 # --------------------------------------------------------------------- 
 # Returns 1 if this is a WovTools project
@@ -24,126 +71,167 @@ if [ "$1" == "--vh-label" ]; then echo "${WOV_VH_VERSION}"; exit 0; fi
 function isProject()
 {
   let retval=1
-  if [      "$WOV_BASEDIR" == "" ]; then echo "  WARNING: not in wovtools project (no git)."; retval=0; fi
-  if [ ! -d "$WOV_BASEDIR/wovtools" ]; then echo "  WARNING: not in wovtools project (no wovtools directory)."; retval=0; fi
-  if [ ! -f "${WOV_BASEDIR}/wovtools/config.json" ]; then echo "  WARNING: not in wovtools project (no wovtools/config.json file)."; retval=0; fi
+  # >&2 echo "WOV_BASEDIR ${WOV_BASEDIR}"
+  if [      "${WOV_BASEDIR}" == "" ]; then echo "WARNING: not in wovtools project (no git)."; retval=0; fi
+  if [ ! -d "${WOV_BASEDIR}/wovtools" ]; then echo "WARNING: not in wovtools project (no wovtools directory)."; retval=0; fi
+  if [ ! -f "${WOV_BASEDIR}/${WOV_CONFIGFILE_MAIN}" ]; then echo "WARNING: not in wovtools project (no ${WOV_CONFIGFILE_MAIN} file)."; retval=0; fi
   return $retval;
 }
 
 # --------------------------------------------------------------------- 
-# git vars
+# Source files for project configuration : finds WOV_BASEDIR if not set
+# - needed by wov-init before a project is created 
+# - wov-init sets WOV_BASEDIR before calling
 # --------------------------------------------------------------------- 
-export WOV_BASEDIR="$(git rev-parse --show-toplevel 2> /dev/null)"
-R=( "$(isProject)" )
-if [ $? != 1 ]; then
-  echo "ERROR: not in a WovTools project. Try using wov-init to create a project here."
-  ( IFS=$'\n'; echo "${R[*]}" )
-  exit 1
+if [ "${WOV_BASEDIR}" == "" ]; then
+  export WOV_BASEDIR="$(git rev-parse --show-toplevel 2> /dev/null)" 
 fi
-export WOV_PVER="$(git rev-list --count $(git rev-parse --abbrev-ref HEAD))"
-export WOV_SVER="$(cd ${WOV_BASEDIR}/wovtools/secrets && git rev-list --count $(git rev-parse --abbrev-ref HEAD))"
-export WOV_USERNAME="$(git config user.name)"
-export WOV_USEREMAIL="$(git config user.email)"
-export WOV_GSTAGE="$(git rev-parse --abbrev-ref HEAD)"
-
-
-# --------------------------------------------------------------------- 
-# Source files for project configuration : build if needed
-# --------------------------------------------------------------------- 
+export WOV_CONFIGFILE_MAIN="wovtools/config.json"
+export WOV_CONFIGFILE_MINE="wovtools/myconfig.json"
 export WOV_CACHEDIR="${WOV_BASEDIR}/wovtools/cache"
-export WOV_CONFIGFILE_RAW="${WOV_BASEDIR}/wovtools/config.json"
-export WOV_CONFIGFILE_LOCALRAW="${WOV_BASEDIR}/wovtools/local.json"
+export WOV_CONFIGFILE_MAINRAW="${WOV_BASEDIR}/${WOV_CONFIGFILE_MAIN}"
+export WOV_CONFIGFILE_MINERAW="${WOV_BASEDIR}/${WOV_CONFIGFILE_MINE}"
 export WOV_CONFIGFILE_MERGED="${WOV_CACHEDIR}/.merged.json"
-#export WOV_FILE_SECRETS_RAW="${WOV_BASEDIR}/wovtools/config.json"
-#export WOV_FILE_SECRETSLOCAL_RAW="${WOV_BASEDIR}/wovtools/local.json"
-#export WOV_FILE_SECRETSMERGED="${WOV_CACHEDIR}/.merged.json"
+SED=`which gsed`
 
-
-# --------------------------------------------------------------------- 
-# global .wovtools file
-# --------------------------------------------------------------------- 
-export WOV_ME=$(cat ${HOME}/.wovtools | jq -r '.me')
-if [ "${WOV_ME}" == "null" ] ; then
-  printf "\n\nERROR: You need to set 'me' in the wovtools/config.json file.\n"
-  printf "  - This is a unique code in this project, to represent yourself. Try using your initials (assuming they are unique to your team).\n\n"
-  exit 1
-fi
-
-# --------------------------------------------------------------------- 
-# vars from merged files (config.json and local.json)
-# --------------------------------------------------------------------- 
-
-# --------------------------------------------------------------------- 
-# Merge if out of date
-if [ ${WOV_CONFIGFILE_RAW} -nt ${WOV_CONFIGFILE_MERGED} ] || [ ${WOV_CONFIGFILE_LOCALRAW} -nt ${WOV_CONFIGFILE_MERGED} ]; then
-  echo "... merged file out of date, creating: ${WOV_CONFIGFILE_MERGED}"
-  echo "" > ${WOV_CONFIGFILE_MERGED}
-  chmod 600 ${WOV_CONFIGFILE_MERGED}
-  jq -s ".[0] * .[1]" ${WOV_CONFIGFILE_RAW} ${WOV_CONFIGFILE_LOCALRAW} >> ${WOV_CONFIGFILE_MERGED} 2> /dev/null
-  if [ "$?" != "0" ]; then
-    F1=$(cat ${WOV_CONFIGFILE_RAW} | jq type 2>&1)
-    F1a=$?
-    if [ "$F1a" != "0" ]; then printf "\n\nERROR: ${WOV_CONFIGFILE_RAW} is not properly formatted.\n${F1}\n\n"; fi
-    F2=$(cat ${WOV_CONFIGFILE_LOCALRAW} | jq type 2>&1)
-    F2a=$?
-    if [ "$F2a" != "0" ]; then printf "\n\nERROR: ${WOV_CONFIGFILE_LOCALRAW} is not properly formatted.\n${F2}\n\n"; fi
-    exit 1;
-  fi
-fi
-
-
-# --------------------------------------------------------------------- 
-# Load merged file in one call
-MERGEDVARS=()
-while read f; do
-  MERGEDVARS+=( "$f" )
-done <<<$(cat ${WOV_CONFIGFILE_MERGED} | jq -r ". | ( .ver, .project.project, .project.type, .project.title, .project.description, .archive.repository, .archive.env  )" )
-WOV_PVERSION=${MERGEDVARS[0]}
-if [ "${WOV_PVERSION}" != "${WOV_VERSION}" ] && [ "${WOV_PVERSION}" != "initing" ] ; then
-  printf "\n\nERROR: Your project version '${WOV_PVERSION}', does not match to the WovTools version '${WOV_VERSION}'.\n\n"
-  exit 1
-fi
-export WOV_WPROJECT="${MERGEDVARS[1]}"
-export WOV_PROJECTTYPE="${MERGEDVARS[2]}"
-export WOV_PROJECTTITLE="${MERGEDVARS[3]}"
-export WOV_PROJECTDESCRIPTION="${MERGEDVARS[4]}"
-export WOV_ARCHIVEREPOSITORY="${MERGEDVARS[5]}"
-export WOV_ARCHIVEENV="${MERGEDVARS[6]}"
-
-
-# vars from Kubernetes
-# --------------------------------------------------------------------- 
-if [ "$GLOBALCOMMAND" != "" ]; then 
-  export WOV_CONTEXT=$GLOBALCOMMAND; 
-else
-  export WOV_CONTEXT="$(kubectl config current-context)"
-fi
-OLDIFS=$IFS
-IFS='-'
-array=( $WOV_CONTEXT )
-IFS=$OLDIFS
-export WOV_KSTAGE="${array[5]}"
-export WOV_KPROJECT="${array[4]}"
-export WOV_NS="${WOV_KPROJECT}-${WOV_KSTAGE}"
-export WOV_FLAVOR="${array[3]}"
-export WOV_REGION="${array[2]}"
-export WOV_PROVIDER="${array[1]}"
-export WOV_CLTYPE="${array[0]}"
-export WOV_CLUSTER="${WOV_CLTYPE}-${WOV_PROVIDER}-${WOV_REGION}-${WOV_FLAVOR}"
-if [ "${#array[@]}" != "6" ]; then
-  # error if no namespace nad not in global context
-  if [ "${GLOBALCOMMAND}" == "" ]; then
-    echo "ERROR: bad context '${WOV_CONTEXT}' (from '-g X' switch or kubectl config current-context). Should be CLTYPE-PROVIDER-REGION-FLAVOR-PROJECT-STAGE."
+function getWovProjectVars() 
+{
+  # --------------------------------------------------------------------- 
+  # git vars
+  # --------------------------------------------------------------------- 
+  R=( "$(isProject)" )
+  if [ ${?} != 1 ]; then
+    echo "ERROR: not in a WovTools project. Try using wov-init to create a project here."
+    ( IFS=$'\n'; echo "${R[*]}" )
     exit 1
   fi
-fi
+  export WOV_PVER="$(git rev-list --count $(git rev-parse --abbrev-ref HEAD))"
+  export WOV_SVER="$(cd ${WOV_BASEDIR}/wovtools/secrets && git rev-list --count $(git rev-parse --abbrev-ref HEAD))"
+  export WOV_USERNAME="$(git config user.name)"
+  export WOV_USEREMAIL="$(git config user.email)"
+  export WOV_GSTAGE="$(git rev-parse --abbrev-ref HEAD)"
 
 
 
-# --------------------------------------------------------------------- 
-# Unifying
-# --------------------------------------------------------------------- 
-export WOV_STAGE="$WOV_KSTAGE"        # KSTAGE has priority since git repo might differ but want to build for current stage.
-export WOV_PROJECT="${WOV_WPROJECT}"  
 
-# echo "PROJECT ${WOV_PROJECT} KSTAGE ${WOV_KSTAGE}"
+  # --------------------------------------------------------------------- 
+  # global .wovtools file
+  # --------------------------------------------------------------------- 
+  export WOV_ME=$(cat ${HOME}/.wovtools | jq -r '.me')
+  if [ "${WOV_ME}" == "null" ] ; then
+    printf "\n\nERROR: You need to set 'me' in the ${WOV_CONFIGFILE_MINE} file.\n"
+    printf "  - This is a unique code in this project, to represent yourself. Try using your initials (assuming they are unique to your team).\n\n"
+    exit 1
+  fi
+
+  # --------------------------------------------------------------------- 
+  # vars from merged config files
+  # --------------------------------------------------------------------- 
+
+  # --------------------------------------------------------------------- 
+  # Merge if out of date
+  if [ ${WOV_CONFIGFILE_MAINRAW} -nt ${WOV_CONFIGFILE_MERGED} ] || [ ${WOV_CONFIGFILE_MINERAW} -nt ${WOV_CONFIGFILE_MERGED} ]; then
+    echo "... merged file out of date, creating: ${WOV_CONFIGFILE_MERGED}"
+    echo "" > ${WOV_CONFIGFILE_MERGED}
+    chmod 600 ${WOV_CONFIGFILE_MERGED}
+    jq -s ".[0] * .[1]" ${WOV_CONFIGFILE_MAINRAW} ${WOV_CONFIGFILE_MINERAW} >> ${WOV_CONFIGFILE_MERGED} 2> /dev/null
+    if [ "$?" != "0" ]; then
+      F1=$(cat ${WOV_CONFIGFILE_MAINRAW} | jq type 2>&1)
+      F1a=$?
+      if [ "$F1a" != "0" ]; then printf "\n\nERROR: ${WOV_CONFIGFILE_MAIN} is not properly formatted.\n${F1}\n\n"; fi
+      F2=$(cat ${WOV_CONFIGFILE_MINERAW} | jq type 2>&1)
+      F2a=$?
+      if [ "$F2a" != "0" ]; then printf "\n\nERROR: ${WOV_CONFIGFILE_MINE} is not properly formatted.\n${F2}\n\n"; fi
+      exit 1;
+    fi
+  fi
+
+
+  # --------------------------------------------------------------------- 
+  # Load merged file in one call
+  MERGEDVARS=()
+  while read f; do
+    MERGEDVARS+=( "$f" )
+  done <<<$(cat ${WOV_CONFIGFILE_MERGED} | jq -r ". | ( .ver, .project.project, .project.type, .project.title, .project.description, .archive.repository, .archive.env  )" )
+  WOV_PVERSION=${MERGEDVARS[0]}
+  if [ "${WOV_PVERSION}" != "${WOV_VERSION}" ] && [ "${WOV_PVERSION}" != "initing" ] ; then
+    printf "\n\nERROR: Your project version '${WOV_PVERSION}', does not match to the WovTools version '${WOV_VERSION}'.\n\n"
+    exit 1
+  fi
+  export WOV_WPROJECT="${MERGEDVARS[1]}"
+  export WOV_PROJECTTYPE="${MERGEDVARS[2]}"
+  export WOV_PROJECTTITLE="${MERGEDVARS[3]}"
+  export WOV_PROJECTDESCRIPTION="${MERGEDVARS[4]}"
+  export WOV_ARCHIVEREPOSITORY="${MERGEDVARS[5]}"
+  export WOV_ARCHIVEENV="${MERGEDVARS[6]}"
+
+
+  # vars from Kubernetes
+  # --------------------------------------------------------------------- 
+  if [ "${WOV_CONTEXT}" == "" ]; then 
+    export WOV_CONTEXT="$(kubectl config current-context)"
+  fi
+  array=( ${WOV_CONTEXT//-/ } )
+  if [ "${#array[@]}" != "6" ]; then
+    echo "ERROR: bad context '${WOV_CONTEXT}'. Should be {ORIGIN:}CLTYPE-PROVIDER-REGION-FLAVOR-PROJECT-STAGE."
+    exit 1
+  fi
+  cltypearray=( ${array[0]//:/ } )
+  export WOV_KSTAGE="${array[5]}"
+  export WOV_KPROJECT="${array[4]}"
+  export WOV_NS="${WOV_KPROJECT}-${WOV_KSTAGE}"
+  export WOV_FLAVOR="${array[3]}"
+  export WOV_REGION="${array[2]}"
+  export WOV_PROVIDER="${array[1]}"
+
+  # if not passed in, load from file
+#  if [ "${WOV_ORIGIN}" == "" ]; then
+#    export WOV_ORIGIN=$(cat ${WOV_CONFIGFILE_MINERAW} | jq -r '.curorigin')
+#  fi
+
+  # from CONTEXT, set CLTYPE to ORIGIN:[CLTYPE] and if CLTYPE does not exist, it's because ORIGIN not set
+  export WOV_CLTYPE="${cltypearray[1]}"
+  if [ "${WOV_CLTYPE}" == "" ]; then
+    export WOV_CLTYPE="${cltypearray[0]}"
+#    >&2 echo "1) load from file if not set by commandline : ${WOV_ORIGIN}"
+    if [ "${WOV_ORIGIN}" == "" ]; then
+#      echo "4) pulling from file"
+      export WOV_ORIGIN=$(cat ${WOV_CONFIGFILE_MINERAW} | jq -r '.curorigin')
+    fi
+  else
+    if [ "${WOV_ORIGIN}" != "" ]; then
+#      echo "2) Ignore origin"
+      >&2 echo "WARNING: ORIGIN '${WOV_ORIGIN}' explicitly set on commandline. Ignoring origin from CONTEXT of '${cltypearray[0]}'."
+    else
+#      >&2 echo "3) Set to part of context"
+      export WOV_ORIGIN=${cltypearray[0]}
+    fi
+  fi
+  export WOV_CONTEXT="${WOV_CLTYPE}-${WOV_PROVIDER}-${WOV_REGION}-${WOV_FLAVOR}-${WOV_KPROJECT}-${WOV_KSTAGE}"
+  export WOV_CLUSTER="${WOV_CLTYPE}-${WOV_PROVIDER}-${WOV_REGION}-${WOV_FLAVOR}"
+  export WOV_WORKINGCONTEXT="${WOV_ORIGIN}:${WOV_CONTEXT}"
+#  echo "WOV_ORIGIN: ${WOV_ORIGIN}"
+#  echo "WOV_CONTEXT: ${WOV_CONTEXT}"
+#  echo "WOV_WORKINGCONTEXT: ${WOV_WORKINGCONTEXT}"
+
+
+  # --------------------------------------------------------------------- 
+  # Unifying
+  # --------------------------------------------------------------------- 
+  export WOV_STAGE="$WOV_KSTAGE"        # KSTAGE has priority since git repo might differ but want to build for current stage.
+  export WOV_PROJECT="${WOV_WPROJECT}"  
+
+  # echo "PROJECT ${WOV_PROJECT} KSTAGE ${WOV_KSTAGE}"
+
+
+  # --------------------------------------------------------------------- 
+  # vars computed from above
+  # --------------------------------------------------------------------- 
+  export WOV_CLUSTERDIR="${WOV_CACHEDIR}/clusters/${WOV_ORIGIN}__${WOV_CONTEXT}"
+#  mkdir -m 700 -p ${WOV_SECRETFILE_path}
+  export WOV_SECRETFILE=${WOV_CLUSTERDIR}/config.json
+
+}
+
+# if it is set to 0, skip, and all other cases load it up
+if [ "${ISWOVPROJECT}" == "0" ]; then ISWOVPROJECT=${ISWOVPROJECT}; else getWovProjectVars; fi
diff --git a/bin/wov-init b/bin/wov-init
--- a/bin/wov-init
+++ b/bin/wov-init
@@ -4,8 +4,47 @@ DOECHO=1
 DOFORCE=0
 FOLD=$(tput cols)
 
-# Don't have this yet
-WOV_BASEDIR=$(git rev-parse --show-toplevel)
+# first call, set WOV_BASEDIR to here
+WOV_BASEDIR=`pwd`
+ISWOVPROJECT="0"
+. wov-env-loader
+
+# --------------------------------------------------------------------- 
+# Work with ~/.wovtools file
+# --------------------------------------------------------------------- 
+if [ ! -e "${HOME}/.wovtools" ]; then
+  echo ""
+  echo "ERROR: no ~/.wovtools file. Need '.me' entry in that file."
+  exit 1
+fi
+WOV_ME=$(cat ${HOME}/.wovtools | jq -r '.me')
+
+# Check for necessary entries in .wovtools file
+Re=0
+EE=( ".me" )
+for p in "${EE[@]}"; do
+  R=$(cat ${HOME}/.wovtools | jq -r "${p}")
+  if [ "${R}" == "" ]; then
+    l_error "in ~/.wovtools, entry for '${p}' is ''."
+    Re=1
+  elif [ "${R}" == "null" ]; then
+    >&2 echo "ERROR: in ~/.wovtools, no entry for '${p}'"
+    Re=1
+  fi
+done
+if [ $Re -ne 0 ]; then exit 1; fi
+
+# Check for eventually needed entries in .wovtools file
+EE=( ".wovtools.secrets" ".archive.env" ".archive.repository" )
+for p in "${EE[@]}"; do
+  R=$(cat ${HOME}/.wovtools | jq -r "${p}")
+  if [ "${R}" == "" ]; then
+    l_warn "in ~/.wovtools, entry for '${p}' is ''. Fill it in later."
+  elif [ "${R}" == "null" ]; then
+    l_warn "in ~/.wovtools, no entry for '${p}'. Fill it in later."
+  fi
+done
+
 
 echo ""
 echo "`basename $0`"
@@ -43,16 +82,6 @@ function timeout_monitor() {
   echo "$*"
 }
 
-# --------------------------------------------------------------------- 
-# Work with ~/.wovtools file
-# --------------------------------------------------------------------- 
-if [ ! -e "${HOME}/.wovtools" ]; then
-  echo ""
-  echo "ERROR: no ~/.wovtools file. Need '.me' entry in that file."
-  exit 1
-fi
-WOV_ME=$(cat ${HOME}/.wovtools | jq -r '.me')
-
 
 # Ensure global entry for the project
 WOV_PROJDIR=$(cat ${HOME}/.wovtools | jq -r ".projects[\"${PROJECT}\"].dir")
@@ -61,6 +90,7 @@ if [ "${WOV_PROJDIR}" == "null" ]; then
   CWD=`pwd`
   cat ~/.wovtools | jq " .projects[\"${PROJECT}\"].dir = \"${CWD}\"" > ~/.wovtools.$$ && cp ~/.wovtools.$$ ~/.wovtools
 fi
+
 
 
 # ---------------------------------------------------------------------
@@ -87,7 +117,7 @@ function InitProject()
   if [ "$?" != "0" ]; then
     echo
     printf "Git repository has no remote repository to push code to. Set that up now, and enter URL below.\n"
-    printf "  Remote git repository : "
+    printf "  Remote git repository :  "
     read A
     if [ "${A}" == "" ]; then echo "ERROR: must provide a repository."; exit 1; fi
     git remote add origin $A
@@ -99,7 +129,6 @@ function InitProject()
 
   # ---------------------------------------------------------------------
   # Select user name
-  echo
   if [ "${WOV_USERNAME}" == "" ]; then WOV_USERNAME=$(git config user.name); fi
   printf "Enter your name (\"${WOV_USERNAME}\"): "
   read A
@@ -107,11 +136,17 @@ function InitProject()
 
   # ---------------------------------------------------------------------
   # Select user email
-  echo
   if [ "${WOV_USEREMAIL}" == "" ]; then WOV_USEREMAIL=$(git config user.email); fi
   printf "Enter your email (\"${WOV_USEREMAIL}\"): "
   read A
   if [ "${A}" != "" ]; then WOV_USEREMAIL="${A}"; fi
+
+#  # ---------------------------------------------------------------------
+#  # Select user code
+#  if [ "${WOV_ME}" == "" ]; then WOV_ME=$(cat ~/.wovtools | jq -r ".me"); fi
+#  printf "Enter your developer code (\"${WOV_ME}\"): "
+#  read A
+#  if [ "${A}" != "" ]; then WOV_ME="${A}"; fi
 
 
   # Ensure data is updated
@@ -120,7 +155,7 @@ function InitProject()
 
   # Ensure lines in .gitignore
   echo "... creating .gitignore"
-  LINES=("*.swp" ".DS_Store" "wovtools/secrets" "wovtools/cache" "wovtools/db/*.deltas" "wovtools/db/archive" "wovtools/local.json" "*.old" "*.orig" ".mochawesome-report" "*.log")
+  LINES=("*.swp" ".DS_Store" "wovtools/secrets" "wovtools/cache" "wovtools/db/*.deltas" "wovtools/db/archive" "${WOV_CONFIGFILE_MINE}" "*.old" "*.orig" ".mochawesome-report" "*.log")
   touch .gitignore
   for f in "${LINES[@]}"; do
     echo "  ... adding to .gitignore: $f"
@@ -134,17 +169,17 @@ function InitProject()
   # Create conf, k8s and containers directories
   mkdir -p ${WOV_BASEDIR}/wovtools/cache
   mkdir -p ${WOV_BASEDIR}/wovtools/data
-  mkdir -p ${WOV_BASEDIR}/wovtools/containers
+  mkdir -p ${WOV_BASEDIR}/wovtools/msrecipes
   mkdir -p ${WOV_BASEDIR}/wovtools/cmds
   mkdir -p ${WOV_BASEDIR}/wovtools/services
 
 
   # ---------------------------------------------------------------------
   # Create the config.json 
-  echo " ... check to create config.json"
-  if [ ! -e ${WOV_BASEDIR}/wovtools/config.json ]; then 
-    echo "   ... try to create config.json"
-    cat <<EOF > ${WOV_BASEDIR}/wovtools/config.json
+  echo " ... check to create '${WOV_CONFIGFILE_MAIN}'"
+  if [ ! -e "${WOV_CONFIGFILE_MAINRAW}" ]; then 
+    echo "   ... try to create '${WOV_CONFIGFILE_MAIN}'"
+    cat <<EOF > "${WOV_CONFIGFILE_MAINRAW}"
 {
   "ver" : "initing",
   "project" : {
@@ -161,7 +196,6 @@ function InitProject()
   "secrets" : {
     "dev" : [ 
       "cluster_defaults.json",
-      "cluster_myaccess.json",
       "cluster_mymanaged.json",
       "repositories.json",
       "${PROJECT}.json",
@@ -171,7 +205,6 @@ function InitProject()
     ],
     "prod" : [
       "cluster_defaults.json",
-      "cluster_myaccess.json",
       "cluster_mymanaged.json",
       "repositories.json",
       "${PROJECT}.json",
@@ -180,12 +213,11 @@ function InitProject()
       "${PROJECT}db_prod.json"
     ]
   },
-  "secretsmods": {
+  "originmods": {
     "local" : {
       "description" : "For deverlopers to develop locally.",
       "routes": [
-        [ "db.CLUSTERlocal",      "db"     ],
-        [ "appcore.CLUSTERlocal", "appcore"   ]
+        [ "${PROJECT}db.CLUSTERlocal",      "${PROJECT}db"     ]
       ]
     },
     "vh" : {
@@ -198,41 +230,40 @@ function InitProject()
 }
 EOF
   fi
-  echo "   ... exit to create config.json"
+  echo "   ... exit to create ${WOV_CONFIGFILE_MAIN}"
 
 
   # ---------------------------------------------------------------------
-  # Create the wovtools/local.json 
-  echo " ... check to create local.json"
-  if [ ! -e ${WOV_BASEDIR}/wovtools/local.json ]; then 
-    echo "   ... try to create local.json"
-    cat <<EOF > ${WOV_BASEDIR}/wovtools/local.json
+  # Create my config file
+  echo " ... check to create '${WOV_CONFIGFILE_MINE}'"
+  if [ ! -e "${WOV_CONFIGFILE_MINERAW}" ]; then 
+    echo "   ... try to create '${WOV_CONFIGFILE_MINE}'"
+    cat <<EOF > "${WOV_CONFIGFILE_MINERAW}"
 {
-  "ver-local" : 1,
-  "localcontext" : "local",
+  "ver-local" : 2,
+  "curorigin" : "local",
   "secrets" : {
     "${WOV_ME}" : [
-      "cluster_myaccess.json",
       "cluster_mymanaged.json",
       "repositories.json",
       "${PROJECT}.json",
       "${PROJECT}db.json",
-      "${PROJECT}_cw.json",
-      "${PROJECT}db_cw.json"
+      "${PROJECT}_${WOV_ME}.json",
+      "${PROJECT}db_${WOV_ME}.json"
     ]
   },
-  "secretsmods" : {
+  "originmods" : {
   }
 }
 EOF
 fi
-  echo "   ... created local.json"
+  echo "   ... created '${WOV_CONFIGFILE_MINE}'"
 
 
   # now commit so we can build branches
   # Build a git revision and all branches
   if [ "$ISNEWGIT" == "1" ]; then
-    git add .gitignore wovtools/config.json
+    git add .gitignore "${WOV_CONFIGFILE_MAIN}"
     git commit -a -m "initial commit"
   fi
 
@@ -259,7 +290,10 @@ fi
     git checkout -b dev || exit 1
     git push --set-upstream origin dev || exit 1
   fi
-  if [ "$(git rev-parse --verify master 2> /dev/null ; echo $?)" != "0" ]; then git branch -d master; echo "  ... deleting branch 'master' (prod will be default)"; fi
+  if [ "$(git rev-parse --verify master 2> /dev/null ; echo $?)" != "0" ]; then
+    echo "  ... deleting branch 'master' (prod will be default)"
+    git branch -d master 2>&1 > /dev/null
+  fi
 
 #    git push -f origin prod
 #  echo "TODO: set branch remote and make sure prod is the default"
@@ -290,17 +324,19 @@ fi
   # ---------------------------------------------------------------------
   # Create secrets repo
   # ---------------------------------------------------------------------
-  SECRETSDIR="`wov-cd -e secrets`/${WOV_ME}_secrets"
-  if [ "${SECRETSDIR}" == "" ]; then
-    echo "ERROR: Unknown secrets dir. Add an entry to ~/.wovtools, for : dirs.secrets.dir."
+
+  # pull location from global file, make sure directory exists, is chmodded and make our project secrets directory there
+  SECRETSDIR="`wov-cd -e secrets`"
+  if [ "${SECRETSDIR}" == "" ]; then echo "ERROR: Unknown secrets dir. Add an entry to ~/.wovtools, for : dirs.secrets.dir."; exit 1; fi
+  if [ ! -e "${SECRETSDIR}" ]; then mkdir -p "${SECRETSDIR}"; chmod 600 "${SECRETSDIR}"; fi
+  if [ ! -e "${SECRETSDIR}/${PROJECT}_secrets" ]; then mkdir -p "${SECRETSDIR}/${PROJECT}_secrets"; chmod 600 "${SECRETSDIR}/${PROJECT}_secrets"; fi
+
+  # remake the softlink
+  rm -f "${WOV_BASEDIR}/wovtools/secrets" || true
+  ln -s "${SECRETSDIR}/${PROJECT}_secrets" "${WOV_BASEDIR}/wovtools/secrets"
+  if [ "$?" != "0" ]; then
+    echo "ERROR: failed linking to '${SECRETSDIR}/${PROJECT}_secrets' at '${WOV_BASEDIR}/wovtools/secrets'."
     exit 1
-  fi
-  if [ ! -e "${WOV_BASEDIR}/wovtools/secrets" ]; then
-    ln -s "${SECRETSDIR}" "${WOV_BASEDIR}/wovtools/secrets"
-    if [ "$?" != "0" ]; then
-      echo "ERROR: failed linking to '${SECRETSDIR}' at '${WOV_BASEDIR}/wovtools/secrets'."
-      exit 1
-    fi
   fi
 
   # make sure default secret files exist
@@ -309,10 +345,12 @@ fi
 {
   "www" : {
     "STAGEdev" : {
-      "app"   : {"fullurl" : "http://app-dev.${PROJECT}.com"}
+      "api"   : {"urlscheme" : "https", "url" : "api-dev.${PROJECT}.com"},
+      "app"   : {"urlscheme" : "https", "url" : "app-dev.${PROJECT}.com"}
     },
     "STAGEprod" : {
-      "app"   : {"fullurl" : "http://app.${PROJECT}.com"}
+      "api"   : {"urlscheme" : "https", "url" : "api.${PROJECT}.com"},
+      "app"   : {"urlscheme" : "https", "url" : "app.${PROJECT}.com"}
     }
   }
 }
@@ -323,21 +361,27 @@ EOF
     cat <<EOF > "${WOV_BASEDIR}/wovtools/secrets/${PROJECT}db.json"
 {
   "${PROJECT}db" : {
-    "host"         : null,
-    "instancename" : "${PROJECT}",
+    "//subhost" : "combined with WOV_CLUSTER to create host name. if localhost, only localhost",
+    "subhost"      : "${PROJECT}dev",
     "username"     : "postgres",
-    "version"      : "9.6.11-R1",
-    "database"     : "",
-    "password"     : "",
-    "type"         : "postgres",
+    "endpoint"     : "unknown.rds.amazonaws.com",
+    "database"     : "${PROJECT}dev",
     "port"         : 5432,
-    "host"         : ".rds.amazonaws.com",
-
+    "type"         : "postgres",
+    "version"      : "9.6.11-R1",
+    "password"     : "$(openssl rand -hex 20)",
     "instanceAvailabilityZone"    : "c",
     "instanceAvailabilityZoneAlt" : "d",
     "instance" : {
       "class"   : "db.t2.small",
       "storage" : 20
+    },
+    "CLUSTERlocal" : {
+      "localdesc": "This is for connecting locally to a running system.",
+      "subhost"  : "localhost",
+      "endpoint" : "localhost",
+      "//port"   : "This is the ssh tunnel port opened through bastion.",
+      "port"     : 65432
     }
   }
 }
@@ -349,7 +393,12 @@ EOF
 {
   "//tokencmd" : "openssl rand -hex 20",
   "microservice" : { "STAGE${WOV_ME}" : { "token" : "GENERATE A TOKEN" } },
-  "www" : { "STAGE${WOV_ME}" : { "app" : { "urlscheme" : "https", "url" : "app-${WOV_ME}.${PROJECT}.com" } } }
+  "www" : {
+    "STAGE${WOV_ME}" : {
+      "api" : {"urlscheme" : "http", "url" : "localhost"},
+      "app" : {"urlscheme" : "http", "url" : "localhost"}
+    }
+  }
 }
 EOF
   fi
@@ -358,7 +407,7 @@ EOF
   if [ ! -e "${WOV_BASEDIR}/wovtools/secrets/${PROJECT}db_${WOV_ME}.json" ]; then 
     cat <<EOF > "${WOV_BASEDIR}/wovtools/secrets/${PROJECT}db_${WOV_ME}.json"
 {
-  "${PROJECT}db" : { "STAGE${WOV_ME}" : { "//" : "Separate database, should use separate user/pass", "database" : "" } }
+  "${PROJECT}db" : { "STAGE${WOV_ME}" : { "//" : "Separate database, should use separate user/pass", "database" : "${PROJECT}${WOV_ME}" } }
 }
 EOF
   fi
@@ -402,6 +451,7 @@ EOF
   fi
 
   WOV_DBREGISTRY=`git config --get remote.origin.url`
+  WOV_DBREGISTRY="${WOV_DBREGISTRY%.git}_db.git"
   if [ "$?" != "0" ]; then
     printf "\nERROR: remote origin is not set for this repository.\n"
     printf "  Use 'git remote add origin X' to set your remote repository.\n\n"
@@ -511,14 +561,11 @@ fi
 InitDBArchive
 
 echo "... loading WovTools values."
-pwd
 initargs=( "$@" )
 set ""
-. wov-env
+. wov-env-loader
 #. wov-ns-check
 set -- "${initargs[@]}"
-
-wov-env -e
 
 # ---------------------------------------------------------------------
 # query for new/updated data, overwriting env vars.
@@ -569,8 +616,9 @@ read A
 if [ "${A}" != "" ]; then WOV_ARCHIVEENV=${A}; fi
 
 
-echo "... writing 'wovtools/config.json'"
-jq ' .ver='${WOV_VERSION}' | .project.type="'"${WOV_PROJECTTYPE}"'" | .project.project="'"${WOV_PROJECT}"'"  | .project.title="'"${WOV_PROJECTTITLE}"'"  | .project.description="'"${WOV_PROJECTDESCRIPTION}"'" | .operation={} | .archive.env="'"${WOV_ARCHIVEENV}"'" | .archive.repository="'"${WOV_ARCHIVEREPOSITORY}"'"' ${WOV_BASEDIR}/wovtools/config.json > ${WOV_BASEDIR}/wovtools/.config.json.$$ && cp ${WOV_BASEDIR}/wovtools/.config.json.$$ ${WOV_BASEDIR}/wovtools/config.json
+echo "... writing '${WOV_CONFIGFILE_MAIN}'"
+touch "${WOV_CONFIGFILE_MAINRAW}"
+jq ' .ver='${WOV_VERSION}' | .project.type="'"${WOV_PROJECTTYPE}"'" | .project.project="'"${WOV_PROJECT}"'"  | .project.title="'"${WOV_PROJECTTITLE}"'"  | .project.description="'"${WOV_PROJECTDESCRIPTION}"'" | .operation={} | .archive.env="'"${WOV_ARCHIVEENV}"'" | .archive.repository="'"${WOV_ARCHIVEREPOSITORY}"'"' "${WOV_CONFIGFILE_MAINRAW}" > ${WOV_BASEDIR}/wovtools/.config.json.$$ && cp ${WOV_BASEDIR}/wovtools/.config.json.$$ "${WOV_CONFIGFILE_MAINRAW}"
 rm ${WOV_BASEDIR}/wovtools/.config.json.*
 
 
diff --git a/bin/wov-push-container b/bin/wov-push-container
--- a/bin/wov-push-container
+++ b/bin/wov-push-container
@@ -1,19 +1,10 @@
 #!/usr/bin/env bash
 
-DOECHO=1
-DOFORCE=0
-DOPUSH=1
-FOLD=$(tput cols)
-BLOCK=0
-DESTDIR=
-SRCDIR=
 
 # --------------------------------------------------------------------- 
 # --------------------------------------------------------------------- 
 function fDisplayOptions()
 { 
-  DDIR="${DESTDIR}"; if [ "${DDIR}" == "" ]; then DDIR="DESTDIR"; fi
-  SDIR="${SRCDIR}";  if [ "${SDIR}" == "" ]; then SDIR="SRCDIR"; fi
   cat <<EOF | fold -w ${FOLD} -s
 
 
@@ -28,17 +19,22 @@ ex. `basename $0` -f ggg hhh
 
 The recipes for containers should:
 
-1) copy code from ${SDIR} to the ${DDIR} directory
-  - where SRCDIR is the root of your git and DESTDIR is the root of the container to be built (i.e. wovtools/cache/containers/CONTAINER).
+1) copy MS code from PROJDIR or MSDIR to the DESTDIR directory
+  - MS is the name of your microservice which will be a single container
+  - CONTAINER is the name of the container (lower of MS), with PROJECT/CONTAINER being its repository name.
+  - PROJDIR is the root of your git
+  - MSDIR is the root of your microservice
+  - DESTDIR is the root of the container to be built (i.e. wovtools/cache/containers/MS).
+  - DOECHO determines logging levels: 0-quiet, 1-normal, 2-verbose
 
 2) create a sub-recipes to insert into the Dockerfile. There are BUILD and RUN stages, where BUILD contains ssh keys to access private repos. RUN tells the container how to run.
-  - ${DDIR}/SECRET/prebuild.docker - called before all files copied into container (do yarn installs here)
-  - ${DDIR}/SECRET/build.docker - all code is in the container
-  - ${DDIR}/SECRET/run.docker - instructions on how to run container
+  - DESTDIR/SECRET/prebuild.docker - called before all files copied into container (do yarn installs here)
+  - DESTDIR/SECRET/build.docker - all code is in the container
+  - DESTDIR/SECRET/run.docker - instructions on how to run container
 
   -p/P : do push, no push
   -h : this help
-  -l : list containers
+#  -l : list containers
   -f : force build
   -q/-v : quiet/verbose
 
@@ -46,58 +42,29 @@ EOF
 }
 
 
-if [ "$1" == "-h" ] || [ "$1" == "--help" ]; then
-  fDisplayOptions
-  exit 0
-fi
+
+
 
 # --------------------------------------------------------------------- 
 # Import Env 
 # --------------------------------------------------------------------- 
-#wov-env-build -q --local
-#if [ "$?" != "0" ]; then
-#  exit 1
-#fi
+. wov-env-ops fDisplayOptions $*
 
-echo "wov-push-container pre : ${WOV_PVER}"
-pushcontainersargs=( "$@" )
-set ""
-. wov-env --provider
-. <(wov-env --provider --exports)
-. wov-ns-check
-. wov-push-common
-set -- "${pushcontainersargs[@]}"
+#pushcontainersargs=( "$@" )
+#set ""
+##. wov-env --provider
+##. wov-ns-check
+#set -- "${pushcontainersargs[@]}"
 
-echo "wov-push-container post : ${WOV_PVER}"
-
-# For dev and prod, check local code and secrets are checked in and pushed.
-doGitChecksOnFormalStages 1
 
 
 # Globals
-RECIPES=( )
-CONTAINERNAME=
-CONTAINER=
-SRCDIR=${WOV_BASEDIR}
+DOFORCE=0
+DOPUSH=1
+RECIPES=
+DESTDIR=
 ARCHDIR=
-
-# echo "NOTE[$0]: Skipping git checks.... will do on wov-push."
-
-
-# If NodeJS project...
-if [ -e "${WOV_BASEDIR}/node_modules" ]; then
-  echo "  ... check for yarn 'linked' packages"
-  R3=( $(cd ${WOV_BASEDIR}/node_modules ; find * -type l -maxdepth 1) )
-  if [ "${R3}" != "" ]; then
-    printf "\n***ERROR: You have linked node modules.\n"
-    printf "\n*Linked NodeJS Modules:\n"
-    for l in ${R3[@]}; do
-      printf "*  : ${l}\n"
-    done
-    printf "*  ... yarn publish those, update package.json and then unlink with 'yarn unlink X'.\n\n"
-    exit 1
-  fi
-fi
+MSRECIPEDIR="${WOV_BASEDIR}/wovtools/msrecipes"
 
 
 
@@ -106,9 +73,13 @@ fi
 # ---------------------------------------------------------------------
 # Put contents together in container directory. Also builds Dockerfile.
 #  NOTE: later will decide if we need to build a container, based upon this
+# $1 - CONTAINER
+# $2 - MS
 # ---------------------------------------------------------------------
 function doPackContainer
 {
+  local CONTAINER="$1"
+  local MS="$2"
   # build the content in wovtools/cache/containers/$f
   mkdir -p ${DESTDIR}
   mkdir -p ${DESTDIR}/SECRET/sshkeys
@@ -117,7 +88,7 @@ function doPackContainer
   echo "" > ${DESTDIR}/Dockerfile
 
   echo "  ... pack container using recipe: '$f'"
-  cd ${WOV_BASEDIR} && SRCDIR=${SRCDIR} DESTDIR=${DESTDIR} CONTAINER=${CONTAINER} DOECHO=${DOECHO} ${WOV_BASEDIR}/wovtools/containers/$f
+  cd ${WOV_BASEDIR} && PROJDIR=${WOV_BASEDIR} MSDIR="${WOV_BASEDIR}/${f}" DESTDIR=${DESTDIR} MS=$f CONTAINER=${CONTAINER} DOECHO=${DOECHO} "${MSRECIPEDIR}/$f"
   if [ "$?" != "0" ]; then
     printf "\n\nERROR: failed building container.\n\n"
     exit 1
@@ -167,13 +138,13 @@ EOF
 
   # --------------------------------------------------------------------- 
   # start building Dockerfile for the container
-  _CONTAINERBASE="WOV_${WOV_PROJECT}${CONTAINERNAME}_containerfrom"
+  _CONTAINERBASE="WOV_${MS}_containerfrom"
   CONTAINERBASE=${!_CONTAINERBASE}
   if [ "${CONTAINERBASE}" == "null" ] || [ "${CONTAINERBASE}" == "" ]; then
-    printf "\nERROR: Docker container for '${repo}' has no known base to build from in secret: 'WOV_${WOV_PROJECT}${CONTAINERNAME}_containerfrom'.\n\n"
+    printf "\nERROR: Docker container for '${repo}' has no known base to build from in secret: 'WOV_${MS}_containerfrom'.\n\n"
     printf "   Check: \n"
     printf "     - secrets are rebuilt\n"
-    printf "     - secrets contain entry for '${WOV_PROJECT}.${CONTAINERNAME}.containerfrom'.\n"
+    printf "     - secrets contain entry for '${WOV_PROJECT}.${MS}.containerfrom'.\n"
     printf "     - secret file containing that entry is included in this stage (see wovtools/confing.json secrets.${WOV_STAGE})\n\n"
     exit 1
   fi
@@ -325,33 +296,62 @@ function doDockerizeContainer
 
 
 # ---------------------------------------------------------------------
-# List the container recipes we have.
+# Make sure it is ok
+# 
+# $1 - container name (sans project name)
+# $2 - microservice name
+# 
+# For now:
+#  - ensure package.json (if exists) is ok
 # ---------------------------------------------------------------------
-function doList()
+function doCheckPackedContainer
 {
-  C=$(ls ${WOV_BASEDIR}/wovtools/containers/* 2> /dev/null )
-  RETVAL=$?
-  if [ $RETVAL -eq 0 ]; then echo $C; else echo "No containers"; fi
+  local CHECKAS=''
+  if [[ $DOECHO -ge 1 ]]; then echo "...checking packed container : ${1}"; fi
+
+  # Determine container type
+  if [ -e "${DESTDIR}/package.json" ]; then
+    if [[ $DOECHO -ge 2 ]]; then echo "  ...found package.json : checking NodeJS container."; fi
+    CHECKAS='nodejs'
+  fi
+
+  # NodeJS
+  if [ "${CHECKAS}" == "nodejs" ]; then
+    local deps=( `cat ${DESTDIR}/package.json | jq -r '.dependencies | to_entries[] |  "\(.key) \(.value)"' 2> /dev/null ` )
+    # echo "deps: ${deps[@]}"
+
+    if [ -e ${WOV_BASEDIR}/$2/node_modules ]; then
+      echo "  ... checking linked npm packages are checked in and published"
+      R3=( $(cd ${WOV_BASEDIR}/$1/node_modules ; find * -type l -maxdepth 1) )
+      if [ "${R3}" != "" ]; then
+        printf "\n***ERROR: You have linked node modules.\n"
+        printf "TODO: see issue #50 : https://github.com/woveon/wovtools/issues/50\n"
+        printf "\n*Linked NodeJS Modules:\n"
+        for l in ${R3[@]}; do
+          wov-git-check "${WOV_BASEDIR}/${2}/node_modules/${l}"
+          local Re=$?
+          printf "*  : ${Re} - ${l}\n"
+        done
+        printf "*  ... yarn publish those, update package.json and then unlink with 'yarn unlink X'.\n\n"
+        exit 1
+      fi
+    fi
+  fi
+
+  l_ "  ...done checking packed container"
 }
 
-
 # --------------------------------------------------------------------- 
-# Push the container: pack, dockerize, push
+# Push the container: pack, dockerize, push.
+#  NOTE: container's name is microservice name, lower cased
+# $1 - name of the microservice.
 # --------------------------------------------------------------------- 
 function doPushContainer()
 {
-  CONTAINERNAME=$f
-  CONTAINER=${WOV_PROJECT}${CONTAINERNAME}
-  SRCDIR=${WOV_BASEDIR}
-  DESTDIR=${WOV_BASEDIR}/wovtools/cache/containers/${CONTAINERNAME}
-  ARCHDIR=${WOV_BASEDIR}/wovtools/cache/containers/archive/${CONTAINERNAME}
-  if [[ $DOECHO -ge 2 ]]; then 
-    echo "CONTAINERNAME=${CONTAINERNAME}"
-    echo "CONTAINER=${CONTAINER}"
-    echo "SRCDIR=${SRCDIR}"
-    echo "DESTDIR=${DESTDIR} # more like a 'content' dir as this is all copied in here"
-    echo "ARCHDIR=${ARCHDIR} # location of archive of DESTDIR"
-  fi
+  local MS=$1
+  local CONTAINER=$(echo ${MS} | tr '[:upper:]' '[:lower:]')
+  DESTDIR=${WOV_BASEDIR}/wovtools/cache/containers/${MS}
+  ARCHDIR=${WOV_BASEDIR}/wovtools/cache/containers/archive/${MS}
 
   mkdir -p ${ARCHDIR}
   if [ "$?" != "0" ]; then
@@ -359,16 +359,19 @@ function doPushContainer()
     exit 1
   fi
 
-  if [[ ! -e "${WOV_BASEDIR}/wovtools/containers/$f" ]]; then 
-    echo "ERROR: recipe for container ${f} does not exist (${WOV_BASEDIR}/wovtools/containers/$f).";
+  if [[ ! -e "${MSRECIPEDIR}/$f" ]]; then 
+    echo "ERROR: recipe for microservice container '${f}' does not exist in '${MSRECIPEDIR}'.";
     exit 1
-  elif [[ ! -x "${WOV_BASEDIR}/wovtools/containers/$f" ]]; then 
-    echo "ERROR: recipe for container ${f} not executable (${WOV_BASEDIR}/wovtools/containers/$f).";
+  elif [[ ! -x "${MSRECIPEDIR}/$f" ]]; then 
+    echo "ERROR: recipe for container ${f} not executable (${MSRECIPEDIR}/$f).";
     exit 1
   else
 
     # Copy in and generate all files in DESTDIR
-    doPackContainer ${f}
+    doPackContainer "${CONTAINER}" "${MS}"
+
+    # Ensure all is well
+    doCheckPackedContainer "${CONTAINER}" "${MS}"
 
     # Just packed container, do we need to build it? Do diffs against archive, then compare remote container
     NEEDSBUILD=0
@@ -380,7 +383,7 @@ function doPushContainer()
       fi
     else
       if [ $DOECHO -ge 2 ]; then echo "  ... check push container status"; fi
-      wov-push-container-check -q ${f}
+      wov-push-container-buildcheck -q ${CONTAINER} ${MS}
       NEEDSBUILD=$?
       if [ "$NEEDSBUILD" != "0" ]; then 
         if [ $DOECHO -ge 2 ]; then echo "  ... pushed containers differ so will build."; fi
@@ -407,8 +410,12 @@ function doPushContainer()
       if [ "${NEEDSBUILD}" == "1" ] || [ "${NEEDSBUILD}" == "5" ] || [ "${DOFORCE}" == "1" ]; then
         if [ $DOECHO -ge 1 ]; then echo "  ... container push needed"; fi
         if [ $DOECHO -ge 2 ]; then echo "    ... tag repo"; fi
-        echo "CMD: docker tag ${WOV_PROJECT}/${CONTAINER} ${WOV_ARCHIVEREPOSITORY}/${WOV_PROJECT}/${CONTAINER}:${WOV_STAGE}_${WOV_PVER}"
-        docker tag ${WOV_PROJECT}/${CONTAINER} ${WOV_ARCHIVEREPOSITORY}/${WOV_PROJECT}/${CONTAINER}:${WOV_STAGE}_${WOV_PVER}
+        #echo "CMD: docker tag ${WOV_PROJECT}/${CONTAINER} ${WOV_ARCHIVEREPOSITORY}/${WOV_PROJECT}/${CONTAINER}:${WOV_STAGE}_${WOV_PVER}"
+        docker tag ${WOV_PROJECT}/${CONTAINER} ${WOV_ARCHIVEREPOSITORY}/${WOV_PROJECT}/${CONTAINER}:${WOV_STAGE}_${WOV_PVER} ; Re=$?
+        if [ $Re -ne 0 ]; then
+          l_error "Failed to tag container: ${WOV_ARCHIVEREPOSITORY}/${WOV_PROJECT}/${CONTAINER}:${WOV_STAGE}_${WOV_PVER}"
+          exit 1
+        fi
 
         if [ $DOECHO -ge 2 ]; then echo "    ... push container to: ${WOV_ARCHIVEREPOSITORY}/${WOV_PROJECT}/${CONTAINER}:${WOV_STAGE}_${WOV_PVER}"; fi
 
@@ -416,10 +423,14 @@ function doPushContainer()
         # aws ecr describe-repositories --repository-names ${WOV_PROJECT}/${CONTAINER}
 
         # If just built, dump log, since it will have to push a lot of data
-        R=$(docker push ${WOV_ARCHIVEREPOSITORY}/${WOV_PROJECT}/${CONTAINER}:${WOV_STAGE}_${WOV_PVER} 2>&1 | tee /dev/tty )
-        RR=$?
-        if [[ $R == 'name unknown'* ]]; then
-          printf "\n\n    ...${R}.\n"
+        R=$(docker push ${WOV_ARCHIVEREPOSITORY}/${WOV_PROJECT}/${CONTAINER}:${WOV_STAGE}_${WOV_PVER} 2>&1 | tee /dev/tty ) ; Re=$?
+        #echo "R: ${Re} '${R}'"
+        if [ $Re -ne 0 ]; then 
+          l_error "Failed to push container: ${WOV_ARCHIVEREPOSITORY}/${WOV_PROJECT}/${CONTAINER}:${WOV_STAGE}_${WOV_PVER}"
+          exit 1
+        fi
+        if [[ $R == *"name unknown"* ]]; then
+          l_error "Create the repository in your Docker Repository (ECR): https://us-east-1.console.aws.amazon.com/ecr/repositories."
           exit 1
         fi
         if [[ $R == *'Your Authorization Token has expired.'* ]]; then
@@ -432,8 +443,8 @@ function doPushContainer()
           else
             echo "      ... SUCCESS auto-login to AWS attempt"
             echo "    ... re-push container to: ${WOV_ARCHIVEREPOSITORY}/${WOV_PROJECT}/${CONTAINER}:${WOV_STAGE}_${WOV_PVER}"
-            R=$(docker push ${WOV_ARCHIVEREPOSITORY}/${WOV_PROJECT}/${CONTAINER}:${WOV_STAGE}_${WOV_PVER} 2>&1  | tee /dev/tty)
-            if [ "$?" != "0" ]; then
+            R=$(docker push ${WOV_ARCHIVEREPOSITORY}/${WOV_PROJECT}/${CONTAINER}:${WOV_STAGE}_${WOV_PVER} 2>&1  | tee /dev/tty) ; Re=$?
+            if [ $Re -ne 0 ]; then
               printf "\n\n  ...still errors: ${R}.\n"
               exit 1
             fi
@@ -466,34 +477,26 @@ function doPushContainer()
 # ---------------------------------------------------------------------
 while [[ $1 =~ ^- ]]; do
 
-  if [ "$1" == "-q" ]; then
-    shift
-    DOECHO=0
-
-  elif [ "$1" == "-v" ]; then
-    shift
-    DOECHO=2
-
-  elif [ "$1" == "-p" ]; then
+  if [ "$1" == "-p" ]; then
     shift
     DOPUSH=1
+    WOV_DODEFAULTCOMMAND=1
 
   elif [ "$1" == "-P" ]; then
     shift
     DOPUSH=0
+    WOV_DODEFAULTCOMMAND=1
 
   elif [ "$1" == "-f" ]; then
     shift
     DOFORCE=1
+    WOV_DODEFAULTCOMMAND=1
 
-  elif [ "$1" == "-l" ]; then
+  elif [ "$1" == "--clean" ]; then
     shift
-    doList
-    BLOCK=1
-
-  elif [ "$1" == "-h" ] || [ "$1" == "--help" ]; then
-    fDisplayOptions
-    exit 0
+    l_ "cleaning container cache at : '${WOV_CACHEDIR}/containers'"
+    rm -Rf "${WOV_CACHEDIR}/containers"
+    WOV_DODEFAULTCOMMAND=0
 
   else
     echo
@@ -506,30 +509,45 @@ done
 
 
 # Find the recipes and push them
-if [ "${BLOCK}" == "0" ]; then
+if [ ${WOV_DODEFAULTCOMMAND} != 0 ]; then
 
-  if [ ! -e "${WOV_BASEDIR}/wovtools/containers" ]; then
-    printf "\nERROR: wovtools/containers directory does not exist. Should have container recipes there.\n\n"
+  . <(wov-env --provider --exports)
+  . wov-env-common
+  . wov-push-common
+
+  if [ ! -e "${MSRECIPEDIR}" ]; then
+    printf "\nERROR: 'wovtools/msrecipes' does not exist. Should have microservice container recipes there.\n\n"
     exit 1
   fi
 
+  # For dev and prod, check local code and secrets are checked in and pushed.
+  # echo "NOTE[$0]: Skipping git checks.... will do on wov-push."
+  doGitChecksOnFormalStages true
+
+  # Get Microservice Recipes from Commandline, or assume all otherwise
   RECIPES=( "$@" )
-  if [ "${#RECIPES[@]}" == "0" ]; then
-    # RECIPES=$(cd ${WOV_BASEDIR}/wovtools/containers && find * -maxdepth 0 -type f 2> /dev/null)
-    fGetContainerRecipes
-  fi
+  if [ "${#RECIPES[@]}" == "0" ]; then fGetMicroserviceRecipes; fi
 #  echo "R: ${RECIPES}"
 
-  # Build containers if needed
+  # Build MS if needed
   for f in ${RECIPES}; do
     if [ $DOECHO -ge 1 ]; then printf "\n%-${FOLD}s\n" "-" | tr ' ' '-' ; echo "... push container '${f}'."; fi
-    doPushContainer $@
+    if [ ! -e ${MSRECIPEDIR}/${f} ]; then
+      l_error "No recipe for container '${f}' in ${MSRECIPEDIR}."
+      exit 1
+    fi
+    if [ ! -e ${WOV_BASEDIR}/${f} ]; then
+      l_error "No '${f}' microservice directory in project."
+      exit 1
+    fi
+    doPushContainer $f
   done
 
   if [[ $DOECHO -ge 1 ]]; then
     printf "\nCompleted Building:\n"
-    for f in ${RECIPES}; do
-      echo "  ... built: ${WOV_PROJECT}/${WOV_PROJECT}${f}"
+    for r in ${RECIPES}; do
+      c=$(echo ${r} | tr '[:upper:]' '[:lower:]')
+      echo "  ... built microservice: '${r}'  container: '${WOV_PROJECT}/${c}'"
     done
     printf "    run locally: 'docker run CONTAINER'\n"
     printf "     open shell: 'docker run --rm -it CONTAINER bash'\n"
diff --git a/bin/wov-push-db b/bin/wov-push-db
--- a/bin/wov-push-db
+++ b/bin/wov-push-db
@@ -1,32 +1,5 @@
 #!/usr/bin/env bash
 
-
-# --------------------------------------------------------------------- 
-# Import Env 
-# --------------------------------------------------------------------- 
-wov-env-build -q --local
-if [ "$?" != "0" ]; then
-  exit 1
-fi
-
-pushenvargs=( "$@" )
-set ""
-. wov-env --provider
-. wov-db-common
-. wov-ns-check
-set -- "${pushenvargs[@]}"
-
-
-DOECHO=1
-DOFORCE=0
-FOLD=$(tput cols)
-DOACTION="commit"
-SKIPGITCHECKS=0
-
-# For dev and prod, check local code and secrets are checked in and pushed.
-doGitChecksOnFormalStages 1
-
-
 # ---------------------------------------------------------------------
 # ---------------------------------------------------------------------
 function fDisplayOptions()
@@ -59,13 +32,23 @@ EOF
 }
 
 
+# ---------------------------------------------------------------------
+# Import Env
+# ---------------------------------------------------------------------
+. wov-env-ops fDisplayOptions $*
+
+DOFORCE=0
+DOACTION="commit"
+SKIPGITCHECKS=0
+
+
 function fFailedDBConnection()
 {
   local RET=$1
   if [ "$2" != "" ]; then
     printf "  > Is db inited?\n"
-    printf "    - init>        'wov-db-connect ${2} -db-init'\n"   
-    printf "    - get version> 'wov-db-connect $2 --db-ver'\n"
+    printf "    - init>        'wov-db ${2} --wdb-init'\n"   
+    printf "    - get version> 'wov-db $2 --wdb-ver'\n"
     printf "\n"
     printf "\n"
   fi
@@ -81,7 +64,7 @@ function fFailedDBConnection()
 # --------------------------------------------------------------------- 
 #function doGetDBSchema()
 #{
-#  local SCHEMA=$(wov-db-connect $1 --schema 2> /dev/null)
+#  local SCHEMA=$(wov-db $1 --schema 2> /dev/null)
 #  if [ "$?" != "0" ]; then printf "\n\nERROR: failed to connect to database server $i.\n"; exit 1; fi
 #  echo ${SCHEMA}
 #}
@@ -92,14 +75,14 @@ function fFailedDBConnection()
 function doHashDBSchema()
 {
   local HASH=0
-  HASH="$(wov-db-connect $1 --schema 2> /dev/null)"; local A=$?
+  HASH="$(wov-db $1 --schema 2> /dev/null)"; local A=$?
   #echo "here1 - $A '$HASH' "
   if [ $A -ne 0 ]; then 
     echo $HASH
     exit 1
   fi
   #echo "here 2 $A $SCK"
-  #local CHKSUM=$(wov-db-connect $1 --schema 2> /dev/null | shasum -a 256 | cut -d' ' -f1)
+  #local CHKSUM=$(wov-db $1 --schema 2> /dev/null | shasum -a 256 | cut -d' ' -f1)
   local CHKSUM=$(echo "${HASH}" | shasum -a 256 | cut -d' ' -f1)
   local A=$?
   #echo "here2 - $A $HASH $CHKSUM"
@@ -120,13 +103,13 @@ function doHashDBSchema()
 function doGetDBPVER()
 {
   local retval=1
-  R=$(wov-db-connect $1 --db-ver 2>&1) ; Re=$?
+  R=$(wov-db $1 --wdb-ver 2>&1) ; Re=$?
   if [ $Re -eq 0 ]; then
     local DB_PVER=`echo ${R} | cut -d'|' -f5`
     retval=0;
   fi
 
-#  DBRAW=$(wov-db-connect $i -d wovtools -c "SELECT * FROM logs WHERE database='$1' ORDER BY id DESC LIMIT 1;" 2>&1) ; DBRAWe=$?
+#  DBRAW=$(wov-db $i -d wovtools -c "SELECT * FROM logs WHERE database='$1' ORDER BY id DESC LIMIT 1;" 2>&1) ; DBRAWe=$?
 #  if [ "$DBRAWe" != "0" ]; then 
 #    printf "${DBRAW}\n"
 #    printf "\nERROR: failed to connect to database wovtools, table logs, on database server $1.\n\n"; 
@@ -146,7 +129,7 @@ function doGetDBPVER()
 function doGetDBLastLogEntry()
 {
   local retval=1
-  local DB_PVER=$(wov-db-connect $i -q -d wovtools -c "SELECT * FROM logs WHERE database='$1' ORDER BY id DESC LIMIT 1;" 2> /dev/null)
+  local DB_PVER=$(wov-db $i -q -d wovtools -c "SELECT * FROM logs WHERE database='$1' ORDER BY id DESC LIMIT 1;" 2> /dev/null)
   if [ "$?" != "0" ]; then 
     printf "\n\nERROR: failed to find wovtools logs on database server $1.\n\n"; 
     fFailedDBConnection 1 $1
@@ -198,7 +181,7 @@ function doPushCheck()
     fi
     DB_PVER=$(doGetDBPVER $1)
     if [ "$?" != "0" ] || [ "$DB_PVER" == "" ]; then
-      printf "${DB_PVER}\nERROR: could not get database version.\n"
+      l_error "${DB_PVER}\nERROR: could not get database version.\n"
       fFailedDBConnection 2 $1
     elif [ ! -e ${WOV_BASEDIR}/wovtools/db/archive/${1}.json ]; then 
       printf "\nERROR: no archive/${1}.json.\n"; 
@@ -278,8 +261,8 @@ function doPushCheck()
       elif [ "${chk_1}" == "T" ]; then # 4 is false then
         printf "FAILED: if you have db schema changes, you need to have deltas in archive to account.\n"
         printf "\n  run: 'wov-push-db -v --any-push-blockage' for more info.\n"
-        printf "\nTo get current schema of database X: 'wov-db-connect DBNAME --schema' (ex. apidb)\n"
-        printf "To diff schema to old version X : 'wov-db-connect DBNAME --schema-diff X'\n"
+        printf "\nTo get current schema of database X: 'wov-db DBNAME --schema' (ex. apidb)\n"
+        printf "To diff schema to old version X : 'wov-db DBNAME --schema-diff X'\n"
   #    elif [ "${chk_4}" == "T" ]; then # 1 is false then
   #      printf "FAILED: if you have deltas in archive, you need to have db schema changes to account.\n"
       fi
@@ -423,7 +406,7 @@ EOF
     # - 2.1 save schema ---------------------------------------------------
     # --------------------------------------------------------------------- 
     mkdir -p ${WOV_BASEDIR}/wovtools/db/archive/$1/schemas
-    wov-db-connect ${1} --schema > ${WOV_BASEDIR}/wovtools/db/archive/$1/schemas/${WOV_PVER}.schema
+    wov-db ${1} --schema > ${WOV_BASEDIR}/wovtools/db/archive/$1/schemas/${WOV_PVER}.schema
     r=$?
     if [ "$r" != "0" ]; then
       printf "\n\nERROR: failed to write schemas to regsitry.\n\n"
@@ -459,7 +442,7 @@ EOF
     # - 4. update archive database log pver number, snapshot, checksum ----
     # --------------------------------------------------------------------- 
     echo "  ... update archive database logs"
-    R=$(wov-db-connect $1 -q -d wovtools -c "INSERT INTO logs (database, wovtoolsver, label, pver, sver, snapshot ) VALUES ( '$1', '${WOV_VERSION}', '${WOV_PVER}_${WOV_SVER}', ${WOV_PVER}, ${WOV_SVER}, '${DB_snapshot}' );")
+    R=$(wov-db $1 -q -d wovtools -c "INSERT INTO logs (database, wovtoolsver, label, pver, sver, snapshot ) VALUES ( '$1', '${WOV_VERSION}', '${WOV_PVER}_${WOV_SVER}', ${WOV_PVER}, ${WOV_SVER}, '${DB_snapshot}' );")
     if [ "$?" != "0" ]; then
       printf "${R}"
       printf "\n\nERROR: failed updating archive database pver number with checksum.\n"
@@ -514,15 +497,7 @@ EOF
 # ---------------------------------------------------------------------
 while [[ $1 =~ ^- ]]; do
 
-  if [ "$1" == "-q" ]; then
-    shift
-    DOECHO=0
-
-  elif [ "$1" == "-v" ]; then
-    shift
-    DOECHO=2
-
-  elif [ "$1" == "--log" ]; then
+  if [ "$1" == "--log" ]; then
     DOACTION="log"
     shift
 
@@ -557,80 +532,95 @@ while [[ $1 =~ ^- ]]; do
 done
 
 
+if [ ${WOV_DODEFAULTCOMMAND} != 0 ]; then
 
-#echo "... starting"
-retval=1
-if [ "$DOACTION" == "check" ]; then
+  # Load in env
+  . <(wov-env --provider --exports)
+  . wov-env-common
+  . wov-push-common
+  . wov-db-common
 
-  DATABASES=( $(doFindDatabases $*) )
-  # echo "DATABASES: ${DATABASES[@]}"
-  if [ "${#DATABASES[@]}" == "0" ]; then
-    if [ $DOECHO -ge 1 ]; then printf "... no databases to check.\n"; fi
-  fi 
+  # For dev and prod, check local code and secrets are checked in and pushed.
+  doGitChecksOnFormalStages 1
+  exitval=$?
 
-  # check each db
-  retval=0
-  for i in "${DATABASES[@]}"; do
-    doPushCheck $i
-    r=${?}
-    if [ "$r" != "0" ]; then retval=1; fi
-  done
-  # printf "\nAny blockage to pushing?:$R1\n\n"
+  if [ $exitval == 0 ]; then
 
-elif [ "$DOACTION" == "log" ]; then
-  DATABASES=( $(doFindDatabases $*) )
+    #echo "... starting"
+    exitval=1
+    if [ "$DOACTION" == "check" ]; then
 
-  # check each db
-  retval=0
-  for i in "${DATABASES[@]}"; do
-    printf "  ... check db '$i'\n"
-    CHKSUM=$(doHashDBSchema $i)
-    r=${?}
-    # printf "    ... CHKSUM ${CHKSUM}\n"
-    if [ "$r" != "0" ]; then retval=1; fi
-    LLE=$(doGetDBLastLogEntry $i)
-    r=${?}
-    # printf "    ... LLE ${LLE}\n"
-    if [ "$r" != "0" ]; then retval=1; fi
-    DBVER=$(doGetDBPVER $i)
-    r=${?}
-    # printf "    ... DBVER ${DBVER}\n"
-    if [ "$r" != "0" ]; then retval=1; fi
-    echo "$i> ver:${DBVER}  chksum:${CHKSUM} lle:${LLE}"
-  done
+      DATABASES=( $(doFindDatabases $*) )
+      # echo "DATABASES: ${DATABASES[@]}"
+      if [ "${#DATABASES[@]}" == "0" ]; then
+        if [ $DOECHO -ge 1 ]; then printf "... no databases to check.\n"; fi
+      fi 
 
-elif [ "$DOACTION" == "checksum" ]; then
+      # check each db
+      exitval=0
+      for i in "${DATABASES[@]}"; do
+        doPushCheck $i
+        r=${?}
+        if [ "$r" != "0" ]; then exitval=1; fi
+      done
+      # printf "\nAny blockage to pushing?:$R1\n\n"
 
-  DATABASES=( $(doFindDatabases $*) )
-  # echo "DATABASES: ${DATABASES[@]}"
+    elif [ "$DOACTION" == "log" ]; then
+      DATABASES=( $(doFindDatabases $*) )
 
-  # check each db
-  retval=0
-  for i in "${DATABASES[@]}"; do
-    CHKSUM=$(doHashDBSchema $i)
-    r=${?}
-    if [ "$r" != "0" ]; then retval=1; fi
-    echo "${CHKSUM} $i"
-  done
+      # check each db
+      exitval=0
+      for i in "${DATABASES[@]}"; do
+        printf "  ... check db '$i'\n"
+        CHKSUM=$(doHashDBSchema $i)
+        r=${?}
+        # printf "    ... CHKSUM ${CHKSUM}\n"
+        if [ "$r" != "0" ]; then exitval=1; fi
+        LLE=$(doGetDBLastLogEntry $i)
+        r=${?}
+        # printf "    ... LLE ${LLE}\n"
+        if [ "$r" != "0" ]; then exitval=1; fi
+        DBVER=$(doGetDBPVER $i)
+        r=${?}
+        # printf "    ... DBVER ${DBVER}\n"
+        if [ "$r" != "0" ]; then exitval=1; fi
+        echo "$i> ver:${DBVER}  chksum:${CHKSUM} lle:${LLE}"
+      done
 
-elif [ "$DOACTION" == "commit" ]; then
+    elif [ "$DOACTION" == "checksum" ]; then
 
-  DATABASES=( $(doFindDatabases $*) )
-#  echo "DATABASES: ${DATABASES[@]}"
-#  if [ "${#DATABASES[@]}" == "0" ]; then
-#    echo "no databases found"
-#  fi
+      DATABASES=( $(doFindDatabases $*) )
+      # echo "DATABASES: ${DATABASES[@]}"
 
-  doCommit
-  retval=$?
-  # echo $R
-else
-  printf "\n\nERROR: unknown action to take!?! '$DOACTION'.\n"
-  fDisplayOptions
-  exit 1
+      # check each db
+      exitval=0
+      for i in "${DATABASES[@]}"; do
+        CHKSUM=$(doHashDBSchema $i)
+        r=${?}
+        if [ "$r" != "0" ]; then exitval=1; fi
+        echo "${CHKSUM} $i"
+      done
+
+    elif [ "$DOACTION" == "commit" ]; then
+
+      DATABASES=( $(doFindDatabases $*) )
+      #  echo "DATABASES: ${DATABASES[@]}"
+      #  if [ "${#DATABASES[@]}" == "0" ]; then
+      #    echo "no databases found"
+      #  fi
+
+      doCommit
+      exitval=$?
+      # echo $R
+    else
+      printf "\n\nERROR: unknown action to take!?! '$DOACTION'.\n"
+      fDisplayOptions
+      exit 1
+    fi
+  fi
+
+
+
+  #echo "exitval $exitval"
+  exit $exitval
 fi
-
-
-
-#echo "retval $retval"
-exit $retval
diff --git a/bin/wov-push-k8s b/bin/wov-push-k8s
--- a/bin/wov-push-k8s
+++ b/bin/wov-push-k8s
@@ -1,10 +1,34 @@
 #!/usr/bin/env bash
 
-DOECHO=1
-DOFORCE=0
-FOLD=`tput cols`
-COMMAND="push"
+# ---------------------------------------------------------------------
+# ---------------------------------------------------------------------
+function fDisplayOptions()
+{
+  cat <<EOF | fold -w ${FOLD} -s
 
+
+usage: `basename $0` [options]
+
+Pushes the Kubernetes files to the archive. Makes sure they are built and then pushes the conf and k8s to the Archive, from which we can deploy. This works with pushing secrets and containers into the Archive (which is actually several storage mediums).
+
+  --conf-ext    : extension to the default conf file (ex. foo/conf/cm/apisocket -> foo/conf/cm/apisocket-vh with --conf-ext '-vh')
+#  --nogitchecks : turns off the checks for changes to local code
+
+#  -f : force push
+  -h : this help
+  -q/-v : quiet/verbose
+
+EOF
+}
+
+
+# ---------------------------------------------------------------------
+# Import Env
+# ---------------------------------------------------------------------
+. wov-env-ops fDisplayOptions $*
+
+RESULT=0
+COMMAND="push"
 CONFEXT=
   # added to conf dir names (ex. "-vh" for vh specific)
 
@@ -13,61 +37,62 @@ CONFEXT=
 # --------------------------------------------------------------------- 
 # Import Env 
 # --------------------------------------------------------------------- 
-if [ ! -z ${WOV_stagemod+x} ]; then
-  printf "\nERROR: Can't have WOV_stagemod set when pushing content.\n\n"
-  exit 1
-fi
-pushenvargs=( "$@" )
-set ""
-. wov-env --provider
-. wov-ns-check
-. wov-push-common
-set -- "${pushenvargs[@]}"
+#if [ ! -z ${WOV_stagemod+x} ]; then
+#  printf "\nERROR: Can't have WOV_stagemod set when pushing content.\n\n"
+#  exit 1
+#fi
+#pushenvargs=( "$@" )
+#set ""
+#. wov-ns-check
+#set -- "${pushenvargs[@]}"
 
 
 
 # ---------------------------------------------------------------------
-# $1 cluster
 # ---------------------------------------------------------------------
 function doPushClusterToArchiveChecks()
 {
-  local CLUSTER="$1"
-  local CLUSTERDIR="${WOV_CACHEDIR}/clusters/${CLUSTER}"
-  local ARCHPATH="`getRelativeArchivePath ${CLUSTER}`"
   local retval=0
 
-  for container in ${RECIPES[@]}; do
+  if [ "${WOV_ORIGIN}" != "self" ]; then
+    l_warn "Cannot push Cluster Configuration to Archive that is not set to Origin self. WOV_ORIGIN is '${WOV_ORIGIN}'"
+    retval=1
+  else
+    local ARCHPATH="`getRelativeArchivePath ${WOV_CLUSTER}`"
 
-    # each container should have a cm
-    if [ ! -e "${CLUSTERDIR}/cm/${WOV_PROJECT}${container}" ]; then
-      echo "WARNING: container '${WOV_PROJECT}${container}' has no K8s ConfigMap file.";
+    for ms in ${RECIPES[@]}; do
+
+      # each ms should have a cm
+      if [ ! -e "${WOV_CLUSTERDIR}/cm/${ms}" ]; then
+        l_warn "microservice '${ms}' has no K8s ConfigMap file.";
+        retval=1;
+      fi
+
+      # each microservice should have a secrets file
+      if [ ! -e "${WOV_CLUSTERDIR}/se/${ms}" ]; then
+        l_warn "microservice '${ms}' has no K8s Secrets file.";
+        retval=1;
+      fi
+
+      # each microservice should have a k8s deployment file
+      if [ ! -e "${WOV_CLUSTERDIR}/k8s/${ms}.yaml" ]; then
+        l_warn "microservice '${ms}' has no K8s Deployment file.";
+        retval=1;
+      fi
+
+      # each microservice should have a k8s service file
+      if [ ! -e "${WOV_CLUSTERDIR}/k8s/${ms}-service.yaml" ]; then
+        l_warn "microservice '${ms}' has no K8s Service file.";
+        retval=1;
+      fi
+
+    done
+
+    # each cluster should have a k8s ingress file
+    if [ ! -e "${WOV_CLUSTERDIR}/k8s/${WOV_PROJECT}-ingress.yaml" ]; then
+      l_warn "project '${WOV_PROJECT}' has no K8s Ingress file ${WOV_PROJECT}-ingress.yaml.";
       retval=1;
     fi
-
-    # each container should have a secrets file
-    if [ ! -e "${CLUSTERDIR}/se/${WOV_PROJECT}${container}" ]; then
-      echo "WARNING: container '${WOV_PROJECT}${container}' has no K8s Secrets file.";
-      retval=1;
-    fi
-
-    # each container should have a k8s deployment file
-    if [ ! -e "${CLUSTERDIR}/k8s/${WOV_PROJECT}${container}.yaml" ]; then
-      echo "WARNING: container '${WOV_PROJECT}${container}' has no K8s Deployment file.";
-      retval=1;
-    fi
-
-    # each container should have a k8s service file
-    if [ ! -e "${CLUSTERDIR}/k8s/${WOV_PROJECT}${container}-service.yaml" ]; then
-      echo "WARNING: container '${WOV_PROJECT}${container}' has no K8s Service file.";
-      retval=1;
-    fi
-
-  done
-
-  # each cluster should have a k8s ingress file
-  if [ ! -e "${CLUSTERDIR}/k8s/${WOV_PROJECT}-ingress.yaml" ]; then
-    echo "WARNING: cluster '${WOV_PROJECT}' has no K8s Ingress file ${WOV_PROJECT}-ingress.yaml.";
-    retval=1;
   fi
 
   return $retval
@@ -79,50 +104,85 @@ function doPushClusterToArchiveChecks()
 # ---------------------------------------------------------------------
 function doPushClusterToArchive() 
 {
-  local CLUSTER="$1"
-  local CLUSTERDIR="${WOV_CACHEDIR}/clusters/${CLUSTER}"
-  local ARCHPATH="`getRelativeArchivePath ${CLUSTER}`"
+  local ARCHPATH="`getRelativeArchivePath ${WOV_CLUSTER}`"
 
 
-  if [ $DOECHO -ge 1 ]; then echo "  ... building cluster configuration: '${CLUSTER}'"; fi
-  wov-env-build -q --cluster ${CLUSTER}
-  A=$?
-  if [ "$A" != "0" ]; then exit $A; fi
+  # already set and built by now
+  #l_  "  ... building cluster configuration: '${WOV_CLUSTER}'"
+  #wov-env-build -q --cluster ${CLUSTER}
+  #A=$?
+  #if [ "$A" != "0" ]; then exit $A; fi
 
-  if [ $DOECHO -ge 1 ]; then echo "  ... pushing to archive: '${WOV_ARCHIVEENV}/${ARCHPATH}'"; fi
-  if [ $DOECHO -ge 2 ]; then echo "$(cd ${CLUSTERDIR} ; ls -d * */* )"; fi
-  A1=$(cd ${CLUSTERDIR} ; aws s3 sync cm  ${WOV_ARCHIVEENV}/${ARCHPATH}/cm  --delete)
-  if [ "${A1}" != "" ]; then printf "$A1\n"; fi
-  A2=$(cd ${CLUSTERDIR} ; aws s3 sync se  ${WOV_ARCHIVEENV}/${ARCHPATH}/se  --delete)
-  if [ "${A2}" != "" ]; then printf "$A2\n"; fi
-  A3=$(cd ${CLUSTERDIR} ; aws s3 sync k8s ${WOV_ARCHIVEENV}/${ARCHPATH}/k8s --delete)
-  if [ "${A3}" != "" ]; then printf "$A3\n"; fi
+  l_ "  ... pushing to archive: '${WOV_ARCHIVEENV}/${ARCHPATH}'"
+  l_verbose "$(cd ${WOV_CLUSTERDIR} ; ls -d * */* )"
+  R=$(cd ${WOV_CLUSTERDIR} ; aws s3 sync cm  ${WOV_ARCHIVEENV}/${ARCHPATH}/cm  --delete)
+  if [ "${R}" != "" ]; then printf "$R\n"; fi
+  R=$(cd ${WOV_CLUSTERDIR} ; aws s3 sync se  ${WOV_ARCHIVEENV}/${ARCHPATH}/se  --delete)
+  if [ "${R}" != "" ]; then printf "$R\n"; fi
+  R=$(cd ${WOV_CLUSTERDIR} ; aws s3 sync k8s ${WOV_ARCHIVEENV}/${ARCHPATH}/k8s --delete)
+  if [ "${R}" != "" ]; then printf "$R\n"; fi
 
-  if [ $DOECHO -ge 1 ]; then echo "  ... success"; fi
+  l_ "  ... success"
 }
 
+
 # ---------------------------------------------------------------------
+# For each named cluster, push to archive
 # ---------------------------------------------------------------------
-function fDisplayOptions()
+function doPushK8sPush()
 {
-  cat <<EOF | fold -w ${FOLD} -s
-
-
-usage: `basename $0` [options] cluster ...
-
-Pushes the Kubernetes files to the archive. Makes sure they are built and then pushes the conf and k8s to the Archive, from which we can deploy. This works with pushing secrets and containers into the Archive (which is actually several storage mediums).
-
-  cluster ...   : the cluster to send
-
-  --conf-ext    : extension to the default conf file (ex. foo/conf/cm/apisocket -> foo/conf/cm/apisocket-vh with --conf-ext '-vh')
-  --nogitchecks : turns off the checks for changes to local code
-
-  -f : force push
-  -h : this help
-  -q/-v : quiet/verbose
-
-EOF
+  local retval=0
+#  for cluster in "${CLUSTERS[@]}"; do
+#    echo "Push to Archive for Cluster: $cluster"
+#    doPushClusterToArchiveChecks ${cluster}
+#    if [ $? != 0 ]; then
+#      echo "  ... skipping cluster push due to warnings."
+#      retval=2
+#    else
+#      doPushClusterToArchive ${cluster}
+#    fi
+#  done
+  doPushClusterToArchiveChecks
+  if [ $? != 0 ]; then
+    l_error "Skipping push due to warnings."
+    retval=2
+  else
+    echo "Push to Archive for Cluster: $WOV_CLUSTER"
+    doPushClusterToArchive
+    retval=$?
+    if [ $? != 0 ]; then
+      l_error "  ... failed"
+    else
+      l_ "  ... success"
+    fi
+  fi
+  return $retval
 }
+
+
+# ---------------------------------------------------------------------
+# ---------------------------------------------------------------------
+function doPushK8sCheck()
+{
+  local retval=0
+#  for cluster in "${CLUSTERS[@]}"; do
+#    echo "Check K8s files for Cluster: $cluster"
+#    doPushClusterToArchiveChecks ${cluster}
+#    if [ $? != 0 ]; then
+#      echo "  ... skipping cluster push due to warnings."
+#      retval=2
+#    fi
+#  done
+  l_ "Check K8s files for Cluster: $WOV_CLUSTER"
+  doPushClusterToArchiveChecks
+  if [ $? != 0 ]; then
+    retval=2
+  else
+    l_ "  ... success"
+  fi
+  return $retval
+}
+
 
 
 # ---------------------------------------------------------------------
@@ -130,34 +190,22 @@ EOF
 # ---------------------------------------------------------------------
 while [[ $1 =~ ^- ]]; do
 
-  if [ "$1" == "-q" ]; then
-    shift
-    DOECHO=0
+#  elif [ "$1" == "--nogitchecks" ]; then
+#    shift
+#    NOGITCHECK=1
 
-  elif [ "$1" == "-v" ]; then
-    shift
-    DOECHO=2
-
-  elif [ "$1" == "--nogitchecks" ]; then
-    shift
-    NOGITCHECK=1
-
-  elif [ "$1" == "--conf-ext" ]; then
+  if [ "$1" == "--conf-ext" ]; then
     shift
     CONFEXT=$1
     shift
 
+  elif [ "$1" == "--push" ]; then
+    shift
+    COMMAND="push"
+
   elif [ "$1" == "--check" ]; then
     shift
     COMMAND="check"
-
-  elif [ "$1" == "-f" ]; then
-    shift
-    DOFORCE=1
-
-  elif [ "$1" == "-h" ] || [ "$1" == "--help" ]; then
-    fDisplayOptions
-    exit 0
 
   else
     echo
@@ -169,63 +217,51 @@ while [[ $1 =~ ^- ]]; do
 done
 
 
-# For dev and prod, check local code and secrets are checked in and pushed.
-doGitChecksOnFormalStages 1
 
-CLUSTERS=( $* )
-if [ "${#CLUSTERS}" == "0" ]; then
-  CLUSTERS=( "${WOV_CLUSTER}" )
-fi
+if [ ${WOV_DODEFAULTCOMMAND} != 0 ]; then
 
-# get the names of containers
-fGetContainerRecipes
+  # Load in env
+  . <(wov-env --provider --exports)
+  . wov-env-common
+  . wov-push-common
 
+  # get the names of microservices
+  fGetMicroserviceRecipes
 
-# ---------------------------------------------------------------------
-# For each named cluster, push to archive
-# ---------------------------------------------------------------------
-function doPushK8sPush()
-{
-  local retval=0
-  for cluster in "${CLUSTERS[@]}"; do
-    echo "Push to Archive for Cluster: $cluster"
-    doPushClusterToArchiveChecks ${cluster}
-    if [ $? != 0 ]; then
-      echo "  ... skipping cluster push due to warnings."
-      retval=2
-    else
-      doPushClusterToArchive ${cluster}
-    fi
-  done
-  return $retval
-}
-
-function doPushK8sCheck()
-{
-  local retval=0
-  for cluster in "${CLUSTERS[@]}"; do
-    echo "Check K8s files for Cluster: $cluster"
-    doPushClusterToArchiveChecks ${cluster}
-    if [ $? != 0 ]; then
-      echo "  ... skipping cluster push due to warnings."
-      retval=2
-    fi
-  done
-  return $retval
-}
-
-
-if [ "$COMMAND" == "push" ]; then
-  doPushK8sPush
+  l_verbose "  ...for dev and prod, check local code and secrets are checked in and pushed."
+  doGitChecksOnFormalStages 1
   RESULT=$?
-elif [ "$COMMAND" == "check" ]; then
-  doPushK8sCheck
-  RESULT=$?
+
+  if [ $RESULT -eq 0 ]; then
+    l_verbose "  ... ensure WOV_ORIGIN is to self."
+    if [ "${WOV_ORIGIN}" != "self" ]; then
+      l_warn "Cannot push Cluster Configuration to Archive that is not set to Origin self. WOV_ORIGIN is '${WOV_ORIGIN}'"
+      RESULT=1
+    fi
+  fi
+
+  if [ $RESULT -eq 0 ]; then
+    l_verbose "  ... make sure cluster information is built."
+    wov-env-build --cluster
+    RESULT=$?
+  fi
+
+  if [ $RESULT -eq 0 ]; then
+    l_verbose "  ... call command '${COMMAND}'"
+    if [ "$COMMAND" == "push" ]; then
+      doPushK8sPush
+      RESULT=$?
+    elif [ "$COMMAND" == "check" ]; then
+      doPushK8sCheck
+      RESULT=$?
+    fi
+  fi
+
 fi
 
 
 # 0 - success, 2- warnings
-if [ $DOECHO -ge 1 ]; then 
+if [ $DOECHO -ge 2 ]; then 
   if [ $RESULT == 0 ]; then echo "  ... wov-push-k8s success";
   else echo "  ... wov-push-k8s failed"; fi
 fi
