A good first pass and completing of Git issue #31, up to wov-deploy. This does a major overhaul of the configuration in WovTools and does a lot more renaming and clustering of files than I was expecting.
- The wovtools/local.json and wovtools/config.json work together well.
- The push commands are much less rigid, fitting with the changes to
wov-deploy --dev option.
- Started to build out Cloud specific tools.
- wov-env and wov-env-build are majorly rewritten, to smooth a lot of
the hacks that I had put in.
- Got rid of stagemods.
- wov-env, the file used by EVERYTHING, is more than twice as fast.

diff --git a/bin/wov-env b/bin/wov-env
--- a/bin/wov-env
+++ b/bin/wov-env
@@ -5,8 +5,10 @@ ECHOMODE=0
 DOALL=1
 SED=`which gsed`
 HAS_SECRET=0
+PROVIDERVARS=()
 
-function fDisplayOptions()
+
+function fWovEnvDisplayOptions()
 {
   cat <<EOF | fold -w ${FOLD} -s
 
@@ -32,8 +34,9 @@ Command Options:
   --rcAWS       : convert a region code to an AWS code (ex. va-> us-east-1)
   --vh-label    : vh label in DockerHub repo
  
-  Basic Configuration:
-  -e            : echo the output
+  Basic Environment Configuration:
+  -e            : echo the output with newlines
+  -E            : echo the output on one line (bash executable)
   -p/--provider : run cluster config as well (WAS -c/--cluster) FIXME|TODO
 
   Secrets/Config:
@@ -56,7 +59,7 @@ Example Usage:
 
 EOF
 }
-if [ "$1" == '--help' ] || [ "$1" == '-h' ]; then fDisplayOptions; exit 0; fi
+if [ "$1" == '--help' ] || [ "$1" == '-h' ]; then fWovEnvDisplayOptions; exit 0; fi
 
 
 # --------------------------------------------------------------------- 
@@ -70,8 +73,7 @@ if [ "$1" == "--vh-label" ]; then echo "0.1"; exit 0; fi
 # --------------------------------------------------------------------- 
 WOV_VERSION=0
 export WOV_VERSION
-WOV_BASEDIR=$(git rev-parse --show-toplevel)
-export WOV_BASEDIR
+export WOV_BASEDIR="$(git rev-parse --show-toplevel)"
 if [ "$WOV_BASEDIR" == "" ]; then
   echo "ERROR: not in wovtools project (no git)."
   exit 1
@@ -85,10 +87,34 @@ fi
 
 
 # --------------------------------------------------------------------- 
+# Source files for project configuration : build if needed
+# --------------------------------------------------------------------- 
+export WOV_CACHEDIR="${WOV_BASEDIR}/wovtools/cache"
+export WOV_FILE_SECRETS_RAW="${WOV_BASEDIR}/wovtools/config.json"
+export WOV_FILE_SECRETSLOCAL_RAW="${WOV_BASEDIR}/wovtools/local.json"
+export WOV_FILE_SECRETSMERGED="${WOV_CACHEDIR}/.merged.json"
+
+
+# ---------------------------------------------------------------------
+# Ensure the SECRET_CACHE_DIR exists and is protected and then merge
+# files config.json and local.json together in SECRETSMERGED_RAW
+# if they have changed.
+# ---------------------------------------------------------------------
+mkdir -p ${WOV_CACHEDIR}
+chmod 700 ${WOV_CACHEDIR}
+if [ ${WOV_FILE_SECRETS_RAW} -nt ${WOV_FILE_SECRETSMERGED} ] || [ ${WOV_FILE_SECRETSLOCAL_RAW} -nt ${WOV_FILE_SECRETSMERGED} ]; then
+  echo "... merged file out of date, creating: ${WOV_FILE_SECRETSMERGED}"
+  echo "" > ${WOV_FILE_SECRETSMERGED}
+  chmod 600 ${WOV_FILE_SECRETSMERGED}
+  jq -s ".[0] * .[1]" ${WOV_FILE_SECRETS_RAW} ${WOV_FILE_SECRETSLOCAL_RAW} >> ${WOV_FILE_SECRETSMERGED}
+fi
+
+
+# --------------------------------------------------------------------- 
 # Sets the cluster we are generating environment vars for. By default,
-# generates using settings in 'local', which is generated by wov-build
-# using the 'localcontext' entry. So, 'local' points to whatever 
-# cluster this project considers the localcontext.
+# generates using settings in 'local', which is generated by 
+# wov-env-build using the 'localcontext' entry. So, 'local' points to
+# whatever cluster this project considers the localcontext.
 # --------------------------------------------------------------------- 
 function doSetCluster
 {
@@ -100,206 +126,170 @@ doSetCluster "local"
 
 
 # --------------------------------------------------------------------- 
-# Calls wov-build to build the secretfile if it does not exist.
+# For dev and prod, check local code and secrets are checked in and pushed.
+# @param {bool} $1 - if true, allows for err msg and exit
+# @return {bool} - 1 if error, 0 if ok
+# --------------------------------------------------------------------- 
+function doGitChecksOnFormalStages()
+{
+  local retval=1
+
+  if [ "$WOV_STAGE" == "prod" ] || [ "$WOV_STAGE" == "dev" ]; then
+
+    local R1=0
+    wov-git-check ${WOV_BASEDIR}
+    R1=$?
+    if [ $R1 -eq 0 ]; then
+      wov-git-check ${WOV_BASEDIR}/wovtools/secrets
+      R2=$?
+      if [ $R2 -eq 0 ]; then
+        retval=0
+      fi
+    fi
+
+    if [ $retval -ne 0 ]; then
+      printf "\n\nERROR: failed git checks.\n\n"
+      exit 1
+    fi
+  fi
+
+  return $retval
+}
+
+
+# --------------------------------------------------------------------- 
+# Used to generate the path where CLuster configuration would sit in 
+# the archive.
+#  ex. local path="`getRelativeArchivePath MyCluster`"
+# --------------------------------------------------------------------- 
+function getRelativeArchivePath()
+{ 
+  echo "${1}/${WOV_PROJECT}/${WOV_STAGE}/${WOV_PVER}_${WOV_SVER}" 
+}
+
+
+# --------------------------------------------------------------------- 
+# Calls wov-env-build to build the secretfile if it does not exist.
 # --------------------------------------------------------------------- 
 function fBuildSecret
-{ if [ ! -e "${WOV_SECRETFILE}" ]; then wov-build --secrets ${CLUSTER}; fi }
+{ if [ ! -e "${WOV_SECRETFILE}" ]; then wov-env-build --secrets ${CLUSTER}; fi }
 
 
-
-
-
-
-# Standard Bash breakdown of context
-WOV_CONTEXT=$(kubectl config current-context)
+# vars from Kubernetes
+# --------------------------------------------------------------------- 
+export WOV_CONTEXT="$(kubectl config current-context)"
 OLDIFS=$IFS
 IFS='-'
 array=( $WOV_CONTEXT )
 IFS=$OLDIFS
-#echo "value = ${array[2]}"
-#echo ${array[*]}
-WOV_KSTAGE=${array[5]}
-WOV_KPROJECT=${array[4]}
-WOV_NS=${WOV_KPROJECT}-${WOV_KSTAGE}
-export WOV_BASEDIR
-WOV_FLAVOR=${array[3]}
-WOV_REGION=${array[2]}
-WOV_PROVIDER=${array[1]}
-WOV_CLTYPE=${array[0]}
-WOV_CLUSTER=${WOV_CLTYPE}-${WOV_PROVIDER}-${WOV_REGION}-${WOV_FLAVOR}
+export WOV_KSTAGE="${array[5]}"
+export WOV_KPROJECT="${array[4]}"
+export WOV_NS="${WOV_KPROJECT}-${WOV_KSTAGE}"
+export WOV_FLAVOR="${array[3]}"
+export WOV_REGION="${array[2]}"
+export WOV_PROVIDER="${array[1]}"
+export WOV_CLTYPE="${array[0]}"
+export WOV_CLUSTER="${WOV_CLTYPE}-${WOV_PROVIDER}-${WOV_REGION}-${WOV_FLAVOR}"
+
 
 # vars from git, if in project directory
-WOV_PVER=$(git rev-list --count $(git rev-parse --abbrev-ref HEAD))
-WOV_SVER=$(cd ${WOV_BASEDIR}/wovtools/secrets && git rev-list --count $(git rev-parse --abbrev-ref HEAD))
-# WOV_USER=$(git config user.email | cut -d@ -f1)
-WOV_USERNAME=$(git config user.name)
-WOV_USEREMAIL=$(git config user.email)
-export WOV_PVER
-export WOV_SVER
-#  export WOV_USER
-export WOV_USERNAME
-export WOV_USEREMAIL
-
-# TODO:  optimize the jq calls into one, returning an array
-#A=( `jq -r ". | ( .rootdir, .srcdir, .secretsdir, .compileddir, .containerdir, .registry, .wovtools )" ${dir_wovtools_rc}/.wovtools.json` )
-#echo "A:${A[*]}:A"
-#dir_root="${A[0]}"
+# --------------------------------------------------------------------- 
+export WOV_PVER="$(git rev-list --count $(git rev-parse --abbrev-ref HEAD))"
+export WOV_SVER="$(cd ${WOV_BASEDIR}/wovtools/secrets && git rev-list --count $(git rev-parse --abbrev-ref HEAD))"
+export WOV_USERNAME="$(git config user.name)"
+export WOV_USEREMAIL="$(git config user.email)"
+export WOV_GSTAGE="$(git rev-parse --abbrev-ref HEAD)"
 
 
-WOV_ME=$(cat ${HOME}/.wovtools | jq -r '.me')
+# vars from global .wovtools file
+# --------------------------------------------------------------------- 
+export WOV_ME=$(cat ${HOME}/.wovtools | jq -r '.me')
 if [ "${WOV_ME}" == "null" ] ; then
   printf "\n\nERROR: You need to set 'me' in the wovtools/config.json file.\n"
   printf "  - This is a unique code in this project, to represent yourself. Try using your initials (assuming they are unique to your team).\n\n"
   exit 1
-
 fi
 
-WOV_PVERSION=$(cat ${WOV_BASEDIR}/wovtools/config.json | jq -r '.ver')
+# vars from merged secrets file
+# --------------------------------------------------------------------- 
+# Do one jq call on the project 'merged' file to get vars needed
+ALLVARS=()
+while read f; do
+  ALLVARS+=( "$f" )
+done <<<$(cat ${WOV_FILE_SECRETSMERGED} | jq -r ". | ( .ver, .project.project, .project.type, .project.title, .project.description, .archive.repository, .archive.env  )" )
+
+WOV_PVERSION=${ALLVARS[0]}
 if [ "${WOV_PVERSION}" != "${WOV_VERSION}" ] && [ "${WOV_PVERSION}" != "initing" ] ; then
   printf "\n\nERROR: Your project version '${WOV_PVERSION}', does not match to the WovTools version '${WOV_VERSION}'.\n\n"
   exit 1
 fi
+export WOV_WPROJECT="${ALLVARS[1]}"
+export WOV_PROJECTTYPE="${ALLVARS[2]}"
+export WOV_PROJECTTITLE="${ALLVARS[3]}"
+export WOV_PROJECTDESCRIPTION="${ALLVARS[4]}"
+export WOV_ARCHIVEREPOSITORY="${ALLVARS[5]}"
+export WOV_ARCHIVEENV="${ALLVARS[6]}"
 
-SECONDS=0
-WOV_WPROJECT=$(cat ${WOV_BASEDIR}/wovtools/config.json | jq -r '.project.project') 
-WOV_PROJECTTYPE=$(cat ${WOV_BASEDIR}/wovtools/config.json | jq -r '.project.type') 
-WOV_PROJECTTITLE=$(cat ${WOV_BASEDIR}/wovtools/config.json | jq -r '.project.title') 
-WOV_PROJECTDESCRIPTION=$(cat ${WOV_BASEDIR}/wovtools/config.json | jq -r '.project.description') 
-export WOV_WPROJECT
-export WOV_PROJECTTYPE
-export WOV_PROJECTTITLE
-export WOV_PROJECTDESCRIPTION
+# Unifying
+# --------------------------------------------------------------------- 
+export WOV_STAGE="$WOV_GSTAGE"        # GSTAGE has priority since it can represent <initials>-local, for local namespaces.
+export WOV_PROJECT="${WOV_WPROJECT}"  
 
-# Track which mode we are in
-#WOV_DEVMODE=$(cat ${WOV_BASEDIR}/wovtools/config.json | jq -r '.project.devmode') 
-#if [ "$WOV_DEVMODE" == "" ]; then WOV_DEVMODE="remote"; fi
-#export WOV_DEVMODE
-
-WOV_ARCHIVEREPOSITORY=$(cat ${WOV_BASEDIR}/wovtools/config.json | jq -r '.archive.repository') 
-WOV_ARCHIVEENV=$(cat ${WOV_BASEDIR}/wovtools/config.json | jq -r '.archive.env') 
-export WOV_ARCHIVEREPOSITORY
-export WOV_ARCHIVEENV
-
-WOV_GSTAGE=$(git rev-parse --abbrev-ref HEAD)
-WOV_STAGE=$WOV_GSTAGE
-  # GSTAGE has priority since it can represent <initials>-local, for local namespaces.
-export WOV_GSTAGE
-export WOV_STAGE
-
-## Set DEVMODE 
-#if [[ ${WOV_GSTAGE} == "${WOV_KSTAGE}-l" ]]; then
-#  WOV_DEVMODE=local
-#elif [[ ${WOV_GSTAGE} == "${WOV_KSTAGE}-v" ]]; then
-#  WOV_DEVMODE=virtual
-#fi
-#export WOV_DEVMODE
-
-WOV_PROJECT=${WOV_WPROJECT}
-export WOV_PROJECT
-
-export WOV_CONTEXT
-export WOV_CLUSTER
-export WOV_NS
-export WOV_CLTYPE
-export WOV_PROVIDER
-export WOV_REGION
-export WOV_FLAVOR
-export WOV_PROJECT
-export WOV_KSTAGE
 
 # --------------------------------------------------------------------- 
 # Functions
 # --------------------------------------------------------------------- 
 
+
+# --------------------------------------------------------------------- 
+# $1 - appending char(s): ex. ' ' or '\n'
+# $2 - prepending char(s) : ex. 'export'
+# --------------------------------------------------------------------- 
 function fDoEcho() 
 {
-  echo WOV_VERSION="${WOV_VERSION}"
-  echo WOV_ME="${WOV_ME}"
-  echo WOV_BASEDIR="${WOV_BASEDIR}"
-  echo WOV_SECRETFILE="${WOV_SECRETFILE}"
-  echo WOV_ARCHIVEREPOSITORY="${WOV_ARCHIVEREPOSITORY}"
-  echo WOV_ARCHIVEENV="${WOV_ARCHIVEENV}"
-  echo WOV_CONTEXT="$WOV_CONTEXT"
-  echo WOV_CLUSTER="$WOV_CLUSTER"
-  echo WOV_NS="$WOV_NS"
-  echo WOV_CLTYPE="$WOV_CLTYPE"
-  echo WOV_PROVIDER="$WOV_PROVIDER"
-  echo WOV_REGION="$WOV_REGION"
-  echo WOV_FLAVOR="$WOV_FLAVOR"
-  echo WOV_PROJECT="$WOV_PROJECT"
-  echo WOV_KSTAGE="$WOV_KSTAGE"
-  echo WOV_GSTAGE="$WOV_GSTAGE"
-  echo WOV_STAGE="$WOV_STAGE"
-#  echo WOV_DEVMODE="${WOV_DEVMODE}"
-  if [ "$RANPROVIDER" == "1" ]; then
-    echo CL_REGION="$CL_REGION"
-    echo CL_ZONES="${CL_ZONES}"
-    echo CL_VPC="${CL_VPC}"
-  fi
+  local v=( 'WOV_VERSION' 'WOV_ME' 'WOV_BASEDIR' 'WOV_ARCHIVEREPOSITORY' 'WOV_ARCHIVEENV' 'WOV_CONTEXT' \
+          'WOV_CLUSTER' 'WOV_NS' 'WOV_CLTYPE' 'WOV_PROVIDER' 'WOV_REGION' 'WOV_FLAVOR' 'WOV_PROJECT' \
+          'WOV_KSTAGE' 'WOV_GSTAGE' 'WOV_STAGE' 'WOV_PVER' 'WOV_SVER' 'WOV_USERNAME' 'WOV_USEREMAIL' \
+          'WOV_PROJECT' 'WOV_PROJECTTYPE' 'WOV_PROJECTTITLE' 'WOV_PROJECTDESCRIPTION' 'WOV_KPROJECT' \
+          'WOV_WPROJECT' )
 
-  echo WOV_PVER="$WOV_PVER"
-  echo WOV_SVER="$WOV_SVER"
-#    echo WOV_USER="$WOV_USER"
-  echo WOV_USERNAME="$WOV_USERNAME"
-  echo WOV_USEREMAIL="$WOV_USEREMAIL"
-  echo WOV_PROJECT="$WOV_PROJECT"
-  echo WOV_PROJECTTYPE="$WOV_PROJECTTYPE"
-  echo WOV_PROJECTTITLE="$WOV_PROJECTTITLE"
-  echo WOV_PROJECTDESCRIPTION="$WOV_PROJECTDESCRIPTION"
-  echo WOV_KPROJECT="$WOV_KPROJECT"
-  echo WOV_WPROJECT="$WOV_WPROJECT"
+  for f in "${v[@]}"; do
+    printf "$2$f='${!f}'$1"
+  done
+  if [ "$RANPROVIDER" == "1" ]; then doProviderEcho "$1"; fi
 }
 
-function fDoBashEcho() 
-{
-  printf "WOV_VERSION=\"${WOV_VERSION}\" "
-  printf "WOV_ME=\"${WOV_ME}\" "
-  printf "WOV_BASEDIR=\"${WOV_BASEDIR}\" "
-  printf "WOV_ARCHIVEREPOSITORY=\"${WOV_ARCHIVEREPOSITORY}\" "
-  printf "WOV_ARCHIVEENV=\"${WOV_ARCHIVEENV}\" "
-  printf "WOV_CONTEXT=\"$WOV_CONTEXT\" "
-  printf "WOV_CLUSTER=\"$WOV_CLUSTER\" "
-  printf "WOV_NS=\"$WOV_NS\" "
-  printf "WOV_CLTYPE=\"$WOV_CLTYPE\" "
-  printf "WOV_PROVIDER=\"$WOV_PROVIDER\" "
-  printf "WOV_REGION=\"$WOV_REGION\" "
-  printf "WOV_FLAVOR=\"$WOV_FLAVOR\" "
-  printf "WOV_PROJECT=\"$WOV_PROJECT\" "
-  printf "WOV_KSTAGE=\"$WOV_KSTAGE\" "
-  printf "WOV_GSTAGE=\"$WOV_GSTAGE\" "
-  printf "WOV_STAGE=\"$WOV_STAGE\" "
-  printf "WOV_PVER=\"$WOV_PVER\" "
-  printf "WOV_SVER=\"$WOV_SVER\" "
-  printf "WOV_USERNAME=\"$WOV_USERNAME\" "
-  printf "WOV_USEREMAIL=\"$WOV_USEREMAIL\" "
-  printf "WOV_PROJECT=\"$WOV_PROJECT\" "
-  printf "WOV_PROJECTTYPE=\"$WOV_PROJECTTYPE\" "
-  printf "WOV_PROJECTTITLE=\"$WOV_PROJECTTITLE\" "
-  printf "WOV_PROJECTDESCRIPTION=\"$WOV_PROJECTDESCRIPTION\" "
-  printf "WOV_KPROJECT=\"$WOV_KPROJECT\" "
-  printf "WOV_WPROJECT=\"$WOV_WPROJECT\" "
-  if [ "$RANPROVIDER" == "1" ]; then
-    printf "CL_REGION=\"$CL_REGION\" "
-    printf "CL_ZONES=\"${CL_ZONES}\" "
-    printf "CL_VPC=\"${CL_VPC}\" "
-  fi
-}
 
+# --------------------------------------------------------------------- 
 # TODO: fill this function in, and remove from WIAAS
+#  NOTE: fills in REGIONVARS and exports variables as needed.
+# --------------------------------------------------------------------- 
 function fDoProvider() # Cluster()
 {
-  echo " NOTE: for now, ignore fDoProvider (used to be Cluster) as it should load a wov-env-PROVIDER file for specific functionality"
   RANPROVIDER=1
-  fConvertRegionCodeAWS ${WOV_REGION}
-  CL_REGION=$cRC
-  CL_ZONES="c d"
-  CL_VPC=$(aws ec2 describe-vpcs --filters "Name=tag:Name,Values=${WOV_CLUSTER}-vpc" --query 'Vpcs[0].VpcId' | ${SED} -e 's/^"//' -e 's/"$//')
-  export CL_REGION
-  export CL_ZONES
-  export CL_VPC
+
+  if [ "$WOV_PROVIDER" == "aws" ]; then . wov-env-aws; 
+  else
+    printf "\n\nERROR: Unknown provider to load env vars from : '${WOV_PROVIDER}'.\n\n"
+    exit 1
+  fi
 }
 
 
+# --------------------------------------------------------------------- 
+# $1 - appending char(s): ex. ' ' or '\n'
+# $2 - prepending char(s): ex. 'export '
+# --------------------------------------------------------------------- 
+function doProviderEcho
+{
+  for f in "${REGIONVARS[@]}"; do
+    printf "$2$f='${!f}'$1"
+  done
+}
+
+
+# --------------------------------------------------------------------- 
+# --------------------------------------------------------------------- 
 function doPrintVarX()
 {
   if [ "$HAS_SECRET" == "0" ]; then fBuildSecret; fi
@@ -317,9 +307,7 @@ function doPrintVarsENVS()
   cat ${WOV_SECRETFILE} |
     jq  -r 'walk( if type == "object" then with_entries(select( .key | test("STAGE.+") or test("//*") | not)) else . end) | [leaf_paths as $path | {"key": $path | join("_"), "value": getpath($path)}] | from_entries | keys[] as $k | "WOV_\($k)=" + @sh "\(.[$k])" '
 
-  if [ "${CL_REGION}" != "" ]; then echo "CL_REGION='${CL_REGION}'"; fi
-  if [ "${CL_ZONES}"  != "" ]; then echo "CL_ZONES='${CL_ZONES}'"; fi
-  if [ "${CL_VPC}"    != "" ]; then echo "CL_VPC='${CL_VPC}'"; fi
+  if [ "$RANPROVIDER" == "1" ]; then doProviderEcho "\n"; fi
 
   HAS_BUILDENV=1
 }
@@ -336,28 +324,10 @@ function doPrintVarsEXPORTS()
   cat ${WOV_SECRETFILE} |
     jq  -r 'walk( if type == "object" then with_entries(select( .key | test("STAGE.+") or test("//*") | not)) else . end) | [leaf_paths as $path | {"key": $path | join("_"), "value": getpath($path)}] | from_entries | keys[] as $k | "export WOV_\($k)=" + @sh "\(.[$k])" '
 
-  if [ "${CL_REGION}" != "" ]; then echo "export CL_REGION='${CL_REGION}'"; fi
-  if [ "${CL_ZONES}"  != "" ]; then echo "export CL_ZONES='${CL_ZONES}'"; fi
-  if [ "${CL_VPC}"    != "" ]; then echo "export CL_VPC='${CL_VPC}'"; fi
+  if [ "$RANPROVIDER" == "1" ]; then doProviderEcho "\n" "export "; fi
 
   HAS_BUILDENV=1
 }
-
-
-# ---------------------------------------------------------------------
-# ---------------------------------------------------------------------
-function fConvertRegionCodeAWS()
-{
-  case $1 in
-    va) cRC='us-east-1' ;;
-    iad) cRC='us-east-1' ;;
-    *)
-      echo
-      echo "***ERROR: unknown AWS region code of '$1'."
-      exit 1
-  esac
-}
-
 
 # --------------------------------------------------------------------- 
 # Generate only the necessary env variables for microservices.
@@ -380,10 +350,8 @@ function fConfGeneration()
   if [ -e "${WOV_BASEDIR}/${1}/src/${1}config.js" ]; then
     local MSCFILE="${WOV_BASEDIR}/${1}/src/${1}config.js"
     if [ "$2" == "cm" ]; then 
-      set -x
       R=( $(node -e "console.log((new (require('${MSCFILE}'))())._genK8SConfigMap())") ) 
       RR=$?
-      set +x
     elif [ "$2" == "se" ]; then
       R=( $(node -e "console.log((new (require('${MSCFILE}'))())._genK8SSecrets())") )
       RR=$?
@@ -436,9 +404,9 @@ function fConfGeneration()
 # --------------------------------------------------------------------- 
 # Command line processing
 while [[ $1 =~ ^- ]]; do
-  if [ "$1" == '-e' ] || [ "$1" == '--echo' ]; then
+  if [ "$1" == '-e' ]; then
     ECHOMODE=1
-  elif [ "$1" == '-E' ] || [ "$1" == '--bash-echo' ]; then
+  elif [ "$1" == '-E' ]; then
     ECHOMODE=2
 
   elif [ "$1" == '-c' ] || [ "$1" == '--cluster' ]; then
@@ -499,8 +467,7 @@ while [[ $1 =~ ^- ]]; do
 
   elif [ "$1" == "--rcAWS" ]; then
     shift
-    fConvertRegionCodeAWS $1
-    echo "$cRC"
+    echo $(fConvertRegionCodeAWS $1)
     shift
 
   elif [ "$1" == "--cluster" ]; then
@@ -528,7 +495,9 @@ while [[ $1 =~ ^- ]]; do
     shift 
     V=$(doPrintVarX $1)
     if [ "$ECHOMODE" == "1" ]; then
-      echo "$1=${V}"
+      printf "$1=\"${V}\"\n"
+    elif [ "$ECHOMODE" == "2" ]; then
+      printf "$1=\"${V}\" "
     else
       echo ${V}
     fi
@@ -537,7 +506,7 @@ while [[ $1 =~ ^- ]]; do
     echo $WOV_VERSION
 
   elif [ "$1" == '--help' ] || [ "$1" == '-h' ]; then
-    fDisplayOptions
+    fWovEnvDisplayOptions
     exit 0
   else
     echo
@@ -550,9 +519,14 @@ done
 
 # if user never asked to show any individual variables, show all
 if [ "$DOALL" == "1" ]; then
-  if [ "$ECHOMODE" == "1" ]; then
-    fDoEcho
+  if   [ "$ECHOMODE" == "0" ]; then
+    printf "" # do nothing
+  elif [ "$ECHOMODE" == "1" ]; then
+    fDoEcho "\n"
   elif [ "$ECHOMODE" == "2" ]; then
-    fDoBashEcho
+    fDoEcho " "
+  else
+    printf "\n\nERROR: Unknown echo mode '$ECHOMODE'.\n\n"
+    exit 1
   fi
 fi
diff --git a/bin/wov-push b/bin/wov-push
--- a/bin/wov-push
+++ b/bin/wov-push
@@ -6,15 +6,7 @@ FOLD=$(tput cols)
 BLOCK=0
 SKIPDBCHECKS=0
 
-# ---------------------------------------------------------------------
-# Build right before to update any files
-# ---------------------------------------------------------------------
-if [ ! -z ${WOV_stagemod+x} ]; then
-  printf "\nERROR: Can't have WOV_stagemod set when pushing content.\n\n"
-  exit 1
-fi
-
-wov-build -e
+wov-env-build -q --local 
 if [ "$?" != "0" ]; then
   exit 1
 fi
@@ -28,11 +20,6 @@ set ""
 . wov-ns-check
 set -- "${pushargs[@]}"
 
-
-#if [ "$WOV_DEVMODE" != "remote" ]; then
-#  printf "\nERROR: Can not push when is devmode '${WOV_DEVMODE}'. Run 'wov-env --remote'.\n\n"
-#  exit 1
-#fi
 
 printf "\n"
 figlet wov-push
@@ -51,14 +38,13 @@ if [[ "$ONSTAGEMODS" != "" ]]; then
   exit 1
 fi
 
-
 # Check local code is checked in and pushed
 wov-git-check ${WOV_BASEDIR}
 R1=$?
 wov-git-check ${WOV_BASEDIR}/wovtools/secrets
 R2=$?
 if [ "$R1" != "0" ] || [ "$R2" != "0" ]; then 
-  printf "\nERROR: wov-push exiting\n" 1>&2
+  printf "\nERROR: wov-push exiting.\n" 1>&2
   exit 1
 fi
 
@@ -74,11 +60,9 @@ function fDisplayOptions()
 
 usage: `basename $0` [options]
 
-Macro command that pushes containers, then env. It uses:
-   wov-build-containers
-   wov-build-conf
+Formal push of a version into the archive. This is a macro command that pushes containers, Kubernetes and database changes at once.
 
-  --skip-db-checks : skip the checks for database inconsistencies
+  --skip-db-checks : skip the checks for database inconsistencies (DB checks are slow)
 
   -h : this help
   -q/-v : quiet/verbose
@@ -122,7 +106,7 @@ done
 
 if [ "$SKIPDBCHECKS" != "1" ]; then
   echo "  ... check for database changes that could block the push"
-  wov-db-commit -v --any-push-blockage
+  wov-push-db -v --any-push-blockage
   R3=$?
   if [ "$R3" != 0 ]; then exit 1; fi
 else
@@ -130,19 +114,19 @@ else
 fi
 
 
-echo "  ... wov-build-containers ${METAARGS}"
-wov-build-containers ${METAARGS}
+echo "  ... wov-push-container ${METAARGS}"
+wov-push-container ${METAARGS}
 if [ "$?" != "0" ]; then
   exit 1
 fi
-echo "  ... wov-build-conf ${METAARGS}"
-wov-build-conf ${METAARGS}
+echo "  ... wov-push-k8s ${METAARGS}"
+wov-push-k8s ${METAARGS}
 if [ "$?" != "0" ]; then
   exit 1
 fi
 
-echo "  ... wov-db-commit ${METAARGS}"
-wov-db-commit ${METAARGS}
+echo "  ... wov-push-db ${METAARGS}"
+wov-push-db ${METAARGS}
 if [ "$?" != "0" ]; then
   exit 1
 fi
diff --git a/bin/wov-push-container b/bin/wov-push-container
--- a/bin/wov-push-container
+++ b/bin/wov-push-container
@@ -4,40 +4,36 @@
 # --------------------------------------------------------------------- 
 # Import Env 
 # --------------------------------------------------------------------- 
-if [ ! -z ${WOV_stagemod+x} ]; then
-  printf "\nERROR: Can't have WOV_stagemod set when pushing content.\n\n"
+wov-env-build -q --local
+if [ "$?" != "0" ]; then
   exit 1
 fi
-wov-build -e
 
 pushcontainersargs=( "$@" )
 set ""
-echo "NOTE: see how I load variables through this redirect and source... should do for all"
-. <(wov-env -c --exports)
+. <(wov-env --provider --exports)
 . wov-ns-check
 set -- "${pushcontainersargs[@]}"
+
+
+# For dev and prod, check local code and secrets are checked in and pushed.
+doGitChecksOnFormalStages 1
 
 DOECHO=1
 DOFORCE=0
 DOPUSH=1
 FOLD=$(tput cols)
 BLOCK=0
-SSHKEY=
-RECIPES=( )
 
+# Globals
+RECIPES=( )
+CONTAINERNAME=
+CONTAINER=
+SRCDIR=${WOV_BASEDIR}
+DESTDIR=
+ARCHDIR=
 
 echo "NOTE[$0]: Skipping git checks.... will do on wov-push."
-
-## Check local code is checked in and pushed
-#wov-git-check ${WOV_BASEDIR}
-#R1=$?
-#wov-git-check ${WOV_BASEDIR}/wovtools/secrets
-#R2=$?
-#if [ "$R1" != "0" ] || [ "$R2" != "0" ]; then 
-#  printf "\nERROR: wov-build-containers exiting\n" 1>&2
-#  exit 1;
-#fi
-
 
 
 # If NodeJS project...
@@ -63,7 +59,7 @@ function fDisplayOptions()
 
 usage: `basename $0` [options] {containercode ...}
 
-Runs the recipe scripts and if there is a change, build the containers.
+Pushes the containers by building and pushing to the archive. Runs the recipe scripts and if there is a change, build the containers.
 
 ex. `basename $0` -f ggg hhh  
     -> for project iii,  forces the building of containers iiiggg and iiihhh
@@ -80,7 +76,6 @@ The recipes for containers should:
   - ${DESTDIR}/SECRET/build.docker - all code is in the container
   - ${DESTDIR}/SECRET/run.docker - instructions on how to run container
 
-  --key X : ssh key to add ex. ${HOME}/.ssh/id_rsa
   -p/P : do push, no push
   -h : this help
   -l : list containers
@@ -92,7 +87,7 @@ EOF
 
 
 # ---------------------------------------------------------------------
-# Put contents together in container directory
+# Put contents together in container directory. Also builds Dockerfile.
 #  NOTE: later will decide if we need to build a container, based upon this
 # ---------------------------------------------------------------------
 function doPackContainer
@@ -105,7 +100,7 @@ function doPackContainer
   echo "" > ${DESTDIR}/Dockerfile
 
   echo "  ... pack container using recipe: '$f'"
-  cd ${WOV_BASEDIR} && SRCDIR=${SRCDIR} DESTDIR=${DESTDIR} CONTAINER=${CONTAINER} ${WOV_BASEDIR}/wovtools/containers/$f
+  cd ${WOV_BASEDIR} && SRCDIR=${SRCDIR} DESTDIR=${DESTDIR} CONTAINER=${CONTAINER} DOECHO=${DOECHO} ${WOV_BASEDIR}/wovtools/containers/$f
   if [ "$?" != "0" ]; then
     printf "\n\nERROR: failed building container.\n\n"
     exit 1
@@ -117,7 +112,7 @@ function doPackContainer
     printf "\nERROR: no 'repositories' entry in secrets. If you have no private repos, create a blank entry.\n"
     exit 1
   fi
-  echo "  ... adding keys for private repos"
+  if [ $DOECHO -ge 2 ]; then echo "    ... adding keys for private repos"; fi
   for repo in "${PRIVATEREPOS[@]}"; do
     # for each item in private repo, append to ssh/config and add its key
     # echo "  ... add in repo key ${repo}, update .ssh/config"
@@ -134,7 +129,7 @@ function doPackContainer
     repoKeyFile="${repoKeyFile/#\~/$HOME}"
       # expand tilde to $HOME
     #echo "    ... repoKeyFile ${repoKeyFile}"
-    echo "    ... repo: '${repo}'  url: '${repoURL}'  user: '${repoUser}'  keyfile: '${repoKeyFile}'"
+    if [ $DOECHO -ge 2 ]; then echo "        ... repo: '${repo}'  url: '${repoURL}'  user: '${repoUser}'  keyfile: '${repoKeyFile}'"; fi
     cat <<EOF >> ${DESTDIR}/SECRET/ssh-config
 
 # repo: ${repo}
@@ -155,14 +150,12 @@ EOF
 
   # --------------------------------------------------------------------- 
   # start building Dockerfile for the container
-  echo "**** Should do all variables like this ****"
   _CONTAINERBASE="WOV_${WOV_PROJECT}${CONTAINERNAME}_containerfrom"
   CONTAINERBASE=${!_CONTAINERBASE}
-  #CONTAINERBASE=$(cat ${WOV_SECRETFILE} | jq -r '.'${WOV_PROJECT}'.'${CONTAINERNAME}'.containerfrom')
   if [ "${CONTAINERBASE}" == "null" ]; then
     printf "\nERROR: Docker container for '${repo}' has no known base to build from in secret: '${WOV_PROJECT}.${CONTAINERNAME}.containerfrom'.\n\n"
     printf "   Check: \n"
-    printf "     - secrets are rebuilt (wov-build -e)\n"
+    printf "     - secrets are rebuilt (wov-env-build --local)\n"
     printf "     - secrets contain entry for '${WOV_PROJECT}.${CONTAINERNAME}.containerfrom'. ('wov-ed -c secrets/current.json')\n"
     printf "     - secret file containing that entry is included in this stage (see wovtools/confing.json secrets.${WOV_STAGE})\n\n"
     exit 1
@@ -296,29 +289,17 @@ EOF
   cat <<EOF >> ${DESTDIR}/Dockerfile
 # --------------------------------------------------------------------- 
 EOF
-
 }
 
 
 # ---------------------------------------------------------------------
 # Pack all into Docker container and archive last build.
 # ---------------------------------------------------------------------
-function doBuildContainer
+function doDockerizeContainer
 {
   echo "  ... creating container '${CONTAINER}'"
-#  if [ "${SSHKEY}" != "" ]; then
-#    echo "      ... adding ssh key to build: '${SSHKEY}'"
-#    cp ${SSHKEY} ${DESTDIR}/$(basename ${SSHKEY})
-#    SS="--build-arg SSH_KEY=$(basename ${SSHKEY})"
-#  fi
 
-#  docker build ${SS} -f ${DESTDIR}/Dockerfile -t ${WOV_PROJECT}/${CONTAINER}:latest ${DESTDIR} || exit 1
   docker build -f ${DESTDIR}/Dockerfile -t ${WOV_PROJECT}/${CONTAINER}:latest ${DESTDIR} || exit 1
-
-#  if [ "${SSHKEY}" != "" ]; then
-#    echo "      ... removing key from dest: '${DESTDIR}/$(basename ${SSHKEY})'"
-#    rm ${DESTDIR}/$(basename ${SSHKEY})
-#  fi
 
   echo "    ... archiving build of container '${CONTAINER}'"
   mkdir -p ${ARCHDIR}
@@ -327,6 +308,7 @@ function doBuildContainer
 
 
 # ---------------------------------------------------------------------
+# List the container recipes we have.
 # ---------------------------------------------------------------------
 function doList()
 {
@@ -334,6 +316,123 @@ function doList()
   RETVAL=$?
   if [ $RETVAL -eq 0 ]; then echo $C; else echo "No containers"; fi
 }
+
+
+# --------------------------------------------------------------------- 
+# Push the container: pack, dockerize, push
+# --------------------------------------------------------------------- 
+function doPushContainer()
+{
+  CONTAINERNAME=$f
+  CONTAINER=${WOV_PROJECT}${CONTAINERNAME}
+  SRCDIR=${WOV_BASEDIR}
+  DESTDIR=${WOV_BASEDIR}/wovtools/cache/containers/${CONTAINERNAME}
+  ARCHDIR=${WOV_BASEDIR}/wovtools/cache/containers/archive/${CONTAINERNAME}
+  if [[ $DOECHO -ge 2 ]]; then 
+    echo "CONTAINERNAME=${CONTAINERNAME}"
+    echo "CONTAINER=${CONTAINER}"
+    echo "SRCDIR=${SRCDIR}"
+    echo "DESTDIR=${DESTDIR} # more like a 'content' dir as this is all copied in here"
+    echo "ARCHDIR=${ARCHDIR} # location of archive of DESTDIR"
+  fi
+
+  if [[ ! -e "${WOV_BASEDIR}/wovtools/containers/$f" ]]; then 
+    echo "ERROR: recipe for container ${f} does not exist (${WOV_BASEDIR}/wovtools/containers/$f).";
+    exit 1
+  elif [[ ! -x "${WOV_BASEDIR}/wovtools/containers/$f" ]]; then 
+    echo "ERROR: recipe for container ${f} not executable (${WOV_BASEDIR}/wovtools/containers/$f).";
+    exit 1
+  else
+
+    # Copy in and generate all files in DESTDIR
+    doPackContainer ${f}
+
+    # Just packed container, do we need to build it? Do diffs against archive, then compare remote container
+    NEEDSBUILD=0
+    diff -q -r ${DESTDIR} ${ARCHDIR} > /dev/null
+    NEEDSBUILD=$?
+    if [ "$NEEDSBUILD" != "0" ]; then 
+      if [ $DOECHO -ge 2 ]; then 
+        echo "  ... packed container differs so will build."
+      fi
+    else
+      if [ $DOECHO -ge 2 ]; then echo "  ... check push container status"; fi
+      wov-push-container-check -q ${f}
+      NEEDSBUILD=$?
+      if [ "$NEEDSBUILD" != "0" ]; then 
+        if [ $DOECHO -ge 2 ]; then echo "  ... pushed containers differ so will build."; fi
+      fi
+    fi
+
+    # Exit with error on failing
+    if [ "${NEEDSBUILD}" ==  "4" ]; then exit ${NEEDSBUILD}; fi
+    if [ "${NEEDSBUILD}" ==  "3" ]; then exit ${NEEDSBUILD}; fi
+    if [ "${NEEDSBUILD}" ==  "2" ]; then exit ${NEEDSBUILD}; fi
+
+    # Dockerize
+    if [ "${NEEDSBUILD}" == "1" ] || [ "${DOFORCE}" == "1" ]; then doDockerizeContainer ${f};
+    else
+      if [ $DOECHO -ge 1 ]; then echo "  ... container build not needed"; fi
+    fi
+
+    # Do we push the container?
+    if [ "$DOPUSH" == "0" ]; then
+      if [ $DOECHO -ge 1 ]; then printf "  ... skipping container push\n"; fi
+
+    else
+      # Tag and Push
+      if [ "${NEEDSBUILD}" == "1" ] || [ "${NEEDSBUILD}" == "5" ] || [ "${DOFORCE}" == "1" ]; then
+        if [ $DOECHO -ge 1 ]; then echo "  ... container push needed"; fi
+        if [ $DOECHO -ge 2 ]; then echo "    ... tag repo"; fi
+        docker tag ${WOV_PROJECT}/${CONTAINER} ${WOV_ARCHIVEREPOSITORY}/${WOV_PROJECT}/${CONTAINER}:${WOV_STAGE}_${WOV_PVER}
+
+        if [ $DOECHO -ge 2 ]; then echo "    ... push container to: ${WOV_ARCHIVEREPOSITORY}/${WOV_PROJECT}/${CONTAINER}:${WOV_STAGE}_${WOV_PVER}"; fi
+
+        # If just built, dump log, since it will have to push a lot of data
+        R=$(docker push ${WOV_ARCHIVEREPOSITORY}/${WOV_PROJECT}/${CONTAINER}:${WOV_STAGE}_${WOV_PVER} 2>&1 | tee /dev/tty )
+        RR=$?
+        if [[ $R == 'name unknown'* ]]; then
+          printf "\n\n    ...${R}.\n"
+          exit 1
+        fi
+        if [[ $R == *'Your Authorization Token has expired.'* ]]; then
+          echo "    ... auto-login to AWS attempt"
+          AWSAUTHCMD=$(aws ecr get-login --no-include-email)
+          eval ${AWSAUTHCMD}
+          if [ "$?" != "0" ]; then
+            echo "      ... FAILED auto-login to AWS attempt"
+            exit 1
+          else
+            echo "      ... SUCCESS auto-login to AWS attempt"
+            echo "    ... re-push container to: ${WOV_ARCHIVEREPOSITORY}/${WOV_PROJECT}/${CONTAINER}:${WOV_STAGE}_${WOV_PVER}"
+            R=$(docker push ${WOV_ARCHIVEREPOSITORY}/${WOV_PROJECT}/${CONTAINER}:${WOV_STAGE}_${WOV_PVER} 2>&1  | tee /dev/tty)
+            if [ "$?" != "0" ]; then
+              printf "\n\n  ...still errors: ${R}.\n"
+              exit 1
+            fi
+          fi
+        fi
+
+      else
+        if [ $DOECHO -ge 1 ]; then echo "  ... container push not needed"; fi
+      fi
+
+      echo "  ... tagging as dev container and pushing"
+      docker tag ${WOV_ARCHIVEREPOSITORY}/${WOV_PROJECT}/${CONTAINER}:${WOV_STAGE}_${WOV_PVER} ${WOV_ARCHIVEREPOSITORY}/${WOV_PROJECT}/${CONTAINER}:${WOV_STAGE}_dev
+      if [ "$?" != "0" ]; then printf "\n\nERROR: failed tagging as _dev.\n\n"; exit 1; fi
+
+      if [ $DOECHO -ge 2 ]; then 
+        docker push ${WOV_ARCHIVEREPOSITORY}/${WOV_PROJECT}/${CONTAINER}:${WOV_STAGE}_dev
+        if [ "$?" != "0" ]; then printf "\n\nERROR: failed pushing _dev.\n\n"; exit 1; fi
+      else
+        docker push ${WOV_ARCHIVEREPOSITORY}/${WOV_PROJECT}/${CONTAINER}:${WOV_STAGE}_dev > /dev/null
+        if [ "$?" != "0" ]; then printf "\n\nERROR: failed pushing _dev.\n\n"; exit 1; fi
+      fi
+      echo "  ... done '${CONTAINER}'."
+    fi
+  fi
+}
+
 
 # ---------------------------------------------------------------------
 # Handle Params
@@ -355,11 +454,6 @@ while [[ $1 =~ ^- ]]; do
   elif [ "$1" == "-P" ]; then
     shift
     DOPUSH=0
-
-  elif [ "$1" == "--key" ]; then
-    shift
-    SSHKEY=$1
-    shift
 
   elif [ "$1" == "-f" ]; then
     shift
@@ -384,11 +478,9 @@ while [[ $1 =~ ^- ]]; do
 done
 
 
-
-
-# Find the recipes
+# Find the recipes and push them
 if [ "${BLOCK}" == "0" ]; then
- 
+
   RECIPES=( "$@" )
   if [ "${#RECIPES[@]}" == "0" ]; then
     RECIPES=$(cd ${WOV_BASEDIR}/wovtools/containers && find * -maxdepth 0 -type f 2> /dev/null)
@@ -397,146 +489,17 @@ if [ "${BLOCK}" == "0" ]; then
 
   # Build containers if needed
   for f in ${RECIPES}; do
-
-    if [ $DOECHO -ge 1 ]; then printf "\n%-${FOLD}s\n" "-" | tr ' ' '-' ; echo "... build container '${f}'."; fi
-
-    CONTAINERNAME=$f
-    CONTAINER=${WOV_PROJECT}${CONTAINERNAME}
-    SRCDIR=${WOV_BASEDIR}
-    DESTDIR=${WOV_BASEDIR}/wovtools/cache/containers/${CONTAINERNAME}
-    ARCHDIR=${WOV_BASEDIR}/wovtools/cache/containers/archive/${CONTAINERNAME}
-    # echo "CONTAINERNAME=${CONTAINERNAME}"
-    # echo "CONTAINER=${CONTAINER}"
-    # echo "SRCDIR=${SRCDIR}"
-    # echo "DESTDIR=${DESTDIR} # more like a 'content' dir as this is all copied in here"
-    # echo "ARCHDIR=${ARCHDIR} # location of archive of DESTDIR"
-
-
-#    echo "    ... DESTDIR=${DESTDIR}"
-#    echo "    ... CONTAINER=${CONTAINER}"
-    if [[ ! -e "${WOV_BASEDIR}/wovtools/containers/$f" ]]; then 
-      echo "ERROR: recipe for container ${f} does not exist (${WOV_BASEDIR}/wovtools/containers/$f).";
-      exit 1
-    elif [[ ! -x "${WOV_BASEDIR}/wovtools/containers/$f" ]]; then 
-      echo "ERROR: recipe for container ${f} not executable (${WOV_BASEDIR}/wovtools/containers/$f).";
-      exit 1
-    else
-
-      doPackContainer ${f}
-
-      # Just packed container, do we need to build it? Do diffs against archive, then compare remote container
-      NEEDSBUILD=0
-      diff -q -r ${DESTDIR} ${ARCHDIR} > /dev/null
-      NEEDSBUILD=$?
-      if [ "$NEEDSBUILD" != "0" ]; then 
-        echo "  ... packed container differs so will build.";
-      else
-        echo "  ... check push container status"
-        wov-pushcontainer-check -q ${f}
-        NEEDSBUILD=$?
-        if [ "$NEEDSBUILD" != "0" ]; then 
-          echo "  ... pushed containers differ so will build.";
-        fi
-      fi
-        #echo "NEEDSBUILD: ${NEEDSBUILD}"
-        # printf "\n\n\n\nNEEDSBUILD: $NEEDSBUILD\n\n\n"
-        #    echo "NEEDSBUILDOUT: $NEEDSBUILDOUT"
-        #    if [ ${NEEDSBUILD} == 1 ] || [ $DOFORCE == 1 ]; then
-        #      echo "    ... forcing container build."
-        #
-        #    elif [ "$(docker images -q ${CONTAINER})" == "" ]; then 
-        #      docker images -q ${CONTAINER}
-        #      echo "    ... no existing container, building"
-        #      NEEDSBUILD=1
-        #
-        #    elif [ ! -e ${ARCHDIR} ]; then 
-        #      echo "    ... no ${ARCHDIR}, building"
-        #      NEEDSBUILD=1; 
-        #
-        #    elif [ "$(diff -rq --exclude='.dirstamp' --exclude='.DS_Store' ${DESTDIR} ${ARCHDIR} &> /dev/null ; echo $?)" != "0" ]; then 
-        #      echo "    ... diffs when comparing ${DESTDIR} to ${ARCHDIR}, building"
-        #      NEEDSBUILD=1; 
-        #    fi
-        #
-      if [ "${NEEDSBUILD}" ==  "4" ]; then exit  ${NEEDSBUILD}; fi
-      if [ "${NEEDSBUILD}" ==  "3" ]; then exit  ${NEEDSBUILD}; fi
-      if [ "${NEEDSBUILD}" ==  "2" ]; then exit  ${NEEDSBUILD}; fi
-
-      # Build
-      JUSTBUILT=0
-      if [ "${NEEDSBUILD}" == "1" ] || [ "${DOFORCE}" == "1" ]; then
-        JUSTBUILT=1
-
-        doBuildContainer ${f}
-
-      else
-        echo "  ... container build not needed"
-      fi
-
-
-      # Do we push the container?
-      if [ "$DOPUSH" == "0" ]; then
-        printf "  ... skipping container push\n"
-      else
-
-        # echo "needsbuild '${NEEDSBUILD}'"
-
-        # Tag and Push
-        if [ "${NEEDSBUILD}" == "1" ] || [ "${NEEDSBUILD}" == "5" ] || [ "${DOFORCE}" == "1" ]; then
-          echo "  ... tag repo"
-          docker tag ${WOV_PROJECT}/${CONTAINER} ${WOV_ARCHIVEREPOSITORY}/${WOV_PROJECT}/${CONTAINER}:${WOV_STAGE}_${WOV_PVER}
-
-          echo "  ... push container to: ${WOV_ARCHIVEREPOSITORY}/${WOV_PROJECT}/${CONTAINER}:${WOV_STAGE}_${WOV_PVER}"
-
-          # If just built, dump log, since it will have to push a lot of data
-  #        if [ "${JUSTBUILT}" == "1" ]; then
-            R=$(docker push ${WOV_ARCHIVEREPOSITORY}/${WOV_PROJECT}/${CONTAINER}:${WOV_STAGE}_${WOV_PVER} 2>&1 | tee /dev/tty )
-            RR=$?
-  #        else
-#          R=$(docker push ${WOV_ARCHIVEREPOSITORY}/${WOV_PROJECT}/${CONTAINER}:${WOV_STAGE}_${WOV_PVER} 2>&1 )
-#          RR=$?
-#        fi
-          # echo "R: ${R} RR=${RR}"
-          if [[ $R == 'name unknown'* ]]; then
-            printf "\n\n  ...${R}.\n"
-            exit 1
-          fi
-          if [[ $R == *'Your Authorization Token has expired.'* ]]; then
-            echo "    ... auto-login to AWS attempt"
-            AWSAUTHCMD=$(aws ecr get-login --no-include-email)
-            eval ${AWSAUTHCMD}
-            if [ "$?" != "0" ]; then
-              echo "      ... FAILED auto-login to AWS attempt"
-              exit 1
-            else
-              echo "      ... SUCCESS auto-login to AWS attempt"
-              echo "    ... re-push container to: ${WOV_ARCHIVEREPOSITORY}/${WOV_PROJECT}/${CONTAINER}:${WOV_STAGE}_${WOV_PVER}"
-              R=$(docker push ${WOV_ARCHIVEREPOSITORY}/${WOV_PROJECT}/${CONTAINER}:${WOV_STAGE}_${WOV_PVER} 2>&1  | tee /dev/tty)
-              if [ "$?" != "0" ]; then
-                printf "\n\n  ...still errors: ${R}.\n"
-                exit 1
-              fi
-            fi
-          fi
-
-        else
-          echo "  ... container push not needed"
-        fi
-
-        echo "  ... tagging as dev container and pushing"
-        docker tag ${WOV_ARCHIVEREPOSITORY}/${WOV_PROJECT}/${CONTAINER}:${WOV_STAGE}_${WOV_PVER} ${WOV_ARCHIVEREPOSITORY}/${WOV_PROJECT}/${CONTAINER}:${WOV_STAGE}_dev
-        docker push ${WOV_ARCHIVEREPOSITORY}/${WOV_PROJECT}/${CONTAINER}:${WOV_STAGE}_dev
-        echo "  ... done '${CONTAINER}'."
-      fi
-    fi
-
-
+    if [ $DOECHO -ge 1 ]; then printf "\n%-${FOLD}s\n" "-" | tr ' ' '-' ; echo "... push container '${f}'."; fi
+    doPushContainer $@
   done
 
-  printf "\nCompleted Building:\n"
-  for f in ${RECIPES}; do
-    echo "  ... built: ${WOV_PROJECT}/${WOV_PROJECT}${f}"
-  done
-  printf "    run locally: 'docker run CONTAINER'\n"
-  printf "     open shell: 'docker run --rm -it CONTAINER bash'\n"
+  if [[ $DOECHO -ge 1 ]]; then
+    printf "\nCompleted Building:\n"
+    for f in ${RECIPES}; do
+      echo "  ... built: ${WOV_PROJECT}/${WOV_PROJECT}${f}"
+    done
+    printf "    run locally: 'docker run CONTAINER'\n"
+    printf "     open shell: 'docker run --rm -it CONTAINER bash'\n"
+  fi
 fi
+
