Intermediate commit as tests don't all pass, but not due to wovtools functionality, but tests themselves.
- moved wov-init-db into own file, from wov-init. added a call to it
from wov-init
- wov-init-ms now adds msname.json to wovtools/config.json for dev and
prod which was breaking configurations
- upgraded 'wov' command
- wov-db
  - fixed -c option for passing commands which was breaking logging
  - added git adds/commit/push for when creating Wov Databases
  - other bug fixes
- Database Archive
  - added wov-db --snapshot to update snapshot entry of WovDB
  - added snapshotting import to wov-push-db
- wov-push-db
  - now uses snapshot from wov-db and skips step 4 of it's own
processes fo pushing db
  - step 5 now has a message auto-assigned to it when pushing to Git
- wov-env --set-origin X to update wovtools/myconfig.json
- bug in wov-init for PROJECT not being set

TESTS: they are closer to passing but in many cases, they don't pass
because the tests themselves have dependencies... i.e. the commands work
as intended but the test cases are flawed.

diff --git a/bin/wov-init b/bin/wov-init
--- a/bin/wov-init
+++ b/bin/wov-init
@@ -51,9 +51,9 @@ echo "`basename $0`"
 echo "Initializes this directory as a wovtools project. This should be non-destructive, only adding at .git and wovtools directories." | fold -w ${FOLD} -s
 echo ""
 
-PROJECT=$(basename $(pwd))
+WOV_PROJECT=$(basename $(pwd))
 while true; do
-  read -r -p "One word PROJECT name (not a title!) : (\"${PROJECT}\") ... Correct? [Y/n] " A
+  read -r -p "One word PROJECT name (not a title!) : (\"${WOV_PROJECT}\") ... Correct? [Y/n] " A
 
   case $A in
     ""|[Yy][Ee][Ss]|[Yy])
@@ -61,14 +61,14 @@ while true; do
     ;;
     [Nn][Oo]|[Nn])
     printf "ok, enter project name: "
-    read PROJECT
-    if [[ ! $PROJECT =~ ^[A-Za-z][A-Za-z_0-9]+$ ]];  then
+    read WOV_PROJECT
+    if [[ ! $WOV_PROJECT =~ ^[A-Za-z][A-Za-z_0-9]+$ ]];  then
       echo "ERROR: bad project name, needs to be a string with no spaces (i.e. [A-Za-z][A-Za-z_0-9]*)" 
-      PROJECT=$(basename $(pwd))
+      WOV_PROJECT=$(basename $(pwd))
     fi
     ;;
   *)
-    echo "Invalid input..."
+    echo "Invalid input... (${A})"
     ;;
   esac
 done
@@ -84,11 +84,11 @@ function timeout_monitor() {
 
 
 # Ensure global entry for the project
-WOV_PROJDIR=$(cat ${HOME}/.wovtools | jq -r ".projects[\"${PROJECT}\"].dir")
+WOV_PROJDIR=$(cat ${HOME}/.wovtools | jq -r ".projects[\"${WOV_PROJECT}\"].dir")
 if [ "${WOV_PROJDIR}" == "null" ]; then
   echo "  ... creating project entry in: ~/.wovtools"
   CWD=`pwd`
-  cat ~/.wovtools | jq " .projects[\"${PROJECT}\"].dir = \"${CWD}\"" > ~/.wovtools.$$ && cp ~/.wovtools.$$ ~/.wovtools
+  cat ~/.wovtools | jq " .projects[\"${WOV_PROJECT}\"].dir = \"${CWD}\"" > ~/.wovtools.$$ && cp ~/.wovtools.$$ ~/.wovtools
 fi
 
 
@@ -184,7 +184,7 @@ function InitProject()
   "ver" : "initing",
   "project" : {
     "type" : "",
-    "project" : "${PROJECT}",
+    "project" : "${WOV_PROJECT}",
     "title" : "",
     "description" : ""
   },
@@ -195,29 +195,27 @@ function InitProject()
   "nodeploy" : [],
   "secrets" : {
     "dev" : [ 
-      "cluster_defaults.json",
       "cluster_mymanaged.json",
       "repositories.json",
-      "${PROJECT}.json",
-      "${PROJECT}db.json",
-      "${PROJECT}_${WOV_ME}.json",
-      "${PROJECT}db_${WOV_ME}.json"
+      "${WOV_PROJECT}.json",
+      "${WOV_PROJECT}db.json",
+      "${WOV_PROJECT}_${WOV_ME}.json",
+      "${WOV_PROJECT}db_${WOV_ME}.json"
     ],
     "prod" : [
-      "cluster_defaults.json",
       "cluster_mymanaged.json",
       "repositories.json",
-      "${PROJECT}.json",
-      "${PROJECT}db.json",
-      "${PROJECT}_prod.json",
-      "${PROJECT}db_prod.json"
+      "${WOV_PROJECT}.json",
+      "${WOV_PROJECT}db.json",
+      "${WOV_PROJECT}_prod.json",
+      "${WOV_PROJECT}db_prod.json"
     ]
   },
   "originmods": {
     "local" : {
       "description" : "For deverlopers to develop locally.",
       "routes": [
-        [ "${PROJECT}db.CLUSTERlocal",      "${PROJECT}db"     ]
+        [ "${WOV_PROJECT}db.CLUSTERlocal",      "${WOV_PROJECT}db"     ]
       ]
     },
     "vh" : {
@@ -246,10 +244,10 @@ EOF
     "${WOV_ME}" : [
       "cluster_mymanaged.json",
       "repositories.json",
-      "${PROJECT}.json",
-      "${PROJECT}db.json",
-      "${PROJECT}_${WOV_ME}.json",
-      "${PROJECT}db_${WOV_ME}.json"
+      "${WOV_PROJECT}.json",
+      "${WOV_PROJECT}db.json",
+      "${WOV_PROJECT}_${WOV_ME}.json",
+      "${WOV_PROJECT}db_${WOV_ME}.json"
     ]
   },
   "originmods" : {
@@ -329,43 +327,43 @@ fi
   SECRETSDIR="`wov-cd -e secrets`"
   if [ "${SECRETSDIR}" == "" ]; then echo "ERROR: Unknown secrets dir. Add an entry to ~/.wovtools, for : dirs.secrets.dir."; exit 1; fi
   if [ ! -e "${SECRETSDIR}" ]; then mkdir -p "${SECRETSDIR}"; chmod 600 "${SECRETSDIR}"; fi
-  if [ ! -e "${SECRETSDIR}/${PROJECT}_secrets" ]; then mkdir -p "${SECRETSDIR}/${PROJECT}_secrets"; chmod 600 "${SECRETSDIR}/${PROJECT}_secrets"; fi
+  if [ ! -e "${SECRETSDIR}/${WOV_PROJECT}_secrets" ]; then mkdir -p "${SECRETSDIR}/${WOV_PROJECT}_secrets"; chmod 600 "${SECRETSDIR}/${WOV_PROJECT}_secrets"; fi
 
   # remake the softlink
   rm -f "${WOV_BASEDIR}/wovtools/secrets" || true
-  ln -s "${SECRETSDIR}/${PROJECT}_secrets" "${WOV_BASEDIR}/wovtools/secrets"
+  ln -s "${SECRETSDIR}/${WOV_PROJECT}_secrets" "${WOV_BASEDIR}/wovtools/secrets"
   if [ "$?" != "0" ]; then
-    echo "ERROR: failed linking to '${SECRETSDIR}/${PROJECT}_secrets' at '${WOV_BASEDIR}/wovtools/secrets'."
+    echo "ERROR: failed linking to '${SECRETSDIR}/${WOV_PROJECT}_secrets' at '${WOV_BASEDIR}/wovtools/secrets'."
     exit 1
   fi
 
   # make sure default secret files exist
-  if [ ! -e "${WOV_BASEDIR}/wovtools/secrets/${PROJECT}.json" ]; then 
-    cat <<EOF > "${WOV_BASEDIR}/wovtools/secrets/${PROJECT}.json"
+  if [ ! -e "${WOV_BASEDIR}/wovtools/secrets/${WOV_PROJECT}.json" ]; then 
+    cat <<EOF > "${WOV_BASEDIR}/wovtools/secrets/${WOV_PROJECT}.json"
 {
   "www" : {
     "STAGEdev" : {
-      "api"   : {"urlscheme" : "https", "url" : "api-dev.${PROJECT}.com"},
-      "app"   : {"urlscheme" : "https", "url" : "app-dev.${PROJECT}.com"}
+      "api"   : {"urlscheme" : "https", "url" : "api-dev.${WOV_PROJECT}.com"},
+      "app"   : {"urlscheme" : "https", "url" : "app-dev.${WOV_PROJECT}.com"}
     },
     "STAGEprod" : {
-      "api"   : {"urlscheme" : "https", "url" : "api.${PROJECT}.com"},
-      "app"   : {"urlscheme" : "https", "url" : "app.${PROJECT}.com"}
+      "api"   : {"urlscheme" : "https", "url" : "api.${WOV_PROJECT}.com"},
+      "app"   : {"urlscheme" : "https", "url" : "app.${WOV_PROJECT}.com"}
     }
   }
 }
 EOF
   fi
 
-  if [ ! -e "${WOV_BASEDIR}/wovtools/secrets/${PROJECT}db.json" ]; then 
-    cat <<EOF > "${WOV_BASEDIR}/wovtools/secrets/${PROJECT}db.json"
+  if [ ! -e "${WOV_BASEDIR}/wovtools/secrets/${WOV_PROJECT}db.json" ]; then 
+    cat <<EOF > "${WOV_BASEDIR}/wovtools/secrets/${WOV_PROJECT}db.json"
 {
-  "${PROJECT}db" : {
+  "${WOV_PROJECT}db" : {
     "//subhost" : "combined with WOV_CLUSTER to create host name. if localhost, only localhost",
-    "subhost"      : "${PROJECT}dev",
+    "subhost"      : "${WOV_PROJECT}dev",
     "username"     : "postgres",
     "endpoint"     : "unknown.rds.amazonaws.com",
-    "database"     : "${PROJECT}dev",
+    "database"     : "${WOV_PROJECT}dev",
     "port"         : 5432,
     "type"         : "postgres",
     "version"      : "9.6.11-R1",
@@ -388,8 +386,8 @@ EOF
 EOF
   fi
 
-  if [ ! -e "${WOV_BASEDIR}/wovtools/secrets/${PROJECT}_${WOV_ME}.json" ]; then 
-    cat <<EOF > "${WOV_BASEDIR}/wovtools/secrets/${PROJECT}_${WOV_ME}.json"
+  if [ ! -e "${WOV_BASEDIR}/wovtools/secrets/${WOV_PROJECT}_${WOV_ME}.json" ]; then 
+    cat <<EOF > "${WOV_BASEDIR}/wovtools/secrets/${WOV_PROJECT}_${WOV_ME}.json"
 {
   "//tokencmd" : "openssl rand -hex 20",
   "microservice" : { "STAGE${WOV_ME}" : { "token" : "GENERATE A TOKEN" } },
@@ -404,10 +402,10 @@ EOF
   fi
 
 
-  if [ ! -e "${WOV_BASEDIR}/wovtools/secrets/${PROJECT}db_${WOV_ME}.json" ]; then 
-    cat <<EOF > "${WOV_BASEDIR}/wovtools/secrets/${PROJECT}db_${WOV_ME}.json"
+  if [ ! -e "${WOV_BASEDIR}/wovtools/secrets/${WOV_PROJECT}db_${WOV_ME}.json" ]; then 
+    cat <<EOF > "${WOV_BASEDIR}/wovtools/secrets/${WOV_PROJECT}db_${WOV_ME}.json"
 {
-  "${PROJECT}db" : { "STAGE${WOV_ME}" : { "//" : "Separate database, should use separate user/pass", "database" : "${PROJECT}${WOV_ME}" } }
+  "${WOV_PROJECT}db" : { "STAGE${WOV_ME}" : { "//" : "Separate database, should use separate user/pass", "database" : "${WOV_PROJECT}${WOV_ME}" } }
 }
 EOF
   fi
@@ -426,67 +424,6 @@ EOF
 }
 
 
-function InitDBArchive()
-{
-echo ""
-if [ -e "${WOV_BASEDIR}/wovtools/db" ] &&
-   [ -e "${WOV_BASEDIR}/wovtools/db/archive" ] &&
-   [ -e "${WOV_BASEDIR}/wovtools/db/archive/.git" ] &&
-   [ -e "${WOV_BASEDIR}/wovtools/db/archive/.gitignore" ] &&
-   [ -e "${WOV_BASEDIR}/wovtools/db/archive/.git/config" ]; then
-  echo "ARCHIVE> Database Registry exists (at wovtools/db/archive)"
-else
-
-  # ensure directory
-  if [ ! -e "${WOV_BASEDIR}/wovtools/db/archive" ]; then
-    mkdir -p ${WOV_BASEDIR}/wovtools/db/archive
-  fi
-  chmod -R 700 "${WOV_BASEDIR}/wovtools/db"
-
-  # make gitignore
-  if [ ! -e "${WOV_BASEDIR}/wovtools/db/archive/.gitignore" ]; then
-    cat <<EOF > ${WOV_BASEDIR}/wovtools/db/archive/.gitignore
-  *.swp
-EOF
-  fi
-
-  WOV_DBREGISTRY=`git config --get remote.origin.url`
-  WOV_DBREGISTRY="${WOV_DBREGISTRY%.git}_db.git"
-  if [ "$?" != "0" ]; then
-    printf "\nERROR: remote origin is not set for this repository.\n"
-    printf "  Use 'git remote add origin X' to set your remote repository.\n\n"
-    exit 1
-  fi
-  #  WOV_DBREGISTRY="${WOV_DBREGISTRY::-4}_archive.git"
-
-  read -r -p "ARCHIVE> Database Registry git location: (\"${WOV_DBREGISTRY}\") ... Correct? [Y/n] " A
-  if [ "${A}" != "" ]; then WOV_DBREGISTRY="${A}"; fi
-
-  # make git repository
-  cd ${WOV_BASEDIR}/wovtools/db/archive && git init -q
-
-  # configure it
-  cat <<EOF > ${WOV_BASEDIR}/wovtools/db/archive/.git/config
-[core]
-  repositoryformatversion = 0
-  filemode = true
-  bare = false
-  logallrefupdates = true
-  ignorecase = true
-  precomposeunicode = true
-[remote "origin"]
-  url = ${WOV_DBREGISTRY}
-  fetch = +refs/heads/*:refs/remotes/origin/*
-[user]
-  name = ${WOV_USERNAME}
-  email = ${WOV_USEREMAIL}
-[branch "master"]
-  remote = origin
-  merge = refs/heads/master
-EOF
-
-fi
-}
 
 
 # ---------------------------------------------------------------------
@@ -552,13 +489,23 @@ if [ "$(wov-env &> /dev/null ; echo $?)" == "1" ]; then
   echo "... creating new wovtools project in this directory."
   InitProject
 else
-  echo "... updating project: ${PROJECT}"
+  echo "... updating project: ${WOV_PROJECT}"
   WOV_BASEDIR=$(git rev-parse --show-toplevel)
 fi
 
 
-# Ensure DB structure so wov-env can run
-InitDBArchive
+echo "...Ensure DB Archive structure so wov-env can run (interactive mode)"
+wov-init-dba --exists-check
+if [ $? -eq  1 ]; then 
+  echo "  ...creating Database Archive"
+  wov-init-dba
+  if [ $? -ne 0 ]; then
+    echo "ERROR: failed to create Database Archive"
+    exit 1
+  fi
+else
+  echo "  ...skipping DB Archive creation"
+fi
 
 echo "... loading WovTools values."
 initargs=( "$@" )
@@ -601,7 +548,7 @@ while true; do
       read WOV_ARCHIVEREPOSITORY
     ;;
   *)
-    echo "Invalid input..."
+    echo "Invalid input... (${A})"
     ;;
   esac
 done
diff --git a/bin/wov-push-db b/bin/wov-push-db
--- a/bin/wov-push-db
+++ b/bin/wov-push-db
@@ -310,6 +310,34 @@ function doCommit()
   done
 }
 
+
+# Add an entry to the deltas so it gets logged and then update the log 
+# $1 - dbname
+# $2 - snapshot
+function doSetSnapshot()
+{
+  DB_snapshot="${2}"
+  echo "# Snapshot : ${DB_snapshot}" >> "${WOV_BASEDIR}/wovtools/db/${1}.deltas"
+  doUpdateDBArchiveLog "$1" "${WOV_PVER}" "${WOV_SVER}" "${2}"
+}
+
+
+# $1 - dbname
+# $2 - PVER
+# $3 - SVER
+# $4 - DB_snapshot
+function doUpdateDBArchiveLog()
+{
+  echo "  ... update Database Archive logs :$1 $2 $3 $4"
+  R=$(wov-db $1 -q -d wovtools -c "INSERT INTO logs (database, wovtoolsver, label, pver, sver, snapshot ) VALUES ( '$1', '${WOV_VERSION}', '${2}_${3}', ${2}, ${3}, '${4}' );")
+  if [ "$?" != "0" ]; then
+    printf "${R}"
+    printf "\n\nERROR: failed updating archive database(${1}) ${2}_${3} snapshot(${4}).\n"
+    fFailedDBConnection 3 $1
+  fi
+}
+
+
 # - 2-4 --------------------------------------------------------------- 
 # TODO: make these transactional, since if these don't complete, system 
 #       can be in a bad state
@@ -329,47 +357,68 @@ function doCommitDB()
   # check deltas exist
   deltafile=${WOV_BASEDIR}/wovtools/db/$1.deltas
   if [ ! -e $deltafile ]; then
-    printf "\n\nERROR: can't find deltas file: 'wovtools/db/$1.deltas'.\n\n"
+    l_error "Can't find deltas file: 'wovtools/db/$1.deltas'."
     fFailedDBConnection 1 $1
   fi
 
   # make sure directory exists for database
   mkdir -p ${WOV_BASEDIR}/wovtools/db/archive/$1
 
-
   # get current db wovtools pver
   DB_ENTRY=$(doGetDBLastLogEntry $1)
   if [ "$?" != "0" ]; then
-    printf "\n\n***ERROR: database not inited.\n"
+    l_error "***ERROR: database not inited."
     fFailedDBConnection 1 $1
   fi
-#  printf "\nDB_ENTRY '${DB_ENTRY}'\n"
+  printf "\nDB_ENTRY '${DB_ENTRY}'\n"
 
-
-  # No parent, consider this the first entry
+  # should have been at least a snapshot entry
   if [ "${DB_ENTRY}" == "" ]; then
-    if [ "${DB_SNAPSHOT}" == "" ]; then
-      printf "\nERROR: need to provide a snapshot for first commit of database. Use --snapshot X. ex. rds:wov-aws-va-ant-db-alywandev-2017-07-17-07-20.\n"
-      fFailedDBConnection 3 $1
-    fi
-    DB_PVER=${WOV_PVER}
-    DB_snapshot="${DB_SNAPSHOT}"
-  else
-    OLDIFS=$IFS
-    IFS='|'
-    DB_ENTRY=( $(echo "${DB_ENTRY[@]}") )
-    IFS=$OLDIFS
-    DB_PVER="$( echo -e "${DB_ENTRY[4]}" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')"
-    DB_snapshot="$( echo -e "${DB_ENTRY[6]}" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')"
+    l_error "ERROR: need to provide a snapshot for first commit of database. Use wov-db --snapshot X. ex. rds:wov-aws-va-ant-db-alywandev-2017-07-17-07-20."
+    fFailedDBConnection 3 $1
+    retval=3
   fi
 
-  if [ "$retval" == "0" ]; then
+  # look for existing data
+#  DB_ENTRY=( "${DB_ENTRY//|/ }" )
+#  printf "DB_ENTRY array '${DB_ENTRY[@]}'\n"
+  # DB_PVER="${DB_ENTRY[4]}"
+#  DB_snapshot="${DB_ENTRY[6]}"
+
+#    if [ "${DB_SNAPSHOT}" == "" ]; then
+#      l_error "ERROR: need to provide a snapshot for first commit of database. Use --snapshot X. ex. rds:wov-aws-va-ant-db-alywandev-2017-07-17-07-20."
+#      fFailedDBConnection 3 $1
+#    fi
+#    DB_PVER=${WOV_PVER}
+#    DB_snapshot="${DB_SNAPSHOT}"
+#  else
+#    DB_snapshot="${DB_SNAPSHOT}"
+#    set -x
+#    #OLDIFS=$IFS
+#    #IFS='|'
+#    #DB_ENTRY=( $(echo "${DB_ENTRY[@]}") )
+#    #IFS=$OLDIFS
+#    DB_ENTRY=( "${DB_ENTRY//|/ }" )
+#    printf "DB_ENTRY array '${DB_ENTRY[@]}'\n"
+#    # DB_PVER="$( echo -e "${DB_ENTRY[4]}" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')"
+#    # DB_snapshot="$( echo -e "${DB_ENTRY[6]}" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')"
+#    DB_PVER="${DB_ENTRY[4]}"
+#    DB_snapshot="${DB_ENTRY[6]}"
+#    set +x
+#    if [ "${DB_SNAPSHOT}" != "" ]; then
+#      l_warn "  ... overwriting existing snapshot with '${DB_SNAPSHOT}'"
+#      DB_snapshot="${DB_SNAPSHOT}"
+#    fi
+#  fi
+#  echo "Using DB_snapshot ${DB_snapshot}"
+
+  if [ $retval -eq 0 ]; then
 
     # validate json file first
     R=$(cat ${WOV_BASEDIR}/wovtools/db/archive/$1.json | jq empty 2>&1) ; Re=$?
     if [ $Re != 0 ]; then
-      echo "${R}"
-      echo "ERROR: wovtools/db/archive/$1.json file is not valid JSON. Exiting."
+      l_ "${R}"
+      l_error "wovtools/db/archive/$1.json file is not valid JSON. Exiting."
       exit 3
     fi
 
@@ -377,15 +426,15 @@ function doCommitDB()
     CHKSUM=$(doHashDBSchema $1)
     DB_PVER=$(doGetDBPVER $1)
     if [ "$?" != "0" ]; then
-      printf "**ERROR: failed connecting to db.\n\n"
+      l_error "failed connecting to db."
       fFailedDBConnection 1 $1
     fi
 
-    echo "Chksum : ${CHKSUM}  DBPVER: ${DB_PVER}  PVER: ${WOV_PVER}"
+    l_ "Chksum : ${CHKSUM}  DBPVER: ${DB_PVER}  PVER: ${WOV_PVER}"
 
     # - 2 ----------------------------------------------------------------- 
     # --------------------------------------------------------------------- 
-    echo "  ... move deltas into archive"
+    l_ "  ... move deltas into archive"
 
     # append delta to file
     appendfile=${WOV_BASEDIR}/wovtools/db/archive/$1/${WOV_PVER}.deltas
@@ -399,7 +448,7 @@ function doCommitDB()
 EOF
     cat ${deltafile} >> ${appendfile}
 
-    echo "  ... cache deltas locally (in case of screw up): wovtools/cache/db/$1.${WOV_PVER}.$(date +%s).deltas"
+    l_ "  ... cache deltas locally (in case of screw up): wovtools/cache/db/$1.${WOV_PVER}.$(date +%s).deltas"
     mv ${deltafile} ${WOV_BASEDIR}/wovtools/cache/db/$1.${WOV_PVER}.$(date +%s).deltas
 
 
@@ -441,13 +490,14 @@ EOF
 
     # - 4. update archive database log pver number, snapshot, checksum ----
     # --------------------------------------------------------------------- 
-    echo "  ... update archive database logs"
-    R=$(wov-db $1 -q -d wovtools -c "INSERT INTO logs (database, wovtoolsver, label, pver, sver, snapshot ) VALUES ( '$1', '${WOV_VERSION}', '${WOV_PVER}_${WOV_SVER}', ${WOV_PVER}, ${WOV_SVER}, '${DB_snapshot}' );")
-    if [ "$?" != "0" ]; then
-      printf "${R}"
-      printf "\n\nERROR: failed updating archive database pver number with checksum.\n"
-      fFailedDBConnection 3 $1
-    fi
+#    echo "  ... update archive database logs"
+#    R=$(wov-db $1 -q -d wovtools -c "INSERT INTO logs (database, wovtoolsver, label, pver, sver, snapshot ) VALUES ( '$1', '${WOV_VERSION}', '${WOV_PVER}_${WOV_SVER}', ${WOV_PVER}, ${WOV_SVER}, '${DB_snapshot}' );")
+#    if [ "$?" != "0" ]; then
+#      printf "${R}"
+#      printf "\n\nERROR: failed updating archive database pver number with checksum.\n"
+#      fFailedDBConnection 3 $1
+#    fi
+    doUpdateDBArchiveLog "${1}" ${WOV_PVER} ${WOV_SVER} "${DB_snapshot}"
 
     # - 5. push db git repo
 
@@ -469,7 +519,7 @@ EOF
     fi
 
     if [ ${DOECHO} -ge 1 ]; then echo "    ... git commit Database Archive"; fi
-    git -C ${WOV_BASEDIR}/wovtools/db/archive commit -a ; Re=$?
+    git -C ${WOV_BASEDIR}/wovtools/db/archive commit -a -m "Version ${WOV_ME}_${WOV_PVER}" ; Re=$?
     if [ $Re != 0 ]; then
       echo "ERROR: failed to commit Database Archive git repo in: ${WOV_BASEDIR}/wovtools/db/archive"
       fFailedDBConnection 4 $1
@@ -511,7 +561,9 @@ while [[ $1 =~ ^- ]]; do
 
   elif [ "$1" == "--snapshot" ]; then
     shift
-    DB_SNAPSHOT=$1
+    doSetSnapshot $1 $2
+    echo "WovDB $1 SNAPSHOT $2"
+    shift
     shift
 
   elif [ "$1" == "--any-push-blockage" ] || [ "$1" == "-pc" ] || [ "$1" == "--push-check" ]; then
@@ -532,6 +584,7 @@ while [[ $1 =~ ^- ]]; do
 done
 
 
+echo "WOV_DODEFAULTCOMMAND ${WOV_DODEFAULTCOMMAND} ${DOACTION}"
 if [ ${WOV_DODEFAULTCOMMAND} != 0 ]; then
 
   # Load in env
