Move existing directory aside before uploading.

diff --git a/bin/wov-vh-pushgit b/bin/wov-vh-pushgit
--- a/bin/wov-vh-pushgit
+++ b/bin/wov-vh-pushgit
@@ -112,6 +112,14 @@ for gd in ${GITDIRS[@]}; do
   wov-git-check ${gd}
   if [[ $? != 0 ]]; then printf "\nERROR: Git repo ${gd} has uncommitted changes.\n\n" 1>&2; CONTINUE=0; fi
 
+
+  if [[ $CONTINUE == 1 ]]; then
+    printf "  ...if existing directory, rename to avoid overwriting\n"
+    kubectl exec -it vh -- bash -c "if [ -e ${G} ]; then mv ${G} ${G}.`date -u +"%Y-%m-%dT%H:%M:%SZ"`; fi"
+    if [[ $? != 0 ]]; then printf "\nERROR: failed moving existing directory.\n\n" 1>&2 ; CONTINUE=0; fi
+  fi
+
+
   if [[ $CONTINUE == 1 ]]; then
     printf "  ...make remote git directory: ${G}\n"
     kubectl exec -it vh -- mkdir -p ${G}
@@ -126,13 +134,11 @@ for gd in ${GITDIRS[@]}; do
     if [[ $? != 0 ]]; then printf "\nERROR: failed making git archive for '$G'.\n\n" 1>&2 ; CONTINUE=0; fi
   fi
 
-
   if [[ $CONTINUE == 1 ]]; then
     printf "  ...cp archive to vh.\n"
     kubectl cp ${WOV_BASEDIR}/wovtools/cache/archive.$$.tar.gz vh:${G}/archive.$$.tar.gz
     if [[ $? != 0 ]]; then printf "\nERROR: failed copying archive to vh.\n\n"  1>&2; CONTINUE=0; fi
   fi
-
 
   if [[ $CONTINUE == 1 ]]; then
     printf "  ...extract $G files in vh.\n"
