Fixed an oops moment of not ensuring that the PROJECT variable was synced between WovTools and K8s. Other fixes as well.

diff --git a/bin/wov-env b/bin/wov-env
--- a/bin/wov-env
+++ b/bin/wov-env
@@ -27,6 +27,8 @@ usage: `basename $0` [options]
   --var X      : only operate on this variable X
   -h/--help    : display these options
   -v/--version : version of wovtools
+  --env X      : echo the environment variables in file X in wovtools/cache/conf/X (NOTE: removes comments)
+  --cmd X      : on one line, echo the environment variables in file X in wovtools/cache/conf/X (NOTE: removes comments)
 
 Example Usage:
   `basename $0`    : sets all environment variables
@@ -51,8 +53,8 @@ IFS=$OLDIFS
 #echo "value = ${array[2]}"
 #echo ${array[*]}
 WOV_KSTAGE=${array[5]}
-WOV_AIM=${array[4]}
-WOV_NS=${WOV_AIM}-${WOV_KSTAGE}
+WOV_KPROJECT=${array[4]}
+WOV_NS=${WOV_KPROJECT}-${WOV_KSTAGE}
 export WOV_BASEDIR
 WOV_FLAVOR=${array[3]}
 WOV_REGION=${array[2]}
@@ -80,11 +82,11 @@ if [ -e "${WOV_BASEDIR}/wovtools/config.json" ]; then
   #echo "A:${A[*]}:A"
   #dir_root="${A[0]}"
 
-  WOV_PROJECT=$(cat ${WOV_BASEDIR}/wovtools/config.json | jq -r '.project.project') 
+  WOV_WPROJECT=$(cat ${WOV_BASEDIR}/wovtools/config.json | jq -r '.project.project') 
   WOV_PROJECTTYPE=$(cat ${WOV_BASEDIR}/wovtools/config.json | jq -r '.project.type') 
   WOV_PROJECTTITLE=$(cat ${WOV_BASEDIR}/wovtools/config.json | jq -r '.project.title') 
   WOV_PROJECTDESCRIPTION=$(cat ${WOV_BASEDIR}/wovtools/config.json | jq -r '.project.description') 
-  export WOV_PROJECT
+  export WOV_WPROJECT
   export WOV_PROJECTTYPE
   export WOV_PROJECTTITLE
   export WOV_PROJECTDESCRIPTION
@@ -97,6 +99,9 @@ if [ -e "${WOV_BASEDIR}/wovtools/config.json" ]; then
   WOV_STAGE=$WOV_GSTAGE
   export WOV_GSTAGE
   export WOV_STAGE
+
+  WOV_PROJECT=${WOV_WPROJECT}
+  export WOV_PROJECT
 fi
 
 export K8S_CONTEXT
@@ -106,7 +111,7 @@ export WOV_CLTYPE
 export WOV_PROVIDER
 export WOV_REGION
 export WOV_FLAVOR
-export WOV_AIM 
+export WOV_PROJECT
 export WOV_KSTAGE
 
 # --------------------------------------------------------------------- 
@@ -125,7 +130,7 @@ function fDoEcho()
   echo WOV_PROVIDER="$WOV_PROVIDER"
   echo WOV_REGION="$WOV_REGION"
   echo WOV_FLAVOR="$WOV_FLAVOR"
-  echo WOV_AIM="$WOV_AIM"
+  echo WOV_PROJECT="$WOV_PROJECT"
   echo WOV_KSTAGE="$WOV_KSTAGE"
   if [ "$RANGIT" == "1" ]; then
     echo WOV_GSTAGE="$WOV_GSTAGE"
@@ -145,6 +150,8 @@ function fDoEcho()
     echo WOV_PROJECTTYPE="$WOV_PROJECTTYPE"
     echo WOV_PROJECTTITLE="$WOV_PROJECTTITLE"
     echo WOV_PROJECTDESCRIPTION="$WOV_PROJECTDESCRIPTION"
+    echo WOV_KPROJECT="$WOV_KPROJECT"
+    echo WOV_WPROJECT="$WOV_WPROJECT"
   fi
 }
 
@@ -158,6 +165,30 @@ function fDoCluster()
   export CL_ZONES
 }
 
+function doEnv() 
+{
+  if [ -e ${WOV_BASEDIR}/wovtools/cache/conf/${1} ]; then
+    cat ${WOV_BASEDIR}/wovtools/cache/conf/${1} | sed -e 's/#.*$//' -e '/^$/d'
+  else
+    echo
+    echo "ERROR: no environment file ${1} in cache."
+    echo
+    exit 1
+  fi
+}
+
+function doCmd() 
+{
+  if [ -e ${WOV_BASEDIR}/wovtools/cache/conf/${1} ]; then
+    cat ${WOV_BASEDIR}/wovtools/cache/conf/${1} | sed -e 's/#.*$//' -e '/^$/d' | tr '\n' ' '
+  else
+    echo
+    echo "ERROR: no environment file ${1} in cache."
+    echo
+    exit 1
+  fi
+}
+
 
 # --------------------------------------------------------------------- 
 # Command line processing
@@ -166,6 +197,15 @@ while [[ $1 =~ ^- ]]; do
     ECHOMODE=1
   elif [ "$1" == '-c' ] || [ "$1" == '--cluster' ]; then
     fDoCluster
+
+  elif [ "$1" == "--env" ]; then
+    shift
+    doEnv $1
+
+  elif [ "$1" == "--cmd" ]; then
+    shift
+    doCmd $1
+
   elif [ "$1" == '--var' ]; then
     shift 
     if [ "$ECHOMODE" == "1" ]; then
diff --git a/bin/wov-push-containers b/bin/wov-push-containers
--- a/bin/wov-push-containers
+++ b/bin/wov-push-containers
@@ -3,6 +3,7 @@
 DOECHO=1
 DOFORCE=0
 FOLD=80
+BLOCK=0
 
 # --------------------------------------------------------------------- 
 # Import Env 
@@ -10,7 +11,7 @@ FOLD=80
 pushcontainersargs=( "$@" )
 set ""
 . wov-env
-. wov-stagecompare
+. wov-ns-check
 set -- "${pushcontainersargs[@]}"
 #set -x
 
@@ -28,14 +29,21 @@ usage: `basename $0` [options]
 
 Runs the recipe scripts and if there is a change, build the containers.
 
-  -f : force build
   -h : this help
+  -l : list containers
+  -f : force build
   -q/-v : quiet/verbose
 
 EOF
 }
 
 
+function doList()
+{
+  C=$(ls ${WOV_BASEDIR}/wovtools/containers/*.sh 2> /dev/null )
+  RETVAL=$?
+  if [ $RETVAL -eq 0 ]; then echo $C; else echo "No containers"; fi
+}
 
 # ---------------------------------------------------------------------
 # Handle Params
@@ -54,6 +62,11 @@ while [[ $1 =~ ^- ]]; do
     shift
     DOFORCE=1
 
+  elif [ "$1" == "-l" ]; then
+    shift
+    doList
+    BLOCK=1
+
   elif [ "$1" == "-h" ] || [ "$1" == "--help" ]; then
     fDisplayOptions
     exit 0
@@ -70,18 +83,20 @@ done
 
 
 
-
+if [ "${BLOCK}" == "0" ]; then
 # Find the recipes
-RECIPES=$(cd ${WOV_BASEDIR}/wovtools/containers; ls *.sh)
+RECIPES=$(cd ${WOV_BASEDIR}/wovtools/containers; ls *.sh 2> /dev/null)
 
 
 # Build containers if needed
 for f in ${RECIPES}; do
 
+  if [ $DOECHO -ge 1 ]; then echo "... build container ${f%.sh}."; fi
+
   SRCDIR=${WOV_BASEDIR}
   DESTDIR=${WOV_BASEDIR}/wovtools/cache/containers/${f%.sh}
   ARCHDIR=${WOV_BASEDIR}/wovtools/cache/containers/archive/${f%.sh}
-  CONTAINER=${WOV_PROJECT}-${WOV_AIM}${f%.sh}
+  CONTAINER=${WOV_PROJECT}${f%.sh}
 #  echo "CONTAINER=${CONTAINER}"
 #  echo "SRCDIR=${SRCDIR}"
 #  echo "DESTDIR=${DESTDIR} # more like a 'content' dir as this is all copied in here"
@@ -89,47 +104,52 @@ for f in ${RECIPES}; do
 
   # build the content in wovtools/cache/containers/$f
   mkdir -p ${DESTDIR}
-  echo "  ... recipe $f"
-  cd ${WOV_BASEDIR} && SRCDIR=${SRCDIR} DESTDIR=${DESTDIR} ${WOV_BASEDIR}/wovtools/containers/$f
-
-  # determine if need to build container
-  NEEDSBUILD=0
-
-  if [ "$(docker images -q ${CONTAINER})" == "" ]; then 
-    docker images -q ${CONTAINER}
-    echo "    ... no existing container, building"
-    NEEDSBUILD=1
-
-  elif [ ! -e ${ARCHDIR} ]; then 
-    echo "    ... no ${ARCHDIR}, building"
-    NEEDSBUILD=1; 
-
-  elif [ "$(diff -rq --exclude='.dirstamp' --exclude='.DS_Store' ${DESTDIR} ${ARCHDIR} &> /dev/null ; echo $?)" != "0" ]; then 
-    echo "    ... diffs when comparing ${DESTDIR} to ${ARCHDIR}, building"
-    NEEDSBUILD=1; 
-  fi
-
-  # do actions 
-  if [ "${NEEDSBUILD}" == "1" ] || [ "${DOFORCE}" == "1" ]; then
-
-    echo "    ... creating container '${CONTAINER}'"
-    docker build -f ${DESTDIR}/Dockerfile -t ${CONTAINER}:latest ${DESTDIR} || exit 1
-
-    echo "    ... archiving build of container '${CONTAINER}'"
-    mkdir -p ${ARCHDIR}
-    rsync -ai --delete ${DESTDIR}/ ${ARCHDIR} &> /dev/null
-
-    echo "    ... tag and push to repo"
-    docker tag ${CONTAINER} ${WOV_ARCHIVEREPOSITORY}/${CONTAINER}:${WOV_STAGE}_${WOV_PVER}
-
-    echo "    ... push container to: ${WOV_ARCHIVEREPOSITORY}/${CONTAINER}:${WOV_STAGE}_${WOV_PVER}"
-    docker push ${WOV_ARCHIVEREPOSITORY}/${CONTAINER}:${WOV_STAGE}_${WOV_PVER} 
-
+  echo "  ... recipe $f (DESTDIR=${DESTDIR}, CONTAINER=${CONTAINER})"
+  if [[ ! -x "${WOV_BASEDIR}/wovtools/containers/$f" ]]; then 
+    echo "ERROR: recipe for container ${f%.sh} not executable (${WOV_BASEDIR}/wovtools/containers/$f).";
   else
-    echo "    ... skipping build of container '${CONTAINER}'"
+    cd ${WOV_BASEDIR} && SRCDIR=${SRCDIR} DESTDIR=${DESTDIR} CONTAINER=${CONTAINER} ${WOV_BASEDIR}/wovtools/containers/$f
+
+    # determine if need to build container
+    NEEDSBUILD=0
+
+    if [ "$(docker images -q ${CONTAINER})" == "" ]; then 
+      docker images -q ${CONTAINER}
+      echo "    ... no existing container, building"
+      NEEDSBUILD=1
+
+    elif [ ! -e ${ARCHDIR} ]; then 
+      echo "    ... no ${ARCHDIR}, building"
+      NEEDSBUILD=1; 
+
+    elif [ "$(diff -rq --exclude='.dirstamp' --exclude='.DS_Store' ${DESTDIR} ${ARCHDIR} &> /dev/null ; echo $?)" != "0" ]; then 
+      echo "    ... diffs when comparing ${DESTDIR} to ${ARCHDIR}, building"
+      NEEDSBUILD=1; 
+    fi
+
+    # do actions 
+    if [ "${NEEDSBUILD}" == "1" ] || [ "${DOFORCE}" == "1" ]; then
+
+      echo "    ... creating container '${CONTAINER}'"
+      docker build -f ${DESTDIR}/Dockerfile -t ${CONTAINER}:latest ${DESTDIR} || exit 1
+
+      echo "    ... archiving build of container '${CONTAINER}'"
+      mkdir -p ${ARCHDIR}
+      rsync -ai --delete ${DESTDIR}/ ${ARCHDIR} &> /dev/null
+
+      echo "    ... tag and push to repo"
+      docker tag ${CONTAINER} ${WOV_ARCHIVEREPOSITORY}/${CONTAINER}:${WOV_STAGE}_${WOV_PVER}
+
+      echo "    ... push container to: ${WOV_ARCHIVEREPOSITORY}/${CONTAINER}:${WOV_STAGE}_${WOV_PVER}"
+      docker push ${WOV_ARCHIVEREPOSITORY}/${CONTAINER}:${WOV_STAGE}_${WOV_PVER} 
+
+    else
+      echo "    ... skipping build of container '${CONTAINER}'"
+    fi
   fi
 
 
 done
+fi
 
 
diff --git a/bin/wov-stage b/bin/wov-stage
--- a/bin/wov-stage
+++ b/bin/wov-stage
@@ -11,7 +11,7 @@ FOLD=80
 wovstageargs=( "$@" )
 set ""
 . wov-env
-. wov-stagecompare
+. wov-ns-check
 set -- "${wovstageargs[@]}"
 
 
@@ -85,22 +85,22 @@ NEWSTAGE=$1
 # echo "NEWSTAGE: ${NEWSTAGE}"
 
 
-if [ ${DOECHO} -ge 2 ]; then echo "... checking for Kubernetes namespace '${WOV_AIM}-${NEWSTAGE}'."; fi
+if [ ${DOECHO} -ge 2 ]; then echo "... checking for Kubernetes namespace '${WOV_PROJECT}-${NEWSTAGE}'."; fi
 FAILURE=0
-ISNS=$(kubectl get namespaces --no-headers=true ${WOV_AIM}-${NEWSTAGE} &> /dev/null ; echo "$?")
+ISNS=$(kubectl get namespaces --no-headers=true ${WOV_PROJECT}-${NEWSTAGE} &> /dev/null ; echo "$?")
 # echo "ISNS: ${ISNS}"
 if [ "$ISNS" != "0" ]; then
-  echo "ERROR: failed to set stage to '${NEWSTAGE}' due to missing Kubernetes namespace '${WOV_AIM}-${NEWSTAGE}'."
+  echo "ERROR: failed to set stage to '${NEWSTAGE}' due to missing Kubernetes namespace '${WOV_PROJECT}-${NEWSTAGE}'."
   FAILURE=1
 else
   if [ ${DOECHO} -ge 2 ]; then echo "  ... success."; fi
 fi
 
-if [ ${DOECHO} -ge 2 ]; then echo "... checking for Kubernetes context '${WOV_CLUSTER}-${WOV_AIM}-${NEWSTAGE}'."; fi
-ISCONTEXT=$(kubectl config get-contexts --no-headers=true -o name | grep ${WOV_CLUSTER}-${WOV_AIM}-${NEWSTAGE})
+if [ ${DOECHO} -ge 2 ]; then echo "... checking for Kubernetes context '${WOV_CLUSTER}-${WOV_PROJECT}-${NEWSTAGE}'."; fi
+ISCONTEXT=$(kubectl config get-contexts --no-headers=true -o name | grep ${WOV_CLUSTER}-${WOV_PROJECT}-${NEWSTAGE})
 # echo "ISCONTEXT=${ISCONTEXT}"
-if [ "$ISCONTEXT" != "${WOV_CLUSTER}-${WOV_AIM}-${NEWSTAGE}" ]; then
-  echo "ERROR: failed to set stage to '${NEWSTAGE}' due to missing Kubernetes context '${WOV_CLUSTER}-${WOV_AIM}-${NEWSTAGE}'."
+if [ "$ISCONTEXT" != "${WOV_CLUSTER}-${WOV_PROJECT}-${NEWSTAGE}" ]; then
+  echo "ERROR: failed to set stage to '${NEWSTAGE}' due to missing Kubernetes context '${WOV_CLUSTER}-${WOV_PROJECT}-${NEWSTAGE}'."
   FAILURE=1
 else
   if [ ${DOECHO} -ge 2 ]; then echo "  ... success."; fi
@@ -119,10 +119,10 @@ fi
 # If no failure, switch stage
 if [ "$FAILURE" == "0" ]; then
 
-  if [ ${DOECHO} -ge 1 ]; then echo "... switching Kubernetes context to '${WOV_CLUSTER}-${WOV_AIM}-${NEWSTAGE}'."; fi
-  kubectl config use-context ${WOV_CLUSTER}-${WOV_AIM}-${NEWSTAGE}
+  if [ ${DOECHO} -ge 1 ]; then echo "... switching Kubernetes context to '${WOV_CLUSTER}-${WOV_PROJECT}-${NEWSTAGE}'."; fi
+  kubectl config use-context ${WOV_CLUSTER}-${WOV_PROJECT}-${NEWSTAGE}
   if [ "$?" != "0" ]; then
-    echo "ERROR: failed to switch to Kubernetes context '${WOV_CLUSTER}-${WOV_AIM}-${NEWSTAGE}'."
+    echo "ERROR: failed to switch to Kubernetes context '${WOV_CLUSTER}-${WOV_PROJECT}-${NEWSTAGE}'."
   else
     if [ ${DOECHO} -ge 2 ]; then echo "  ... success."; fi
   fi
@@ -138,5 +138,5 @@ if [ "$FAILURE" == "0" ]; then
   # Run this again in case this is included in a script
   set ""
   . wov-env
-  . wov-stagecompare
+  . wov-ns-check
 fi
