Checking in. Wov-env-build uses wov-env-loader but wov-env does not.

diff --git a/bin/wov-env b/bin/wov-env
--- a/bin/wov-env
+++ b/bin/wov-env
@@ -90,6 +90,34 @@ elif [ ! -e "${WOV_BASEDIR}/wovtools/config.json" ]; then
   exit 1
 fi
 
+# --------------------------------------------------------------------- 
+# Calls wov-env-build to build the secretfile if it does not exist.
+#  if $1 == force, force
+# --------------------------------------------------------------------- 
+function fBuildSecret
+{ 
+  if [ ! -f "${WOV_SECRETFILE}" ] || [ "$1" == "force" ]; then 
+    echo "buidling"
+    wov-env-build --secrets ${CLUSTER}; 
+  fi
+}
+
+# --------------------------------------------------------------------- 
+# Sets the cluster we are generating environment vars for. By default,
+# generates using settings in 'local', which is generated by 
+# wov-env-build using the 'localcontext' entry. So, 'local' points to
+# whatever cluster this project considers the localcontext.
+# NOTE: creates the directory, but not file since that would look like 
+#       it was current.
+# --------------------------------------------------------------------- 
+function doSetCluster
+{
+  CLUSTER=$1
+  local WOV_SECRETFILE_path=${WOV_BASEDIR}/wovtools/cache/clusters/${CLUSTER}
+  mkdir -m 700 -p ${WOV_SECRETFILE_path}
+  WOV_SECRETFILE=${WOV_SECRETFILE_path}/secrets.json
+  export WOV_SECRETFILE
+}
 
 # --------------------------------------------------------------------- 
 # Source files for project configuration : build if needed
@@ -98,6 +126,7 @@ export WOV_CACHEDIR="${WOV_BASEDIR}/wovtools/cache"
 export WOV_FILE_SECRETS_RAW="${WOV_BASEDIR}/wovtools/config.json"
 export WOV_FILE_SECRETSLOCAL_RAW="${WOV_BASEDIR}/wovtools/local.json"
 export WOV_FILE_SECRETSMERGED="${WOV_CACHEDIR}/.merged.json"
+doSetCluster "local"
 
 
 # ---------------------------------------------------------------------
@@ -105,8 +134,21 @@ export WOV_FILE_SECRETSMERGED="${WOV_CACHEDIR}/.merged.json"
 # files config.json and local.json together in SECRETSMERGED_RAW
 # if they have changed.
 # ---------------------------------------------------------------------
-mkdir -p ${WOV_CACHEDIR}
-chmod 700 ${WOV_CACHEDIR}
+mkdir -m 700 -p ${WOV_CACHEDIR}
+set -x
+# if [ ! -f ${WOV_SECRETFILE} ] || [ "${WOV_BASEDIR}/wovtools/secrets" -nt ${WOV_FILE_SECRETSMERGED} ]; then
+if [ "${WOV_BASEDIR}/wovtools/secrets" -nt ${WOV_FILE_SECRETSMERGED} ]; then
+  # make sure there is no loop since wov-env-build calls wov-env
+  touch ${WOV_FILE_SECRETSMERGED}
+
+  # build/rebuild files
+  fBuildSecret force 
+
+  # make sure we do the merge next
+  touch ${WOV_FILE_SECRETS_RAW}
+fi
+exit 1
+
 if [ ${WOV_FILE_SECRETS_RAW} -nt ${WOV_FILE_SECRETSMERGED} ] || [ ${WOV_FILE_SECRETSLOCAL_RAW} -nt ${WOV_FILE_SECRETSMERGED} ]; then
   echo "... merged file out of date, creating: ${WOV_FILE_SECRETSMERGED}"
   echo "" > ${WOV_FILE_SECRETSMERGED}
@@ -128,19 +170,6 @@ if [ ${WOV_FILE_SECRETS_RAW} -nt ${WOV_FILE_SECRETSMERGED} ] || [ ${WOV_FILE_SEC
 fi
 
 
-# --------------------------------------------------------------------- 
-# Sets the cluster we are generating environment vars for. By default,
-# generates using settings in 'local', which is generated by 
-# wov-env-build using the 'localcontext' entry. So, 'local' points to
-# whatever cluster this project considers the localcontext.
-# --------------------------------------------------------------------- 
-function doSetCluster
-{
-  CLUSTER=$1
-  WOV_SECRETFILE=${WOV_BASEDIR}/wovtools/cache/clusters/${CLUSTER}/secrets.json
-  export WOV_SECRETFILE
-}
-doSetCluster "local"
 
 
 # --------------------------------------------------------------------- 
@@ -200,33 +229,67 @@ function getClusterConfigPath()
   echo $RETVAL
 }
 
+function doK8sBadContext()
+{
+  # Kubernetes Context in ~/.kube/config
+  printf "\n***ERROR: bad WOV_CONTEXT of '${WOV_CONTEXT}'.\n\n"
 
-# --------------------------------------------------------------------- 
-# Calls wov-env-build to build the secretfile if it does not exist.
-# --------------------------------------------------------------------- 
-function fBuildSecret
-{ if [ ! -e "${WOV_SECRETFILE}" ]; then wov-env-build --secrets ${CLUSTER}; fi }
+  printf "...check kops clusters\n"
+  if [ -z ${KOPS_STATE_STORE+x} ]; then 
+    echo "WARNING: KOPS_STATE_STORE is unset... skipping cluster listing."
+    echo "  - ex. export KOPS_STAGE_STORE='s3://kops.woveon.com'"
+  else
+    kops get clusters
+  fi
+
+  OLDIFS=$IFS
+  IFS='.'
+  local carray=( $WOV_FLAVOR )
+  IFS=$OLDIFS
+  WOVCONTEXTMAYBE="${WOV_CLTYPE}-${WOV_PROVIDER}-${WOV_REGION}-${carray[0]}"
+  if [ "${#carray[@]}" != "1" ]; then
+    echo "WARNING: WOV_FLAVOR of '${WOV_FLAVOR}' may be from the default kops. You probably need to create a WovTools context of '${WOVCONTEXTMAYBE}'."
+  fi
+
+  printf "...checking kubernetes context (cluster/user/namespace)\n"
+
+  kubectl config get-clusters | \grep -- ${WOV_CLUSTER} > /dev/null
+  if [ "$?" != "0" ]; then echo "  ... no cluster ${WOV_CLUSTER}"; else echo "  ... found cluster ${WOV_CLUSTER}."; fi
+
+  kubectl config view | yaml json write - | jq -r '.users[].name' | \grep -- ${WOV_CONTEXT} > /dev/null 2>&1
+  if [ "$?" != "0" ]; then 
+    echo "  ... no user ${WOV_CONTEXT}"
+  else
+    echo "  ... found user ${WOV_CONTEXT}"
+  fi
+
+  kubectl get ns "${WOV_WPROJECT}-${WOV_GSTAGE}" > /dev/null 2>&1
+  if [ "$?" != "0" ]; then 
+    printf "  ... no kubernetes namespace '${WOV_WPROJECT}-${WOV_GSTAGE}'.\n"
+    printf "    - create with: 'kubectl create namespace ${WOV_WPROJECT}-${WOV_GSTAGE}'.\n"
+  else
+    printf "  ... found kubernetes namespace '${WOV_WPROJECT}-${WOV_GSTAGE}'.\n"
+  fi
+
+  kubectl config get-contexts ${WOV_CLUSTER}-${WOV_WPROJECT}-${WOV_GSTAGE} 1> /dev/null 2>&1
+  if [ "$?" == "0" ]; then 
+    echo "  ... found context ${WOV_CLUSTER}-${WOV_WPROJECT}-${WOV_GSTAGE}"
+  else
+    echo "  ... no context ${WOV_CLUSTER}-${WOV_WPROJECT}-${WOV_GSTAGE}"
+    kubectl config get-contexts ${WOVCONTEXTMAYBE} 1> /dev/null 2>&1
+    if [ "$?" == "0" ]; then
+      echo "  ... Oh hey, context '${WOVCONTEXTMAYBE}' exists... try 'kubectl config use-context ${WOVCONTEXTMAYBE}'?"
+    fi
+  fi
 
 
-# vars from Kubernetes
-# --------------------------------------------------------------------- 
-if [ "$GLOBALCOMMAND" != "" ]; then 
-  export WOV_CONTEXT=$GLOBALCOMMAND; 
-else
-  export WOV_CONTEXT="$(kubectl config current-context)"
-fi
-OLDIFS=$IFS
-IFS='-'
-array=( $WOV_CONTEXT )
-IFS=$OLDIFS
-export WOV_KSTAGE="${array[5]}"
-export WOV_KPROJECT="${array[4]}"
-export WOV_NS="${WOV_KPROJECT}-${WOV_KSTAGE}"
-export WOV_FLAVOR="${array[3]}"
-export WOV_REGION="${array[2]}"
-export WOV_PROVIDER="${array[1]}"
-export WOV_CLTYPE="${array[0]}"
-export WOV_CLUSTER="${WOV_CLTYPE}-${WOV_PROVIDER}-${WOV_REGION}-${WOV_FLAVOR}"
+  exit 1
+}
+
+
+
+
+
 
 
 # vars from git, if in project directory
@@ -254,7 +317,6 @@ ALLVARS=()
 while read f; do
   ALLVARS+=( "$f" )
 done <<<$(cat ${WOV_FILE_SECRETSMERGED} | jq -r ". | ( .ver, .project.project, .project.type, .project.title, .project.description, .archive.repository, .archive.env  )" )
-
 WOV_PVERSION=${ALLVARS[0]}
 if [ "${WOV_PVERSION}" != "${WOV_VERSION}" ] && [ "${WOV_PVERSION}" != "initing" ] ; then
   printf "\n\nERROR: Your project version '${WOV_PVERSION}', does not match to the WovTools version '${WOV_VERSION}'.\n\n"
@@ -266,6 +328,39 @@ export WOV_PROJECTTITLE="${ALLVARS[3]}"
 export WOV_PROJECTDESCRIPTION="${ALLVARS[4]}"
 export WOV_ARCHIVEREPOSITORY="${ALLVARS[5]}"
 export WOV_ARCHIVEENV="${ALLVARS[6]}"
+
+# vars from kops
+# --------------------------------------------------------------------- 
+if [ -z ${KOPS_STATE_STORE+x} ]; then 
+  echo "ERROR: KOPS_STATE_STORE is unset. ex. export KOPS_STATE_STORE='s3://kops.woveon.com'"
+  exit 1
+fi
+
+
+# vars from Kubernetes
+# --------------------------------------------------------------------- 
+if [ "$GLOBALCOMMAND" != "" ]; then 
+  export WOV_CONTEXT=$GLOBALCOMMAND; 
+else
+  export WOV_CONTEXT="$(kubectl config current-context)"
+fi
+OLDIFS=$IFS
+IFS='-'
+array=( $WOV_CONTEXT )
+IFS=$OLDIFS
+export WOV_KSTAGE="${array[5]}"
+export WOV_KPROJECT="${array[4]}"
+export WOV_NS="${WOV_KPROJECT}-${WOV_KSTAGE}"
+export WOV_FLAVOR="${array[3]}"
+export WOV_REGION="${array[2]}"
+export WOV_PROVIDER="${array[1]}"
+export WOV_CLTYPE="${array[0]}"
+export WOV_CLUSTER="${WOV_CLTYPE}-${WOV_PROVIDER}-${WOV_REGION}-${WOV_FLAVOR}"
+if [ "${#array[@]}" != "6" ]; then
+  doK8sBadContext; 
+fi
+
+
 
 # Unifying
 # --------------------------------------------------------------------- 
