Too many changes. Need to completely change how WovTools handles configuration mods for local and clusters/stages.
See github issue:31 - https://github.com/woveon/wovtools/issues/31

Basically, these are longstanding issues all tied together, and
I finally have a plan. This came to a head since I can't push until I
fix this.

So, here is a full checkin that hasn't been done in a while, with a lot
of junk, so that I can checkpoint this code as I move forward.

...wish me luck.

diff --git a/bin/wov-cmd b/bin/wov-cmd
--- a/bin/wov-cmd
+++ b/bin/wov-cmd
@@ -2,17 +2,24 @@
 
 DOECHO=1
 FOLD=80
+DIDLIST=0
 
-
-# --------------------------------------------------------------------- 
-# Import Env 
-# --------------------------------------------------------------------- 
 cmdargs=( "$@" )
 set ""
 . wov-build -e
 . wov-env
 . wov-ns-check
 set -- "${cmdargs[@]}"
+CMDDIR=${WOV_BASEDIR}/wovtools/cmds
+
+
+# ---------------------------------------------------------------------
+# ---------------------------------------------------------------------
+function doList() 
+{
+  ls ${CMDDIR}
+  DIDLIST=1
+}
 
 # check that stages align, but project does not need to for commands,
 # as this allows running commands in another project withouth changing K8s namespace
@@ -21,6 +28,7 @@ set -- "${cmdargs[@]}"
 #  printf "\n\nERROR: stages do not match.\n\n"
 #  exit 1
 #fi
+
 
 
 # --------------------------------------------------------------------- 
@@ -32,15 +40,15 @@ function fDisplayOptions()
 
 usage: `basename $0` [options]
 
-Runs a command found in the cmds directory. These commands have access to wov-env variables.
+Runs a command found in the cmds directory. 
+
+These commands have access to wov-env variables.
 
   -v|-q : verbose/quiet output
   -h    : this help text
 
 EOF
 }
-
-
 
 # ---------------------------------------------------------------------
 # Handle Params
@@ -56,6 +64,10 @@ while [[ $1 =~ ^- ]]; do
     shift
     DOECHO=2
 
+  elif [ "$1" == "-l" ]; then
+    shift
+    doList
+
   elif [ "$1" == "-h" ] || [ "$1" == "--help" ]; then
     fDisplayOptions
     exit 0
@@ -69,15 +81,23 @@ while [[ $1 =~ ^- ]]; do
   fi
 done
 
-CMDFILE=${WOV_BASEDIR}/wovtools/cmds/$1
 
-if [ ! -e  ${CMDFILE} ]; then
-  printf "\n\nERROR: no cmd named '$1'.\n" 2>&1
-  exit 1
-elif [ ! -x ${CMDFILE} ]; then
-  printf "\n\nERROR: cmd '$1' not executable (run 'chmod 775 wovtools/cmds/$1').\n" 2>&1
-  exit 1
-else
-  shift
-  ${CMDFILE} $*
+
+
+if [ "$DIDLIST" == "0" ]; then
+
+  CMDFILE=${CMDDIR}/$1
+
+  if [ ! -e  ${CMDFILE} ]; then
+    printf "\n\nERROR: no cmd named '$1'.\n" 2>&1
+    exit 1
+  elif [ ! -x ${CMDFILE} ]; then
+    printf "\n\nERROR: cmd '$1' not executable (run 'chmod 775 ${CMDFILE}').\n" 2>&1
+    exit 1
+  else
+    shift
+    ${CMDFILE} $*
+  fi
+
 fi
+
diff --git a/bin/wov-deploy b/bin/wov-deploy
--- a/bin/wov-deploy
+++ b/bin/wov-deploy
@@ -58,9 +58,10 @@ function doDeployConf()
 {
   RECIPES=( "$@" )
   if [ "${#RECIPES[@]}" == "0" ]; then
-    RECIPES=$(cd ${WOV_BASEDIR}/wovtools/containers && find * -maxdepth 0 -type f 2> /dev/null)
+    RECIPES=( $(cd ${WOV_BASEDIR}/wovtools/containers && find * -maxdepth 0 -type f 2> /dev/null) )
+    RECIPES+=( "" )
   fi
-#  echo "RECIPES: ${RECIPES[@]}"
+  echo "RECIPES: ${RECIPES[@]}"
 
   # Files for Configmap file
   CMDIR=${WOV_BASEDIR}/wovtools/cache/conf/cm
@@ -77,10 +78,16 @@ function doDeployConf()
 
   # Read files from directory (note the appended FILEEXT)
   #CMFILES=( $(cd ${CMDIR} && ls 2> /dev/null) )
-  for f in ${RECIPES}; do
+  for f in "${RECIPES[@]}"; do
 
     local MSROOT=${WOV_PROJECT}${f}${FILEEXT}
     local CMFILE="${CMDIR}/${MSROOT}"          # full path to file
+
+    # delete existing configmap
+    kubectl delete configmap ${MSROOT} 2> /dev/null
+
+    # if no configmap file, continue on
+    if [ ! -e "${CMFILE}" ]; then continue; fi
 
     # Convert X=Y into ConfigMap commands in DATA
     DATA=()
@@ -91,7 +98,6 @@ function doDeployConf()
     done <${CMFILE}
 
     #echo "DATA: ${DATA[@]}"
-    kubectl delete configmap ${MSROOT} 2> /dev/null
     kubectl create configmap ${MSROOT} "${DATA[@]}"
     if [ "$?" != "0" ]; then
       printf "\nERROR: failed creating ConfigMap $f from '${CMFILE}'.\n"
@@ -105,10 +111,16 @@ function doDeployConf()
 
   # Read files from directory (note the appended FILEEXT)
   #SEFILES=( $(cd ${SEDIR} && ls 2> /dev/null) )
-  for f in ${RECIPES}; do
+  for f in "${RECIPES[@]}"; do
 
     local MSROOT=${WOV_PROJECT}${f}${FILEEXT}
     local SEFILE="${SEDIR}/${MSROOT}"          # full path to file
+
+    # delete existing secret
+    kubectl delete secret ${MSROOT} 2> /dev/null
+
+    # if no secret file, continue on
+    if [ ! -e "${SEFILE}" ]; then continue; fi
 
     # Convert X=Y into Secret commands in DATA
     DATA=()
@@ -118,7 +130,6 @@ function doDeployConf()
       if [ "$d" != "" ]; then DATA+=("$d"); fi
     done <${SEFILE}
 
-    kubectl delete secret ${MSROOT} 2> /dev/null
     kubectl create secret generic ${MSROOT} "${DATA[@]}"
     if [ "$?" != "0" ]; then
       printf "\nERROR: failed creating Secret $MSROOT from '${SEFILE}'.\n"
@@ -291,7 +302,7 @@ function doDeployDev()
   {
     wov-mod -q --off ALL
     if [ "$?" != "0" ]; then exit 1; fi
-    wov-build-conf -q --skip-push $*
+    wov-build-conf -q --skip-push --nogitchecks $*
     if [ "$?" != "0" ]; then exit 1; fi
   }
 
@@ -302,8 +313,51 @@ function doDeployDev()
     if [ "$?" != "0" ]; then
       echo "ERROR: no entry for vh. set that up in wovtools/config.json."
     fi
-    wov-build-conf -q --skip-push --allow-stagemods --conf-ext vh $*
+
+    # create the blank compoound files ( ex. {WOV_PROJECT}vh )
+    VHcmFILE="${WOV_BASEDIR}/wovtools/cache/conf/cm/${WOV_PROJECT}vh"
+    echo -n "" > ${VHcmFILE}
+    chmod 600 ${VHcmFILE}
+    VHseFILE="${WOV_BASEDIR}/wovtools/cache/conf/se/${WOV_PROJECT}vh"
+    echo -n "" > ${VHseFILE}
+    chmod 600 ${VHseFILE}
+
+    # create individual files (or maybe just one compound)
+    wov-build-conf -q --skip-push --allow-stagemods --nogitchecks --conf-ext "vh" $*
     if [ "$?" != "0" ]; then exit 1; fi
+
+    # merge all cm files into one, so can be loaded as one file in vh
+    VHcmFILES=$(cd ${WOV_BASEDIR}/wovtools/cache/conf/cm ; find * -maxdepth 0 -type f | \grep 'vh$')
+    for f in ${VHcmFILES}; do
+      if [ "$f" == "${WOV_PROJECT}vh" ]; then continue; fi   # skip compound file
+      echo "  ... append file ${f} into ${VHcmFILE}"
+      cat ${WOV_BASEDIR}/wovtools/cache/conf/cm/${f} >> ${VHcmFILE}
+    done
+
+    # sort and uniq the file to remove duplicates
+    rm ${VHcmFILE}.1 >& /dev/null || true
+    touch ${VHcmFILE}.1
+    chmod 600 ${VHcmFILE}.1
+    sort ${VHcmFILE} | uniq >> ${VHcmFILE}.1
+    rm ${VHcmFILE}
+    mv ${VHcmFILE}.1 ${VHcmFILE}
+
+    # merge all those into one, so can be loaded as one file in vh
+    VHseFILES=$(cd ${WOV_BASEDIR}/wovtools/cache/conf/se ; find * -maxdepth 0 -type f | \grep 'vh$')
+    for f in ${VHseFILES}; do
+      if [ "$f" == "${WOV_PROJECT}vh" ]; then continue; fi   # skip compound file
+      echo "  ... append file ${f} into ${VHseFILE}"
+      cat ${WOV_BASEDIR}/wovtools/cache/conf/se/${f} >> ${VHseFILE}
+    done
+
+    # sort and uniq the file to remove duplicates
+    rm ${VHseFILE}.1 >& /dev/null || true
+    touch ${VHseFILE}.1
+    chmod 600 ${VHseFILE}.1
+    sort ${VHseFILE} | uniq >> ${VHseFILE}.1
+    rm ${VHseFILE}
+    mv ${VHseFILE}.1 ${VHseFILE}
+
   fi
 
   # Return wov-mod status
@@ -333,9 +387,64 @@ function doDeployDev()
     # doCleanUp // no cleanup in devdeploy
   fi
 
+  doPatchDeployments $*
+
   doCheckContainersExist $*
 }
 
+function join_by { local IFS="$1"; shift; echo "$*"; }
+
+# Patch deployemnts to point to STAGE_dev. each deployment overwrites this, so call each time to keep
+function doPatchDeployments()
+{
+  if [ ${WOV_STAGE} == 'prod' ]; then
+    printf "\n\n\nERROR: patching straight into production is not allowed. Do a 'wov-push' and then a 'wov-deploy --stage'.\n\n"
+    exit 1
+  fi
+
+  local DEPS=( "$@" )
+  if [ "${#DEPS[@]}" == "0" ]; then
+    DEPS=( $(cd ${WOV_BASEDIR}/wovtools/containers && find * -maxdepth 0 -type f 2> /dev/null) )
+    # DEPS+=( "" )
+  fi
+  #local DEPS=( `kubectl get --no-headers=true deployments | awk '{print $1}'` )
+  echo "DEPS: '${DEPS[*]}'"
+
+  # for each Deployment, patch it
+  for c in "${DEPS[@]}"; do
+
+    local d="${WOV_PROJECT}${c}"
+
+    echo "Deployment: $d, container: $c"
+
+    # get container and remove trailing tag
+    cntr=`kubectl get deployment $d -o json | jq -r '.spec.template.spec.containers[0].image'`
+    cntr_bits=(${cntr//:/ })
+    #echo "${cntr_bits[@]}"
+    unset 'cntr_bits[${#cntr_bits[@]}-1]'
+    #echo "${cntr_bits[@]}"
+    cntr1=`join_by : ${cntr_bits}`
+    #echo "  cntr1: ${cntr1}"
+    cntr2="${cntr1}:${WOV_STAGE}_dev"
+    #echo "  cntr2: ${cntr2}"
+
+    # patch for ${STAGE}_dev containers for deployment
+    local patchport="{ \"spec\" : { \"template\" : { \"spec\" : { \"containers\" : [{ \"name\" : \"$d\", \"image\" : \"${cntr2}\"}]}}}}"
+    #printf "    ${patchport}\n"
+    kubectl patch deployment $d -p "$patchport"
+    A=$?
+    if [[ $A == 0 ]]; then
+      printf "  ... patch success\n"
+      RETVAL=0
+    elif [[ $A == 1 ]]; then
+      printf "  ... not patched\n"
+      RETVAL=0
+    else
+      printf "  ... patch failed (error code $A)\n"
+      RETVAL=1
+  fi
+  done
+}
 
 # ---------------------------------------------------------------------
 # Proper roll to stage call
@@ -478,6 +587,11 @@ while [[ $1 =~ ^- ]]; do
     WOV_SVER="$1"
     shift
 
+  elif [ "$1" == "-p" ] || [ "$1" == "--patch" ]; then
+    shift
+    DEPLOYTYPE=patch
+    #doPatchDeployments
+
   elif [ "$1" == "-h" ] || [ "$1" == "--help" ]; then
     fDisplayOptions
     exit 0
@@ -500,15 +614,18 @@ fi
 if [ "${DEPLOYTYPE}" == "" ]; then
   echo ""
   echo "***ERROR deploy needs to specify incremental or full"
-  echo "  --dev   : just deploy current dev environment (non-production)"
-  echo "  --stage : deploy versioned system"
+  echo "  --dev   [...] : just deploy current dev environment (non-production)"
+  echo "  --stage [...] :  deploy versioned system"
+  echo "  --patch [...] : patch deployments to point to the STAGE_dev container (--dev does for its own deployments)"
   echo ""
 
 elif [ "${DEPLOYTYPE}" == "dev" ]; then
   doDeployDev $*
 
+elif [ "${DEPLOYTYPE}" == "patch" ]; then
+  doPatchDeployments $*
+
 elif [ "${DEPLOYTYPE}" == "stage" ]; then
   doDeployStage $*
-
 fi
 
diff --git a/bin/wov-env b/bin/wov-env
--- a/bin/wov-env
+++ b/bin/wov-env
@@ -299,6 +299,10 @@ function doPrintVarsENVS()
   cat ${WOV_SECRETFILE} |
     jq  -r 'walk( if type == "object" then with_entries(select( .key | test("STAGE.+") or test("//*") | not)) else . end) | [leaf_paths as $path | {"key": $path | join("_"), "value": getpath($path)}] | from_entries | keys[] as $k | "WOV_\($k)=" + @sh "\(.[$k])" '
 
+  if [ "${CL_REGION}" != "" ]; then echo "CL_REGION='${CL_REGION}'"; fi
+  if [ "${CL_ZONES}"  != "" ]; then echo "CL_ZONES='${CL_ZONES}'"; fi
+  if [ "${CL_VPC}"    != "" ]; then echo "CL_VPC='${CL_VPC}'"; fi
+
   HAS_BUILDENV=1
 }
 
@@ -313,6 +317,10 @@ function doPrintVarsEXPORTS()
 
   cat ${WOV_SECRETFILE} |
     jq  -r 'walk( if type == "object" then with_entries(select( .key | test("STAGE.+") or test("//*") | not)) else . end) | [leaf_paths as $path | {"key": $path | join("_"), "value": getpath($path)}] | from_entries | keys[] as $k | "export WOV_\($k)=" + @sh "\(.[$k])" '
+
+  if [ "${CL_REGION}" != "" ]; then echo "export CL_REGION='${CL_REGION}'"; fi
+  if [ "${CL_ZONES}"  != "" ]; then echo "export CL_ZONES='${CL_ZONES}'"; fi
+  if [ "${CL_VPC}"    != "" ]; then echo "export CL_VPC='${CL_VPC}'"; fi
 
   HAS_BUILDENV=1
 }
@@ -335,6 +343,8 @@ function doPrintVarsEXPORTS()
 #    doEnv $c
 #  done
 #}
+
+#NOTE: never called
 function doLoadExports()
 {
   CONFS=( $(cd ${WOV_BASEDIR}/wovtools/cache/conf/ && ls *.ck8s *.sk8s 2> /dev/null) )
@@ -430,27 +440,44 @@ function fConfGeneration()
 {
 
   local R=
+
   # Read in envs
   if [ "${HAS_BUILDENV}" != "1" ]; then . <(doPrintVarsEXPORTS); fi
 
   # Get echo env vars, checking multiple locations
   if [ -e "${WOV_BASEDIR}/${1}/src/${1}config.js" ]; then
     local MSCFILE="${WOV_BASEDIR}/${1}/src/${1}config.js"
-    if [ "$2" == "cm" ]; then   R=( $(node -e "console.log((new (require('${MSCFILE}'))())._genK8SConfigMap())") ) ; 
-    elif [ "$2" == "se" ]; then R=( $(node -e "console.log((new (require('${MSCFILE}'))())._genK8SSecrets())") ) ; fi
+    if [ "$2" == "cm" ]; then 
+      R=( $(node -e "console.log((new (require('${MSCFILE}'))())._genK8SConfigMap())") ) 
+      RR=$?
+    elif [ "$2" == "se" ]; then
+      R=( $(node -e "console.log((new (require('${MSCFILE}'))())._genK8SSecrets())") )
+      RR=$?
+    fi
+    if [ "${RR}" != "0" ]; then echo "ERROR: failed to generate '${1}' config from NodeJS source code."; exit 1 ; fi
 
   elif [ -e "${WOV_BASEDIR}/src/${1}config.js" ]; then
     local MSCFILE="${WOV_BASEDIR}/src/${1}config.js"
-    if [ "$2" == "cm" ]; then   R=( $(node -e "console.log((new (require('${MSCFILE}'))())._genK8SConfigMap())") ) ; 
-    elif [ "$2" == "se" ]; then R=( $(node -e "console.log((new (require('${MSCFILE}'))())._genK8SSecrets())") ) ; fi
+    if [ "$2" == "cm" ]; then
+      R=( $(node -e "console.log((new (require('${MSCFILE}'))())._genK8SConfigMap())") ) 
+      RR=$?
+    elif [ "$2" == "se" ]; then 
+      R=( $(node -e "console.log((new (require('${MSCFILE}'))())._genK8SSecrets())") ) 
+      RR=$?
+    fi
+    if [ "${RR}" != "0" ]; then echo "ERROR: failed to generate '${1}' config from NodeJS source code."; exit 1 ; fi
 
   elif [ -e "${WOV_BASEDIR}/${1}/src/${1}config.sh" ]; then
     local MSCFILE="${WOV_BASEDIR}/${1}/src/${1}config.sh"
     R=( $(${MSCFILE} $2) )
+    RR=$?
+    if [ "${RR}" != "0" ]; then echo "ERROR: failed to generate '${1}' config from NodeJS source code."; exit 1 ; fi
 
   elif [ -e "${WOV_BASEDIR}/src/${1}config.sh" ]; then
     local MSCFILE="${WOV_BASEDIR}/src/${1}config.sh"
     R=( $(${MSCFILE} $2) )
+    RR=$?
+    if [ "${RR}" != "0" ]; then echo "ERROR: failed to generate '${1}' config from NodeJS source code."; exit 1 ; fi
 
   else
     (>&2 printf "\nERROR: could not find '${1}config.js'. Should be in ./src or ./${1}/src.\n\n")
diff --git a/bin/wov-mod b/bin/wov-mod
--- a/bin/wov-mod
+++ b/bin/wov-mod
@@ -187,6 +187,23 @@ function doGetOnMods()
 }
 
 
+# ---------------------------------------------------------------------
+# ---------------------------------------------------------------------
+function doTestMod()
+{
+  RET="0"
+  R=`jq -r '(.stagemods[] | select(.status == "on") | select(.name == "'"$1"'" ) | .name )' ${WOV_BASEDIR}/wovtools/config.json `
+  RR=$?
+  if [ "$RR" != "0" ]; then
+    printf "\n\nERROR: failed testing '$1'.\n\n"
+    exit 1
+  fi
+  if [ "$R" != "" ]; then
+    RET="1"
+  fi
+  echo $RET
+}
+
 
 # ---------------------------------------------------------------------
 # Handle Params
@@ -217,6 +234,18 @@ while [[ $1 =~ ^- ]]; do
   elif [ "$1" == "--get-on" ]; then
     shift
     doGetOnMods
+    shift
+
+  elif [ "$1" == "--test" ] || [ "$1" == "-t" ]; then
+    shift
+    R=`doTestMod $1`
+    echo $R
+    shift
+
+  elif [ "$1" == "--test-throw" ] || [ "$1" == "-tt" ]; then
+    shift
+    R=`doTestMod $1`
+    if [ "$R" == "0" ]; then exit 1; fi
     shift
 
   elif [ "$1" == "-l" ]; then
diff --git a/bin/wov-vh b/bin/wov-vh
--- a/bin/wov-vh
+++ b/bin/wov-vh
@@ -62,16 +62,31 @@ function doStart()
   DIDCOMMAND=1
   CL_ZONES_ARRAY=($CL_ZONES)
 
-  echo "  ... ensuring a volume in AWS: 'vh-vol-${WOV_PROJECT}-${WOV_STAGE}'"
+  local VOLNAME="vh-vol-${WOV_PROJECT}-${WOV_STAGE}"
+  echo "  ... ensuring a volume in AWS: '${VOLNAME}'"
+  volid=`wov-aws volume-ensure "${VOLNAME}" 20`
+#  volid=`aws ec2 describe-volumes --filter Name="tag:Name",Values=\"vh-vol-${WOV_PROJECT}-${WOV_STAGE}\" | jq '.Volumes[0].VolumeId' -r`
+#  if [ "$volid" == "null" ]; then
+#    volid=`aws ec2 create-volume --size 20 --region ${CL_REGION} --availability-zone ${CL_REGION}${CL_ZONES_ARRAY[0]} --volume-type gp2 \
+#      --tag-specifications "ResourceType=volume,Tags=[{Key=Name,Value=vh-vol-${WOV_PROJECT}-${WOV_STAGE}}]" | jq ".VolumeId" -r`
+#  fi
+#
+  echo "  ... Volume: ${VOLNAME}, VolumeId: $volid"
 
-  volid=`aws ec2 describe-volumes --filter Name="tag:Name",Values=\"vh-vol-${WOV_PROJECT}-${WOV_STAGE}\" | jq '.Volumes[0].VolumeId' -r`
-
-  if [ "$volid" == "null" ]; then
-    volid=`aws ec2 create-volume --size 20 --region ${CL_REGION} --availability-zone ${CL_REGION}${CL_ZONES_ARRAY[0]} --volume-type gp2 \
-      --tag-specifications "ResourceType=volume,Tags=[{Key=Name,Value=vh-vol-${WOV_PROJECT}-${WOV_STAGE}}]" | jq ".VolumeId" -r`
+  echo "  ... ensure Configmap and Secrets in AWS: '${WOV_PROJECT}vh'"
+  kubectl get cm      ${WOV_PROJECT}vh &> /dev/null
+  CHECKCM=$?
+  kubectl get secrets ${WOV_PROJECT}vh &> /dev/null
+  CHECKSE=$?
+  if [ "${CHECKCM}" != "0" ]; then echo "FAILED: no Configmap of ${WOV_PROJECT}vh."; fi
+  if [ "${CHECKSE}" != "0" ]; then echo "FAILED: no Secret    of ${WOV_PROJECT}vh."; fi
+  if [ "${CHECKCM}" != "0" ] || [ "${CHECKCM}" != "0" ]; then
+    echo
+    echo "run 'wov-deploy --dev --conf-only' to generate these"
+    echo 
+    exit 1
   fi
 
-  echo "  ... Volume: vh-vol-${WOV_PROJECT}-${WOV_STAGE}, VolumeId: $volid"
 
   # Wait a sec to make sure it is ready
   sleep 1
@@ -204,6 +219,23 @@ function doConfigVol() {
   printf -v CV "%s  - name: secret-volume\n" "$CV"
   printf -v CV "%s    secret:\n" "$CV"
   printf -v CV "%s      secretName: ${WOV_PROJECT}vh\n" "$CV"
+
+#  local RECIPES=$(cd ${WOV_BASEDIR}/wovtools/containers && find * -maxdepth 0 -type f 2> /dev/null)
+#
+#  # add all generated ConfigMap (via wov-build-conf)
+#  for f in ${RECIPES}; do
+#    printf -v CV   "  - name: configmap-volume\n"
+#    printf -v CV "%s    configMap:\n" "$CV"
+#    printf -v CV "%s      name: ${WOV_PROJECT}${f}\n" "$CV"
+#  done
+#
+#  # add all generated Secrets (via wov-build-conf)
+#  for f in ${RECIPES}; do
+#    printf -v CV "%s  - name: secret-volume\n" "$CV"
+#    printf -v CV "%s    secret:\n" "$CV"
+#    printf -v CV "%s      secretName: ${WOV_PROJECT}${f}\n" "$CV"
+#  done
+
   printf "$CV"
 }
 
