Enabled 'MS' value in k8s files, for microservice. ex. wovtools/k8s/myms-service.yaml.wov will be passed 'myms' as MS, so it can have '  name : {{MS}}' -> name: myms.
- wov-compile and wov-hbs now have a -d switch to directly pass JSON.
- wov-env-build
  - pulls the microservice name when it compiles k8s files.
  - builds WOV_DATABASE_hostres for each database

- wov-push
  - created a --check option
  - now does a wov-push-k8s --check before actual pushes... so it fails early

diff --git a/bin/wov-push b/bin/wov-push
--- a/bin/wov-push
+++ b/bin/wov-push
@@ -113,6 +113,12 @@ else
   echo "  ... WARNING: skipping check for database changes that could block the push"
 fi
 
+echo "  ... wov-push-k8s check"
+wov-push-k8s --check ${METAARGS}
+if [ "$?" != "0" ]; then
+  echo "   ... wov-push-k8s check failed"
+  exit 1
+fi
 
 echo "  ... wov-push-container ${METAARGS}"
 wov-push-container ${METAARGS}
