Multiple changes to make this operational.
wov-ed allows for editing of multiple types of files now.

wov-env had some improvements to its output.

Others are minor updates.

diff --git a/bin/wov-ed b/bin/wov-ed
--- a/bin/wov-ed
+++ b/bin/wov-ed
@@ -6,6 +6,7 @@ FOLD=80
 HAS_SECRET=0
 HAS_BUILDENV=0
 SECRETDIFF=1
+DONEW=0
 EDPATH=''
 
 
@@ -27,15 +28,17 @@ function fDisplayOptions()
   cat <<EOF | fold -w ${FOLD} -s
 
 
-usage: `basename $0` [options] resource ...
+usage: `basename $0` [options] resource/file 
 
-Opens an editor to view the compiled resources.
+Opens an editor to edit the project's WovTools src or compiled resource file. Exact path not required.
+NOTE: this will test for '.wov' extension if needed.
 
-  secrets
-  conf X  : 
+  ex. `basename $0` -s conf/a.ck8s
+      `basename $0` -c secrets/current.json
 
+  -n : new, creates the file
   -s : edit the src file
-  -o : edit the output file
+  -c : edit the cached file
   -h : this help
 
 EOF
@@ -55,11 +58,15 @@ while [[ $1 =~ ^- ]]; do
     shift
     DOECHO=2
 
+  elif [ "$1" == "-n" ]; then
+    shift
+    DONEW=1
+
   elif [ "$1" == "-s" ]; then
     shift
     EDPATH=''
 
-  elif [ "$1" == "-o" ]; then
+  elif [ "$1" == "-c" ]; then
     shift
     EDPATH='cache/'
 
@@ -76,33 +83,28 @@ while [[ $1 =~ ^- ]]; do
   fi
 done
 
-if [ "$1" == "secrets" ]; then
+
+if [ "${EDITOR}" == "" ]; then
+  printf "\nERROR: environment variable EDITOR not defined.\n"
+  exit 1
+fi
+
+
+if [[ $1 == conf/* ]]     || [[ $1 == k8s/* ]]  || [[ $1 == containers/* ]] || 
+   [[ $1 == services/* ]] || [[ $1 == cmds/* ]] || [[ $1 == secrets/* ]]; then
+  
   if [ "$#" != "1" ]; then
     printf "\nERROR: bad number of arguments for 'secrets'.\n"
     fDisplayOptions
     exit 1
   fi
-  $EDITOR ${WOV_BASEDIR}/wovtools/${EDPATH}secrets/current.json
-elif [ "$1" == "conf" ]; then
 
-  # list
-  if [ "$#" == "1" ]; then
-    ls ${WOV_BASEDIR}/wovtools/${EDPATH}conf
-    exit 0
-  fi
-
-  if [ "$#" != "2" ]; then
-    printf "\nERROR: bad number of arguments for 'conf'.\n"
-    fDisplayOptions
-    exit 1
-  fi
-
-  P=${WOV_BASEDIR}/wovtools/${EDPATH}conf/$2
-  if [ ! -e ${P} ]; then
-    P=${WOV_BASEDIR}/wovtools/${EDPATH}conf/$2.wov
+  P=${WOV_BASEDIR}/wovtools/${EDPATH}$1
+  if [ ! -e ${P} ] && [ "${DONEW}" == "0" ]; then
+    P=${WOV_BASEDIR}/wovtools/${EDPATH}$1.wov
     if [ ! -e ${P} ]; then
-      printf "\nERROR: no conf file of '${2}'.\n"
-      ls ${WOV_BASEDIR}/wovtools/${EDPATH}conf
+      printf "\nERROR: no WovTools file '${1}'. Use '-n' to create a new file of that name.\n\n"
+      ls ${WOV_BASEDIR}/wovtools/${EDPATH}$(dirname ${1})
       exit 1
     fi
   fi
diff --git a/bin/wov-env b/bin/wov-env
--- a/bin/wov-env
+++ b/bin/wov-env
@@ -28,7 +28,9 @@ usage: `basename $0` [options]
   -h/--help    : display these options
   -v/--version : version of wovtools
   --env X      : echo the environment variables in file X in wovtools/cache/conf/X (NOTE: removes comments)
-  --cmd X      : on one line, echo the environment variables in file X in wovtools/cache/conf/X (NOTE: removes comments)
+  --cmd X      : for commands on one line, echo the environment variables in file X in wovtools/cache/conf/X (NOTE: removes comments)
+  --qcmd X     :   ", quoted
+  --sl X       :   ", string literal output
 
 Example Usage:
   `basename $0`    : sets all environment variables
@@ -61,6 +63,7 @@ WOV_REGION=${array[2]}
 WOV_PROVIDER=${array[1]}
 WOV_CLTYPE=${array[0]}
 WOV_CLUSTER=${WOV_CLTYPE}-${WOV_PROVIDER}-${WOV_REGION}-${WOV_FLAVOR}
+WOV_DEVMODE=
 
 #set -x 
 # vars from git, if in project directory
@@ -82,6 +85,12 @@ if [ -e "${WOV_BASEDIR}/wovtools/config.json" ]; then
   #echo "A:${A[*]}:A"
   #dir_root="${A[0]}"
 
+  WOV_PVERSION=$(cat ${WOV_BASEDIR}/wovtools/config.json | jq -r '.ver')
+  if [ "${WOV_PVERSION}" != "${WOV_VERSION}" ]; then
+    printf "\n\nERROR: Your project version '${WOV_PVERSION}', does not match to the WovTools version '${WOV_VERSION}'.\n\n"
+    exit 1
+  fi
+
   WOV_WPROJECT=$(cat ${WOV_BASEDIR}/wovtools/config.json | jq -r '.project.project') 
   WOV_PROJECTTYPE=$(cat ${WOV_BASEDIR}/wovtools/config.json | jq -r '.project.type') 
   WOV_PROJECTTITLE=$(cat ${WOV_BASEDIR}/wovtools/config.json | jq -r '.project.title') 
@@ -101,6 +110,14 @@ if [ -e "${WOV_BASEDIR}/wovtools/config.json" ]; then
     # GSTAGE has priority since it can represent <initials>-local, for local namespaces.
   export WOV_GSTAGE
   export WOV_STAGE
+
+  # Set DEVMODE 
+  if [[ ${WOV_GSTAGE} == "${WOV_KSTAGE}-l" ]]; then
+    WOV_DEVMODE=local
+  elif [[ ${WOV_GSTAGE} == "${WOV_KSTAGE}-v" ]]; then
+    WOV_DEVMODE=virtual
+  fi
+  export WOV_DEVMODE
 
   WOV_PROJECT=${WOV_WPROJECT}
   export WOV_PROJECT
@@ -138,6 +155,7 @@ function fDoEcho()
     echo WOV_GSTAGE="$WOV_GSTAGE"
     echo WOV_STAGE="$WOV_STAGE"
   fi
+  echo WOV_DEVMODE="${WOV_DEVMODE}"
   if [ "$RANCLUSTER" == "1" ]; then
     echo CL_REGION="$CL_REGION"
     echo CL_ZONES="${CL_ZONES}"
@@ -178,6 +196,17 @@ function doEnv()
     exit 1
   fi
 }
+function doQCmd() 
+{
+  if [ -e ${WOV_BASEDIR}/wovtools/cache/conf/${1} ]; then
+    cat ${WOV_BASEDIR}/wovtools/cache/conf/${1} | sed -e 's/#.*$//' -e '/^$/d' -e 's/^/'"'"'/g' -e 's/$/'"'"'/g' | tr '\n' ' '
+  else
+    echo
+    echo "ERROR: no environment file ${1} in cache."
+    echo
+    exit 1
+  fi
+}
 
 function doCmd() 
 {
@@ -191,6 +220,17 @@ function doCmd()
   fi
 }
 
+function doStringLiteral() 
+{
+  if [ -e ${WOV_BASEDIR}/wovtools/cache/conf/${1} ]; then
+    cat ${WOV_BASEDIR}/wovtools/cache/conf/${1} | sed -e 's/#.*$//' -e '/^$/d' -e 's/^/\$'"'"'/g' -e 's/$/'"'"'/g' | tr '\n' ' '
+  else
+    echo
+    echo "ERROR: no environment file ${1} in cache."
+    echo
+    exit 1
+  fi
+}
 
 # --------------------------------------------------------------------- 
 # Command line processing
@@ -207,6 +247,14 @@ while [[ $1 =~ ^- ]]; do
   elif [ "$1" == "--cmd" ]; then
     shift
     doCmd $1
+
+  elif [ "$1" == "--qcmd" ]; then
+    shift
+    doQCmd $1
+
+  elif [ "$1" == "--sl" ]; then
+    shift
+    doStringLiteral $1
 
   elif [ "$1" == '--var' ]; then
     shift 
