Major work on cluster creation and cluster database configuration scripts.
- a lot more thought has gone into databases. They should be in the default VPC and networked in via peer connections. And, there should be a production and a dev, where all developers are in as well.
- wov-cluster-createdb is redone (from wov-cluster-configdb) to show actual things to type in for a new database
- wov-cluster-configdbnet - this is the bulk
  - it works now and can be rerun multiple times as it is not destructive
  - running this sets up the default VPC for databases
  - running this configures the cluster's VPC for using databases in the default VPC
  - it's pretty good about checking for errors and such

TODO:
- wov-db-cloud - should probably not use any of the database creation code here
- wov-push-db - under dev

Minor:
- created a wov-env-common file that stores the function for naming AWS resources. This should be specific to AWS in the future, in a provider file. It was pulled from wov-db-cloud I think.
- wov-basion-connection has a new switch to check that the database has a tunneling port open
- wov-env now has '--res' switch to return the names of resources
- wov-env now has '--vref' to check resourcs exist
- minor fixes for bad verbase spew and such

diff --git a/bin/wov-env b/bin/wov-env
--- a/bin/wov-env
+++ b/bin/wov-env
@@ -51,6 +51,14 @@ Command Options:
   -p/--provider : run cluster config as well (queries cloud provider via wov-env-PROVIDER)
   --health      : check routes of a deployment
 
+  Resource Names:
+  --res SN RES ZONE  : subnet name
+  --res DBSNG RES    : DB subnet group
+  --res SG RES       : security group
+  --res DB RES       : database name
+  --res DBDNS RES    : DB DNS address
+  --vres RN RES      : verify resource of type RN, name RES
+
   Secrets/Config:
   --envs        : print all the configuration as environment variables (sep lines)
   --conf        : print all the configuration as environment variables (one line)
@@ -75,6 +83,14 @@ EOF
 
 if [ "$1" == '--help' ] || [ "$1" == '-h' ]; then fWovEnvDisplayOptions; exit 0; fi
 
+
+#_ARGS=()
+#shift_globally () {
+#  echo "...shift_globally on : '$@' ${#@}"
+#  shift
+#  _ARGS=$@
+#  echo "  ...shifted_globally: '${_ARGS[@]}' ${#_ARGS[@]}"
+#}
 
 
 # --------------------------------------------------------------------- 
@@ -537,6 +553,42 @@ doHealthChecks()
   done
 }
 
+# 1 exists, 0 does not, anything else, error
+# [res] [resname]
+#   -resname, get from doResName func
+# TODO move to provider-wov-env-aws
+function doResVerify()
+{
+  local retval=0
+
+  if [ "$2" == "" ]; then printf "\n\nERROR: resname name not provided to resVerify.\n"; fDisplayOptions; exit 1; fi
+  if [ "$1" == "SN" ]; then
+    R=$(aws ec2 describe-subnets --filters "Name=tag:Name,Values=${2}" --query 'Subnets[0]')
+    RR=$?
+    if [ "$R" == "null" ]; then retval=0; else retval=1; fi
+
+  elif [ "$1" == "DBSNG" ]; then
+    R=$(aws rds describe-db-subnet-groups --db-subnet-group-name ${2} >& /dev/null )
+    RR=$?
+    if [ "$RR" == "0" ]; then retval=1; else retval=0; fi
+
+  elif [ "$1" == "SG" ]; then
+    SG=$(aws ec2 describe-security-groups --filters "Name=group-name,Values=${2}" --query 'SecurityGroups[].GroupName' --output=text)
+    if [ "${SG}" == "" ]; then
+#      echo "  ... no existing secrurity group '${SG}'"
+      retval=0
+    else
+      retval=1
+    fi
+  else
+    printf "\n\nERROR: unknown resource of ${1} to resVerify.\n"
+    fDisplayOptions
+    exit 1
+  fi
+
+  echo $retval
+}
+
 
 
 # --------------------------------------------------------------------- 
@@ -546,12 +598,18 @@ doHealthChecks()
 . wov-env-loader
 doSetCluster "local"
 
+# --------------------------------------------------------------------- 
+# Load common functionality
+# --------------------------------------------------------------------- 
+. wov-env-common
+
 
 # --------------------------------------------------------------------- 
 # Command line processing
 while [[ $1 =~ ^- ]]; do
   if [ "$1" == '-e' ]; then
     ECHOMODE=1
+
   elif [ "$1" == '-E' ]; then
     ECHOMODE=2
 
@@ -630,6 +688,24 @@ while [[ $1 =~ ^- ]]; do
   elif [ "$1" == '--help' ] || [ "$1" == '-h' ]; then
     fWovEnvDisplayOptions
     exit 0
+
+  elif [ "$1" == '--res' ]; then
+    shift
+    doResName $@
+    A=$?
+    if [ $A -ne 0 ]; then exit $A; fi
+    # clear params until next '-'
+    while [[ ! ( $1 =~ ^- ) ]]; do shift; if [ "$1" == "" ]; then break; fi; done 
+    set - blank "$@"
+      # -- pushes 'blank' onto arguments, so next shift can get rid of it
+
+  elif [ "$1" == '--vres' ]; then
+    R1=$(doResVerify ${2} ${3}) ; RR1=$?
+    if [ ${DOECHO} -ge 2 ]; then echo "  ... verify ${2} ${3}"; fi
+    if [ "$R1" == "1" ]; then echo "true"; else echo "false"; fi
+    shift
+    shift
+
   else
     echo
     echo "***ERROR: unknown option '$1'."
@@ -637,6 +713,8 @@ while [[ $1 =~ ^- ]]; do
     exit 1
   fi
   shift
+
+
 done
 
 # if user never asked to show any individual variables, show all
diff --git a/bin/wov-init b/bin/wov-init
--- a/bin/wov-init
+++ b/bin/wov-init
@@ -508,7 +508,8 @@ rm ${WOV_BASEDIR}/wovtools/.config.json.*
 echo ""
 if [ -e "${WOV_BASEDIR}/wovtools/db" ] && 
    [ -e "${WOV_BASEDIR}/wovtools/db/archive" ] &&
-   [ -e "${WOV_BASEDIR}/wovtools/db/archive/.git" ]; then
+   [ -e "${WOV_BASEDIR}/wovtools/db/archive/.git" ] &&
+   [ -e "${WOV_BASEDIR}/wovtools/db/archive/.git/config" ]; then
   echo "ARCHIVE> Database Registry exists (at wovtools/db/archive)"
 else
   mkdir -p ${WOV_BASEDIR}/wovtools/db/archive/.git
@@ -519,7 +520,13 @@ else
 EOF
 
   WOV_DBREGISTRY=`git config --get remote.origin.url`
-  WOV_DBREGISTRY="${WOV_DBREGISTRY::-4}_archive.git"
+  if [ "$?" != "0" ]; then
+    printf "\nERROR: remote origin is not set for this repository.\n"
+    printf "  Use 'git remote add origin X' to set your remote repository.\n\n"
+    exit 1
+  fi
+  #  WOV_DBREGISTRY="${WOV_DBREGISTRY::-4}_archive.git"
+
   read -r -p "ARCHIVE> Database Registry git location: (\"${WOV_DBREGISTRY}\") ... Correct? [Y/n] " A
   if [ "${A}" != "" ]; then WOV_DBREGISTRY="${A}"; fi
 
@@ -550,7 +557,7 @@ fi
 
 echo "... test Git remote repo configuration/existence"
 #  cd ${WOV_BASEDIR}/wovtools/db/archive && git remote -v
-timeout_monitor 8 "$$" "TIMEOUT ERROR: failed to connect to remote repository. You should: 1) check network connection 2) ensure repo exists." &
+timeout_monitor 8 "$$" "TIMEOUT ERROR: failed to connect to remote repository. You should: 1) check network connection 2) ensure repo exists 3) ensure you are using ssh, not https." &
 Timeout_monitor_pid=$!
 cd ${WOV_BASEDIR}/wovtools/db/archive && git ls-remote -q > /dev/null
 if [ "$?" != "0" ]; then
diff --git a/bin/wov-push-container b/bin/wov-push-container
--- a/bin/wov-push-container
+++ b/bin/wov-push-container
@@ -34,7 +34,7 @@ SRCDIR=${WOV_BASEDIR}
 DESTDIR=
 ARCHDIR=
 
-echo "NOTE[$0]: Skipping git checks.... will do on wov-push."
+# echo "NOTE[$0]: Skipping git checks.... will do on wov-push."
 
 
 # If NodeJS project...
@@ -493,6 +493,11 @@ done
 
 # Find the recipes and push them
 if [ "${BLOCK}" == "0" ]; then
+
+  if [ ! -e "${WOV_BASEDIR}/wovtools/containers" ]; then
+    printf "\nERROR: wovtools/containers directory does not exist. Should have container recipes there.\n\n"
+    exit 1
+  fi
 
   RECIPES=( "$@" )
   if [ "${#RECIPES[@]}" == "0" ]; then
diff --git a/bin/wov-push-db b/bin/wov-push-db
--- a/bin/wov-push-db
+++ b/bin/wov-push-db
@@ -59,13 +59,15 @@ EOF
 function fFailedDBConnection()
 {
   local RET=$1
-  printf "  > Is db inited?\n"
-  printf "    - init>        'wov-db-cloud -D ${1} -I'\n"   
-  printf "    - get version> 'wov-db-cloud -D $1 --ver'\n"
-  printf "\n"
-  printf "\n"
+  if [ "$2" != "" ]; then
+    printf "  > Is db inited?\n"
+    printf "    - init>        'wov-db-cloud -D ${2} -I'\n"   
+    printf "    - get version> 'wov-db-cloud -D $2 --ver'\n"
+    printf "\n"
+    printf "\n"
+  fi
   printf "  > Is it a bastion issue, or a privileges issue.\n"
-      printf "  - is 'vh' pod up and running?\n"
+  printf "  - is 'vh' pod up and running?\n"
   printf "\n"
   printf "\n"
 
@@ -86,10 +88,21 @@ function fFailedDBConnection()
 # --------------------------------------------------------------------- 
 function doHashDBSchema()
 {
-  local CHKSUM=$(wov-db-connect $1 --schema 2> /dev/null | shasum -a 256 | cut -d' ' -f1)
-  if [ "$?" != "0" ]; then 
-    printf "\n\nERROR: failed to connect to database server $i.\n"; 
-    fFailedDBConnection 1
+  local HASH=0
+  HASH="$(wov-db-connect $1 --schema 2> /dev/null)"; local A=$?
+  #echo "here1 - $A '$HASH' "
+  if [ $A -ne 0 ]; then 
+    echo $HASH
+    exit 1
+  fi
+  #echo "here 2 $A $SCK"
+  #local CHKSUM=$(wov-db-connect $1 --schema 2> /dev/null | shasum -a 256 | cut -d' ' -f1)
+  local CHKSUM=$(echo "${HASH}" | shasum -a 256 | cut -d' ' -f1)
+  local A=$?
+  #echo "here2 - $A $HASH $CHKSUM"
+  if [ "$A" != "0" ]; then 
+    printf "\n\nERROR: failed to connect to database server '$1'.\n"; 
+    fFailedDBConnection 2 $1
   fi
   echo ${CHKSUM}
 }
@@ -108,7 +121,7 @@ function doGetDBPVER()
   local r=$?
   if [ "$r" != "0" ]; then 
     printf "\n\nERROR: failed to connect to database wovtools, table logs, on database server $1.\n\n"; 
-    fFailedDBConnection 1
+    fFailedDBConnection 1 $1
   fi
 #  echo "DBRAW ${DBRAW}" 1>&2
   local DB_PVER=`echo ${DBRAW} | cut -d'|' -f5`
@@ -127,7 +140,7 @@ function doGetDBLastLogEntry()
   local DB_PVER=$(wov-db-connect $i -q -d wovtools -c "SELECT * FROM logs WHERE database='$1' ORDER BY id DESC LIMIT 1;" 2> /dev/null)
   if [ "$?" != "0" ]; then 
     printf "\n\nERROR: failed to find wovtools logs on database server $1.\n\n"; 
-    fFailedDBConnection 1
+    fFailedDBConnection 1 $1
   else
     retval=0
     echo ${DB_PVER}
@@ -226,15 +239,19 @@ function doPushCheck()
   #     or if nothing checked in yet, then db's pver is parent pver, so hash that
   if [ "$retval" == "0" ]; then
     if [ $DOECHO -ge 1 ]; then printf "... retrieve db hash.\n"; fi
-    DB_HASH=$(doHashDBSchema $1)
-    echo "db hash: ${DB_HASH}"
+    DB_HASH=$(doHashDBSchema $1) ; local A=$?
+    #echo "db hash: $A '${DB_HASH}'"
+    if [ $A -ne 0 ]; then
+      echo "${DB_HASH}"
+      fFailedDBConnection 2 $1
+    fi
     DB_PVER=$(doGetDBPVER $1)
     if [ "$?" != "0" ] || [ "$DB_PVER" == "" ]; then
       printf "\n\nERROR: could not get database version.\n"
-      fFailedDBConnection 2
+      fFailedDBConnection 2 $1
     elif [ ! -e ${WOV_BASEDIR}/wovtools/db/archive/${1}.json ]; then 
       printf "\nERROR: no archive/${1}.json.\n"; 
-      fFailedDBConnection 2
+      fFailedDBConnection 2 $1
     else
       REG_HASH=$( jq -r " .versions.\"${WOV_PVER}\".checksum" ${WOV_BASEDIR}/wovtools/db/archive/${1}.json )
       if [ "${REG_HASH}" == "null" ]; then
@@ -371,7 +388,7 @@ function doCommitDB()
   deltafile=${WOV_BASEDIR}/wovtools/db/$1.deltas
   if [ ! -e $deltafile ]; then
     printf "\n\nERROR: can't find deltas file: 'wovtools/db/$1.deltas'.\n\n"
-    fFailedDBConnection 1
+    fFailedDBConnection 1 $1
   fi
 
   # make sure directory exists for database
@@ -383,10 +400,10 @@ function doCommitDB()
 #  DB_PVER=$(doGetDBPVER $1)
   if [ "$?" != "0" ]; then
     printf "\n\n***ERROR: database not inited.\n"
-    fFailedDBConnection 1
+    fFailedDBConnection 1 $1
   elif [ "${DB_ENTRY}" == "" ]; then
     printf "\n\n***ERROR: database has no parent.\n"
-    fFailedDBConnection 2
+    fFailedDBConnection 2 $1
   fi
 #  printf "\nDB_ENTRY '${DB_ENTRY}'\n"
   OLDIFS=$IFS
@@ -404,7 +421,7 @@ function doCommitDB()
     DB_PVER=$(doGetDBPVER $1)
     if [ "$?" != "0" ]; then
       printf "**ERROR: failed connecting to db.\n\n"
-      fFailedDBConnection 1
+      fFailedDBConnection 1 $1
     fi
 
     echo "Chksum : ${CHKSUM}  DBPVER: ${DB_PVER}  PVER: ${WOV_PVER}"
@@ -436,7 +453,7 @@ EOF
     r=$?
     if [ "$r" != "0" ]; then
       printf "\n\nERROR: failed to write schemas to regsitry.\n\n"
-      fFailedDBConnection 1
+      fFailedDBConnection 1 $1
     fi
 
 
@@ -470,7 +487,7 @@ EOF
     R=$(wov-db-connect $1 -q -d wovtools -c "INSERT INTO logs (database, wovtoolsver, label, pver, sver ) VALUES ( '$1', '${WOV_VERSION}', '${WOV_PVER}_${WOV_SVER}', ${WOV_PVER}, ${WOV_SVER} );")
     if [ "$?" != "0" ]; then
       printf "\n\nERROR: failed updating archive database pver number with checksum.\n"
-      fFailedDBConnection 3
+      fFailedDBConnection 3 $1
     fi
   fi
 
@@ -524,12 +541,15 @@ done
 
 
 
-echo ".. starting"
+#echo "... starting"
 retval=1
 if [ "$DOACTION" == "check" ]; then
 
   DATABASES=( $(doFindDatabases $*) )
-  #echo "DATABASES: ${DATABASES[@]}"
+  # echo "DATABASES: ${DATABASES[@]}"
+  if [ "${#DATABASES[@]}" == "0" ]; then
+    if [ $DOECHO -ge 1 ]; then printf "... no databases to check.\n"; fi
+  fi 
 
   # check each db
   retval=0
