Checking in after getting DB versioning working... kinda. Still needs to be able to roll to a point. Easiest thing is to build the SQL file and the wov-db-commit -f X that file. Other bug fixes and updates to wov-cd. Fixed that bug last commit in wov-push which was rebuilding containers unecessarily (aws ec2 cli was returning tagged repos out of order).

diff --git a/bin/wov-cd b/bin/wov-cd
--- a/bin/wov-cd
+++ b/bin/wov-cd
@@ -11,12 +11,25 @@ fi
 if [ "$#" == 1 ]; then
 
   P=$(echo $1 | cut -d'/' -f1)
-  D=$(jq -r ".projects.$P.dir" ${HOME}/.wovtools)
-  D1=( ${1//\// } )
-  D1=( "${D1[@]:1:}" )
-#  echo ": '$D' / '$D1'"
-  GO="$D$D1"
-  cd $GO
+  D=$(jq -r ".projects.$P.dir" ${HOME}/.wovtools 2> /dev/null)
+  if [ "$?" != "0" ]; then
+    printf "\nERROR: json related error. Check your ~/.wovtools file.\n";
+    printf " - $(jq -r ".projects.$P.dir" ${HOME}/.wovtools 2>&1)\n"
+  else
+    if [ "$D" == "null" ]; then 
+      printf "\n\nERROR: no project entry of '$P'.\n"
+    else
+      D1=( ${1//\// } )
+      D1=( "${D1[@]:1:}" )
+      GO="$D$D1"
+      if [ ! -e "${D}${D1}" ]; then
+        printf "\n\nERROR: no directory '$D$D1'.\n"
+      else
+        printf "project '$P' : $GO\n"
+        cd $GO
+      fi
+    fi
+  fi
 else
   printf "\n\nERROR: bad number of parameters. Requires a project name.\n"
   exit 1
