The 'vh' service had a lot of extra configmaps and secrets added to it... which overwrote the same variables and messed up the development environment.
- Changes wov-build to clean 'conf' files before building.
- Changed wov-vh to only load Secrets and ConfigMaps (i.e. 'conf') from
those generated by the build command (i.e. only those in wovtools/conf.

- Minor: corrected error message of wov-build-containers which was
saying container recipe was not executable, but really it didn't exist.
Confusing due to the container/microservice similarity which caused me a
moment or two to figure out. Fixed for future screwups.

diff --git a/bin/wov-build-containers b/bin/wov-build-containers
--- a/bin/wov-build-containers
+++ b/bin/wov-build-containers
@@ -348,8 +348,12 @@ if [ "${BLOCK}" == "0" ]; then
 
 #    echo "    ... DESTDIR=${DESTDIR}"
 #    echo "    ... CONTAINER=${CONTAINER}"
-    if [[ ! -x "${WOV_BASEDIR}/wovtools/containers/$f" ]]; then 
+    if [[ ! -e "${WOV_BASEDIR}/wovtools/containers/$f" ]]; then 
+      echo "ERROR: recipe for container ${f} does not exist (${WOV_BASEDIR}/wovtools/containers/$f).";
+      exit 1
+    elif [[ ! -x "${WOV_BASEDIR}/wovtools/containers/$f" ]]; then 
       echo "ERROR: recipe for container ${f} not executable (${WOV_BASEDIR}/wovtools/containers/$f).";
+      exit 1
     else
 
       doPackContainer ${f}
