Lots of changes after coming back to this. Just pushing all in.

diff --git a/bin/wov-env-build b/bin/wov-env-build
--- a/bin/wov-env-build
+++ b/bin/wov-env-build
@@ -274,7 +274,13 @@ EOF
     if [ "$DOECHO" == "2" ]; then echo "  ... updating local context"; fi
     mkdir -p     "${WOV_CACHEDIR}/clusters/local"
     chmod -R 700 "${WOV_CACHEDIR}/clusters/local"
-    cp "${WOV_CACHEDIR}/clusters/${LOCALCONTEXT}/secrets.json" "${WOV_CACHEDIR}/clusters/local/secrets.json" 
+    if [ "${LOCALCONTEXT}" != "local" ]; then
+      cp "${WOV_CACHEDIR}/clusters/${LOCALCONTEXT}/secrets.json" "${WOV_CACHEDIR}/clusters/local/secrets.json" 2> /dev/null
+      if [ "$?" != "0" ]; then
+        echo "ERROR: failed copy of secrets to cache dir 'clusters/local/secrets.json'." 1>&2
+        exit 1
+      fi
+    fi
   fi
 
   # Is secret different from last run?
diff --git a/bin/wov-push b/bin/wov-push
--- a/bin/wov-push
+++ b/bin/wov-push
@@ -27,16 +27,16 @@ printf " version: ${WOV_STAGE}_${WOV_PVER}_${WOV_SVER}\n\n"
 
 
 # Check all stagemods are off
-ONSTAGEMODS=( $(jq -r '.stagemods[] | select(.status == "on") | .["name"]' ${WOV_BASEDIR}/wovtools/config.json ) )
-if [[ "$ONSTAGEMODS" != "" ]]; then
-  printf "\nERROR: turn off stagemods when pushing content.\n"
-  printf "  active stagemods: ${ONSTAGEMODS[*]}\n\n"
-  for sm in ${ONSTAGEMODS[@]}; do
-    printf "  ex. wov-mod --off ${sm}\n"
-  done
-  printf "\n"
-  exit 1
-fi
+#ONSTAGEMODS=( $(jq -r '.stagemods[] | select(.status == "on") | .["name"]' ${WOV_BASEDIR}/wovtools/config.json ) )
+#if [[ "$ONSTAGEMODS" != "" ]]; then
+#  printf "\nERROR: turn off stagemods when pushing content.\n"
+#  printf "  active stagemods: ${ONSTAGEMODS[*]}\n\n"
+#  for sm in ${ONSTAGEMODS[@]}; do
+#    printf "  ex. wov-mod --off ${sm}\n"
+#  done
+#  printf "\n"
+#  exit 1
+#fi
 
 # Check local code is checked in and pushed
 wov-git-check ${WOV_BASEDIR}
