Added to wov-aws ability to add permissions as well as shifted datasets from wovtools/data to wovtools/ds with wovtools/ds/conf.
wov-aws
- added permissions

wov-compile wov-hbs wov-db
- changed how it uses conf data for DataSets

wov-init
- creates wovtools/ds/conf

diff --git a/bin/wov-aws b/bin/wov-aws
--- a/bin/wov-aws
+++ b/bin/wov-aws
@@ -149,6 +149,153 @@ function doVolumeEnsure()
   return 0
 }
 
+function doGrantUserAccessToS3()
+{
+  local AWSUser=$1
+  local PolicyName="S3-WovToolsProject-k8sarchive-${WOV_PROJECT}-${WOV_CLUSTER}"
+  local UserCode=$2
+  local f=".tmp.$$"
+
+
+  touch $f
+  chmod 600 $f
+  cat <<EOF > $f
+{
+  "Version": "2012-10-17",
+  "Statement": [
+      {
+          "Effect": "Allow",
+          "Action":   ["s3:PutObject","s3:GetObject"],
+          "Resource": "arn:aws:s3:::${WOV_ARCHIVEENV:5}/${WOV_CLUSTER}/${WOV_PROJECT}/${UserCode}/*"
+        }
+  ]
+}
+EOF
+
+  echo "Summary: "
+  cat $f
+  echo "AWS Command: aws iam put-user-policy --user-name "${AWSUser}" --policy-name "${PolicyName}" --policy-document 'file://$f'"
+  echo ""
+  read -r -p "Grant user access? [y/N]" A
+  case $A in
+    [Yy]|[Yy][Ee][Ss])
+      echo ""
+      ;;
+    *)
+      echo "  exiting. NO ACTION TAKEN."
+      rm ./.tmp.$$
+      exit 1
+      ;;
+  esac
+
+  # Run command
+  set -x
+  aws iam put-user-policy --user-name "${AWSUser}" --policy-name "${PolicyName}" --policy-document file://$f
+  if [ $? -ne 0 ]; then
+    #rm "$f"
+    echo "Failed" 
+    exit 1
+#  else
+#    rm "$f"
+  fi
+}
+
+# https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_examples_codecommit_pull.html
+# https://docs.aws.amazon.com/codecommit/latest/userguide/auth-and-access-control-iam-identity-based-access-control.html#managed-policies
+function doGrantUserAccessToCodeCommit()
+{
+  local REPO=$1
+  local Branch=$2
+  local AWSUser=$3
+  local PolicyName="CodeCommit-$4"
+  local Conditions=
+  local RESOURCE="arn:aws:codecommit:us-east-1:*:${REPO}"
+
+  if [ "${REPO}" == "" ]; then l_error "No repository name provided as param 1."; exit 1; fi
+  if [ "${Branch}" == "" ]; then l_error "No branch name provided as param 2."; exit 1; fi
+  if [ "${AWSUser}" == "" ]; then l_error "No AWSUser specified as param 3."; exit 1; fi
+  if [ "${4}" == "" ]; then l_error "No policy name provided as param 4."; exit 1; fi
+
+  if [ "${Branch}" == "full" ]; then
+    read -r -p "WARNING: Granting user '${AWSUser}' access to all branches of '${REPO}'. Correct? [y/N]" A
+    case $A in
+      [Yy]|[Yy][Ee][Ss])
+        Conditions=
+        ;;
+      *)
+        echo "  exiting. NO ACTION TAKEN."
+        exit 1
+        ;;
+    esac
+  else
+    read -r -d '' Conditions <<EOF
+        "StringEquals": {
+          "codecommit:References": [ "refs/heads/${Branch}" ]
+        }
+EOF
+  fi
+
+
+  touch ./.tmp.$$
+  chmod 600 ./.tmp.$$
+  cat <<EOF > ./.tmp.$$
+{
+  "Version": "2012-10-17",
+  "Statement": [
+    {
+      "Effect": "Allow",
+      "Action": [
+        "codecommit:GitPull"
+      ],
+      "Resource": "${RESOURCE}"
+    },
+    {
+      "Effect": "Allow",
+      "Action": [
+        "codecommit:GitPush"
+      ],
+      "Resource": "${RESOURCE}",
+      "Condition": {
+        ${Conditions}
+      }
+    }
+  ]
+}
+EOF
+
+  echo "Summary: "
+  echo "  REPO     : ${REPO}"
+  echo "  Branch   : ${Branch}"
+  echo "  RESOURCE : ${RESOURCE}"
+  echo "  Policy   : ${PolicyName}"
+  echo "  AWSUser  : ${AWSUser}"
+  cat ./.tmp.$$
+  echo ""
+  read -r -p "Grant user access? [y/N]" A
+  case $A in
+    [Yy]|[Yy][Ee][Ss])
+      # echo "aws iam put-user-policy --user-name ${AWSUser} --policy-name ${PolicyName} --policy-document file://.tmp.$$"
+      echo ""
+      ;;
+    *)
+      echo "  exiting. NO ACTION TAKEN."
+      rm ./.tmp.$$
+      exit 1
+      ;;
+  esac
+
+  # Run command
+  aws iam put-user-policy --user-name "${AWSUser}" --policy-name "${PolicyName}" --policy-document file://.tmp.$$
+  if [ $? -ne 0 ]; then
+    rm ./.tmp.$$
+    echo "Failed" 
+    exit 1
+  else
+    rm ./.tmp.$$
+  fi
+
+}
+
 
 
 # ---------------------------------------------------------------------
@@ -200,6 +347,12 @@ elif [ "${COMMAND}" == "cluster" ]; then
 #  doCluster
 #  EXIT=1
   exit 1
+
+elif [ "${COMMAND}" == "repoaccess" ]; then
+  doGrantUserAccessToCodeCommit"${@}"
+
+elif [ "${COMMAND}" == "k8saccess" ]; then
+  doGrantUserAccessToS3 "${@}"
 
 else
   printf "ERROR: unknown command \"${COMMAND}\".\n" 1>&2
diff --git a/bin/wov-db b/bin/wov-db
--- a/bin/wov-db
+++ b/bin/wov-db
@@ -57,7 +57,7 @@ COMMANDS:
   --wdb-log       : returns the log of commits for the database
   --wdb-edit      : edit the current wov database schema deltas file (i.e. add SQL that you use to change things)
 
- DataSets : non-production data management:
+ DataSets : non-production data management: stored in wovtools/ds with consts in wovtools/ds/const
   -lds               : list all DataSets
   --ds-schema/-ds X : with DataSet X, reloads the database schema (clearing existing data)
   --ds-clear/-dc  X : with DataSet X, clears data in the database
@@ -125,7 +125,7 @@ function doDataSetList()
 
   # find files
   for s in ${DATASETFILES[@]}; do
-    fname+=( $(cd ${WOV_BASEDIR}/wovtools/data ; ls -- *_$s.sql* 2> /dev/null ) )
+    fname+=( $(cd ${WOV_BASEDIR}/wovtools/ds; ls -- *_$s.sql* 2> /dev/null ) )
   done
 #  echo "fname: '${fname[@]}'"
 
@@ -215,42 +215,42 @@ doSetDBData()
 #DB_PORT=$(wov-bastion --bhost ${WOV_CLUSTER}-bastion --ldp ${WOVDBNAME})
 #DB_HOST=localhost   # bastion
 # --------------------------------------------------------------------- 
-# Builds the X data set for a database from the wovtools/data/X_* files
+# Builds the X data set for a database from the wovtools/ds/X_* files
 #  $1 - data set name (ex. alywan)
 # --------------------------------------------------------------------- 
-function doDBDataBuild()
+function doDBDataSetBuild()
 {
-  if [ "$1" == "" ]; then echo "ERROR: need a data set name parameter to wov-db::doDBDataBuild."; exit 1; fi
+  if [ "$1" == "" ]; then echo "ERROR: need a data set name parameter to wov-db::doDBDataSetBuild."; exit 1; fi
 
 
   # Make the target directory
-  mkdir -m 700 -p ${WOV_BASEDIR}/wovtools/cache/data
-  if [ $? -ne 0 ]; then echo "ERROR: failed to make target data directory in cache."; exit 1; fi
+  mkdir -m 700 -p ${WOV_BASEDIR}/wovtools/cache/ds
+  if [ $? -ne 0 ]; then echo "ERROR: failed to make target data set directory in cache."; exit 1; fi
 
   for f in ${DATASETFILES[@]}; do
 
-    local fname=`cd ${WOV_BASEDIR}/wovtools/data ; ls $1_$f.*`
+    local fname=`cd ${WOV_BASEDIR}/wovtools/ds; ls $1_$f.*`
     l_verbose "f: '${f}'  fname: '${fname}'   last 4: '${fname: -4}'"
 
     if [ "${fname: -4}" == ".wov" ]; then
       local finname="${fname::-4}"
       l_verbose "  ... compile '${fname}' since it has .wov on it :${finname}"
-      if [ ! -e "${WOV_BASEDIR}/wovtools/cache/data/${finname}" ] ||
-         [ "${WOV_BASEDIR}/wovtools/data/${1}_const.js" -nt "${WOV_BASEDIR}/wovtools/cache/data/${finname}" ] ||
-         [ "${WOV_BASEDIR}/wovtools/data/${fname}"      -nt "${WOV_BASEDIR}/wovtools/cache/data/${finname}" ]; then
+      if [ ! -e "${WOV_BASEDIR}/wovtools/cache/ds/${finname}" ] ||
+         [ "${WOV_BASEDIR}/wovtools/ds/const/${1}_const.js" -nt "${WOV_BASEDIR}/wovtools/cache/ds/${finname}" ] ||
+         [ "${WOV_BASEDIR}/wovtools/ds/${fname}"      -nt "${WOV_BASEDIR}/wovtools/cache/ds/${finname}" ]; then
         l_ "  ... compile ${finname}"
         WOV_BASEDIR=${WOV_BASEDIR} wov-compile -ds ${1} \
           "`WOV_getClusterConfigDir ${WOV_ORIGIN} ${WOV_CONTEXT}`/config.json" \
-          "${WOV_BASEDIR}/wovtools/data/${fname}" > "${WOV_BASEDIR}/wovtools/cache/data/${finname}"
+          "${WOV_BASEDIR}/wovtools/ds/${fname}" > "${WOV_BASEDIR}/wovtools/cache/ds/${finname}"
       else
         l_ "  ... no need to compile '${fname}'"
       fi
 
     else
       l_verbose "  ... copy over '${fname}'"
-      #if [ ! -e "${WOV_BASEDIR}/wovtools/cache/data/${fname}" ]; then
+      #if [ ! -e "${WOV_BASEDIR}/wovtools/cache/ds/${fname}" ]; then
       #  l_ "  ... cp ${fname}"
-      cp "${WOV_BASEDIR}/wovtools/data/${fname}" "${WOV_BASEDIR}/wovtools/cache/data/."
+      cp "${WOV_BASEDIR}/wovtools/ds/${fname}" "${WOV_BASEDIR}/wovtools/cache/ds/."
       #fi
     fi
 
@@ -263,20 +263,20 @@ function doDBDataBuild()
 # $1 - data set to use
 # #2 - data command to run: schema, clear or data which match to a file 
 # --------------------------------------------------------------------- 
-function doDBDataCommand()
+function doDBDataSetCommand()
 {
   if [ "$WOV_STAGE" == "prod" ]; then echo "ERROR: wov-db DataSets do not work on production."; exit 1; fi
-  if [ "$1" == "" ]; then echo "ERROR: need a data set name parameter to wov-db::doDBDataCommand."; exit 1; fi
+  if [ "$1" == "" ]; then echo "ERROR: need a data set name parameter to wov-db::doDBDataSetCommand."; exit 1; fi
   if [ "$2" == "schema" ] ||
      [ "$2" == "clear" ] ||
      [ "$2" == "data" ]; then
     local A=1
   else
-    echo "ERROR: Unknown command for doDBDataCommand of '${2}'. Should be one of 'schema', 'clear', or 'data'."
+    echo "ERROR: Unknown command for doDBDataSetCommand of '${2}'. Should be one of 'schema', 'clear', or 'data'."
     exit 1
   fi
 
-  R=$(PGPASSWORD=${DB_PASSWORD} psql --quiet -P "footer=off" -p ${DB_PORT} -h ${DB_HOST} -U ${DB_USERNAME} -d ${DB_DATABASE} -f "${WOV_BASEDIR}/wovtools/cache/data/${1}_${2}.sql") ; Re=$?
+  R=$(PGPASSWORD=${DB_PASSWORD} psql --quiet -P "footer=off" -p ${DB_PORT} -h ${DB_HOST} -U ${DB_USERNAME} -d ${DB_DATABASE} -f "${WOV_BASEDIR}/wovtools/cache/ds/${1}_${2}.sql") ; Re=$?
   if [ ${DOECHO} -ge 2 ]; then echo "${R}"; fi
   if [ ${DOECHO} -ge 1 ]; then echo "  ... loaded ${1}_${2}.sql"; fi
   if [ "$Re" != "0" ]; then
@@ -773,43 +773,43 @@ while [[ $1 =~ ^- ]]; do
   elif [ "$1" == "--ds-schema" ] || [ "$1" == "-ds" ]; then
     shift
     exitIfProd
-    doDBDataBuild $1
-    doDBDataCommand $1 "schema"
+    doDBDataSetBuild $1
+    doDBDataSetCommand $1 "schema"
     exit 0
     shift
 
   elif [ "$1" == "--ds-clear" ] || [ "$1" == "-dc" ]; then
     shift
     exitIfProd
-    doDBDataBuild $1
-    doDBDataCommand $1 "clear"
+    doDBDataSetBuild $1
+    doDBDataSetCommand $1 "clear"
     exit 0
     shift
 
   elif [ "$1" == "--ds-data" ] || [ "$1" == "-dd" ]; then
     shift
     exitIfProd
-    doDBDataBuild $1
-    doDBDataCommand $1 "data"
+    doDBDataSetBuild $1
+    doDBDataSetCommand $1 "data"
     exit 0
     shift
 
   elif [ "$1" == "--ds-reload" ] || [ "$1" == "-dr" ]; then
     shift
     exitIfProd
-    doDBDataBuild $1
-    doDBDataCommand $1 'clear'
-    doDBDataCommand $1 'data'
+    doDBDataSetBuild $1
+    doDBDataSetCommand $1 'clear'
+    doDBDataSetCommand $1 'data'
     exit 0
     shift
 
   elif [ "$1" == "--ds-full" ] || [ "$1" == "-df" ]; then
     shift
     exitIfProd
-    doDBDataBuild $1
-    doDBDataCommand $1 'schema'
-    doDBDataCommand $1 'clear'
-    doDBDataCommand $1 'data'
+    doDBDataSetBuild $1
+    doDBDataSetCommand $1 'schema'
+    doDBDataSetCommand $1 'clear'
+    doDBDataSetCommand $1 'data'
     exit 0
     shift
 
