Created a "stagemod" concept, where wov-build can incorporate configuration changes via paths. This allows for very flexible configuration, useful for generating configuration for local development, pod development and k8s running.
NOTE: other changes could have been incorporated since I have a lot of
outstanding changes (i.e. lots of things work well enough for me but I
have yet to commit).

NOTE2: each route adds about 1/10th of a second to wov-build.

Changes:
- wov-mod - manages the 'stagemods' entry in wovtools/config.json
- wov-build - applies routes in wovtools/config.json:stagemods
- wov-push and wov-push-env - won't push if any stagemods are active

diff --git a/bin/wov-push b/bin/wov-push
--- a/bin/wov-push
+++ b/bin/wov-push
@@ -39,6 +39,19 @@ figlet wov-push
 printf " version: ${WOV_STAGE}_${WOV_PVER}_${WOV_SVER}\n\n"
 
 
+# Check all stagemods are off
+ONSTAGEMODS=( $(jq -r '.stagemods[] | select(.status == "on") | .["name"]' wovtools/config.json ) )
+if [[ "$ONSTAGEMODS" != "" ]]; then
+  printf "\nERROR: turn off stagemods when pushing content.\n"
+  printf "  active stagemods: ${ONSTAGEMODS[*]}\n\n"
+  for sm in ${ONSTAGEMODS[@]}; do
+    printf "  ex. wov-mod --off ${sm}\n"
+  done
+  printf "\n"
+  exit 1
+fi
+
+
 # Check local code is checked in and pushed
 wov-git-check ${WOV_BASEDIR}
 R1=$?
@@ -48,6 +61,7 @@ if [ "$R1" != "0" ] || [ "$R2" != "0" ]; then
   printf "\nERROR: wov-push exiting\n" 1>&2
   exit 1
 fi
+
 
 
 
@@ -108,7 +122,7 @@ done
 
 if [ "$SKIPDBCHECKS" != "1" ]; then
   echo "  ... check for database changes that could block the push"
-  wov-db-commit --any-push-blockage
+  wov-db-commit -v --any-push-blockage
   R3=$?
   if [ "$R3" != 0 ]; then exit 1; fi
 else
diff --git a/bin/wov-push-env b/bin/wov-push-env
--- a/bin/wov-push-env
+++ b/bin/wov-push-env
@@ -19,6 +19,18 @@ set ""
 set -- "${pushenvargs[@]}"
 
 
+# Check all stagemods are off
+ONSTAGEMODS=( $(jq -r '.stagemods[] | select(.status == "on") | .["name"]' wovtools/config.json ) )
+if [[ "$ONSTAGEMODS" != "" ]]; then
+  printf "\nERROR: turn off stagemods when pushing content.\n"
+  printf "  active stagemods: ${ONSTAGEMODS[*]}\n\n"
+  for sm in ${ONSTAGEMODS[@]}; do
+    printf "  ex. wov-mod --off ${sm}\n"
+  done
+  printf "\n"
+  exit 1
+fi
+
 # Check local code is checked in and pushed
 wov-git-check ${WOV_BASEDIR}
 R1=$?
