Checking in a bunch of uncommented changes. It's building up but I need to push.

diff --git a/bin/wov-build-containers b/bin/wov-build-containers
--- a/bin/wov-build-containers
+++ b/bin/wov-build-containers
@@ -25,15 +25,17 @@ SSHKEY=
 RECIPES=( )
 
 
-# Check local code is checked in and pushed
-wov-git-check ${WOV_BASEDIR}
-R1=$?
-wov-git-check ${WOV_BASEDIR}/wovtools/secrets
-R2=$?
-if [ "$R1" != "0" ] || [ "$R2" != "0" ]; then 
-  printf "\nERROR: wov-build-containers exiting\n" 1>&2
-  exit 1;
-fi
+echo "NOTE[$0]: Skipping git checks.... will do on wov-push."
+
+## Check local code is checked in and pushed
+#wov-git-check ${WOV_BASEDIR}
+#R1=$?
+#wov-git-check ${WOV_BASEDIR}/wovtools/secrets
+#R2=$?
+#if [ "$R1" != "0" ] || [ "$R2" != "0" ]; then 
+#  printf "\nERROR: wov-build-containers exiting\n" 1>&2
+#  exit 1;
+#fi
 
 
 
diff --git a/bin/wov-db-commit b/bin/wov-db-commit
--- a/bin/wov-db-commit
+++ b/bin/wov-db-commit
@@ -48,6 +48,14 @@ EOF
 }
 
 # --------------------------------------------------------------------- 
+# --------------------------------------------------------------------- 
+#function doGetDBSchema()
+#{
+#  local SCHEMA=$(wov-db-connect $1 --schema 2> /dev/null)
+#  if [ "$?" != "0" ]; then printf "\n\nERROR: failed to connect to database server $i.\n"; exit 1; fi
+#  echo ${SCHEMA}
+#}
+# --------------------------------------------------------------------- 
 # NOTE: just hashes return, fail messages included!
 # $1 = database name
 # --------------------------------------------------------------------- 
@@ -66,6 +74,7 @@ function doGetDBPVER()
 {
   local retval=1
   local DB_PVER=$(wov-db-connect $i -q -d wovtools -c "SELECT * FROM logs WHERE database='$1' ORDER BY id DESC LIMIT 1;" 2> /dev/null |  cut -d'|' -f5)
+#  local DB_PVER=$(wov-db-connect $i -q -d wovtools -c 'SELECT * FROM logs WHERE database=\''"$1"'\' ORDER BY id DESC LIMIT 1;' 2> /dev/null |  cut -d'|' -f5)
 #  printf "DB_PVER : $DB_PVER"
   if [ "$?" != "0" ]; then 
     printf "\n\nERROR: failed to find wovtools logs on database server $1.\n\n"; 
@@ -84,7 +93,6 @@ function doGetDBPVER()
 # --------------------------------------------------------------------- 
 function doGetDBLastLogEntry()
 {
-  set -x
   local retval=1
   local DB_PVER=$(wov-db-connect $i -q -d wovtools -c "SELECT * FROM logs WHERE database='$1' ORDER BY id DESC LIMIT 1;" 2> /dev/null)
   if [ "$?" != "0" ]; then 
@@ -95,7 +103,6 @@ function doGetDBLastLogEntry()
     retval=0
     echo ${DB_PVER}
   fi
-  set +x
 
   return $retval
 }
@@ -189,6 +196,7 @@ function doPushCheck()
   #     or if nothing checked in yet, then db's pver is parent pver, so hash that
   if [ "$retval" == "0" ]; then
     DB_HASH=$(doHashDBSchema $1)
+    echo "db hash: ${DB_HASH}"
     DB_PVER=$(doGetDBPVER $1)
     if [ "$?" != "0" ] || [ "$DB_PVER" == "" ]; then
       printf "\n\nERROR: could not get database version.\n"
@@ -333,19 +341,20 @@ function doCommitDB()
     printf "\n\n***ERROR: database has no parent.\n"
     retval=2
   fi
-  printf "\nDB_ENTRY '${DB_ENTRY}'\n"
+#  printf "\nDB_ENTRY '${DB_ENTRY}'\n"
   OLDIFS=$IFS
   IFS='|'
-  dbverarray=( $(wov-db -D ${WOVDB_DBNAME} --ver)  )
+  # CAW - just commented out dbverarray=( $(wov-db -D ${WOVDB_DBNAME} --ver)  )
   DB_ENTRY=( $(echo "${DB_ENTRY[@]}") )
   IFS=$OLDIFS
-  printf "\nDB_ENTRY '${DB_ENTRY[@]}'\n"
+#  printf "\nDB_ENTRY '${DB_ENTRY[*]}'\n"
   DB_PVER="$( echo -e "${DB_ENTRY[4]}" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')"
 
   if [ "$retval" == "0" ]; then
 
     # get current db checksum
     CHKSUM=$(doHashDBSchema $1)
+    DB_PVER=$(doGetDBPVER $1)
 
     echo "Chksum : ${CHKSUM}  DBPVER: ${DB_PVER}  PVER: ${WOV_PVER}"
 
@@ -367,6 +376,16 @@ EOF
 
     echo "  ... cache deltas locally (in case of screw up)"
     mv ${deltafile} ${WOV_BASEDIR}/wovtools/cache/db/$1.${WOV_PVER}.$(date +%s).deltas
+
+
+    # - 2.1 save schema ---------------------------------------------------
+    # --------------------------------------------------------------------- 
+    mkdir -p ${WOV_BASEDIR}/wovtools/db/registry/$1/schemas
+    wov-db-connect ${1} --schema > ${WOV_BASEDIR}/wovtools/db/registry/$1/schemas/${WOV_PVER}.schema
+    if [ "$?" != "0" ]; then
+      printf "\n\nERROR: failed to write schemas to regsitry.\n\n"
+      exit 1
+    fi
 
 
     # - 3. update db registry entry for this pver -------------------------
@@ -422,6 +441,10 @@ while [[ $1 =~ ^- ]]; do
     shift
     DOECHO=2
 
+  elif [ "$1" == "--log" ]; then
+    DOACTION="log"
+    shift
+
   elif [ "$1" == "--checksum" ]; then
     shift
     DOACTION="checksum"
@@ -460,10 +483,28 @@ if [ "$DOACTION" == "check" ]; then
   done
   # printf "\nAny blockage to pushing?:$R1\n\n"
 
+elif [ "$DOACTION" == "log" ]; then
+  DATABASES=( $(doFindDatabases $*) )
+
+  # check each db
+  retval=0
+  for i in "${DATABASES[@]}"; do
+    r=${?}
+    if [ "$r" != "0" ]; then retval=1; fi
+    LLE=$(doGetDBLastLogEntry $i)
+    r=${?}
+    if [ "$r" != "0" ]; then retval=1; fi
+    DBVER=$(doGetDBPVER $i)
+    r=${?}
+    if [ "$r" != "0" ]; then retval=1; fi
+    set +x
+    echo "$i : ${DBVER} : ${CHKSUM} : ${LLE}"
+  done
+
 elif [ "$DOACTION" == "checksum" ]; then
 
   DATABASES=( $(doFindDatabases $*) )
-  #echo "DATABASES: ${DATABASES[@]}"
+  echo "DATABASES: ${DATABASES[@]}"
 
   # check each db
   retval=0
diff --git a/bin/wov-db-connect b/bin/wov-db-connect
--- a/bin/wov-db-connect
+++ b/bin/wov-db-connect
@@ -177,11 +177,12 @@ done
 
 
 # Check vh pod exists
-wov-p vh >/dev/null
-if [ "$?" == "1" ]; then
-  printf "\n\nERROR: 'vh' has not been created. Run 'wov-vh -s'.\n\n"
-  exit 1
-fi
+# wov-p vh >/dev/null
+#kubectl get pods vh > /dev/null
+#if [ "$?" == "1" ]; then
+#  printf "\n\nERROR: 'vh' has not been created. Run 'wov-vh -s'.\n\n"
+#  exit 1
+#fi
 
 if [ "${DB_TYPE}" == "postgres" ]; then
 
diff --git a/bin/wov-deploy b/bin/wov-deploy
--- a/bin/wov-deploy
+++ b/bin/wov-deploy
@@ -1,6 +1,7 @@
 #!/usr/bin/env bash
 
 
+
 # --------------------------------------------------------------------- 
 # Import Env 
 # --------------------------------------------------------------------- 
@@ -26,6 +27,22 @@ K8SFILES=
 # Cache the current values
 WOV_CUR_PVER=${WOV_PVER}
 WOV_CUR_SVER=${WOV_SVER}
+
+
+# --------------------------------------------------------------------- 
+# test if string in array : 1 is yes, 0 is no
+#  ex. 
+# arr=( "A" "B" "a" "b" )
+# containsElement "a" "${arr[@]}"  # $? is 1
+# containsElement "c" "${arr[@]}"  # $? is 0
+# --------------------------------------------------------------------- 
+function containsElement () 
+{
+  local e match="$1"
+  shift
+  for e; do [[ "$e" == "$match" ]] && return 1; done
+  return 0
+}
 
 
 # --------------------------------------------------------------------- 
@@ -105,16 +122,23 @@ function doDeployK8s()
 
   if [ "$#" != "0" ]; then
     K8SFILES=( $* )
-    for f in "${K8SFILES[@]}"; do
-      if [ ! -e ${DEPLOYDIR}/k8s/$f.yaml ]; then
-        printf "ERROR: unknown k8s file '$f.yaml'.\n"
-      else
-        kubectl apply -f ${DEPLOYDIR}/k8s/$f.yaml
-      fi
-    done
   else
-    kubectl apply -f ${DEPLOYDIR}/k8s
+    K8SFILES=( $(cd ${DEPLOYDIR}/k8s/ && ls * | sed -e 's/\(.*\)\..*/\1/') )
   fi
+
+  # printf "K8S FILES: ${K8SFILES[*]}"
+
+  for f in "${K8SFILES[@]}"; do
+    if [ ! -e ${DEPLOYDIR}/k8s/$f.yaml ]; then
+      printf "ERROR: unknown k8s file '$f.yaml'.\n"
+
+    # NOTE: using ^ and $ for exact match of string
+    elif [ "$(jq '.nodeploy[] | test("'"^${f}$"'")' wovtools/config.json)" == "true" ]; then
+      printf "...skipping '$f': as it is on the nodeploy list in wovtools/config.json\n"
+    else
+      kubectl apply -f ${DEPLOYDIR}/k8s/$f.yaml
+    fi
+  done
 }
 
 
@@ -237,7 +261,7 @@ if [ "${WOV_CUR_PVER}" != "${WOV_PVER}" ] || [ "${WOV_CUR_SVER}" != "${WOV_SVER}
 fi
 printf "\n"
 
-printf " check : pver : ${WOV_PVER}   sver: ${WOV_SVER}\n"
+# printf " check : pver : ${WOV_PVER}   sver: ${WOV_SVER}\n"
 
 
 # If deploying the latest PVER, check that all code is pushed to archive
@@ -248,7 +272,7 @@ if [ "${WOV_CUR_PVER}" == "${WOV_PVER}" ]; then
   R2=$?
   if [ "$R1" != "0" ] || [ "$R2" != "0" ]; then exit 1; fi
 fi
-printf " check : pver : ${WOV_PVER}   sver: ${WOV_SVER}\n"
+#printf " check : pver : ${WOV_PVER}   sver: ${WOV_SVER}\n"
 
 # If deploying the latest SVER, check that all env is pushed to archive
 if [ "${WOV_CUR_SVER}" == "${WOV_SVER}" ]; then
@@ -259,7 +283,7 @@ if [ "${WOV_CUR_SVER}" == "${WOV_SVER}" ]; then
   wov-push-env -q
 fi
 
-printf " check : pver : ${WOV_PVER}   sver: ${WOV_SVER}\n"
+# printf " check : pver : ${WOV_PVER}   sver: ${WOV_SVER}\n"
 
 ARCHBASE=${WOV_PROJECT}/${WOV_STAGE}/${WOV_PVER}_${WOV_SVER}
 
@@ -273,14 +297,14 @@ mkdir -p ${DEPLOYDIR}/k8s
 chmod -R 700 ${DEPLOYDIR}
 
 
-printf " check : pver : ${WOV_PVER}   sver: ${WOV_SVER}\n"
+# printf " check : pver : ${WOV_PVER}   sver: ${WOV_SVER}\n"
 
 # --------------------------------------------------------------------- 
 # Pull env files
 aws s3 sync ${WOV_ARCHIVEENV}/${ARCHBASE}/conf ${DEPLOYDIR}/conf  --delete
 aws s3 sync ${WOV_ARCHIVEENV}/${ARCHBASE}/k8s ${DEPLOYDIR}/k8s  --delete
 
-printf " check : pver : ${WOV_PVER}   sver: ${WOV_SVER}\n"
+# printf " check : pver : ${WOV_PVER}   sver: ${WOV_SVER}\n"
 
 if [ "${DRYRUN}" == "0" ]; then 
   if [ "${CONFONLY}" == "1" ]; then
diff --git a/bin/wov-env b/bin/wov-env
--- a/bin/wov-env
+++ b/bin/wov-env
@@ -61,6 +61,7 @@ usage: `basename $0` [options]
   --qcmd X     :   ", quoted
   --sl X       :   ", string literal output
   --rcAWS      : convert a region code to an AWS code (ex. va-> us-east-1)
+  -c           : run cluster config as well
 
 Example Usage:
   `basename $0`    : sets all environment variables
@@ -110,6 +111,15 @@ export WOV_USEREMAIL
 #A=( `jq -r ". | ( .rootdir, .srcdir, .secretsdir, .compileddir, .containerdir, .registry, .wovtools )" ${dir_wovtools_rc}/.wovtools.json` )
 #echo "A:${A[*]}:A"
 #dir_root="${A[0]}"
+
+
+WOV_ME=$(cat ${HOME}/.wovtools | jq -r '.me')
+if [ "${WOV_ME}" == "null" ] ; then
+  printf "\n\nERROR: You need to set 'me' in the wovtools/config.json file.\n"
+  printf "  - This is a unique code in this project, to represent yourself. Try using your initials (assuming they are unique to your team).\n\n"
+  exit 1
+
+fi
 
 WOV_PVERSION=$(cat ${WOV_BASEDIR}/wovtools/config.json | jq -r '.ver')
 if [ "${WOV_PVERSION}" != "${WOV_VERSION}" ] && [ "${WOV_PVERSION}" != "initing" ] ; then
@@ -170,6 +180,7 @@ export WOV_KSTAGE
 function fDoEcho() 
 {
   echo WOV_VERSION="${WOV_VERSION}"
+  echo WOV_ME="${WOV_ME}"
   echo WOV_BASEDIR="${WOV_BASEDIR}"
   echo WOV_SECRETFILE="${WOV_SECRETFILE}"
   echo WOV_ARCHIVEREPOSITORY="${WOV_ARCHIVEREPOSITORY}"
@@ -208,6 +219,7 @@ function fDoEcho()
 function fDoBashEcho() 
 {
   printf "WOV_VERSION=\"${WOV_VERSION}\" "
+  printf "WOV_ME=\"${WOV_ME}\" "
   printf "WOV_BASEDIR=\"${WOV_BASEDIR}\" "
   printf "WOV_ARCHIVEREPOSITORY=\"${WOV_ARCHIVEREPOSITORY}\" "
   printf "WOV_ARCHIVEENV=\"${WOV_ARCHIVEENV}\" "
@@ -342,6 +354,7 @@ function fConvertRegionCodeAWS()
 {
   case $1 in
     va) cRC='us-east-1' ;;
+    iad) cRC='us-east-1' ;;
     *)
       echo
       echo "***ERROR: unknown AWS region code of '$1'."
diff --git a/bin/wov-pwait b/bin/wov-pwait
--- a/bin/wov-pwait
+++ b/bin/wov-pwait
@@ -4,6 +4,8 @@ JUSTCHECK=0
 WAITTIME=3
 WAITFIRST=0
 NAMESPACE=
+PODSTEM=0
+  # 1 if this looks by stem, 
 
 
 function fDoDisplay()
@@ -12,16 +14,17 @@ function fDoDisplay()
 
 usage: `basename $0` [options] ([podname] ...)
 
-Waits for a pod to enter the running state, by continuous polling. 
+Waits for a pod (full name) to enter the running state, by continuous polling. 
 
   -h|--help : Display this help.
   -f|--first : initial time to wait before polling, otherwise standard
   -w|--wait  : wait time in seconds between polling (default=3)
+  --stem    : look up the pod names by their stem
   -n|--namespace : search for pod in namespace
   -j|--just-check : check if pod is ready
   -c : NOT IMPLEMENTED - wait for cluster to come online
 
-Pod names are matched to the stem, so the full name is not necessary. 
+Pod names are matched to the stem if --stem is used, so the full name is not necessary. 
    ex. 'plfb-mongodb-384393937-hdfk' is matched by 'plfb-mongodb'
 
 EOF
@@ -45,6 +48,10 @@ while [[ $1 =~ ^- ]]; do
   elif [ "$1" == '-c' ] || [ "$1" == '--cluster' ]; then
     fDoCluster
     shift
+  elif [ "$1" == '--stem' ]; then
+    PODSTEM=1
+    shift
+
   elif [ "$1" == '-n' ] || [ "$1" == '--namespace' ]; then
     shift
     NAMESPACE=" -n $1 "
@@ -65,7 +72,16 @@ done
 first=1
 for p in $*; do
 
-  podname=`wov-p $NAMESPACE $p`
+  if [ "$PODSTEM" == "1" ]; then
+    podname=`wov-p $NAMESPACE $p`
+    if [ "$?" != "0" ]; then
+      printf "\n\nERROR: unable to find pod with that stem '${p}'.\n"
+      exit 1
+    fi
+
+  else
+    podname=$p
+  fi
   stat=`kubectl describe $NAMESPACE pods $podname | grep "^Status" | awk '{print $2}'`
 
   if [ "$JUSTCHECK" == "1" ]; then
