Fixed push of k8s.
- validate exported yaml for wov-compile
- wov-push-k8s was checking wrong directories... fixed

diff --git a/bin/wov-env-build b/bin/wov-env-build
--- a/bin/wov-env-build
+++ b/bin/wov-env-build
@@ -516,6 +516,13 @@ fBuildClusterDir()
         #      echo "SHOULD CALL: wov-compile ${SECRETFILE} ${SRC} > ${DEST}"
         # echo "{\"MS\" : \"${ms}\"}"
         wov-compile -d "{\"MS\" : \"${MS}\"}" ${SECRETFILE} ${SRC} > ${DEST}
+
+        # validate output
+        python -c 'import yaml, sys; yaml.safe_load(sys.stdin)' < ${DEST}
+        if [ $? != 0 ]; then
+          echo "WARNING: generated invalid yaml: ${DEST} from ${SRC}"
+        fi
+
       else
         if [ "$DOECHO" == "2" ]; then echo "  ... skipping ${SRC}"; fi
       fi
