Lots of changes.
The bigged change is stage modifiers. Most everything else is related to
this in one way or another (or just a bug fix). I think I call them
devmodes in the code but this will be changed. Checking in the code now
as I am going to fix this code to make it more granular.

Major:
* introduced stage modifiers. the allow local development of a
microservice with the effect of being in the cluster. It port forwards
necessary ports into the cluster (i.e. other microservices or
databases). With this, a microservice can pull information from a
running system and you can overserve how it reacts.
  * The magic of getting this to work is how it overwrites configuration
  information in the build stage. So. a configuration of "plugin.STAGE.url" would point
  to something in the cluster. When switching to local, the wov-build
  script finds the modifiers for "plugin.STAGE-local.url" and overwrites
  the value. This adds some non-insignificant additional overhead in time. It is also nice because I can write configuration information for local operation right next to the other configuration information in the file.
  * However, the limitation is you can't port forward from
other microservices to this microservice (lots of discussion about this
online because why the fudge didn't they allow this? (I know...
security).
  * not granular enough though, since I need to work local on one microservice but remote on others. this manages the port forwarding through scripts for now.
  * this should make testing MUCH easier to accomplish however in a more
scriptable form.
  * the other problem is changing modes causes git changes, causing a
  new push and a new deploy... very annoying. So, introducing a new
  config_local.json file next, where local changes are placed that are
  not tracked by git. This will undoubtedly be used by other scripts in
  time.
  * created a process to manage portforwards on the localhost... needed
  for when you toggle devmodes.

Other Changes:
* fixed some issues with scripts rewriting global vars when other
scripts are run in hte same namespace
* ignore namespace added to some scripts (helpful for working between
    namespaces)
* bug fix for push scripts that broke pushes when AWS keys were outdated
* added mongodb to the wov-db-connect script... so to my scripts,
  postgres and mongodb look the same
* Can deploy only certain microservices now, instead of multiple
* Huge bug in ConfigMap/Secret creation that I have no idea how it was
working beforehand. Bash crap and quoting was to blame.
* wov-ed can open a editor in new window now with -x switch
* added more attributes to deployments so they are clearer what version
the deployment is. wov-ns now shows lables.
* GREATLY sped up wov-push. It was taking, on a very good internet
connection, an additional 30 seconds (several minutes at Panera). Now,
it gets it down to about 20 seconds total, 10 seconds being network
delays. much less disruptive to development.

diff --git a/bin/wov-cd b/bin/wov-cd
--- a/bin/wov-cd
+++ b/bin/wov-cd
@@ -4,8 +4,7 @@ DOECHO=1
 FOLD=140
 
 if [ ! -e ${HOME}/.wovtools ]; then 
-  printf "\n\nERROR: no .wovtools file in home directory.\n"
-  exit 1
+  printf "\n\nERROR: no .wovtools file in home directory.\n" 1>&2
 fi
 
 if [ "$#" == 1 ]; then
@@ -13,26 +12,27 @@ if [ "$#" == 1 ]; then
   P=$(echo $1 | cut -d'/' -f1)
   D=$(jq -r ".projects.$P.dir" ${HOME}/.wovtools 2> /dev/null)
   if [ "$?" != "0" ]; then
-    printf "\nERROR: json related error. Check your ~/.wovtools file.\n";
-    printf " - $(jq -r ".projects.$P.dir" ${HOME}/.wovtools 2>&1)\n"
+    printf "\nERROR: json related error. Check your ~/.wovtools file.\n" 1>&2
+    printf " - $(jq -r ".projects.$P.dir" ${HOME}/.wovtools 2>&1)\n" 1>&2
   else
     if [ "$D" == "null" ]; then 
-      printf "\n\nERROR: no project entry of '$P'.\n"
+      printf "\n\nERROR: no project entry of '$P'.\n" 1>&2
     else
       D1=( ${1//\// } )
       D1=( "${D1[@]:1:}" )
       GO="$D$D1"
       if [ ! -e "${D}${D1}" ]; then
-        printf "\n\nERROR: no directory '$D$D1'.\n"
+        printf "\n\nERROR: no directory '$D$D1'.\n" 1>&2
       else
-        printf "project '$P' : $GO\n"
         cd $GO
+        printf "\n---- project '$P' : $GO\n"
+        sleep .5
+        ls
       fi
     fi
   fi
 else
-  printf "\n\nERROR: bad number of parameters. Requires a project name.\n"
-  exit 1
+  printf "\n\nERROR: bad number of parameters. Requires a project name.\n" 1>&2
 fi
 
 
diff --git a/bin/wov-push b/bin/wov-push
--- a/bin/wov-push
+++ b/bin/wov-push
@@ -20,12 +20,25 @@ set ""
 set -- "${pushargs[@]}"
 
 
+if [ "$WOV_DEVMODE" != "remote" ]; then
+  printf "\nERROR: Can not push when is devmode '${WOV_DEVMODE}'. Run 'wov-env --remote'.\n\n"
+  exit 1
+fi
+
+printf "\n"
+figlet wov-push
+printf " version: ${WOV_STAGE}_${WOV_PVER}_${WOV_SVER}\n\n"
+
+
 # Check local code is checked in and pushed
 wov-git-check ${WOV_BASEDIR}
 R1=$?
 wov-git-check ${WOV_BASEDIR}/wovtools/secrets
 R2=$?
-if [ "$R1" != "0" ] || [ "$R2" != "0" ]; then exit 1; fi
+if [ "$R1" != "0" ] || [ "$R2" != "0" ]; then 
+  printf "\nERROR: wov-push exiting\n" 1>&2
+  exit 1
+fi
 echo "  ... check for database changes that could block the push"
 wov-db-commit --any-push-blockage
 R3=$?
diff --git a/bin/wov-push-containers b/bin/wov-push-containers
--- a/bin/wov-push-containers
+++ b/bin/wov-push-containers
@@ -23,7 +23,10 @@ wov-git-check ${WOV_BASEDIR}
 R1=$?
 wov-git-check ${WOV_BASEDIR}/wovtools/secrets
 R2=$?
-if [ "$R1" != "0" ] || [ "$R2" != "0" ]; then exit 1; fi
+if [ "$R1" != "0" ] || [ "$R2" != "0" ]; then 
+  printf "\nERROR: wov-push-containers exiting\n" 1>&2
+  exit 1;
+fi
 
 
 
@@ -140,7 +143,7 @@ if [ "${BLOCK}" == "0" ]; then
 
       wov-pushcontainer-check ${f}
       NEEDSBUILD=$?
-#      echo "NEEDSBUILD: ${NEEDSBUILD}"
+      #echo "NEEDSBUILD: ${NEEDSBUILD}"
       # printf "\n\n\n\nNEEDSBUILD: $NEEDSBUILD\n\n\n"
       #    echo "NEEDSBUILDOUT: $NEEDSBUILDOUT"
       #    if [ ${NEEDSBUILD} == 1 ] || [ $DOFORCE == 1 ]; then
@@ -186,6 +189,8 @@ if [ "${BLOCK}" == "0" ]; then
         echo "    ... archiving build of container '${CONTAINER}'"
         mkdir -p ${ARCHDIR}
         rsync -ai --delete ${DESTDIR}/ ${ARCHDIR} &> /dev/null
+      else
+        echo "    ... skipping container creation"
       fi
 
 
@@ -201,10 +206,10 @@ if [ "${BLOCK}" == "0" ]; then
           R=$(docker push ${WOV_ARCHIVEREPOSITORY}/${WOV_PROJECT}/${CONTAINER}:${WOV_STAGE}_${WOV_PVER} 2>&1 | tee /dev/tty )
           RR=$?
         else
-          R=$(docker push ${WOV_ARCHIVEREPOSITORY}/${WOV_PROJECT}/${CONTAINER}:${WOV_STAGE}_${WOV_PVER} 2> /dev/null )
+          R=$(docker push ${WOV_ARCHIVEREPOSITORY}/${WOV_PROJECT}/${CONTAINER}:${WOV_STAGE}_${WOV_PVER} 2>&1 )
           RR=$?
         fi
-#        echo "R: ${R}"
+        # echo "R: ${R} RR=${RR}"
         if [[ $R == 'name unknown'* ]]; then
           printf "\n\n  ...${R}.\n"
           exit 1
@@ -228,8 +233,9 @@ if [ "${BLOCK}" == "0" ]; then
         fi
 
       else
-        echo "    ... skipping build of container '${CONTAINER}'"
+        echo "    ... skipping build and pushing of container '${CONTAINER}'"
       fi
+      echo "  ... done '${CONTAINER}'."
     fi
 
 
