Created pushcontainer-check to see if the current container needs to be built.
Since changes to some code could not lead to changes in container
code (ex. K8s files for example), then the PVER could increment (i.e a
git commit) but no container built and labeled in the remote repo. So,
this checks for remote container existence.

NOTE: this ONLY works for AWS repos... bummer.
NOTE2: don't really need to rebuild the container, which this will do,
  since the code didn't change. Docker will see no difference anyway and
  just apply a different label. In the future, could make two calls
  before building to prevent an unnecessary build.

diff --git a/bin/wov-push b/bin/wov-push
--- a/bin/wov-push
+++ b/bin/wov-push
@@ -1,6 +1,73 @@
 #!/usr/bin/env bash
 
+DOECHO=1
+DOFORCE=0
+FOLD=80
+BLOCK=0
 
+# ---------------------------------------------------------------------
+# Import Env
+# ---------------------------------------------------------------------
+pushargs=( "$@" )
+set ""
+. wov-env
+. wov-ns-check
 . wov-pushcode-check
-. wov-push-containers
-. wov-push-env
+set -- "${pushargs[@]}"
+
+
+
+# ---------------------------------------------------------------------
+# ---------------------------------------------------------------------
+function fDisplayOptions()
+{
+  cat <<EOF | fold -w ${FOLD} -s
+
+
+usage: `basename $0` [options]
+
+Macro command that pushes containers, then env. It uses:
+   wov-push-containers
+   wov-push-env
+
+  -h : this help
+  -q/-v : quiet/verbose
+
+EOF
+}
+
+METAARGS=""
+
+# ---------------------------------------------------------------------
+# Handle Params
+# ---------------------------------------------------------------------
+while [[ $1 =~ ^- ]]; do
+
+  if [ "$1" == "-q" ]; then
+    shift
+    DOECHO=0
+    METAARGS="${METAARGS} -q "
+
+  elif [ "$1" == "-v" ]; then
+    shift
+    DOECHO=2
+    METAARGS="${METAARGS} -v "
+
+
+  elif [ "$1" == "-h" ] || [ "$1" == "--help" ]; then
+    fDisplayOptions
+    exit 0
+
+  else
+    echo
+    echo "***ERROR: unknown option '$1'."
+    echo
+    fDisplayOptions
+    exit 1
+  fi
+done
+
+
+set -x
+wov-push-containers ${METAARGS}
+wov-push-env ${METAARGS}
