Wov-push-db works.
- Created a common wov-db-common file: for doFindDatabases function
- wov-env-common - made sure 'localhost' databases return 'localhost', not CLUSTER-db-localhost
- wov-cluster-createdb
  - I found the command to create the database, and it probably works, but I did not use it, just print it.
  - added a command to init the db.
- wov-db-clout - deprecated the file, moving all functionality into wov-db-connect
-wov-db-connect
  - added : --data-reload, --info, --list
  - added DB management commands for --db-init, --db-ver, --db-wait, --db-log
  - --db-init is a pretty important command
  - fixed --data-full so it launches the correct version of postgres locally
- wov-push-db
  - lots of corrections
  - can set snapshots to apply
  - handles first commit of database as opposed to erroring out
  - added validation checks on the DB archive json file before pushing
  - snapshots committed to DB log now, not just json file

diff --git a/bin/wov-cluster-createdb b/bin/wov-cluster-createdb
--- a/bin/wov-cluster-createdb
+++ b/bin/wov-cluster-createdb
@@ -28,6 +28,13 @@ WOV_DB_database="WOV_${1}_database" ; WOV_DB_database=${!WOV_DB_database}
 WOV_DB_version="WOV_${1}_version" ; WOV_DB_version=${!WOV_DB_version}
 WOV_DB_instance_class="WOV_${1}_instance_class" ; WOV_DB_instance_class=${!WOV_DB_instance_class}
 WOV_DB_instance_storage="WOV_${1}_instance_storage" ; WOV_DB_instance_storage=${!WOV_DB_instance_storage}
+aws_zones=( ${AWS_ZONES} )
+
+DVPCID=`aws ec2 describe-vpcs --filters "Name=tag-key, Values=Name, Name=tag-value, Values=default" | jq -r ".Vpcs[].VpcId"`
+if [ "$?" != "0" ]; then echo "\nERROR: failed to find default VPC.\n"; exit 1; fi
+
+DBSG_GroupId=$(aws ec2 describe-security-groups --filters "Name=tag:KubernetesCluster,Values=${WOV_CLUSTER}.${WOV_cluster_dns_domain}" --filters "Name=vpc-id,Values=${DVPCID}" --group-names "${DBSG}" 2> /dev/null |  jq -r ".SecurityGroups[].GroupId") ; DBSG_GroupIde=$?
+if [[ ${DBSG_GroupIde} -ne 0 ]]; then printf "\n\nERROR: failed to query the security group.\n"; exit 1; fi
 
 cat <<EOF
 
@@ -65,7 +72,31 @@ This is a manual process, so follow these steps:
  IAM DB Authentication - disabled
 
 
-3) Bastion configuration:
+aws rds create-db-instance \
+    --db-instance-identifier ${DB} \
+    --allocated-storage ${WOV_DB_instance_storage} \
+    --db-instance-class ${WOV_DB_instance_class} \
+    --engine ${WOV_DB_type} \
+    --engine-version ${WOV_DB_version} \
+    --backup-retention-period 7 \
+    --master-username ${WOV_DB_username} \
+    --no-publicly-accessible \
+    --master-user-password ${WOV_DB_password} \
+    --db-subnet-group-name ${DBSNG} \
+    --vpc-security-group-ids  ${DBSG_GroupId} \
+    --availability-zone ${AWS_REGION}${aws_zones[0]} \
+    --storage-type gp2 \
+    --storage-encrypted \
+    --deletion-protection
+
+3) Init Database
+--------------------------------------------------
+
+  wov-db-connect -I
+
+
+
+4) Bastion configuration:
 --------------------------------------------------
   You should add a line to ~/.ssh/config, to your bastion host entry:
 EOF
diff --git a/bin/wov-db-connect b/bin/wov-db-connect
--- a/bin/wov-db-connect
+++ b/bin/wov-db-connect
@@ -9,6 +9,7 @@ pushdbenvargs=( "$@" )
 set ""
 . <(wov-env --exports -e)
 . wov-env-common
+. wov-db-common
 set -- "${pushdbenvargs[@]}"
 
 DOECHO=1
@@ -19,6 +20,9 @@ DB_OP=
 DB_FILE=
 
 DB_HEADEROPTIONS=
+
+
+
 
 # ---------------------------------------------------------------------
 # ---------------------------------------------------------------------
@@ -40,6 +44,7 @@ DBSERVER - the name of a database server in the project (created via wov-cluster
   -c [command]  : run a DB command
   -f [file]     : load file of SQL commands into a DB
   --schema      : return the DB's schema
+  --info        : reports about the database
 
  Data Mods:
   -d [database] : changes the database name (DB inside the DB server)
@@ -50,12 +55,19 @@ DBSERVER - the name of a database server in the project (created via wov-cluster
   --data-schema/-ds : reloads the database schema (clearing existing data)
   --data-clear/-dc  : clears data in the database
   --data-data/-dd   : loads the database data
+  --data-reload/-dr : reloads the database data (clear and data)
   --data-full/-df   : loads a full DataSet by loading schema, clear and load data
 
  Local Postgres via Docker:
   --docker-postgres-start : start a local Postgres database via Docker
   --docker-postgres-stop  : stop a local Postgres database in Docker
 
+ DB Management: (note: change namespace or turn off local to change databases)
+  --db-init    : initialize the database for WovTools
+  --db-ver     : returns the current 
+  --db-log     : returns the log of commits for the database
+  --db-wait    : wait for a database to come online after creation
+  -l/--list       : list all databases
 
 NOTE:
 About commands (-c)... you have to be careful about quotes as both bash and psql are very particular. Here, use single quotes so '*' is not expanded, and quote the single quote so mydatabase is interpret properly by postgres.
@@ -65,8 +77,17 @@ ex. -c 'SELECT * FROM logs WHERE database=\'mydatabase\' ORDER BY id DESC LIMIT 
 EOF
 }
 
+# ---------------------------------------------------------------------
+# ---------------------------------------------------------------------
+function doDBList()
+{
+  local DATABASES=( $(doFindDatabases) )
+  echo "${DATABASES[@]}"
+}
+
 # Help command catch here
 if [ "$1" == "-h" ] || [ "$1" == "--help" ]; then fDisplayOptions; exit 0; fi
+if [ "$1" == "-l" ] || [ "$1" == "--list" ]; then doDBList; exit 0; fi
 
 
 # Set the default commands
@@ -83,34 +104,53 @@ shift
 # --------------------------------------------------------------------- 
 # Set config from env vars and project type
 # --------------------------------------------------------------------- 
-DB_TYPE=WOV_${DATABASESERVER}_type
-DB_DATABASE=WOV_${DATABASESERVER}_database
-DB_USERNAME=WOV_${DATABASESERVER}_username
-DB_PASSWORD=WOV_${DATABASESERVER}_password
-DB_HOST=WOV_${DATABASESERVER}_host
-DB_PORT=WOV_${DATABASESERVER}_port
+doSetDBData()
+{
+  DB_SUBHOST=WOV_${DATABASESERVER}_subhost
+  DB_TYPE=WOV_${DATABASESERVER}_type
+  DB_DATABASE=WOV_${DATABASESERVER}_database
+  DB_USERNAME=WOV_${DATABASESERVER}_username
+  DB_PASSWORD=WOV_${DATABASESERVER}_password
+#  DB_HOST=WOV_${DATABASESERVER}_host
+  DB_HOST=localhost
+  DB_PORT=WOV_${DATABASESERVER}_port
+  DB_INSTANCEAVAILABILITYZONE=WOV_${DATABASESERVER}_instanceAvailabilityZone
+  DB_INSTANCEAVAILABILITYZONEALT=WOV_${DATABASESERVER}_instanceAvailabilityZoneAlt
+  DB_INSTANCE_CLASS=WOV_${DATABASESERVER}_instance_class
+  DB_INSTANCE_STORAGE=WOV_${DATABASESERVER}_instance_storage
+  DB_VERSION=WOV_${DATABASESERVER}_version
 
-DB_HEADEROPTIONS=-t
+  DB_HEADEROPTIONS=-t
 
-## if in Plugin and using default database, default to the mongodb
-#if [[ ( "$DATABASESERVER" == "" ) || ( "$DATABASESERVER" == "${WOV_PROJECT}db" ) ]] && [[ "${WOV_PROJECTTYPE}" == "pl" ]]; then
-#  # echo "...defaulting to plugin mongodb."
-#  DB_TYPE=WOV_we_db_type
-#  DB_DATABASE=WOV_we_db_collection
-#  DB_USERNAME=WOV_we_db_user
-#  DB_PASSWORD=WOV_we_db_password
-#  DB_HOST=WOV_we_db_url
-#  DB_PORT=WOV_we_db_port
-#  DATABASESERVER=${WOV_PROJECT}db
-#fi
+  ## if in Plugin and using default database, default to the mongodb
+  #if [[ ( "$DATABASESERVER" == "" ) || ( "$DATABASESERVER" == "${WOV_PROJECT}db" ) ]] && [[ "${WOV_PROJECTTYPE}" == "pl" ]]; then
+  #  # echo "...defaulting to plugin mongodb."
+  #  DB_TYPE=WOV_we_db_type
+  #  DB_DATABASE=WOV_we_db_collection
+  #  DB_USERNAME=WOV_we_db_user
+  #  DB_PASSWORD=WOV_we_db_password
+  #  DB_HOST=WOV_we_db_url
+  #  DB_PORT=WOV_we_db_port
+  #  DATABASESERVER=${WOV_PROJECT}db
+  #fi
 
-# Set variables to values of the name
-DB_TYPE=${!DB_TYPE}
-DB_DATABASE=${!DB_DATABASE}
-DB_USERNAME=${!DB_USERNAME}
-DB_PASSWORD=${!DB_PASSWORD}
-DB_HOST=${!DB_HOST}
-DB_PORT=${!DB_PORT}
+  # Set variables to values of the name
+  DB_SUBHOST=${!DB_SUBHOST}
+  DB_TYPE=${!DB_TYPE}
+  DB_DATABASE=${!DB_DATABASE}
+  DB_USERNAME=${!DB_USERNAME}
+  DB_PASSWORD=${!DB_PASSWORD}
+#  DB_HOST=${!DB_HOST}
+  DB_PORT=${!DB_PORT}
+  DB_INSTANCEAVAILABILITYZONE=${!DB_INSTANCEAVAILABILITYZONE}
+  DB_INSTANCEAVAILABILITYZONEALT=${!DB_INSTANCEAVAILABILITYZONEALT}
+  DB_INSTANCE_CLASS=${!DB_INSTANCE_CLASS}
+  DB_INSTANCE_STORAGE=${!DB_INSTANCE_STORAGE}
+  DB_VERSION=${!DB_VERSION}
+}
+
+# 1st call
+doSetDBData
 
 
 # NOTE: using bastion so this overrides cluster settings
@@ -215,6 +255,138 @@ function setAsAdmin()
 
 
 # ---------------------------------------------------------------------
+# ---------------------------------------------------------------------
+function doDBInit()
+{
+  mkdir -p ${WOV_BASEDIR}/wovtools/db/archive
+
+  # Create 'wovtools' database in db server if it does not exist
+  export PGPASSWORD=${DB_PASSWORD}
+  psql -h localhost -U ${DB_USERNAME} -tc "SELECT 1 FROM pg_database WHERE datname = 'wovtools'" | grep -q 1 || psql -U ${DB_USERNAME} -h localhost -c "CREATE DATABASE wovtools"
+
+  # in 'wovtools', create the logs table, and insert a row
+  psql -U ${DB_USERNAME} -h localhost -d wovtools -tc "CREATE TABLE IF NOT EXISTS logs (id SERIAL NOT NULL PRIMARY KEY, database varchar, wovtoolsver varchar, label varchar, pver integer, sver integer, snapshot varchar, schema varchar DEFAULT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW() );"
+
+  # first delta is that it exists
+  cat <<EOF >> ${WOV_BASEDIR}/wovtools/db/${DATABASESERVER}.deltas
+# ---------------------------------------------------------------------
+# doInitDB called for: ${DATABASESERVER}
+# ---------------------------------------------------------------------
+# 1) create wovtools database if not exist
+# 2) create the logs database in wovtools
+# ---------------------------------------------------------------------
+EOF
+
+  # Init the archive for it
+  if [ ! -e "${WOV_BASEDIR}/wovtools/db/archive/${DATABASESERVER}.json" ]; then
+    cat <<EOF >> ${WOV_BASEDIR}/wovtools/db/archive/${DATABASESERVER}.json
+{
+  "wovtoolsversion": "0",
+  "versions": {}
+}
+EOF
+  fi
+
+}
+
+
+# ---------------------------------------------------------------------
+# returns 0 on success
+# ---------------------------------------------------------------------
+function doDBGetVer()
+{
+  local retval=1
+
+  R=$(PGPASSWORD=${DB_PASSWORD} psql -h localhost -d wovtools -U ${DB_USERNAME} --tuples-only -c "SELECT * from logs order by id DESC limit 1;" 2> /dev/null ) ; Re=$?
+  if [ ${Re} == "0" ] ; then
+    if [ "${R}" == "" ]; then echo "None"; 
+    else 
+      echo "${R}" | cut -d'|' -f5 | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//'
+    fi
+    retval=0
+  else
+    echo "Uninited"
+  fi
+
+  return $retval
+}
+
+
+# ---------------------------------------------------------------------
+# returns 0 on success
+# ---------------------------------------------------------------------
+function doDBGetLog()
+{
+  local retval=1
+
+  R=$(PGPASSWORD=${DB_PASSWORD} psql -h localhost -d wovtools -U ${DB_USERNAME} --tuples-only -c "SELECT * from logs order by id DESC;" 2> /dev/null ) ; Re=$?
+  if [ ${Re} == "0" ] ; then
+    if [ "${R}" == "" ]; then echo "None"; 
+    else echo $R; fi
+    retval=0
+  else
+    echo "Uninited"
+  fi
+
+  return $retval
+}
+
+
+# ---------------------------------------------------------------------
+# ---------------------------------------------------------------------
+function doInfo()
+{
+#  . <(wov-env -c wov-aws-va-grape --exports)
+#  doSetDBData
+
+  cat <<EOF
+
+DB Information
+---------------------------------------------------------------------
+  AWS Server : $(doResName DB ${WOV_CLUSTER} ${DB_SUBHOST}):${DB_PORT}
+    Database : ${DB_DATABASE}  User: ${DB_USERNAME} PASSWORDXXX
+        Type : ${DB_TYPE} ${DB_VERSION}, ${DB_INSTANCE_STORAGE} GB, ${DB_INSTANCE_CLASS}, zones: ${AWS_REGION}${DB_INSTANCEAVAILABILITYZONE} ${AWS_REGION}${DB_INSTANCEAVAILABILITYZONEALT}
+
+  WovTools Version: $(doDBGetVer)
+  
+EOF
+}
+
+
+# ---------------------------------------------------------------------
+# Wait for db to get address, meaning it is ready to go
+# $1=[dbname]
+# ---------------------------------------------------------------------
+function doDBWait()
+{
+
+  if [ "$1" == "localhost" ]; then
+    echo "ERROR: asking to wait for localhost database. Turn off local database in config/local.json secretsmods.local."
+    exit 1
+  fi
+
+  # check for existence
+  S=$(aws rds describe-db-instances --db-instance-identifier $(doResName DB ${WOV_CLUSTER} ${1}) --query 'DBInstances[0].Endpoint.Address' --output text) ; Se=$?
+  if [ $Se == 255 ]; then echo "ERROR: unknown database."; exit 1; fi
+
+
+  # wait for it to get an address
+  while [ "$(aws rds describe-db-instances --db-instance-identifier $(doResName DB ${WOV_CLUSTER} ${1}) --query 'DBInstances[0].Endpoint.Address' --output text)" == "None" ]; do
+    echo "    ... waiting for database to get address."
+    sleep 5
+  done
+
+  # wait for it to be available
+  while [ "$(aws rds describe-db-instances --db-instance-identifier $(doResName DB ${WOV_CLUSTER} ${1}) --query 'DBInstances[0].DBInstanceStatus' --output text)" != "available" ]; do
+    echo "    ... waiting for database to come online."
+    sleep 5
+  done
+}
+
+
+
+
+# ---------------------------------------------------------------------
 # Handle Params
 # ---------------------------------------------------------------------
 while [[ $1 =~ ^- ]]; do
@@ -231,6 +403,10 @@ while [[ $1 =~ ^- ]]; do
     shift
     read DB_PASSWORD
     shift
+
+  elif [ "$1" == "--info" ]; then
+    doInfo
+    exit 0
 
   elif [ "$1" == "--admin" ]; then
     shift
@@ -299,6 +475,14 @@ while [[ $1 =~ ^- ]]; do
     exit 0
     shift
 
+  elif [ "$1" == "--data-reload" ] || [ "$1" == "-dr" ]; then
+    shift
+    doDBDataBuild $1
+    doDBDataCommand $1 'clear'
+    doDBDataCommand $1 'data'
+    exit 0
+    shift
+
   elif [ "$1" == "--data-full" ] || [ "$1" == "-df" ]; then
     shift
     doDBDataBuild $1
@@ -313,7 +497,12 @@ while [[ $1 =~ ^- ]]; do
     pg_isready -p 5432 -h localhost 2>&1  > /dev/null
     A=$?
     if [ "$A" == "0" ]; then echo "ERROR: postgres already accepting connections. Try --docker-postgres-stop."; exit 1; fi
-    docker run --rm --name postgres-local -e POSTGRES_PASSWORD=${DB_PASSWORD} -d -p 5432:5432 postgres
+
+    # match major/minor versions
+    pgsplit=( $(echo $DB_VERSION | tr "." "\n") )
+    pgmajorminor="${pgsplit[0]}.${pgsplit[1]}"
+
+    docker run --rm --name postgres-local -e POSTGRES_PASSWORD=${DB_PASSWORD} -d -p 5432:5432 "postgres:${pgmajorminor}"
     I=0
     while [ "$(pg_isready -p 5432 -h localhost 2>&1 > /dev/null ; echo $?)" != "0" ]; do
       sleep 1 # sleep to account for time for it to spin up
@@ -329,6 +518,31 @@ while [[ $1 =~ ^- ]]; do
     shift
     docker stop postgres-local > /dev/null
     if [ "$?" == "0" ]; then echo "  ... success"; exit 0; fi
+    exit 0
+
+  elif [ "$1" == "--db-init" ]; then
+    shift
+    doDBInit
+    exit 0
+
+  elif [ "$1" == "--db-ver" ]; then
+    shift
+    doDBGetVer
+    exit 0
+
+  elif [ "$1" == "--db-log" ]; then
+    shift
+    doDBGetLog
+    exit 0
+
+  elif [ "$1" == "--db-wait" ]; then
+    shift
+    doDBWait ${DB_SUBHOST}
+    exit 0
+
+  elif [ "$1" == "-l" ] || [ "$1" == "--list" ]; then
+    shift
+    doDBList
     exit 0
 
   elif [ "$1" == "-H" ]; then
@@ -391,10 +605,16 @@ if [ "${DB_TYPE}" == "postgres" ]; then
 #      PGPASSWORD=${DB_PASSWORD} psql --tuples-only -h ${DB_HOST} -U ${DB_USERNAME} -d ${DB_DATABASE} -c \"${DB_COMMAND[@]}\"
 #    fi
 
-    PGPASSWORD="${DB_PASSWORD}" psql ${DB_HEADEROPTIONS} -p ${DB_PORT} -h ${DB_HOST} -U ${DB_USERNAME} -d ${DB_DATABASE} -c "${DB_COMMAND[*]}"
+    R=$(PGPASSWORD="${DB_PASSWORD}" psql ${DB_HEADEROPTIONS} -p ${DB_PORT} -h ${DB_HOST} -U ${DB_USERNAME} -d ${DB_DATABASE} -c "${DB_COMMAND[*]}"  2>&1 ) ; Re=$?
     #PGPASSWORD=${DB_PASSWORD} psql --tuples-only -p ${DB_PORT} -h ${DB_HOST} -U ${DB_USERNAME} -d ${DB_DATABASE} -c "${DB_COMMAND[*]}"
-    if [ "$?" != "0" ]; then
-      printf "\n\nERROR: could not connect... have you tunneled to the bastion server?\n\n"
+    if [ "${Re}" != "0" ]; then
+      if [ "$R" == "psql: FATAL:  database \"wovtools\" does not exist" ]; then
+        printf "\n${R}\nERROR: did you init the database? 'wov-db-connect ${DATABASESERVER} --db-init'\n"
+        exit 1
+      fi
+      printf "${R}\n"
+      printf "\n\nERROR(${Re}): could not connect... have you tunneled to the bastion server?\n\n"
+      exit 1
     fi
 
 
@@ -408,8 +628,9 @@ if [ "${DB_TYPE}" == "postgres" ]; then
 #      PGPASSWORD=${DB_PASSWORD} psql -h ${DB_HOST} -U ${DB_USERNAME} -d ${DB_DATABASE} -f ${DB_FILE}
 #    fi
     PGPASSWORD="${DB_PASSWORD}" psql -p ${DB_PORT} -h ${DB_HOST} -U ${DB_USERNAME} -d ${DB_DATABASE} -f ${DB_FILE}
-    if [ "$?" != "0" ]; then
-      printf "\n\nERROR: could not connect... have you tunneled to the bastion server?\n\n"
+    PGPASSWORDe=$?
+    if [ "$PGPASSWORDe" != "0" ]; then
+      printf "\n\nERROR(${PGPASSWORDe}): could not connect... have you tunneled to the bastion server?\n\n"
       exit 1
     fi
 
diff --git a/bin/wov-push-db b/bin/wov-push-db
--- a/bin/wov-push-db
+++ b/bin/wov-push-db
@@ -12,6 +12,7 @@ fi
 pushenvargs=( "$@" )
 set ""
 . wov-env --provider
+. wov-db-common
 . wov-ns-check
 set -- "${pushenvargs[@]}"
 
@@ -48,6 +49,7 @@ By default, checks all database delta files that exist.
 Switches:
   --checksum
   --skip-git-checks  : ignores unchecked git changes of secrets and code (dev and prod stages will override this). Does not skip archive checks.
+  --snapshot X : a snapshot to use for this push (i.e. a new checkpoint, not a delta)
   -pc|--push-check|--any-push-blockage : checks if the database changes are checked in for pver, and ready to push to archive
   -h : this help
   -q/-v : quiet/verbose
@@ -61,8 +63,8 @@ function fFailedDBConnection()
   local RET=$1
   if [ "$2" != "" ]; then
     printf "  > Is db inited?\n"
-    printf "    - init>        'wov-db-cloud -D ${2} -I'\n"   
-    printf "    - get version> 'wov-db-cloud -D $2 --ver'\n"
+    printf "    - init>        'wov-db-connect ${2} -db-init'\n"   
+    printf "    - get version> 'wov-db-connect $2 --db-ver'\n"
     printf "\n"
     printf "\n"
   fi
@@ -117,15 +119,21 @@ function doHashDBSchema()
 function doGetDBPVER()
 {
   local retval=1
-  local DBRAW=$(wov-db-connect $i -q -d wovtools -c "SELECT * FROM logs WHERE database='$1' ORDER BY id DESC LIMIT 1;" 2> /dev/null)
-  local r=$?
-  if [ "$r" != "0" ]; then 
-    printf "\n\nERROR: failed to connect to database wovtools, table logs, on database server $1.\n\n"; 
-    fFailedDBConnection 1 $1
+  R=$(wov-db-connect $1 --db-ver 2>&1) ; Re=$?
+  if [ $Re -eq 0 ]; then
+    local DB_PVER=`echo ${R} | cut -d'|' -f5`
+    retval=0;
   fi
-#  echo "DBRAW ${DBRAW}" 1>&2
-  local DB_PVER=`echo ${DBRAW} | cut -d'|' -f5`
-  retval=$?
+
+#  DBRAW=$(wov-db-connect $i -d wovtools -c "SELECT * FROM logs WHERE database='$1' ORDER BY id DESC LIMIT 1;" 2>&1) ; DBRAWe=$?
+#  if [ "$DBRAWe" != "0" ]; then 
+#    printf "${DBRAW}\n"
+#    printf "\nERROR: failed to connect to database wovtools, table logs, on database server $1.\n\n"; 
+#    fFailedDBConnection 1 $1
+#  fi
+#  # echo "DBRAW ${DBRAW}" 1>&2
+#  local DB_PVER=`echo ${DBRAW} | cut -d'|' -f5`
+#  retval=$?
 
   echo "${DB_PVER}"
   return $retval
@@ -147,64 +155,6 @@ function doGetDBLastLogEntry()
   fi
 
   return $retval
-}
-
-# Create a list of databases to look at
-# 1. take from command line if they have it
-# 2. else, from all deltas files and archive files
-function doFindDatabases()
-{
-  DATABASES=$*
-  if [ ! -e ${WOV_BASEDIR}/wovtools/db ]; then
-    printf "\n\nERROR: no database directory in wovtools: '${WOV_BASEDIR}/wovtools/db' missing.\n" 1>&2
-    fFailedDBConnection 1
-
-  elif [ ! -e ${WOV_BASEDIR}/wovtools/db/archive ]; then
-    printf "\n\nERROR: no database archive in wovtools/db: '${WOV_BASEDIR}/wovtools/db/archive' missing.\n" 1>&2
-    fFailedDBConnection 1
-
-  elif [ "$DATABASES" == "" ]; then
-    DATABASES=()
-    D1=()
-    D2=()
-    DELTAS=( $(cd ${WOV_BASEDIR}/wovtools/db && ls *.deltas 2> /dev/null ) )
-    for d in "${DELTAS[@]}"; do
-      D1+=("${d%.deltas}")
-    done
-    REGFILES=( $(cd ${WOV_BASEDIR}/wovtools/db/archive && ls *.json 2> /dev/null ) )
-    for f in "${REGFILES[@]}"; do
-      D2+=("${f%.json}")
-    done
-
-    # Make sure only one entry : so add y, then every z not in y
-#    echo "D1: ${D1[@]}" 1>&2
-#    echo "D2: ${D2[@]}" 1>&2
-    i=0
-    for y in ${D2[@]}
-    do
-      DATABASES[i++]="$y"
-    done
-
-    # add in z's if not in y
-    for z in ${D1[@]}
-    do
-#      DATABASES[i++]="$z"
-      doskip=0
-      for y in ${D2[@]}
-      do
-        if [ "$z" == "$y" ]; then 
-          doskip=1
-        fi
-      done
-      if [ "${doskip}" == "0" ]; then
-#        echo "adding $z"
-        DATABASES[i++]="$z"
-      fi
-    done
-  fi
-#  echo "${DATABASES[@]}" 1>&2
-  echo "${DATABASES[@]}"
-#  exit 1
 }
 
 
@@ -240,14 +190,14 @@ function doPushCheck()
   if [ "$retval" == "0" ]; then
     if [ $DOECHO -ge 1 ]; then printf "... retrieve db hash.\n"; fi
     DB_HASH=$(doHashDBSchema $1) ; local A=$?
-    #echo "db hash: $A '${DB_HASH}'"
+    # echo "db hash: $A '${DB_HASH}'"
     if [ $A -ne 0 ]; then
       echo "${DB_HASH}"
       fFailedDBConnection 2 $1
     fi
     DB_PVER=$(doGetDBPVER $1)
     if [ "$?" != "0" ] || [ "$DB_PVER" == "" ]; then
-      printf "\n\nERROR: could not get database version.\n"
+      printf "${DB_PVER}\nERROR: could not get database version.\n"
       fFailedDBConnection 2 $1
     elif [ ! -e ${WOV_BASEDIR}/wovtools/db/archive/${1}.json ]; then 
       printf "\nERROR: no archive/${1}.json.\n"; 
@@ -397,24 +347,39 @@ function doCommitDB()
 
   # get current db wovtools pver
   DB_ENTRY=$(doGetDBLastLogEntry $1)
-#  DB_PVER=$(doGetDBPVER $1)
   if [ "$?" != "0" ]; then
     printf "\n\n***ERROR: database not inited.\n"
     fFailedDBConnection 1 $1
-  elif [ "${DB_ENTRY}" == "" ]; then
-    printf "\n\n***ERROR: database has no parent.\n"
-    fFailedDBConnection 2 $1
   fi
 #  printf "\nDB_ENTRY '${DB_ENTRY}'\n"
-  OLDIFS=$IFS
-  IFS='|'
-  # CAW - just commented out dbverarray=( $(wov-db-cloud -D ${WOVDB_DBNAME} --ver)  )
-  DB_ENTRY=( $(echo "${DB_ENTRY[@]}") )
-  IFS=$OLDIFS
-#  printf "\nDB_ENTRY '${DB_ENTRY[*]}'\n"
-  DB_PVER="$( echo -e "${DB_ENTRY[4]}" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')"
+
+
+  # No parent, consider this the first entry
+  if [ "${DB_ENTRY}" == "" ]; then
+    if [ "${DB_SNAPSHOT}" == "" ]; then
+      printf "\nERROR: need to provide a snapshot for first commit of database. Use --snapshot X. ex. rds:wov-aws-va-ant-db-alywandev-2017-07-17-07-20.\n"
+      fFailedDBConnection 3 $1
+    fi
+    DB_PVER=${WOV_PVER}
+    DB_snapshot="${DB_SNAPSHOT}"
+  else
+    OLDIFS=$IFS
+    IFS='|'
+    DB_ENTRY=( $(echo "${DB_ENTRY[@]}") )
+    IFS=$OLDIFS
+    DB_PVER="$( echo -e "${DB_ENTRY[4]}" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')"
+    DB_snapshot="$( echo -e "${DB_ENTRY[6]}" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')"
+  fi
 
   if [ "$retval" == "0" ]; then
+
+    # validate json file first
+    R=$(cat ${WOV_BASEDIR}/wovtools/db/archive/$1.json | jq empty 2>&1) ; Re=$?
+    if [ $Re != 0 ]; then
+      echo "${R}"
+      echo "ERROR: wovtools/db/archive/$1.json file is not valid JSON. Exiting."
+      exit 3
+    fi
 
     # get current db checksum
     CHKSUM=$(doHashDBSchema $1)
@@ -469,23 +434,25 @@ EOF
 }
 EOF
     fi
+
+
     # append this entry
     jq " .versions.\"${WOV_PVER}\"={ \"checksum\": \"${CHKSUM}\", \"parent\": { \"type\": \"pver\", \"pver\": \"${DB_PVER}\" } }" \
        ${WOV_BASEDIR}/wovtools/db/archive/$1.json > ${WOV_BASEDIR}/wovtools/db/archive/.$1.json.$$ && cp ${WOV_BASEDIR}/wovtools/db/archive/.$1.json.$$ ${WOV_BASEDIR}/wovtools/db/archive/$1.json && rm ${WOV_BASEDIR}/wovtools/db/archive/.$1.json.$$
-    DB_snapshot="$( echo -e "${DB_ENTRY[6]}" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')"
     #echo "DBENTRY snapshot : ${DB_snapshot}" 1>&2
     if [ "$DB_snapshot" != "" ]; then
-      echo "DBENTRY append snapshot : ${DB_snapshot}" 1>&2
+      echo "    ... append snapshot : ${DB_snapshot}" 1>&2
       jq " .versions.\"${WOV_PVER}\".parent.snapshot=\"${DB_snapshot}\"" \
        ${WOV_BASEDIR}/wovtools/db/archive/$1.json > ${WOV_BASEDIR}/wovtools/db/archive/.$1.json.$$ && cp ${WOV_BASEDIR}/wovtools/db/archive/.$1.json.$$ ${WOV_BASEDIR}/wovtools/db/archive/$1.json && rm ${WOV_BASEDIR}/wovtools/db/archive/.$1.json.$$
     fi
 
 
-    # - 4. update archive database pver number, with checksum ------------
+    # - 4. update archive database log pver number, snapshot, checksum ----
     # --------------------------------------------------------------------- 
-    echo "  ... update archive database pver number, with checksum"
-    R=$(wov-db-connect $1 -q -d wovtools -c "INSERT INTO logs (database, wovtoolsver, label, pver, sver ) VALUES ( '$1', '${WOV_VERSION}', '${WOV_PVER}_${WOV_SVER}', ${WOV_PVER}, ${WOV_SVER} );")
+    echo "  ... update archive database logs"
+    R=$(wov-db-connect $1 -q -d wovtools -c "INSERT INTO logs (database, wovtoolsver, label, pver, sver, snapshot ) VALUES ( '$1', '${WOV_VERSION}', '${WOV_PVER}_${WOV_SVER}', ${WOV_PVER}, ${WOV_SVER}, '${DB_snapshot}' );")
     if [ "$?" != "0" ]; then
+      printf "${R}"
       printf "\n\nERROR: failed updating archive database pver number with checksum.\n"
       fFailedDBConnection 3 $1
     fi
@@ -521,6 +488,11 @@ while [[ $1 =~ ^- ]]; do
   elif [ "$1" == "--checksum" ]; then
     shift
     DOACTION="checksum"
+
+  elif [ "$1" == "--snapshot" ]; then
+    shift
+    DB_SNAPSHOT=$1
+    shift
 
   elif [ "$1" == "--any-push-blockage" ] || [ "$1" == "-pc" ] || [ "$1" == "--push-check" ]; then
     shift
