Fixing issues that were identified once put into container.
- Issue #62 - Global Config File Name - https://github.com/woveon/wovtools/issues/62
- Issue with WOV_ME vs WOV_STAGE in running scripts, vs init scripts.
Still remains mostly in scripts, but handled in init.

Fixes
- Made ~/.wovtools a directory of config file (formerly ~/.wovtools file) and directories for local archives of sea, dba, dsa.
  - WOVCONFIGF is ~/.wovtools/config and WOVCONFIGDIR is ~/.wovtools in wov-env-loader
- Updated all scripts to use this file
  - problems in test scripts that didn't normally load wov-env-loader
- added --usercode to wov-init-cluster and wov-init-coderepoaccess

diff --git a/bin/wov-init-coderepoaccess b/bin/wov-init-coderepoaccess
--- a/bin/wov-init-coderepoaccess
+++ b/bin/wov-init-coderepoaccess
@@ -12,6 +12,8 @@ usage: `basename $0` {options} [DOMAIN]
 
 Defines secrets for private code repositories.
 
+  --usercode - overrides WOV_ME
+
 EOF
 }
 . wov-env-ops fDisplayOptions "$@"
@@ -19,6 +21,25 @@ EOF
 
 
 MYREPOSITORIESFILE="${WOV_BASEDIR}/wovtools/secrets/repositories.json"
+
+
+# ---------------------------------------------------------------------
+while [[ $1 =~ ^- ]]; do
+#  echo "param '$1'"
+
+  if [ "$1" == "--usercode" ]; then
+    shift
+    WOV_ME=$1
+    shift
+
+  else
+    echo
+    echo "***ERROR (`basename $0`): unknown option '$1'."
+    echo
+    fDisplayOptions
+    exit 1
+  fi
+done
 
 
 iProjConfig_MergeToSecrets "dev"         "repositories.json" || exit 1
