Updating the woveon engine and email plugin caught many issues.
Minor:
- path for secrets is _sea_stage so you can have multiple profiles for
the same project.
- updates for init scripts and catching small errors. found as I updated
an old project.
- init uses default directory for local archive base if nothing
specified
- added validation to iProjConfig and iProjConfig_ReadIn calls this now
- improved error messages for initialization of single/many projects
- added extport to db files so we have port, for normal operation, and
extport for testing
- db files, changed local to laptop since it was using localhost

wov-aws
- converted [se|db|ds]archive to [se|db|ds]a but
- when creating volumes, use AWS_ZONES instead of CL_ZONES

wov-bastion-connection
- opened up its expected naming of dbs, to catch mongodbs as well
- failure to find an entry returns 1, not 0 now

wov-checkout
- converted [se|db|ds]archive to [se|db|ds]a but
- added repo checks for git urls when deciding if a URL is local or
remote
- checks out correct branch now

wov-db
- errors when it doens not have mongo functionality yet

wov-deploy-service
- updated to new wovtools scripting

wov-init
- fixed local archive naming assumptions for when ensuring local
archives

diff --git a/bin/wov-db b/bin/wov-db
--- a/bin/wov-db
+++ b/bin/wov-db
@@ -440,6 +440,7 @@ function doDBGetVer()
 {
   local retval=1
 
+  if [ "$DB_TYPE" != "postgres" ]; then >&2 echo "ERROR: only setup for postgres! Can not wov-db doDBGetVer to get version."; retval=2; fi
   if [ "$DB_PORT" == "" ]; then >&2 echo "ERROR: no port specified."; retval=2; fi
   if [ "$DB_USERNAME" == "" ]; then >&2 echo "ERROR: no username specified."; retval=2; fi
   if [ "$DB_PASSWORD" == "" ]; then >&2 echo "ERROR: no password specified."; retval=2; fi
