minor changes and bug fixes

diff --git a/bin/wov-build b/bin/wov-build
--- a/bin/wov-build
+++ b/bin/wov-build
@@ -104,6 +104,14 @@ EOF
   # remove prying eyes...
   chmod 600 ${SECRETFILE}
 
+  # Check for file existence
+  for sf in ${SECRETFILES[*]}; do
+    if [ ! -e ${WOV_BASEDIR}/wovtools/secrets/$sf ]; then
+      printf "\n\nERROR: file for secret build does not exist: 'wovtools/secrets/$sf'.\n"
+      exit 1
+    fi
+  done
+
   # merge files in order
   for sf in ${SECRETFILES[*]}; do
     if [ "$DOECHO" == "2" ]; then echo "  ... adding secret file $sf"; fi
diff --git a/bin/wov-push-containers b/bin/wov-push-containers
--- a/bin/wov-push-containers
+++ b/bin/wov-push-containers
@@ -118,6 +118,10 @@ for f in ${RECIPES}; do
     echo "ERROR: recipe for container ${f%.sh} not executable (${WOV_BASEDIR}/wovtools/containers/$f).";
   else
     cd ${WOV_BASEDIR} && SRCDIR=${SRCDIR} DESTDIR=${DESTDIR} CONTAINER=${CONTAINER} ${WOV_BASEDIR}/wovtools/containers/$f
+    if [ "$?" != "0" ]; then
+      printf "\n\nERROR: failed building container.\n\n"
+      exit 1
+    fi
 
     # determine if need to build container
     NEEDSBUILD=0
