Fixed issue #4 where changes could occur which do not push the container, which causes errors when Kubernetes tries to run. This was annoying.
https://github.com/woveon/wovtools2/issues/4

diff --git a/bin/wov-push-containers b/bin/wov-push-containers
--- a/bin/wov-push-containers
+++ b/bin/wov-push-containers
@@ -5,6 +5,7 @@ DOFORCE=0
 FOLD=80
 BLOCK=0
 SSHKEY=
+RECIPES=( )
 
 
 # --------------------------------------------------------------------- 
@@ -28,7 +29,7 @@ function fDisplayOptions()
   cat <<EOF | fold -w ${FOLD} -s
 
 
-usage: `basename $0` [options]
+usage: `basename $0` [options] containers ...
 
 Runs the recipe scripts and if there is a change, build the containers.
 
@@ -92,110 +93,119 @@ done
 
 
 
-if [ "${BLOCK}" == "0" ]; then
 # Find the recipes
-RECIPES=$(cd ${WOV_BASEDIR}/wovtools/containers; ls *.sh 2> /dev/null)
-
-
-# Build containers if needed
-for f in ${RECIPES}; do
-
-  if [ $DOECHO -ge 1 ]; then echo "... build container ${f%.sh}."; fi
-
-  SRCDIR=${WOV_BASEDIR}
-  DESTDIR=${WOV_BASEDIR}/wovtools/cache/containers/${f%.sh}
-  ARCHDIR=${WOV_BASEDIR}/wovtools/cache/containers/archive/${f%.sh}
-  CONTAINER=${WOV_PROJECT}${f%.sh}
-#  echo "CONTAINER=${CONTAINER}"
-#  echo "SRCDIR=${SRCDIR}"
-#  echo "DESTDIR=${DESTDIR} # more like a 'content' dir as this is all copied in here"
-#  echo "ARCHDIR=${ARCHDIR} # location of archive of DESTDIR"
-
-  # build the content in wovtools/cache/containers/$f
-  mkdir -p ${DESTDIR}
-  echo "  ... recipe $f (DESTDIR=${DESTDIR}, CONTAINER=${CONTAINER})"
-  if [[ ! -x "${WOV_BASEDIR}/wovtools/containers/$f" ]]; then 
-    echo "ERROR: recipe for container ${f%.sh} not executable (${WOV_BASEDIR}/wovtools/containers/$f).";
-  else
-    cd ${WOV_BASEDIR} && SRCDIR=${SRCDIR} DESTDIR=${DESTDIR} CONTAINER=${CONTAINER} ${WOV_BASEDIR}/wovtools/containers/$f
-    if [ "$?" != "0" ]; then
-      printf "\n\nERROR: failed building container.\n\n"
-      exit 1
-    fi
-
-    # determine if need to build container
-    NEEDSBUILD=0
-
-    wov-pushcontainer-check ${f%.sh}
-    NEEDSBUILD=$?
-#    echo "NEEDSBUILD: $NEEDSBUILD"
-#    echo "NEEDSBUILDOUT: $NEEDSBUILDOUT"
-#    if [ ${NEEDSBUILD} == 1 ] || [ $DOFORCE == 1 ]; then
-#      echo "    ... forcing container build."
-#
-#    elif [ "$(docker images -q ${CONTAINER})" == "" ]; then 
-#      docker images -q ${CONTAINER}
-#      echo "    ... no existing container, building"
-#      NEEDSBUILD=1
-#
-#    elif [ ! -e ${ARCHDIR} ]; then 
-#      echo "    ... no ${ARCHDIR}, building"
-#      NEEDSBUILD=1; 
-#
-#    elif [ "$(diff -rq --exclude='.dirstamp' --exclude='.DS_Store' ${DESTDIR} ${ARCHDIR} &> /dev/null ; echo $?)" != "0" ]; then 
-#      echo "    ... diffs when comparing ${DESTDIR} to ${ARCHDIR}, building"
-#      NEEDSBUILD=1; 
-#    fi
-#
-    if [ "${NEEDSBUILD}" ==  "-2" ]; then exit  ${NEEDSBUILD}; fi
-
-    # do actions 
-    if [ "${NEEDSBUILD}" == "1" ] || [ "${DOFORCE}" == "1" ]; then
-
-      echo "    ... creating container '${CONTAINER}'"
-      if [ "${SSHKEY}" != "" ]; then
-        echo "      ... adding ssh key to build: '${SSHKEY}'"
-        cp ${SSHKEY} ${DESTDIR}/$(basename ${SSHKEY})
-        SS="--build-arg SSH_KEY=$(basename ${SSHKEY})"
-      fi
-
-      docker build ${SS} -f ${DESTDIR}/Dockerfile -t ${WOV_PROJECT}/${CONTAINER}:latest ${DESTDIR} || exit 1
-
-      if [ "${SSHKEY}" != "" ]; then
-        echo "      ... removing key from dest: '${DESTDIR}/$(basename ${SSHKEY})'"
-        rm ${DESTDIR}/$(basename ${SSHKEY})
-      fi
-
-      echo "    ... archiving build of container '${CONTAINER}'"
-      mkdir -p ${ARCHDIR}
-      rsync -ai --delete ${DESTDIR}/ ${ARCHDIR} &> /dev/null
-
-      echo "    ... tag and push to repo"
-      docker tag ${WOV_PROJECT}/${CONTAINER} ${WOV_ARCHIVEREPOSITORY}/${WOV_PROJECT}/${CONTAINER}:${WOV_STAGE}_${WOV_PVER}
-
-      echo "    ... push container to: ${WOV_ARCHIVEREPOSITORY}/${WOV_PROJECT}/${CONTAINER}:${WOV_STAGE}_${WOV_PVER}"
-      docker push ${WOV_ARCHIVEREPOSITORY}/${WOV_PROJECT}/${CONTAINER}:${WOV_STAGE}_${WOV_PVER}
-      if [ "$?" != "0" ]; then
-        echo "    ... auto-login to AWS attempt"
-        AWSAUTHCMD=$(aws ecr get-login --no-include-email)
-        eval ${AWSAUTHCMD}
-        if [ "$?" != "0" ]; then
-          echo "      ... FAILED auto-login to AWS attempt"
-          exit 1
-        else
-          echo "      ... SUCCESS auto-login to AWS attempt"
-          echo "    ... re-push container to: ${WOV_ARCHIVEREPOSITORY}/${WOV_PROJECT}/${CONTAINER}:${WOV_STAGE}_${WOV_PVER}"
-          docker push ${WOV_ARCHIVEREPOSITORY}/${WOV_PROJECT}/${CONTAINER}:${WOV_STAGE}_${WOV_PVER} 
-        fi
-      fi
-
-    else
-      echo "    ... skipping build of container '${CONTAINER}'"
-    fi
+if [ "${BLOCK}" == "0" ]; then
+ 
+  RECIPES=( "$@" )
+  if [ "${#RECIPES[@]}" == 0 ]; then
+    RECIPES=( $(cd ${WOV_BASEDIR}/wovtools/containers; ls *.sh 2> /dev/null) )
   fi
 
+  # Build containers if needed
+  for f in ${RECIPES}; do
 
-done
+    if [ $DOECHO -ge 1 ]; then echo "... build container ${f%.sh}."; fi
+
+    SRCDIR=${WOV_BASEDIR}
+    DESTDIR=${WOV_BASEDIR}/wovtools/cache/containers/${f%.sh}
+    ARCHDIR=${WOV_BASEDIR}/wovtools/cache/containers/archive/${f%.sh}
+    CONTAINER=${WOV_PROJECT}${f%.sh}
+    #  echo "CONTAINER=${CONTAINER}"
+    #  echo "SRCDIR=${SRCDIR}"
+    #  echo "DESTDIR=${DESTDIR} # more like a 'content' dir as this is all copied in here"
+    #  echo "ARCHDIR=${ARCHDIR} # location of archive of DESTDIR"
+
+    # build the content in wovtools/cache/containers/$f
+    mkdir -p ${DESTDIR}
+    echo "  ... recipe $f (DESTDIR=${DESTDIR}, CONTAINER=${CONTAINER})"
+    if [[ ! -x "${WOV_BASEDIR}/wovtools/containers/$f" ]]; then 
+      echo "ERROR: recipe for container ${f%.sh} not executable (${WOV_BASEDIR}/wovtools/containers/$f).";
+    else
+      cd ${WOV_BASEDIR} && SRCDIR=${SRCDIR} DESTDIR=${DESTDIR} CONTAINER=${CONTAINER} ${WOV_BASEDIR}/wovtools/containers/$f
+      if [ "$?" != "0" ]; then
+        printf "\n\nERROR: failed building container.\n\n"
+        exit 1
+      fi
+
+      # determine if need to build container
+      NEEDSBUILD=0
+
+      wov-pushcontainer-check ${f%.sh}
+      NEEDSBUILD=$?
+      # printf "\n\n\n\nNEEDSBUILD: $NEEDSBUILD\n\n\n"
+      #    echo "NEEDSBUILDOUT: $NEEDSBUILDOUT"
+      #    if [ ${NEEDSBUILD} == 1 ] || [ $DOFORCE == 1 ]; then
+      #      echo "    ... forcing container build."
+      #
+      #    elif [ "$(docker images -q ${CONTAINER})" == "" ]; then 
+      #      docker images -q ${CONTAINER}
+      #      echo "    ... no existing container, building"
+      #      NEEDSBUILD=1
+      #
+      #    elif [ ! -e ${ARCHDIR} ]; then 
+      #      echo "    ... no ${ARCHDIR}, building"
+      #      NEEDSBUILD=1; 
+      #
+      #    elif [ "$(diff -rq --exclude='.dirstamp' --exclude='.DS_Store' ${DESTDIR} ${ARCHDIR} &> /dev/null ; echo $?)" != "0" ]; then 
+      #      echo "    ... diffs when comparing ${DESTDIR} to ${ARCHDIR}, building"
+      #      NEEDSBUILD=1; 
+      #    fi
+      #
+      if [ "${NEEDSBUILD}" ==  "3" ]; then exit  ${NEEDSBUILD}; fi
+      if [ "${NEEDSBUILD}" ==  "2" ]; then exit  ${NEEDSBUILD}; fi
+
+      # do actions 
+      if [ "${NEEDSBUILD}" == "1" ] || [ "${DOFORCE}" == "1" ]; then
+
+        echo "    ... creating container '${CONTAINER}'"
+        if [ "${SSHKEY}" != "" ]; then
+          echo "      ... adding ssh key to build: '${SSHKEY}'"
+          cp ${SSHKEY} ${DESTDIR}/$(basename ${SSHKEY})
+          SS="--build-arg SSH_KEY=$(basename ${SSHKEY})"
+        fi
+
+        docker build ${SS} -f ${DESTDIR}/Dockerfile -t ${WOV_PROJECT}/${CONTAINER}:latest ${DESTDIR} || exit 1
+
+        if [ "${SSHKEY}" != "" ]; then
+          echo "      ... removing key from dest: '${DESTDIR}/$(basename ${SSHKEY})'"
+          rm ${DESTDIR}/$(basename ${SSHKEY})
+        fi
+
+        echo "    ... archiving build of container '${CONTAINER}'"
+        mkdir -p ${ARCHDIR}
+        rsync -ai --delete ${DESTDIR}/ ${ARCHDIR} &> /dev/null
+
+        echo "    ... tag and push to repo"
+        docker tag ${WOV_PROJECT}/${CONTAINER} ${WOV_ARCHIVEREPOSITORY}/${WOV_PROJECT}/${CONTAINER}:${WOV_STAGE}_${WOV_PVER}
+
+        echo "    ... push container to: ${WOV_ARCHIVEREPOSITORY}/${WOV_PROJECT}/${CONTAINER}:${WOV_STAGE}_${WOV_PVER}"
+        R=$(docker push ${WOV_ARCHIVEREPOSITORY}/${WOV_PROJECT}/${CONTAINER}:${WOV_STAGE}_${WOV_PVER} 2>&1 )
+        if [ "$?" != "0" ]; then
+          echo "R: ${R}"
+          if [[ $R == 'name unknown'* ]]; then
+            printf "\n\n  ...${R}.\n"
+            exit 1
+          fi
+          echo "    ... auto-login to AWS attempt"
+          AWSAUTHCMD=$(aws ecr get-login --no-include-email)
+          eval ${AWSAUTHCMD}
+          if [ "$?" != "0" ]; then
+            echo "      ... FAILED auto-login to AWS attempt"
+            exit 1
+          else
+            echo "      ... SUCCESS auto-login to AWS attempt"
+            echo "    ... re-push container to: ${WOV_ARCHIVEREPOSITORY}/${WOV_PROJECT}/${CONTAINER}:${WOV_STAGE}_${WOV_PVER}"
+            docker push ${WOV_ARCHIVEREPOSITORY}/${WOV_PROJECT}/${CONTAINER}:${WOV_STAGE}_${WOV_PVER} 
+          fi
+        fi
+
+      else
+        echo "    ... skipping build of container '${CONTAINER}'"
+      fi
+    fi
+
+
+  done
 fi
 
 
diff --git a/bin/wov-pushcontainer-check b/bin/wov-pushcontainer-check
--- a/bin/wov-pushcontainer-check
+++ b/bin/wov-pushcontainer-check
@@ -86,10 +86,10 @@ while [[ $1 =~ ^- ]]; do
 done
 
 
-# Echoes 1 if found, 0 not found, -1 unknown, -2 if no repo
+# Echoes 1 if found, 0 not found, 2 unknown, 3 if no repo
 function fCheckForRemoteImage() 
 {
-  local retval=-1
+  local retval=2
   local RR=""
 
 
@@ -99,17 +99,16 @@ function fCheckForRemoteImage()
     RR=$(ecs-cli images ${WOV_PROJECT}/${WOV_PROJECT}${CONTAINER} 2>&1 )
     if [[ $RR == *"RepositoryNotFoundException"* ]]; then
       printf "\n\nERROR: Repository Not Found. Create '${WOV_PROJECT}/${WOV_PROJECT}${CONTAINER}' in AWS CodeCommit, then try again.\n" 1>&2
-      retval=-2
+      retval=3
     elif [ "$RR" == "" ]; then
       retval=0
     fi
 
 
     # if no errors, check
-    if [[ $retval -eq -1 ]]; then
+    if [[ $retval -eq 2 ]]; then
       # NOTE: check KSTAGE since GSTAGE is mixed with local
       R=$(echo "${RR}" | awk '{print $2}' | \grep ${WOV_KSTAGE}_${WOV_PVER})
-      echo "R $R"
       if [ "${R}" != "" ]; then
         retval=1
       fi
@@ -117,13 +116,26 @@ function fCheckForRemoteImage()
   else
     printf "\n\nERROR: Unknown provider to check (only AWS known in wov-pushcontainer-check).\n" 1>&2&
     printf "    NOTE: sohuld be an easy fix for regular git!\n\n" 1>&2
-    retval=-2
+    retval=2
   fi
 
   # 
 
 #  echo "TAG ${WOV_KSTAGE}_${WOV_PVER}"
 
+  echo $retval
+}
+
+function fGetRepoLabel() 
+{
+  local retval=""
+  if [[ $WOV_ARCHIVEREPOSITORY == *".amazonaws.com" ]]; then
+    retval=$(ecs-cli images api/apirest | awk '{print $2}' | sed -n '3p')
+#    echo "RETVAL: ${retval}"
+  else
+    printf "\n\nERROR: Unknown provider to check (only AWS known in wov-pushcontainer-check).\n" 1>&2&
+    printf "    NOTE: should be an easy fix for regular git!\n\n" 1>&2
+  fi
   echo $retval
 }
 
@@ -142,7 +154,7 @@ NEEDSBUILD=1
 
 #echo "CHECK : "
 #fCheckForRemoteImage
-#exit 1
+#fGetRepoLabel
 
 
 if [ ${DOFORCE} -eq 1 ]; then
@@ -155,20 +167,36 @@ elif [ "$(docker images -q ${WOV_PROJECT}/${WOV_PROJECT}${CONTAINER} )" == "" ];
 elif [ ! -e ${ARCHDIR} ]; then
   if [ $DOECHO -ge 1 ]; then echo "    ... no ${ARCHDIR}, building"; fi
 
-elif [ "$(fCheckForRemoteImage)" != "1" ]; then
-  LC=$?
-  if [ "${LC}" == "0" ]; then
-    if [ $DOECHO -ge 1 ]; then echo "    ... no remote tagged image found."; fi
-  fi
-  if [ "${LC}" == "-2" ]; then
-    if [ $DOECHO -ge 1 ]; then echo "    ... no repo found."; fi
-  fi
+else 
 
-elif [ "$(diff -rq --exclude='.dirstamp' --exclude='.DS_Store' ${DESTDIR} ${ARCHDIR} &> /dev/null ; echo $?)" != "0" ]; then
-  if [ $DOECHO -ge 1 ]; then echo "    ... diffs when comparing ${DESTDIR} to ${ARCHDIR}, building"; fi
+  CH=$(fCheckForRemoteImage)
+  #echo "CH: ${CH}"
+  if [ "${CH}" != "1" ]; then
+    if [ "${CH}" == "0" ]; then
+      if [ $DOECHO -ge 1 ]; then echo "    ... no remote tagged image found."; fi
+      NEEDSBUILD=1
+    fi
+    if [ "${CH}" == "3" ]; then
+      if [ $DOECHO -ge 1 ]; then echo "    ... no repo found."; fi
+    fi
+    if [ "${CH}" == "2" ]; then
+      if [ $DOECHO -ge 1 ]; then echo "    ... some error or other."; fi
+    fi
 
-else
-  NEEDSBUILD=0
+  # check remote repo version... since if the git version is diff from that, then need to build!!!
+  elif [ "$(fGetRepoLabel)" != "${WOV_STAGE}_${WOV_PVER}" ]; then
+    if [ $DOECHO -ge 1 ]; then echo "    ... remote repo is behind."; fi
+    NEEDSBUILD=1
+
+
+  # ok, so remote repo exists and no error, check for diffs
+  elif [ "$(diff -rq --exclude='.dirstamp' --exclude='.DS_Store' ${DESTDIR} ${ARCHDIR} &> /dev/null ; echo $?)" != "0" ]; then
+    if [ $DOECHO -ge 1 ]; then echo "    ... diffs when comparing ${DESTDIR} to ${ARCHDIR}, building"; fi
+    NEEDSBUILD=1
+
+  else
+    NEEDSBUILD=0
+  fi
 fi
 
 if [ ${DOECHO} -ge 2 ]; then echo "... needs build ${NEEDSBUILD}"; fi
