Added checks not just for committing to local repo, but also pushing that to the origin.

diff --git a/bin/wov-push-check b/bin/wov-push-check
--- a/bin/wov-push-check
+++ b/bin/wov-push-check
@@ -56,18 +56,22 @@ while [[ $1 =~ ^- ]]; do
 done
 
 
+# --------------------------------------------------------------------- 
+# Check code changes and added/removed files are committed into current branch.
+# --------------------------------------------------------------------- 
+
 # check current repo
 if [ "$(git status -s)" != "" ]; then
   if [ "$DOECHO" == "1" ]; then
-    echo "WARNING: failed code/env push-check. Check in your archive."
+    echo "WARNING: failed code/env commit-check. Check in your archive."
   elif [ "$DOECHO" == "2" ]; then
-    echo "WARNING: failed code/env push-check. Check in your archive."
+    echo "WARNING: failed code/env commit-check. Check in your archive."
     git status
   fi
   exit 1
 else
   if [ "$DOECHO" == "2" ]; then
-    echo "SUCCESS: wov-push-check code/env"
+    echo "SUCCESS: wov-push-check commit code/env"
   fi
 fi
 
@@ -75,15 +79,52 @@ fi
 # check secrets repo
 if [ "$(cd ${WOV_BASEDIR}/wovtools/secrets && git status -s)" != "" ]; then
   if [ "$DOECHO" == "1" ]; then
-    echo "WARNING: failed secrets push-check. Check in your secrets archives."
+    echo "WARNING: failed secrets commit-check. Check in your secrets archives."
   elif [ "$DOECHO" == "2" ]; then
-    echo "WARNING: failed secrets push-check. Check in your secrets archives."
+    echo "WARNING: failed secrets commit-check. Check in your secrets archives."
     cd ${WOV_BASEDIR}/wovtools/secrets && git status
   fi
   exit 1
 else
   if [ "$DOECHO" == "2" ]; then
-    echo "SUCCESS: wov-push-check secrets"
+    echo "SUCCESS: wov-push-check commit secrets."
   fi
 fi
 
+
+
+# --------------------------------------------------------------------- 
+# Check local changes are pushed to origin
+# --------------------------------------------------------------------- 
+MYBRANCH=$(git rev-parse --abbrev-ref HEAD)
+MYSBRANCH=$(cd ${WOV_BASEDIR}/wovtools/secrets && git rev-parse --abbrev-ref HEAD)
+
+# check code/env
+if [ "$(git log origin/${MYBRANCH}..${MYBRANCH})" != "" ]; then
+  if [ "$DOECHO" == "1" ] || [ "$DOECHO" == "2" ]; then
+    echo "WARNING: failed code/env push check. Push your archive."
+  fi
+  exit 1
+else
+  if [ "$DOECHO" == "2" ]; then
+    echo "SUCCESS: wov-push-check push code/env."
+  fi
+fi
+
+# check secrets
+if [ "$(cd ${WOV_BASEDIR}/wovtools/secrets && git log origin/${MYSBRANCH}..${MYSBRANCH})" != "" ]; then
+  if [ "$DOECHO" == "1" ] || [ "$DOECHO" == "2" ]; then
+    echo "WARNING: failed secrets push check. Push your secrets archive."
+  fi
+  exit 1
+else
+  if [ "$DOECHO" == "2" ]; then
+    echo "SUCCESS: wov-push-check push secrets."
+  fi
+fi
+
+
+
+if [ "$DOECHO" == "1" ] || [ "$DOECHO" == "2" ]; then
+  echo "SUCCESS: wov-push-check"
+fi
