Worked on wov-push and wov-deploy. Mostly catching missing errors and files but also added to env variables for databases.
wov-push
- checks for k8s file existence for each container (cm se k8s/service|deployment k8s/ingres)
- more spew about errors and catches missing k8s files as errors
- created a wov-push-common for finding recipes

wov-deploy
- catch errors when can't find k8s files
-

wov-env
- WOV_DATABASES is now computed as a list of databases by wov-build
- wov-env-build also has an additional step to compute things.
  - compute WOV_DATABASE_host from doResName DB CLUSTER WOV_DATABASE_subhost

wov-init
- added automatic creation of wovtools/containers

diff --git a/bin/wov-deploy b/bin/wov-deploy
--- a/bin/wov-deploy
+++ b/bin/wov-deploy
@@ -206,7 +206,8 @@ function doCheckContainersExist()
   # Build files to check for containers, from arguments or all directory files
   local k8sfiles=()
   if [ "$#" == "0" ]; then
-    k8sfiles=( $(cd ${rdir} && ls *.yaml) )
+    k8sfiles=( $(cd ${rdir} && ls *.yaml) ) ; k8sfilese=$?
+    if [ $k8sfilese != 0 ]; then echo "ERROR: failed to find k8s files."; exit 1; fi
   else
     for f in ${*}; do
       k8sfiles+=( "deployment-${f}.yaml" )
@@ -276,7 +277,8 @@ function doDeployK8s()
     done
   else
     # echo "k8sdir ${K8SDIR}"
-    FILES=( $(cd ${K8SDIR} && ls *.yaml | sed -e 's/\(.*\)\..*/\1/') )
+    FILES=( $(cd ${K8SDIR} && ls *.yaml | sed -e 's/\(.*\)\..*/\1/') ) ; FILESe=$?
+    if [ $FILESe != 0 ]; then echo "ERROR: failed to find files."; exit 1; fi
   fi
 
   # printf "K8S deployment FILES: ${FILES[*]}\n"
diff --git a/bin/wov-env-build b/bin/wov-env-build
--- a/bin/wov-env-build
+++ b/bin/wov-env-build
@@ -83,6 +83,8 @@ done
 envbuildargs=( "$@" )
 set ""
 . wov-env-loader
+. wov-env-common
+. wov-db-common
 set -- "${envbuildargs[@]}"
 
 # --------------------------------------------------------------------- 
@@ -204,6 +206,9 @@ function fBuildSecrets()
     exit 1
   fi
 
+  # Find the databases as array, then flatten for WOV_DATABASES
+  DATABASES=( $(doFindDatabases) )
+  WOV_DATABASES="${DATABASES[@]}"
 
 
   # ---------------------------------------------------------------------
@@ -230,6 +235,7 @@ function fBuildSecrets()
   "PROJECTTYPE"        : "${WOV_PROJECTTYPE}",
   "PROJECTTITLE"       : "${WOV_PROJECTTITLE}",
   "PROJECTDESCRIPTION" : "${WOV_PROJECTDESCRIPTION}",
+  "DATABASES"          : "${WOV_DATABASES}",
 
   "ARCHIVEREPOSITORY" : "${WOV_ARCHIVEREPOSITORY}",
   "ARCHIVEENV"        : "${WOV_ARCHIVEENV}",
@@ -345,6 +351,8 @@ EOF
   wov_stage-select ${SECRETFILE}_ STAGE ${WOV_STAGE} clean >> ${SECRETFILE}.7
   ${MV} ${SECRETFILE}.7  ${SECRETFILE}_
 
+  # Specific post-processing of variables
+  fPostBuildSecretsJSON 8 ${SECRETFILE}
 
   # FINAL: move it back into place
   ${MV} ${SECRETFILE}_  ${SECRETFILE}
@@ -384,6 +392,43 @@ EOF
   cp ${SECRETFILE} ${SECRETFILELAST}
 
   return ${SECRETDIFF}
+}
+
+
+# --------------------------------------------------------------------- 
+# Post processing rules
+# --------------------------------------------------------------------- 
+# $1 file to dump to
+# $2 SECRETFILE
+# --------------------------------------------------------------------- 
+function fPostBuildSecretsJSON()
+{
+  local cmd=""
+
+  # make and protect the file
+  echo "" > ${2}.${1}
+  chmod 600 ${2}.${1}
+
+  # build database host values for .DB.host by calling doResName
+  for db in ${DATABASES[@]}; do
+    local subhost=`jq -r ".${db}.subhost" ${2}_`
+    # echo "subhost : ${subhost}"
+    if [ "${cmd}" != "" ]; then cmd+=" | "; fi
+    cmd+=" .${db}.host=\"$(doResName DB ${WOV_CLUSTER} ${subhost})\" "
+    #echo "cmd : ${cmd}"
+  done
+  
+  # run command that adds all the hosts
+  if [ "${cmd}" != "" ]; then 
+    jq "${cmd}" "${2}_" >> ${2}.${1}
+    if [ $? != 0 ]; then
+      echo "ERROR: post build on secrets failed for cmd: '${cmd}'."
+      exit 1
+    fi
+
+    # Success, use the file
+    ${MV} ${2}.${1} ${2}_
+  fi
 }
 
 
