Bug fixes an also added smart command line completion. Wov-cmd and wov-ed are VASTLY improved due to a few lines fo code.

diff --git a/bin/wov-push-containers b/bin/wov-push-containers
--- a/bin/wov-push-containers
+++ b/bin/wov-push-containers
@@ -180,7 +180,8 @@ if [ "${BLOCK}" == "0" ]; then
         docker tag ${WOV_PROJECT}/${CONTAINER} ${WOV_ARCHIVEREPOSITORY}/${WOV_PROJECT}/${CONTAINER}:${WOV_STAGE}_${WOV_PVER}
 
         echo "    ... push container to: ${WOV_ARCHIVEREPOSITORY}/${WOV_PROJECT}/${CONTAINER}:${WOV_STAGE}_${WOV_PVER}"
-        R=$(docker push ${WOV_ARCHIVEREPOSITORY}/${WOV_PROJECT}/${CONTAINER}:${WOV_STAGE}_${WOV_PVER} 2>&1 )
+
+        R=$(docker push ${WOV_ARCHIVEREPOSITORY}/${WOV_PROJECT}/${CONTAINER}:${WOV_STAGE}_${WOV_PVER} 2>&1 | tee /dev/tty )
         if [ "$?" != "0" ]; then
           echo "R: ${R}"
           if [[ $R == 'name unknown'* ]]; then
@@ -196,7 +197,11 @@ if [ "${BLOCK}" == "0" ]; then
           else
             echo "      ... SUCCESS auto-login to AWS attempt"
             echo "    ... re-push container to: ${WOV_ARCHIVEREPOSITORY}/${WOV_PROJECT}/${CONTAINER}:${WOV_STAGE}_${WOV_PVER}"
-            docker push ${WOV_ARCHIVEREPOSITORY}/${WOV_PROJECT}/${CONTAINER}:${WOV_STAGE}_${WOV_PVER} 
+            R=$(docker push ${WOV_ARCHIVEREPOSITORY}/${WOV_PROJECT}/${CONTAINER}:${WOV_STAGE}_${WOV_PVER} 2>&1  | tee /dev/tty)
+            if [ "$?" != "0" ]; then
+              printf "\n\n  ...still errors: ${R}.\n"
+              exit 1
+            fi
           fi
         fi
 
diff --git a/bin/wov-pushcontainer-check b/bin/wov-pushcontainer-check
--- a/bin/wov-pushcontainer-check
+++ b/bin/wov-pushcontainer-check
@@ -87,6 +87,7 @@ done
 
 
 # Echoes 1 if found, 0 not found, 2 unknown, 3 if no repo
+# NOTE: echo to stderr since return value is stdout
 function fCheckForRemoteImage() 
 {
   local retval=2
@@ -98,7 +99,17 @@ function fCheckForRemoteImage()
     # do check
     RR=$(ecs-cli images ${WOV_PROJECT}/${WOV_PROJECT}${CONTAINER} 2>&1 )
     if [[ $RR == *"RepositoryNotFoundException"* ]]; then
-      printf "\n\nERROR: Repository Not Found. Create '${WOV_PROJECT}/${WOV_PROJECT}${CONTAINER}' in AWS CodeCommit, then try again.\n" 1>&2
+      printf "\n\nERROR: Docker Repository Not Found: Create '${WOV_PROJECT}/${WOV_PROJECT}${CONTAINER}' in AWS ElasticContainerService, then try again.\n" 1>&2
+      printf "   : https://console.aws.amazon.com/ecs\n\n" 1>&2
+      printf "   Open repo in browser for you? (no) " 1>&2
+      read A
+      if [[ $A == [yY][eE][sS] ]] || [[ $A == [yY] ]]; then
+        echo "    ... opening repo in browser" 1>&2
+        open https://console.aws.amazon.com/ecs &
+      else
+        echo "    ... skipping" 1>&2
+      fi
+
       retval=3
     elif [ "$RR" == "" ]; then
       retval=0
@@ -178,9 +189,11 @@ else
     fi
     if [ "${CH}" == "3" ]; then
       if [ $DOECHO -ge 1 ]; then echo "    ... no repo found."; fi
+      NEEDSBUILD=3
     fi
     if [ "${CH}" == "2" ]; then
       if [ $DOECHO -ge 1 ]; then echo "    ... some error or other."; fi
+      NEEDSBUILD=2
     fi
 
   # check remote repo version... since if the git version is diff from that, then need to build!!!
