Push and Deploy is working now due to linked package dependencies not working in issue https://github.com/woveon/wovtools/issues/50.
Test test032_wov-push-db.sh still fails. Probably an error in the test, not system.

Major:

- wov-git-check
  - rewrote it to clarify how it worked
  - needs another pass to clean it up fully and delete commented out code

- wov-push
  - overall, this fixes the bug of built containers not having the correct
    code on them due to locally developing packages which are linked.
  - This magic is in doCheckNodeJSLocallyLinkedDependency
  - does more checks on nodejs linked repositories by ensuring that the
    dependency in package.json actually matches to the linked package. this
    does a lot of change on commit versions.

Minor:

- wov
  - echoed new debug spew to devnull

- wov-bastion-connection
  - port checks were broken. fixed so wov-db calls have useful error messages now.
  - fixed some error messages

- fixed in multiple files the cluster secrets.json to use WOV_getClusterConfigDir / config.json. This fixed a lot of known/unknown bugs in code.

- wov-db
  - cleaned up the file

- wov-ed
  - updated to use wov-env-ops

- wov-log
  - added follow and no follow params

- updated some test cases

diff --git a/bin/wov-db b/bin/wov-db
--- a/bin/wov-db
+++ b/bin/wov-db
@@ -237,9 +237,11 @@ function doDBDataBuild()
       local finname="${fname::-4}"
       if [ ! -e "${WOV_BASEDIR}/wovtools/cache/data/${finname}" ] ||
          [ "${WOV_BASEDIR}/wovtools/data/${1}_const.js" -nt "${WOV_BASEDIR}/wovtools/cache/data/${finname}" ] ||
-         [ "${WOV_BASEDIR}/wovtools/data/${fname}" -nt "${WOV_BASEDIR}/wovtools/cache/data/${finname}" ]; then
+         [ "${WOV_BASEDIR}/wovtools/data/${fname}"      -nt "${WOV_BASEDIR}/wovtools/cache/data/${finname}" ]; then
         if [ ${DOECHO} -ge 1 ]; then echo "  ... compile ${finname}"; fi
-        WOV_BASEDIR=${WOV_BASEDIR} wov-compile -ds ${1} "${WOV_BASEDIR}/wovtools/cache/clusters/${WOV_CLUSTER}/secrets.json" "${WOV_BASEDIR}/wovtools/data/${fname}" > "${WOV_BASEDIR}/wovtools/cache/data/${finname}"
+        WOV_BASEDIR=${WOV_BASEDIR} wov-compile -ds ${1} \
+          "`WOV_getClusterConfigDir ${WOV_ORIGIN} ${WOV_CONTEXT}`/config.json" \
+          "${WOV_BASEDIR}/wovtools/data/${fname}" > "${WOV_BASEDIR}/wovtools/cache/data/${finname}"
       fi
 
     # or copy it over
@@ -282,18 +284,20 @@ function doDBDataCommand()
 }
 
 
+# --------------------------------------------------------------------- 
 # $1 - port
 # $2 - error message
+# --------------------------------------------------------------------- 
 function showConnectionFailure()
 {
   if [ "${1}" == "" ]; then
     >&2 printf "ERROR: No port specified. Configuration error.\n";
   else
-    wov-bastion-connection -q --test-port ${1}
+    wov-bastion-connection -q --test-port "${1}"
     if [ $? -ne 0 ]; then
-      >&2 printf "ERROR: Port ${1} is not open. Is your bastion connection open?\n";
+      l_error "Port ${1} is not open. Is your bastion connection open?"
     else
-      >&2 printf "$2";
+      l_error "$2"
     fi
   fi
 }
@@ -954,49 +958,45 @@ if [ ${WOV_DODEFAULTCOMMAND} != 0 ]; then
       rm ${SDF1}
 
     elif [ "${DB_OP}" == "command" ]; then
-      # Log into pod 'vh', run psql
-      #    echo "dbcommand  : \"${DB_COMMAND}\""
-      #    echo "dbcommand q: \"${DB_COMMAND[@]}\""
-      #    VARS=( "PGPASSWORD=${DB_PASSWORD}" "psql" "--tuples-only" "-h" "${DB_HOST}" "-U" "${DB_USERNAME}" "-d" "${DB_DATABASE}" "-c" "${DB_COMMAND}" )
-      #    kubectl exec -i vh -- /bin/bash -c "${VARS[@]}"
-      #    kubectl exec -i vh -- /bin/bash -c "PGPASSWORD=${DB_PASSWORD} psql --tuples-only -h ${DB_HOST} -U ${DB_USERNAME} -d ${DB_DATABASE} -c ${DB_COMMAND}"
-      #    if [ "${DB_HOST}" != "localhost" ]; then
-      #      kubectl exec -i vh -- /bin/bash -c "PGPASSWORD=${DB_PASSWORD} psql --tuples-only -h ${DB_HOST} -U ${DB_USERNAME} -d ${DB_DATABASE} -c \"${DB_COMMAND[@]}\""
-      #    else
-      #      PGPASSWORD=${DB_PASSWORD} psql --tuples-only -h ${DB_HOST} -U ${DB_USERNAME} -d ${DB_DATABASE} -c \"${DB_COMMAND[@]}\"
-      #    fi
 
       l_verbose "PGPASSWORD=XXX psql ${DB_HEADEROPTIONS} -p ${DB_PORT} -h ${DB_HOST} -U ${DB_USERNAME} -d ${DB_DATABASE} -c \"${DB_COMMAND[@]}\""
       R=$(PGPASSWORD="${DB_PASSWORD}" psql ${DB_HEADEROPTIONS} -p ${DB_PORT} -h ${DB_HOST} -U ${DB_USERNAME} -d ${DB_DATABASE} -c "${DB_COMMAND[*]}"  2>&1 ) ; Re=$?
-      #PGPASSWORD=${DB_PASSWORD} psql --tuples-only -p ${DB_PORT} -h ${DB_HOST} -U ${DB_USERNAME} -d ${DB_DATABASE} -c "${DB_COMMAND[*]}"
       if [ "${Re}" != "0" ]; then
-        if [ "$R" == "psql: FATAL:  database \"wovtools\" does not exist" ]; then
+        wov-bastion-connection -q --test-port ${DB_PORT}
+        if [ $? -ne 0 ]; then 
+          l_error "Port is not open. Did you give the wrong port? Is your bastion connection open?"
+        elif [ "$R" == "psql: FATAL:  database \"wovtools\" does not exist" ]; then
           printf "\n${R}\nERROR: did you init the database? 'wov-db ${WOVDBNAME} --wdb-init'\n"
           exit 1
+        else
+          l_ "${R}\n"
         fi
-        printf "${R}\n"
         showConnectionFailure "${DB_PORT}" "ERROR: could not connect\n"
         exit 1
       else
-        echo $R
+        l_ "$R"
       fi
-
 
     elif [ "${DB_OP}" == "file" ]; then
-      # copy file; exectute it in database, delete file
-      #    if [ "${DB_HOST}" != "localhost" ]; then
-      #      kubectl cp ${DB_FILE} vh:.${WOVDBNAME}.sql.$$
-      #      kubectl exec -i vh -- /bin/bash -c "PGPASSWORD=${DB_PASSWORD} psql -h ${DB_HOST} -U ${DB_USERNAME} -d ${DB_DATABASE} -f .${WOVDBNAME}.sql.$$"
-      #      kubectl exec -i vh -- /bin/bash -c "rm -f .${WOVDBNAME}.sql.$$"
-      #    else
-      #      PGPASSWORD=${DB_PASSWORD} psql -h ${DB_HOST} -U ${DB_USERNAME} -d ${DB_DATABASE} -f ${DB_FILE}
-      #    fi
-      PGPASSWORD="${DB_PASSWORD}" psql -p ${DB_PORT} -h ${DB_HOST} -U ${DB_USERNAME} -d ${DB_DATABASE} -f ${DB_FILE}
-      PGPASSWORDe=$?
-      if [ "$PGPASSWORDe" != "0" ]; then
+
+      set -x
+      R=$(PGPASSWORD="${DB_PASSWORD}" psql -p ${DB_PORT} -h ${DB_HOST} -U ${DB_USERNAME} -d ${DB_DATABASE} -f ${DB_FILE}) ; Re=$?
+      if [ ${Re} -ne 0 ]; then
+        wov-bastion-connection -q --test-port ${DB_PORT}
+        if [ $? -ne 0 ]; then 
+          l_error "Port is not open. Did you give the wrong port? Is your bastion connection open?"
+        elif [ "$R" == "psql: FATAL:  database \"wovtools\" does not exist" ]; then
+          printf "\n${R}\nERROR: did you init the database? 'wov-db ${WOVDBNAME} --wdb-init'\n"
+          exit 1
+        else
+          l_ "${R}\n"
+        fi
         showConnectionFailure "${DB_PORT}" "ERROR: could not connect\n"
         exit 1
+      else
+        l_ "$R"
       fi
+      set +x
 
     elif [ "${DB_OP}" == "" ]; then
       # Log into pod 'vh', run psql
@@ -1007,8 +1007,13 @@ if [ ${WOV_DODEFAULTCOMMAND} != 0 ]; then
       #    else
       #      PGPASSWORD=${DB_PASSWORD} psql -h ${DB_HOST} -U ${DB_USERNAME} -d ${DB_DATABASE}
       #    fi
-      PGPASSWORD="${DB_PASSWORD}" psql -p ${DB_PORT} -h ${DB_HOST} -U ${DB_USERNAME} -d ${DB_DATABASE}
-      if [ "$?" != "0" ]; then
+      PGPASSWORD="${DB_PASSWORD}" psql -p ${DB_PORT} -h ${DB_HOST} -U ${DB_USERNAME} -d ${DB_DATABASE}  ; Re=$?
+
+      #wov-bastion-connection -q --test-port ${DB_PORT}
+      #if [ $? -ne 0 ]; then 
+      #  l_error "Port is not open. Did you give the wrong port? Is your bastion connection open?"
+
+      if [ $Re -ne 0 ]; then
         showConnectionFailure "${DB_PORT}" "ERROR: could not connect\n  : is the db inited? 'wov-db --wdb-init'\n  : is the db created? 'wov-db --wdb-create'\n"
         exit 1
       fi
@@ -1035,47 +1040,39 @@ db.getCollectionNames().forEach(function(collname) {
 EOF
 )
 
-kubectl exec -it $(wov-p ${WOVDBNAME}-${WOV_STAGE} ) -- sh -c "mongo --quiet ${DB_DATABASE} --eval \"${DB_COMMAND}\""
-#    if [ "${DB_HOST}" != "localhost" ]; then
-#      kubectl exec -it vh -- /bin/bash -c "mongo --quiet mongodb://${DB_HOST}/${DB_DATABASE} --eval \"${DB_COMMAND}\""
-#    else
-#      mongo --quiet mongodb://${DB_HOST}/${DB_DATABASE} --eval \"${DB_COMMAND}\"
-#    fi
+      kubectl exec -it $(wov-p ${WOVDBNAME}-${WOV_STAGE} ) -- sh -c "mongo --quiet ${DB_DATABASE} --eval \"${DB_COMMAND}\""
 
+    elif [ "${DB_OP}" == "command" ]; then
+      kubectl exec -it $(wov-p ${WOVDBNAME}-${WOV_STAGE} ) -- sh -c "mongo --quiet ${DB_DATABASE} --eval \"${DB_COMMAND}\""
+      #    if [ "${DB_HOST}" != "localhost" ]; then
+      #      kubectl exec -it vh -- /bin/bash -c "mongo --quiet mongodb://${DB_HOST}/${DB_DATABASE} --eval \"${DB_COMMAND}\""
+      #    else
+      #      mongo --quiet mongodb://${DB_HOST}/${DB_DATABASE} --eval \"${DB_COMMAND}\"
+      #    fi
+    elif [ "${DB_OP}" == "file" ]; then
+      printf "\nFile: untested\n\n";
+      if [ "${DB_HOST}" != "localhost" ]; then
+        kubectl cp ${DB_FILE} vh:.${WOVDBNAME}.sql.$$
+        kubectl exec -it vh -- /bin/bash -c "mongo --quiet mongodb://${DB_HOST}/${DB_DATABASE} ${WOVDBNAME}.sql.$$"
+        kubectl exec -i vh -- /bin/bash -c "rm -f .${WOVDBNAME}.sql.$$"
+      else
+        mongo --quiet mongodb://${DB_HOST}/${DB_DATABASE} ${DB_FILE}
+      fi
+    elif [ "${DB_OP}" == "" ]; then
+      if [ $DOECHO -ge 1 ]; then doDatabaseConnectMessage; fi
 
-  elif [ "${DB_OP}" == "command" ]; then
-    kubectl exec -it $(wov-p ${WOVDBNAME}-${WOV_STAGE} ) -- sh -c "mongo --quiet ${DB_DATABASE} --eval \"${DB_COMMAND}\""
-    #    if [ "${DB_HOST}" != "localhost" ]; then
-    #      kubectl exec -it vh -- /bin/bash -c "mongo --quiet mongodb://${DB_HOST}/${DB_DATABASE} --eval \"${DB_COMMAND}\""
-    #    else
-    #      mongo --quiet mongodb://${DB_HOST}/${DB_DATABASE} --eval \"${DB_COMMAND}\"
-    #    fi
-  elif [ "${DB_OP}" == "file" ]; then
-    printf "\nFile: untested\n\n";
-    if [ "${DB_HOST}" != "localhost" ]; then
-      kubectl cp ${DB_FILE} vh:.${WOVDBNAME}.sql.$$
-      kubectl exec -it vh -- /bin/bash -c "mongo --quiet mongodb://${DB_HOST}/${DB_DATABASE} ${WOVDBNAME}.sql.$$"
-      kubectl exec -i vh -- /bin/bash -c "rm -f .${WOVDBNAME}.sql.$$"
-    else
-      mongo --quiet mongodb://${DB_HOST}/${DB_DATABASE} ${DB_FILE}
+      echo "entering pod ${WOVDBNAME}-${WOV_STAGE}"
+      kubectl exec -it $(wov-p ${WOVDBNAME}-${WOV_STAGE} ) -- sh -c "mongo --quiet ${DB_DATABASE}"
+      #    if [ "${DB_HOST}" != "localhost" ]; then
+      #      kubectl exec  -it vh -- /bin/bash -c "mongo --quiet mongodb://${DB_HOST}/${DB_DATABASE}"
+      #    else
+      #      mongo --quiet mongodb://${DB_HOST}/${DB_DATABASE}
+      #    fi
+
     fi
-  elif [ "${DB_OP}" == "" ]; then
-    if [ $DOECHO -ge 1 ]; then doDatabaseConnectMessage; fi
-
-    echo "entering pod ${WOVDBNAME}-${WOV_STAGE}"
-    kubectl exec -it $(wov-p ${WOVDBNAME}-${WOV_STAGE} ) -- sh -c "mongo --quiet ${DB_DATABASE}"
-    #    if [ "${DB_HOST}" != "localhost" ]; then
-    #      kubectl exec  -it vh -- /bin/bash -c "mongo --quiet mongodb://${DB_HOST}/${DB_DATABASE}"
-    #    else
-    #      mongo --quiet mongodb://${DB_HOST}/${DB_DATABASE}
-    #    fi
 
   fi
-
 else
   printf "\n\nERROR: Unknown database type of '${DB_TYPE}'. Probably need to implement it in wov-db, and ensure it is supported in vh container.\n"
   exit 1
-fi
-
-
 fi
diff --git a/bin/wov-git-check b/bin/wov-git-check
--- a/bin/wov-git-check
+++ b/bin/wov-git-check
@@ -1,6 +1,8 @@
 #!/usr/bin/env bash
 
 RETVAL=0
+ENSUREHEAD=0
+ENSUREVERSION=
 
 # ---------------------------------------------------------------------
 # ---------------------------------------------------------------------
@@ -9,9 +11,14 @@ function fDisplayOptions()
   cat <<EOF | fold -w ${FOLD} -s
 
 
-usage: `basename $0` [options] [path ...]
+usage: `basename $0` [options] [PATH ...]
 
 Checks that the git archives on path(s) are committed and pushed to origin.
+
+PATH - path to a git repo
+
+  --ensure-nodejs-version : ensure that the PATH's version 
+  --ensure-version X : ensure that the version at path is version X and that version has a remote version tagged
 
   -h : this help
   -q : quiet, no output
@@ -22,14 +29,101 @@ EOF
 
 . wov-env-ops fDisplayOptions "$@"
 
+
+
+# ---------------------------------------------------------------------
+# Check local changes are committed (i.e. status is cool with it)
+# $1 - path
+# ---------------------------------------------------------------------
+function doCheckCommit()
+{
+  local retval=0
+  local R=
+  local Re=
+
+  if [ $retval -eq 0 ]; then
+    l_verbose "  ...check for path variable"
+    if [ "$1" == "" ]; then
+      retval=1
+      l_error "No path supplied to Git repo."
+    fi
+  fi
+
+  if [ $retval -eq 0 ]; then
+    l_verbose "  ...check path exists"
+    if [ ! -e "$1" ]; then
+      retval=2
+      l_error "Path to Git repo does not exist '${1}'."
+    fi
+  fi
+
+  if [ $retval -eq 0 ]; then
+    l_verbose "  ...check repo status"
+    R=$(git -C "${1}" status -s) ; Re=$?
+    if [ $Re -ne 0 ]; then
+      retval=3
+      l_error "Failed calling 'status' on repo at '${1}'."
+    elif [ "${R}" != "" ]; then
+      retval=4
+      l_warn "Path '${1}': failed code/env commit-check. Check in your code/env values."
+      if [ $DOECHO -ge 2 ]; then
+        l_verbose "*** git status : start ************************************************"
+        git -C "${1}" status
+        l_verbose "*** git status : end **************************************************"
+      fi
+    fi
+  fi
+
+  if [ $retval -eq 0 ]; then l_verbose "SUCCESS: '${1}': wov-git-check commit code/env"; fi
+
+  return $retval
+}
+
+# ---------------------------------------------------------------------
+# Check local changes are pushed
+# NOTE: assume doCheckCommit already called which checks path
+# $1 - path
+# ---------------------------------------------------------------------
+function doCheckPush()
+{
+  local retval=0
+  local R=
+  local Re=
+
+  l_verbose '  ...check upstream and head commits are the same.'
+  R=$(test "$(git -C "${1}" rev-parse @{u})" = "$(git -C "${1}" rev-parse HEAD)" ); Re=$?
+  if [ $Re -ne 0 ] || [ "$R" != "" ]; then
+    retval=10
+    l_warn "'${1}': failed code/env push check. Push your archive."
+    if [ $DOECHO -ge 2 ]; then
+      l_verbose "*** git status : start ************************************************ "
+      git -C "${1}" status
+      l_verbose "*** git status : end ************************************************** "
+    fi
+  else
+    l_verbose "SUCCESS: '${1}': wov-push-check push code/env."
+  fi
+
+  return $retval
+}
+
+
 # ---------------------------------------------------------------------
 # Handle Params
 # ---------------------------------------------------------------------
 while [[ $1 =~ ^- ]]; do
 
-  l_error "***ERROR: unknown option '$1'."
-  fDisplayOptions
-  exit 1
+  if [ "${1}" == "--ensure-nodejs-linked" ]; then
+    shift
+    ENSURE_NJSLINKED=1
+    shift
+
+  else
+    l_error "***ERROR: unknown option '$1'."
+    fDisplayOptions
+    exit 1
+  fi
+
 done
 
 
@@ -39,57 +133,90 @@ else
   PATHS=${@}
 fi
 
+
 for p in ${PATHS}; do
 
-  # ---------------------------------------------------------------------
-  # Check code changes and added/removed files are committed into current branch.
-  # ---------------------------------------------------------------------
+  doCheckCommit $p
+  Re=$?
+  if [ $Re -ne 0 ]; then RETVAL=1; fi
 
-  # check current repo
-  R=$(cd ${p} && git status -s)
-  RR=${?}
-  if [ "$RR" != "0" ] || [ "$R" != "" ]; then
-    if [ $DOECHO -ge 1 ]; then
-      l_warn "directory '${p}': failed code/env commit-check. Check in your code/env values to Archive."
-    fi
-    if [ $DOECHO -ge 2 ]; then 
-      l_verbose "*** git status : start ************************************************" 
-      cd ${p} && git status
-      l_verbose "*** git status : end **************************************************"
-    fi
-    # RETVAL=$((RETVAL+1))
-    RETVAL=1
-  else
-    l_verbose "SUCCESS: '${p}': wov-push-check commit code/env"
+  if [ $Re -eq 0 ]; then
+    doCheckPush $p
+    Re=$?
+    if [ $Re -ne 0 ]; then RETVAL=1; fi
   fi
 
-
-  if [ "$RETVAL" == "0" ]; then
-    # ---------------------------------------------------------------------
-    # Check local changes are pushed
-    # ---------------------------------------------------------------------
-    # check code/env
-    # R=$(cd ${p} && git push -nq)
-    R=$(cd ${p} && test "$(git rev-parse @{u})" = "$(git rev-parse HEAD)" )
-    RR=${?}
-    if [ "$RR" != "0" ] || [ "$R" != "" ]; then
-      if [ $DOECHO -ge 1 ]; then
-        l_warn "'${p}': failed code/env push check. Push your archive."
-      fi
-      if [ $DOECHO -ge 2 ]; then 
-        l_verbose "*** git status : start ************************************************ " 
-        cd ${p} && git status
-        l_verbose "*** git status : end ************************************************** " 
-      fi
-      # RETVAL=$((RETVAL+4))
-      RETVAL=2
-    else
-      l_verbose "SUCCESS: '${p}': wov-push-check push code/env."
-    fi
-  fi
+#  if [ $Re -eq 0 ] && [ ${ENSURE_NJSLINKED} -eq 1 ]; then
+#    doCheckNJSLinked $p
+#    Re=$?
+#    if [ $Re -ne 0 ]; then RETVAL=1; fi
+#  fi
 
 done
 
-if [ "${RETVAL}" != "0" ]; then
-  exit ${RETVAL}
-fi
+exit ${RETVAL}
+
+#  if [ "$RETVAL" == "0" ]; then
+#    if [ ${ENSUREHEAD} -eq 1 ]; then
+#      l_verbose "... ensure head"
+#    doEnsureHead 
+#
+#
+#    # Version must be a specificly tagged git version
+#    # NOTE: npmjs is a separate versioning system (though it looks like git tags) so can't use in 
+#    #       local comparisons since there is no assurance they are the same.
+#    # NOTE: use 'np' to git checkin, push and tag all at once
+#    elif [ "${ENSUREVERSION}" != "" ]; then
+#      l_verbose "... ensure version '${ENSUREVERSION}'"
+#      l_ "1"
+#      git rev-list -n 1 HEAD
+#      l_ "2"
+#      git ls-remote
+##      l_ "3"
+##      git rev-list -n 1 "v${ENSUREVERSION}" 
+#      # ex. v0.1.64
+#      #AA=$(cat "${WOV_BASEDIR}/alywandata/package.json" | jq -r ".version")
+#      AB=$(cat "${WOV_BASEDIR}/alywandata/package.json" | jq -r '.dependencies["woveon-service"]')
+#
+#
+#      # l_ "yarn version : ${p} ${AA} ${AB}"
+#      # yarn info woveon-service versions --json | jq -r '.data | index( "0.1.65" ) '
+#
+#      l_ "AB ${AB}"
+#      APROTOCOL=( ${AB//:\/\// } )
+#      l_ "APROTOCOL '${APROTOCOL[0]}'" 
+#      if [ ${#APROTOCOL[@]} -ne 2 ]; then l_error "No protocol (ex. https, git-sshfor depdencncy version. Must be a link to a git repo."; exit 1; fi
+#      case "${APROTOCOL[0]}" in
+#        "https" | "git+https" | "git+ssh")
+#          l_ "URL protocol '${APROTOCOL[0]}'"
+#          ;;
+#        *)
+#          l_error "Bad protocol. Requires a URL to a git repo."
+#          exit 1
+#          ;;
+#      esac
+#
+#      AV=( ${AB//#/ } )
+#      if [ ${#AV[@]} -ne 2 ]; then l_error "No specific version number specified"; exit 1; fi
+#
+#      echo "VERSION ${AV[1]}"
+#
+#      l_verbose "  ...now make sure that tagged version exists in github"
+#      rtag=$(git ls-remote --tags origin "refs/tags/${AV[1]}") ; Re=$?
+#      if [ $Re -ne 0 ]; then
+#        l_error "Failed to connect to remote server"
+#        RETVAL=1
+#      elif [ "$rtag" != "" ]; then
+#        l_verbose "  ...found remote tagged repo in git."
+#      else
+#        RETVAL=1
+#      fi
+#
+#    fi
+#  fi
+#
+#done
+#
+#if [ "${RETVAL}" != "0" ]; then
+#  exit ${RETVAL}
+#fi
