Added a curses UI to wov-stage.

diff --git a/bin/wov-stage b/bin/wov-stage
--- a/bin/wov-stage
+++ b/bin/wov-stage
@@ -144,21 +144,21 @@ function doSetStage()
     retval=1
   else
 
-    if [ ${DOECHO} -ge 1 ]; then echo "... switching Kubernetes context to '${WOV_CLUSTER}-${WOV_PROJECT}-${1}'."; fi
+    if [ ${DOECHO} -ge 1 ]; then echo "  ... switching Kubernetes context to '${WOV_CLUSTER}-${WOV_PROJECT}-${1}'."; fi
     local R1=$(kubectl config use-context ${WOV_CLUSTER}-${WOV_PROJECT}-${1}) ; Re=$?
     if [ ${Re} != 0 ]; then
       >&2 echo "ERROR: failed to switch to Kubernetes context '${WOV_CLUSTER}-${WOV_PROJECT}-${1}'."
       >&2 echo "  : ${R1}"
     else
-      if [ ${DOECHO} -ge 2 ]; then echo "  ... success."; fi
+      if [ ${DOECHO} -ge 2 ]; then echo "    ... success."; fi
     fi
 
-    if [ ${DOECHO} -ge 1 ]; then echo "... switching git branch to '${1}'."; fi
+    if [ ${DOECHO} -ge 1 ]; then echo "  ... switching git branch to '${1}'."; fi
     git checkout ${1} 
     if [ "$?" != "0" ]; then
       >&2 echo "ERROR: failed to switch to git branch '${1}'."
     else
-      if [ ${DOECHO} -ge 2 ]; then echo "  ... success."; fi
+      if [ ${DOECHO} -ge 2 ]; then echo "    ... success."; fi
     fi
 
     retval=0
@@ -170,6 +170,26 @@ function doSetStage()
   . wov-ns-check
 
   return $retval
+}
+
+function doSelectStage()
+{
+  local STAGES=$(doListStages) ; Re=$?
+  if [ "$Re" != 0 ]; then echo "ERROR: failed getting stages."; exit 1; fi
+
+  local OPTIONS=""
+  for st in ${STAGES[@]}; do
+    OPTIONS+=" ${st} '${WOV_PROJECT}-${st}' "
+  done
+
+  exec 3>&1; result=$(dialog --keep-tite --title 'Stage Selection' --menu 'Select a stage' 15 80 6 ${OPTIONS} 2>&1 1>&3); ret=$? ; exec 3>&-
+  # echo "result ($ret): ${result} "
+  if [ "$ret" == "0" ]; then
+    if [ ${DOECHO} -ge 1 ]; then echo "... setting stage to ${result} : ${WOV_PROJECT}_${result}"; fi
+    doSetStage $result
+  else
+    exit $ret
+  fi
 }
 
 # ---------------------------------------------------------------------
@@ -228,6 +248,11 @@ while [[ $1 =~ ^- ]]; do
 done
 
 if [ $DIDCOMMAND == 0 ]; then
-  doSetStage $1
+  if [ $# == 0 ]; then
+    doSelectStage
+  else
+    doSetStage $1
+  fi
 fi
+
 
