Wov-env/wov-env-build updated to allow for global commands. Wov-deploy updated for kops and fixed for pushgin stages (updates to allow --dev     pushes broke stage pushes).

diff --git a/bin/wov-deploy b/bin/wov-deploy
--- a/bin/wov-deploy
+++ b/bin/wov-deploy
@@ -29,6 +29,10 @@ DEPLOYCONF_EXT=
 WOV_CUR_PVER=${WOV_PVER}
 WOV_CUR_SVER=${WOV_SVER}
 
+RECIPES=
+RECIPESCM=
+RECIPESSE=
+
 
 
 # --------------------------------------------------------------------- 
@@ -43,10 +47,37 @@ function doAddLabels()
     printf "\n\nERROR: missing namespace '${WOV_NS}'. Type : 'kubectl create namespace ${WOV_NS}' to create one.\n\n"
     exit 1
   fi
+  printf "  ..."
   kubectl label namespace ${WOV_NS} -v=0 --overwrite WOV_DEPLOYED=`date +%s` WOV_PVER=${WOV_PVER} WOV_SVER=${WOV_SVER}
    # --quiet=true
 }
 
+
+#  $1 - directory with cm/se k8s files
+#  $@ - named recipes, otherwise all from directory are used
+function doBuildRecipes()
+{
+  # Files for Configmap and Secrets file
+  CMDIR=${1}/cm
+  SEDIR=${1}/se
+  shift
+
+  # New microservice for each container if you give them on the command line, or just read the directory
+  RECIPES=( "$@" )
+  if [ "${#RECIPES[@]}" == "0" ]; then
+    #echo "CMDIR: ${CMDIR}"
+  #  RECIPES=( $(cd ${WOV_BASEDIR}/wovtools/containers && find * -maxdepth 0 -type f 2> /dev/null) )
+    RECIPESCM=( $(cd ${CMDIR} && find * -maxdepth 0 -type f 2> /dev/null) )
+    RECIPESSE=( $(cd ${SEDIR} && find * -maxdepth 0 -type f 2> /dev/null) )
+  else
+    RECIPESCM=$RECIPES
+    RECIPESSE=$RECIPES
+  fi
+  #echo "RECIPES: ${#RECIPES[@]} : ${RECIPES[@]}"
+  #echo "RECIPESCM: ${#RECIPESCM[@]} : ${RECIPESCM[@]}"
+  #echo "RECIPESSE: ${#RECIPESSE[@]} : ${RECIPESSE[@]}"
+
+}
 
 
 # --------------------------------------------------------------------- 
@@ -64,25 +95,8 @@ function doDeployConf()
   shift
   shift
 
-  # Files for Configmap file
-  CMDIR=${DEPLOYSRC}/cm
+  doBuildRecipes ${DEPLOYSRC} $@
 
-  # Files for Secrets file
-  SEDIR=${DEPLOYSRC}/se
-
-  # New microservice for each container if you give them on the command line, or just read the directory
-  RECIPES=( "$@" )
-  if [ "${#RECIPES[@]}" == "0" ]; then
-  #  RECIPES=( $(cd ${WOV_BASEDIR}/wovtools/containers && find * -maxdepth 0 -type f 2> /dev/null) )
-    RECIPESCM=( $(cd ${CMDIR} && find * -maxdepth 0 -type f 2> /dev/null) )
-    RECIPESSE=( $(cd ${SEDIR} && find * -maxdepth 0 -type f 2> /dev/null) )
-  else
-    RECIPESCM=$RECIPES
-    RECIPESSE=$RECIPES
-  fi
-  # echo "RECIPES: ${#RECIPES[@]} : ${RECIPES[@]}"
-  # echo "RECIPESCM: ${#RECIPESCM[@]} : ${RECIPESCM[@]}"
-  # echo "RECIPESSE: ${#RECIPESSE[@]} : ${RECIPESSE[@]}"
 
   # Create ConfigMap PLUGIN
   # --------------------------------------------------------------------- 
@@ -91,6 +105,7 @@ function doDeployConf()
     #local MSNAME=${WOV_PROJECT}${f}
     local MSNAME=${f}
     local CMFILE="${CMDIR}/${MSNAME}"          # full path to file
+    # echo "CMFILE1: ${CMFILE}"
 
     # delete existing configmap
     kubectl delete configmap "${MSNAME}${CONFEXT}" 2>&1 > /dev/null
@@ -102,7 +117,7 @@ function doDeployConf()
       # continue; 
     fi
 
-    # echo "CMFILE: ${CMFILE}"
+    #echo "CMFILE: ${CMFILE}"
     # Convert X=Y into ConfigMap commands in DATA
     DATA=()
     while read l; do
@@ -111,10 +126,13 @@ function doDeployConf()
       if [ "$d" != "" ]; then DATA+=("$d"); fi
     done <${CMFILE}
 
-    #echo "DATA: ${DATA[@]}"
+    # echo "DATA: ${DATA[@]}"
+    printf "  ..."
     kubectl create configmap "${MSNAME}${CONFEXT}" "${DATA[@]}"
     if [ "$?" != "0" ]; then
       printf "\nERROR: failed creating ConfigMap '${MSNAME}${CONFEXT}' from '${CMFILE}'.\n"
+      printf "CMFILE values: (should be 'k=v' format for K8s ConfigMap generation)\n"
+      cat ${CMFILE}
       exit 1
     fi
   done
@@ -143,11 +161,13 @@ function doDeployConf()
     done <${SEFILE}
 
     # Create and label secret
+    printf "  ..."
     kubectl create secret generic "${MSNAME}${CONFEXT}" "${DATA[@]}"
     if [ "$?" != "0" ]; then
       printf "\nERROR: failed creating Secret '${MSNAME}${CONFEXT}' from '${SEFILE}'.\n"
       exit 1
     fi
+    printf "  ..."
     kubectl label secret "${MSNAME}${CONFEXT}" --overwrite WOV_DEPLOYED=`date +%s` WOV_PVER=${WOV_PVER} WOV_SVER=${WOV_SVER}
     if [ "$?" != "0" ]; then printf "\nWARNING: failed labeling '${MSNAME}${CONFEXT}'. CONTINUING...\n"; fi
 
@@ -156,30 +176,50 @@ function doDeployConf()
 }
 
 
+# --------------------------------------------------------------------- 
 # If dev deploy, then might not have an image to use. test if aws image exists
 # NOTE: only for AWS ECR... other Docker registries will be problematic...
+#  $1 - recipe directory
+#  $* - named containers
+# --------------------------------------------------------------------- 
 function doCheckContainersExist()
 {
   local imageissues=()
 
-  if [ "${DEPLOYTYPE}" == "dev" ]; then
+  if [ $DOECHO -ge 2 ]; then echo "... testing container images exist"; fi
 
-    if [ $DOECHO -ge 2 ]; then echo "... testing container images exist"; fi
+  #local rdir=${WOV_CACHEDIR}/clusters/${WOV_CLUSTER}
+  local rdir="$1"
 
-    for f in ${RECIPES}; do
-      local img="${WOV_PROJECT}/${WOV_PROJECT}${f}"
-      local tag="${WOV_STAGE}_${WOV_PVER}"
+  local containers=()
+  for f in $( ls ${rdir}/*.yaml ); do
+    # local k=`yaml get $f kind`
+    local k=`grep -i 'kind' $f | sed 's/.*://g' | tr -d '[:space:]' | tr '[:upper:]' '[:lower:]'`
+    if [ "$k" == "deployment" ]; then
+      local kk=`basename $f`
+      kk="${kk%.*}"
+      containers+=("$kk")
+      if [ ${DOECHO} -ge 2 ]; then printf "  ... check for container $kk\n"; fi
+    fi
+  done
 
-      # test if image exists
-      aws ecr list-images --repository-name ${img} --filter=tagStatus=TAGGED | jq '.imageIds[].imageTag' | grep "${tag}" > /dev/null
-      if [ "$?" != "0" ]; then
-        echo "***WARNING*** : image '${img}:${tag}' does not exist in AWS ECR! This will fail to load pod."
-        imgissues+=( $f )
-      fi
-    done
+  for f in ${containers[@]}; do
 
-    if [ "${#imgissues}" != "0" ]; then echo "" ; echo "  run: 'wov-push-container ${imgissues[*]}'"; echo ""; fi
-  fi
+#    echo "test container: $f"
+    local img="${WOV_PROJECT}/${f}"
+    local tag="${WOV_STAGE}_${WOV_PVER}"
+
+    # test if image exists
+    aws ecr list-images --repository-name ${img} --filter=tagStatus=TAGGED | jq '.imageIds[].imageTag' | grep "${tag}" > /dev/null
+    if [ "$?" == "0" ]; then
+      if [ ${DOECHO} -ge 1 ]; then printf "  ... container $f:${tag} exists\n"; fi
+    else
+      echo "***WARNING*** : image '${img}:${tag}' does not exist in AWS ECR! This will fail to load pod."
+      imgissues+=( $f )
+    fi
+  done
+
+  if [ "${#imgissues}" != "0" ]; then echo "" ; echo "  run: 'wov-push-container ${imgissues[*]}'"; echo ""; fi
 }
 
 
@@ -197,7 +237,7 @@ function doDeployK8s()
 
   # Deploy the k8s files
   if [ $DOECHO -ge 1 ]; then echo "... deploying Kubernetes"; fi
-  if [ $DOECHO -ge 2 ]; then echo "  ... from ${K8SDIR}/k8s"; fi
+  if [ $DOECHO -ge 2 ]; then echo "  ... from ${K8SDIR}"; fi
 
   # If $# is not empty, then this is called with recipes, so convert those to files
   if [ "$#" != "0" ]; then
@@ -219,8 +259,9 @@ function doDeployK8s()
 
     # NOTE: using ^ and $ for exact match of string
     elif [ "$(jq '.nodeploy[] | test("'"^${f}$"'")' ${WOV_FILE_SECRETSMERGED})" == "true" ]; then
-      printf "...skipping '$f': as it is on the nodeploy list.\n"
+      printf "  ...skipping '$f': as it is on the nodeploy list.\n"
     else
+      printf "  ..."
       kubectl apply -f ${K8SDIR}/$f.yaml
     fi
   done
@@ -247,10 +288,11 @@ files   : all by default, or type them here and do individual only
  Deploy Options:
   --pver|--sver X : sets the Project and Secret version for roll-backs
   -f : force push
-  --vh : build vh (default)
-  --VH : no build VH
+  --vh : build vh configuration (default)
+  --VH : no build VH configuration
 
  Utility:
+  --check-containers : check that these containers exist in the container repository
   --conf-only : Only push configuration files (ConfigMaps and Secrets)
   --dry-run : pull files but don't deploy
   -r|--retain : retains the deployment values locally (potential security risk)
@@ -293,6 +335,8 @@ function doDeployDev()
     exit 1
   fi
 
+  if [ ${DOECHO} -ge 1 ]; then printf "... dev development\n"; fi
+
   # Ensure the cluster's environment (and vh if needed) is up to date
   if [ $DOECHO -ge 1 ]; then printf "  ... deploy cluster configuration '${WOV_CLUSTER}'.\n"; fi
   wov-env-build -q --cluster ${WOV_CLUSTER}
@@ -315,11 +359,11 @@ function doDeployDev()
     # Update the cluster to current environments
     doDeployK8s ${WOV_CACHEDIR}/clusters/${WOV_CLUSTER} $*
 
+
     # Point to development containers and make sure they are available
     doPatchDeployments $*
-    doCheckContainersExist $*
+    doCheckContainersExist ${WOV_CACHEDIR}/clusters/${WOV_CLUSTER}/k8s
   fi
-  set +x
 
 }
 
@@ -370,16 +414,17 @@ function doPatchDeployments()
     # patch for ${STAGE}_dev containers for deployment
     local patchport="{ \"spec\" : { \"template\" : { \"spec\" : { \"containers\" : [{ \"name\" : \"$d\", \"image\" : \"${cntr2}\"}]}}}}"
     #printf "    ${patchport}\n"
+    printf "  ..."
     kubectl patch deployment $d -p "$patchport"
     A=$?
     if [[ $A == 0 ]]; then
-      if [ $DOECHO -ge 2 ]; then printf "  ... patch success\n"; fi
+      if [ $DOECHO -ge 2 ]; then printf "    ... patch success\n"; fi
       RETVAL=0
     elif [[ $A == 1 ]]; then
-      if [ $DOECHO -ge 2 ]; then printf "  ... not patched\n"; fi
+      if [ $DOECHO -ge 2 ]; then printf "    ... not patched\n"; fi
       RETVAL=0
     else
-      if [ $DOECHO -ge 2 ]; then printf "  ... patch failed (error code $A)\n"; fi
+      if [ $DOECHO -ge 2 ]; then printf "    ... patch failed (error code $A)\n"; fi
       RETVAL=1
   fi
   done
@@ -396,48 +441,88 @@ function doDeployStage()
   fi
   printf "\n"
 
+#  # If deploying the latest PVER, check that all code is pushed to archive
+#  if [ "${WOV_CUR_PVER}" == "${WOV_PVER}" ]; then
+#    wov-git-check ${WOV_BASEDIR}
+#    R1=$?
+#    wov-git-check ${WOV_BASEDIR}/wovtools/secrets
+#    R2=$?
+#    if [ "$R1" != "0" ] || [ "$R2" != "0" ]; then exit 1; fi
+#  fi
+#  #printf " check : pver : ${WOV_PVER}   sver: ${WOV_SVER}\n"
+#
+#
+#  # Push containers if deploying current
+#  if [ "${WOV_CUR_SVER}" == "${WOV_SVER}" ]; then
+#    echo "  ... pushing to archive"
+#    wov-push-k8s -q
+#    if [ "$?" != "0" ]; then exit 1; fi
+#  fi
+#
+#  # If deploying the latest SVER, check that all env is pushed to archive
+#  if [ "${WOV_CUR_SVER}" == "${WOV_SVER}" ]; then
+#
+#    # Ensure the cluster's environment (and vh if needed) is up to date
+#    if [ $DOECHO -ge 1 ]; then printf "  ... build for cluster '${WOV_CLUSTER}'.\n"; fi
+#    wov-env-build -q --cluster ${WOV_CLUSTER}
+#    if [ "$?" != "0" ]; then exit 1; fi
+#    if [ "$BUILDVH" == "1" ]; then 
+#      if [ $DOECHO -ge 1 ]; then printf "  ... build for cluster 'vh'.\n"; fi
+#      wov-env-build -q --cluster vh; 
+#      if [ "$?" != "0" ]; then exit 1; fi 
+#    fi
+#
+#  fi
+#
+#  if [ "${WOV_CUR_SVER}" != "${WOV_SVER}" ]; then
+#    echo "ERROR: I don't think this below will work since it generates the Conf. "
+#    echo "       It should just push the k8s configmaps, secrets and k8s yaml."
+#    echo " TODO: Implement this"
+#    exit 1
+#  fi
+#
+#  # Check Containers exist
+#  doCheckContainersExist
+#
+#  # Pull environment from the Archive (that was just built)
+#  # --------------------------------------------------------------------- 
+#  #local ARCHBASE="$(getRelativeArchivePath) ${WOV_CLUSTER}"
+#  local ARCHBASE="$(getRelativeArchivePath ${WOV_CLUSTER})"
+#  local DEPLOYSRC=${WOV_CACHEDIR}/.deployments/${ARCHBASE}.$$
+#  mkdir -p ${DEPLOYSRC}
+#  if [ "$?" != "0" ]; then exit 1; fi
+#  chmod 700 ${DEPLOYSRC}
+#  if [ "$?" != "0" ]; then exit 1; fi
+#  echo "DEBUG PRINTONLY : aws s3 sync ${WOV_ARCHIVEENV}/${ARCHBASE} ${DEPLOYSRC}  --delete"
+#  aws s3 sync ${WOV_ARCHIVEENV}/${ARCHBASE} ${DEPLOYSRC}  --delete
+#
+#  # 
+#  if [ "${DRYRUN}" == "0" ]; then 
+#    if [ "${CONFONLY}" == "1" ]; then
+#      doDeployConf ${DEPLOYSRC} "null" $*
+#    else
+#      doAddLabels
+#      doDeployConf ${DEPLOYSRC} "null" $*
+#      doDeployK8s  ${DEPLOYSRC} $*
+#      rm -Rf ${DEPLOYSRC}
+#    fi
+#  fi
 
-  # Ensure the cluster's environment (and vh if needed) is up to date
-  if [ $DOECHO -ge 1 ]; then printf "  ... build for cluster '${WOV_CLUSTER}'.\n"; fi
-  wov-env-build -q --cluster ${WOV_CLUSTER}
-  if [ "$?" != "0" ]; then exit 1; fi
-  if [ "$BUILDVH" == "1" ]; then 
-    if [ $DOECHO -ge 1 ]; then printf "  ... build for cluster 'vh'.\n"; fi
-    wov-env-build -q --cluster vh; 
-    if [ "$?" != "0" ]; then exit 1; fi 
-  fi
 
-
-  # Deploy to cluster, the relevant K8s "stuff"
-  doDeployConf ${WOV_CACHEDIR}/clusters/${WOV_CLUSTER} "null" $*
-  if [ "$BUILDVH" == "1" ]; then doDeployConf ${WOV_CACHEDIR}/clusters/vh "vh" $*; fi
-
-
-  # If deploying the latest PVER, check that all code is pushed to archive
-  if [ "${WOV_CUR_PVER}" == "${WOV_PVER}" ]; then
-    wov-git-check ${WOV_BASEDIR}
-    R1=$?
-    wov-git-check ${WOV_BASEDIR}/wovtools/secrets
-    R2=$?
-    if [ "$R1" != "0" ] || [ "$R2" != "0" ]; then exit 1; fi
-  fi
-  #printf " check : pver : ${WOV_PVER}   sver: ${WOV_SVER}\n"
-
-  # If deploying the latest SVER, check that all env is pushed to archive
-  if [ "${WOV_CUR_SVER}" == "${WOV_SVER}" ]; then
-    echo "  ... pushing k8s to be sure"
-    wov-push-k8s -q
-    if [ "$?" != "0" ]; then exit 1; fi
-  fi
-
-  # Pull environment from the Archive
+  # Pull environment from the Archive (that was just built)
   # --------------------------------------------------------------------- 
-  local ARCHBASE="$(getRelativeArchivePath) ${WOV_CLUSTER}"
-  local DEPLOYSRC=${WOV_CACHDIR}/.deployments/${ARCHBASE}.$$
+  local ARCHBASE="$(getRelativeArchivePath ${WOV_CLUSTER})"
+  local DEPLOYSRC=${WOV_CACHEDIR}/.deployments/${ARCHBASE}.$$
   mkdir -p ${DEPLOYSRC}
+  if [ "$?" != "0" ]; then exit 1; fi
   chmod 700 ${DEPLOYSRC}
-  echo "DEBUG PRINTONLY : aws s3 sync ${WOV_ARCHIVEENV}/${ARCHBASE} ${DEPLOYSRC}  --delete"
-  # aws s3 sync ${WOV_ARCHIVEENV}/${ARCHBASE} ${DEPLOYSRC}  --delete
+  if [ "$?" != "0" ]; then exit 1; fi
+
+  if [ ${DOECHO} -ge 1 ]; then printf "...pulling deployment from Archive : '${WOV_ARCHIVEENV}/${ARCHBASE}'\n"; fi
+  aws s3 sync --quiet  ${WOV_ARCHIVEENV}/${ARCHBASE} ${DEPLOYSRC}  --delete
+
+  # Check Containers exist before deploying
+  doCheckContainersExist ${DEPLOYSRC}/k8s
 
   if [ "${DRYRUN}" == "0" ]; then 
     if [ "${CONFONLY}" == "1" ]; then
@@ -449,6 +534,7 @@ function doDeployStage()
       rm -Rf ${DEPLOYSRC}
     fi
   fi
+
 }
 
 
@@ -490,6 +576,10 @@ while [[ $1 =~ ^- ]]; do
     BUILDVH=0
 
 
+  elif [ "$1" == "--check-containers" ]; then
+    shift
+    doCheckContainersExist ${WOV_CACHEDIR}/clusters/${WOV_CLUSTER}/k8s
+    exit 0
 
 
 
diff --git a/bin/wov-env b/bin/wov-env
--- a/bin/wov-env
+++ b/bin/wov-env
@@ -7,6 +7,7 @@ SED=`which gsed`
 HAS_SECRET=0
 PROVIDERVARS=()
 RANCLUSTER=0
+#GLOBALCOMMAND=
 
 
 function fWovEnvDisplayOptions()
@@ -36,6 +37,7 @@ Command Options:
   --vh-label    : vh label in DockerHub repo
  
   Basic Environment Configuration:
+  -g/--global X : target output for another context (not from Kubernetes)  NOTE: must be 1st param
   -e            : echo the output with newlines
   -E            : echo the output on one line (bash executable)
   -p/--provider : run cluster config as well (WAS -c/--cluster) FIXME|TODO
@@ -62,6 +64,7 @@ Example Usage:
 EOF
 }
 if [ "$1" == '--help' ] || [ "$1" == '-h' ]; then fWovEnvDisplayOptions; exit 0; fi
+if [ "$1" == '-g' ] || [ "$1" == '--global' ]; then shift; GLOBALCOMMAND=$1; shift; fi
 
 
 # --------------------------------------------------------------------- 
@@ -207,7 +210,11 @@ function fBuildSecret
 
 # vars from Kubernetes
 # --------------------------------------------------------------------- 
-export WOV_CONTEXT="$(kubectl config current-context)"
+if [ "$GLOBALCOMMAND" != "" ]; then 
+  export WOV_CONTEXT=$GLOBALCOMMAND; 
+else
+  export WOV_CONTEXT="$(kubectl config current-context)"
+fi
 OLDIFS=$IFS
 IFS='-'
 array=( $WOV_CONTEXT )
@@ -419,7 +426,12 @@ function fConfGeneration()
 
 #  R+=( WOV_STAGE=${WOV_STAGE} WOV_ME=${WOV_ME} )
 
-  # echo "R: ${R[*]}"
+#  echo "R: ${R[*]}"
+  if [[ "${R[@]}" =~ "[WARN"  ]]; then
+    echo "${R[*]}"
+    printf "\n***ERROR(wov-env): warning message in generation of environment variables. Stopping.\n\n"
+    exit 2
+  fi
 
   local SEP=' '
   if [ "$3" == "1" ]; then SEP='\n'; fi
@@ -427,10 +439,10 @@ function fConfGeneration()
   for f in "${R[@]}"; do
     printf "$f$SEP"
   done
-  if [[ "${R[@]}" =~ "[WARN"  ]]; then
-    printf "\n***ERROR(wov-env): warning message in generation of environment variables. Stopping.\n\n"
-    exit 1
-  fi
+  #if [[ "${R[@]}" =~ "[WARN"  ]]; then
+  #  printf "\n***ERROR(wov-env): warning message in generation of environment variables. Stopping.\n\n"
+  #  exit 2
+  #fi
 }
 
 
diff --git a/bin/wov-env-build b/bin/wov-env-build
--- a/bin/wov-env-build
+++ b/bin/wov-env-build
@@ -8,9 +8,11 @@ HAS_BUILDENV=0
 #DONSIGNORE=0
 DOFORCE=0
 LOCALCONTEXT=
+GLOBALCOMMAND=
 
 CONFEXT=
   # see wov-push-k8s
+
 
 # --------------------------------------------------------------------- 
 # --------------------------------------------------------------------- 
@@ -29,6 +31,8 @@ Builds WovTool configurations for secrets (-s) and clusters (-c) (K8s, ConfigMap
   --clean        : cleans the cache
   -f/--force     : force build of secrets and cluster
 
+  -g/--global X  : global rules; ignore project and namespaces (TODO FIX: redundant with secrets and cluster X)
+
   -s/--secrets X : build secrets for cluster X
   -c/--cluster X : build the secret and Kubernetes files for cluster X
   --local        : build local secrets
@@ -40,6 +44,14 @@ EOF
 if [ "$1" == '--help' ] || [ "$1" == '-h' ]; then fWovEnvBuildDisplayOptions; exit 0; fi
 
 
+if [ "$1" == '--global' ] || [ "$1" == '-g' ]; then 
+  shift; 
+  export GLOBALCOMMAND="$1";
+#  export WOV_PROJECT="global";
+#  export WOV_STAGE="global";
+  shift; 
+fi
+
 
 # --------------------------------------------------------------------- 
 # Import Env 
@@ -49,7 +61,23 @@ set ""
 . wov-env
 set -- "${buildargs[@]}"
 
+# --------------------------------------------------------------------- 
+# Global checks
+#if [ "$1" == '--global' ] || [ "$1" == '-g' ]; then 
+#  GLOBALCOMMAND=1; 
+#  shift; 
+#  export WOV_PROJECT="global"
+#  export WOV_STAGE="global"
+#fi
+#echo "WOV_PROJECT ${WOV_PROJECT} ${WOV_STAGE}"
+if [ "$GLOBALCOMMAND" != "" ]; then
+  export WOV_PROJECT="global"
+  export WOV_STAGE="global"
+fi
 
+# --------------------------------------------------------------------- 
+# Namespace checks
+if [ "$GLOBALCOMMAND" == "" ]; then
 wov-ns-check
 if [ "$?" != "0" ]; then
   if [ "${WOV_KPROJECT}" != "${WOV_WPROJECT}" ]; then
@@ -63,6 +91,7 @@ if [ "$?" != "0" ]; then
     printf "WOV_STAGE/KSTAGE/GSTAGE      : '${WOV_STAGE}' '${WOV_KSTAGE}' '${WOV_GSTAGE}'\n"
     exit 1
   fi
+fi
 fi
 
 # --------------------------------------------------------------------- 
@@ -143,6 +172,7 @@ function fBuildSecrets()
   fi
 
 
+
   # ---------------------------------------------------------------------
   # Build temp secret file
   # ---------------------------------------------------------------------
@@ -216,8 +246,8 @@ EOF
   # - concat child attributes into parent that are prefixed by CLUSTERx, where x is your CLUSTER
   echo "" > ${SECRETFILE}.3
   chmod 600 ${SECRETFILE}.3
-  if [[ $DOECHO -ge 1 ]]; then   echo "  ... using cluster     : ${WOV_CLUSTER}"; fi
-  wov_stage-select ${SECRETFILE}_ CLUSTER${WOV_CLUSTER} >> ${SECRETFILE}.3
+  if [[ $DOECHO -ge 1 ]]; then   echo "  ... using cluster     : ${CLUSTER}"; fi
+  wov_stage-select ${SECRETFILE}_ CLUSTER${CLUSTER} >> ${SECRETFILE}.3
   ${MV} ${SECRETFILE}.3  ${SECRETFILE}_
 
 
@@ -272,7 +302,10 @@ EOF
 
   else
     if [ "$DOECHO" == "2" ]; then echo "  ... no secretsmods entry for cluster: ${CLUSTER}"; fi
+    ${MV} ${SECRETFILE}_  ${SECRETFILE}
   fi
+
+
 
   # mark as secret being updated
   HAS_SECRET=1
@@ -401,7 +434,7 @@ fBuildClusterDir()
   if [ "${#RECIPES[@]}" == "0" ]; then
     RECIPES=$(cd ${WOV_BASEDIR}/wovtools/containers && find * -maxdepth 0 -type f 2> /dev/null)
   fi
-  # echo "Container Recipes: ${RECIPES}"
+  #echo "Container Recipes: ${RECIPES}"
 
   # ensure directories
   mkdir -p  "${CLUSTER_DIR}/cm"
@@ -439,13 +472,25 @@ fBuildClusterDir()
       touch ${CMFILE}
       chmod 600 ${CMFILE}
       wov-env --cluster ${CLUSTER} --cm ${MICROSERVICE} >> ${CMFILE} 2>&1
-      if [ "$?" != "0" ]; then
+      local a=$?
+      if [ "$a" == "2" ]; then
+        printf "ERROR: failed generating configmap in cluster: '${CLUSTER}' for microservice: '${MICROSERVICE}'.\n" >&2
+        cat ${CMFILE}
+        exit 1
+      fi
+      if [ "$a" != "0" ]; then
         rm ${CMFILE}
         CMFILE="${CMFILE2}"
         if [ "$hasbuiltbasecm" == "0" ]; then
           if [[ $DOECHO -ge 2 ]]; then echo "  ... using config for ${WOV_PROJECT}, instead of ${MICROSERVICE}"; fi
           wov-env --cluster ${CLUSTER} --cm ${WOV_PROJECT} >> ${CMFILE}
-          if [ "$?" != "0" ]; then exit 1; fi
+          local a=$?
+          if [ "$a" == "2" ]; then
+            printf "ERROR: failed generating configmap in cluster: '${CLUSTER}' for project: '${WOV_PROJECT}'.\n" >&2
+            cat ${CMFILE}
+            exit 1
+          fi
+          if [ "$a" != "0" ]; then exit 1; fi
           hasbuiltbasecm=1
           if [ "${DOECHO}" == "2" ]; then echo "  ... compiled ${CMFILE}."; fi
         fi
@@ -480,11 +525,23 @@ fBuildClusterDir()
       touch ${SEFILE}
       chmod 600 ${SEFILE}
       wov-env --cluster ${CLUSTER} --se ${MICROSERVICE} >> ${SEFILE} 2>&1
-      if [ "$?" != "0" ]; then
+      local a=$?
+      if [ "$a" == "2" ]; then
+        printf "ERROR: failed generating configmap in cluster: '${CLUSTER}' for microservice: '${MICROSERVICE}'.\n" >&2
+        cat ${SEFILE}
+        exit 1
+      fi
+      if [ "$a" != "0" ]; then
         rm ${SEFILE}
         SEFILE="${SEFILE2}"
         if [ "$hasbuiltbasese" == "0" ]; then
           wov-env --cluster ${CLUSTER} --se ${WOV_PROJECT} >> ${SEFILE}
+          local a=$?
+          if [ "$a" == "2" ]; then
+            printf "ERROR: failed generating configmap in cluster: '${CLUSTER}' for project: '${WOV_PROJECT}'.\n" >&2
+            cat ${SEFILE}
+            exit 1
+          fi
           if [ "$?" != "0" ]; then exit 1; fi
           hasbuiltbasese=1
           if [ "${DOECHO}" == "2" ]; then echo "  ... compiled ${SEFILE}."; fi
@@ -539,6 +596,10 @@ while [[ $1 =~ ^- ]]; do
     shift
     fBuildSecrets $1
     shift
+
+  elif [ "$1" == "-g" ] || [ "$1" == "--global" ]; then
+    printf "\n\nERROR: '$1' needs to be first param in args array. Retype your command.\n\n"
+    exit 1
 
   elif [ "$1" == "-c" ] || [ "$1" == "--cluster" ]; then
     shift
