Ncurses GUI for logging

diff --git a/bin/wov-db-connect b/bin/wov-db-connect
--- a/bin/wov-db-connect
+++ b/bin/wov-db-connect
@@ -42,6 +42,8 @@ databaseserver - the name of a database server in the project. assumes conf/[dat
   -h : this help
   -q/-v : quiet/verbose
 
+  --schema      : return the db's schema
+
 About commands... you have to be careful about quotes as both bash and psql are very particular. Here, use single quotes so '*' is not expanded, and quote the single quote so mydatabase is interpret properly by postgres.
 
 ex. -c 'SELECT * FROM logs WHERE database=\'mydatabase\' ORDER BY id DESC LIMIT 1'
@@ -110,6 +112,9 @@ DB_PORT=${!DB_PORT}
 #DB_PORT=$(wov-bastion --bhost ${WOV_CLUSTER}-bastion --ldp ${DATABASESERVER})
 #DB_HOST=localhost   # bastion
 
+
+# --------------------------------------------------------------------- 
+# --------------------------------------------------------------------- 
 function doDatabaseConnectMessage()
 {
   printf "\n\n"
@@ -120,6 +125,20 @@ function doDatabaseConnectMessage()
   printf "  Host     : ${DB_HOST}\n"
   printf "  Database : ${DB_DATABASE}\n\n"
 }
+
+
+# --------------------------------------------------------------------- 
+# --------------------------------------------------------------------- 
+function setAsAdmin()
+{
+  DB_USERNAME="$(wov-env --var WOV_${DATABASESERVER}_admin_username)"
+  DB_PASSWORD="$(wov-env --var WOV_${DATABASESERVER}_admin_password)"
+  if [ "${DB_USERNAME}" == "" ] || [ "${DB_PASSWORD}" == "" ]; then
+    printf "\n\nERROR: Setting as admin, but you have no admin configured. Ensure WOV_${DATABASESERVER}_admin_[username/password] is configured in your secrets.\n\n"
+    exit 1
+  fi
+}
+
 
 # ---------------------------------------------------------------------
 # Handle Params
@@ -138,6 +157,10 @@ while [[ $1 =~ ^- ]]; do
     shift
     read DB_PASSWORD
     shift
+
+  elif [ "$1" == "--admin" ]; then
+    shift
+    setAsAdmin
 
 #  elif [ "$1" == "-n" ] || [ "$1" == "--namespace" ]; then
 #    shift
@@ -222,7 +245,7 @@ if [ "${DB_TYPE}" == "postgres" ]; then
 #      PGPASSWORD=${DB_PASSWORD} pg_dump -h ${DB_HOST} -U ${DB_USERNAME} -d ${DB_DATABASE} -s
 #    fi
 
-    PGPASSWORD=${DB_PASSWORD} pg_dump -p ${DB_PORT} -h ${DB_HOST} -U ${DB_USERNAME} -d ${DB_DATABASE} -s
+    PGPASSWORD="${DB_PASSWORD}" pg_dump -p ${DB_PORT} -h ${DB_HOST} -U ${DB_USERNAME} -d ${DB_DATABASE} -s
     if [ "$?" != "0" ]; then
       printf "\n\nERROR: could not connect... have you tunneled to the bastion server?\n\n"
     fi
@@ -240,7 +263,7 @@ if [ "${DB_TYPE}" == "postgres" ]; then
 #      PGPASSWORD=${DB_PASSWORD} psql --tuples-only -h ${DB_HOST} -U ${DB_USERNAME} -d ${DB_DATABASE} -c \"${DB_COMMAND[@]}\"
 #    fi
 
-    PGPASSWORD=${DB_PASSWORD} psql ${DB_HEADEROPTIONS} -p ${DB_PORT} -h ${DB_HOST} -U ${DB_USERNAME} -d ${DB_DATABASE} -c "${DB_COMMAND[*]}"
+    PGPASSWORD="${DB_PASSWORD}" psql ${DB_HEADEROPTIONS} -p ${DB_PORT} -h ${DB_HOST} -U ${DB_USERNAME} -d ${DB_DATABASE} -c "${DB_COMMAND[*]}"
     #PGPASSWORD=${DB_PASSWORD} psql --tuples-only -p ${DB_PORT} -h ${DB_HOST} -U ${DB_USERNAME} -d ${DB_DATABASE} -c "${DB_COMMAND[*]}"
     if [ "$?" != "0" ]; then
       printf "\n\nERROR: could not connect... have you tunneled to the bastion server?\n\n"
@@ -256,10 +279,12 @@ if [ "${DB_TYPE}" == "postgres" ]; then
 #    else
 #      PGPASSWORD=${DB_PASSWORD} psql -h ${DB_HOST} -U ${DB_USERNAME} -d ${DB_DATABASE} -f ${DB_FILE}
 #    fi
-    PGPASSWORD=${DB_PASSWORD} psql -p ${DB_PORT} -h ${DB_HOST} -U ${DB_USERNAME} -d ${DB_DATABASE} -f ${DB_FILE}
+set -x
+    PGPASSWORD="${DB_PASSWORD}" psql -p ${DB_PORT} -h ${DB_HOST} -U ${DB_USERNAME} -d ${DB_DATABASE} -f ${DB_FILE}
     if [ "$?" != "0" ]; then
       printf "\n\nERROR: could not connect... have you tunneled to the bastion server?\n\n"
     fi
+    set +x
 
   elif [ "${DB_OP}" == "" ]; then
     # Log into pod 'vh', run psql
@@ -271,7 +296,7 @@ if [ "${DB_TYPE}" == "postgres" ]; then
 #      PGPASSWORD=${DB_PASSWORD} psql -h ${DB_HOST} -U ${DB_USERNAME} -d ${DB_DATABASE}
 #    fi
   set -x
-    PGPASSWORD=${DB_PASSWORD} psql -p ${DB_PORT} -h ${DB_HOST} -U ${DB_USERNAME} -d ${DB_DATABASE}
+    PGPASSWORD="${DB_PASSWORD}" psql -p ${DB_PORT} -h ${DB_HOST} -U ${DB_USERNAME} -d ${DB_DATABASE}
     if [ "$?" != "0" ]; then
       printf "\n\nERROR: could not connect... have you tunneled to the bastion server?\n\n"
     fi
diff --git a/bin/wov-push-db b/bin/wov-push-db
--- a/bin/wov-push-db
+++ b/bin/wov-push-db
@@ -87,9 +87,11 @@ function doGetDBPVER()
   local DB_PVER=$(wov-db-connect $i -q -d wovtools -c "SELECT * FROM logs WHERE database='$1' ORDER BY id DESC LIMIT 1;" 2> /dev/null |  cut -d'|' -f5)
 #  local DB_PVER=$(wov-db-connect $i -q -d wovtools -c 'SELECT * FROM logs WHERE database=\''"$1"'\' ORDER BY id DESC LIMIT 1;' 2> /dev/null |  cut -d'|' -f5)
 #  printf "DB_PVER : $DB_PVER"
-  if [ "$?" != "0" ]; then 
-    printf "\n\nERROR: failed to find wovtools logs on database server $1.\n\n"; 
-    printf "  NOTE: if the datbaseserver is not inited, run:\n"
+  local a=$?
+  if [ "$a" != "0" ]; then 
+    printf "\n\nERROR: failed to connect to database wovtools, table logs, on database server $1.\n\n"; 
+    printf "  ...could be a bastion issue, or a privileges issue. ERROR CODE $a\n"
+    printf "  OLD > NOTE: if the datbaseserver is not inited, run:\n"
     printf "    'wov-db-cloud -D ${1} -I'\n\n"   
   else
     retval=0
@@ -295,7 +297,7 @@ function doPushCheck()
       elif [ "${chk_1}" == "T" ]; then # 4 is false then
         printf "FAILED: if you have db schema changes, you need to have deltas in registry to account.\n"
         printf "\n  run: 'wov-push-db -v --any-push-blockage' for more info.\n"
-        printf "\nTo get current schema of database X: 'wov-db-cloud -D X --schema'\n"
+        printf "\nTo get current schema of database X: 'wov-db-connect DBNAME --schema' (ex. apidb)\n"
   #    elif [ "${chk_4}" == "T" ]; then # 1 is false then
   #      printf "FAILED: if you have deltas in registry, you need to have db schema changes to account.\n"
       fi
@@ -503,6 +505,7 @@ done
 
 
 
+echo ".. starting"
 retval=1
 if [ "$DOACTION" == "check" ]; then
 
