Lots of small changes.

diff --git a/bin/wov-cd b/bin/wov-cd
--- a/bin/wov-cd
+++ b/bin/wov-cd
@@ -3,6 +3,78 @@
 DOECHO=1
 FOLD=140
 
+
+# ---------------------------------------------------------------------
+# ---------------------------------------------------------------------
+function fDisplayOptions()
+{
+  cat <<EOF | fold -w ${FOLD} -s
+
+
+usage: . `basename $0` {options} [project]
+
+Changes directory to the *project* directory. These projects are defined in the wovtools file, found in your HOME directory.
+
+NOTE: $HOME/.wovtools is a JSON file with .projects.{}, where each entry in .projects has a '.dir' entry, corresponding to the project directory.
+
+NOTE2: Call with the '.' in front, or set a line in your .bash_profile :
+  function wcd() {
+    . wov-cd $*
+  }
+
+ex. $HOME/.wovtools: { "projects" : { "myproject" : { "dir" : "/path/to/project" } } }
+
+  -q : quiet output
+  -v : verbose output
+  -h/--help : this help
+  -l : list projects
+
+EOF
+}
+
+
+# ---------------------------------------------------------------------
+# ---------------------------------------------------------------------
+function doListProjects()
+{
+  jq -r ".projects" ${HOME}/.wovtools
+}
+
+
+# ---------------------------------------------------------------------
+# Handle Params
+# ---------------------------------------------------------------------
+while [[ $1 =~ ^- ]]; do
+
+  if [ "$1" == "-q" ]; then
+    shift
+    DOECHO=0
+
+  elif [ "$1" == "-v" ]; then
+    shift
+    DOECHO=2
+
+  elif [ "$1" == "-h" ] || [ "$1" == "--help" ]; then
+    fDisplayOptions
+    exit 0
+
+  elif [ "$1" == "-l" ]; then
+    shift
+    doListProjects
+    exit 0
+
+  else
+    echo
+    echo "***ERROR: unknown option '$1'."
+    echo
+    fDisplayOptions
+    exit 1
+  fi
+done
+
+
+
+
 if [ ! -e ${HOME}/.wovtools ]; then 
   printf "\n\nERROR: no .wovtools file in home directory.\n" 1>&2
 fi
@@ -25,9 +97,11 @@ if [ "$#" == 1 ]; then
         printf "\n\nERROR: no directory '$D$D1'.\n" 1>&2
       else
         cd $GO
-        printf "\n---- project '$P' : $GO\n"
-        sleep .5
-        ls
+        if [ ${DOECHO} -ge 1 ]; then
+          printf "\n---- project '$P' : $GO\n"
+          sleep .5
+          ls
+        fi
       fi
     fi
   fi
diff --git a/bin/wov-deploy b/bin/wov-deploy
--- a/bin/wov-deploy
+++ b/bin/wov-deploy
@@ -4,6 +4,10 @@
 # --------------------------------------------------------------------- 
 # Import Env 
 # --------------------------------------------------------------------- 
+if [ ! -z ${WOV_stagemod+x} ]; then
+  printf "\nERROR: Can't have WOV_stagemod set when deploying content.\n\n"
+  exit 1
+fi
 deployenvargs=( "$@" )
 set ""
 . wov-env
@@ -272,9 +276,10 @@ if [ "${DRYRUN}" == "0" ]; then
   if [ "${CONFONLY}" == "1" ]; then
     doDeployConf
   else
+    k8ses=( $* )
     doAddLabels
     doDeployConf
-    doDeployK8s "$*"
+    doDeployK8s $k8ses
     doCleanUp
   fi
 fi
diff --git a/bin/wov-push b/bin/wov-push
--- a/bin/wov-push
+++ b/bin/wov-push
@@ -8,6 +8,10 @@ BLOCK=0
 # ---------------------------------------------------------------------
 # Build right before to update any files
 # ---------------------------------------------------------------------
+if [ ! -z ${WOV_stagemod+x} ]; then
+  printf "\nERROR: Can't have WOV_stagemod set when pushing content.\n\n"
+  exit 1
+fi
 wov-build -e
 
 # ---------------------------------------------------------------------
diff --git a/bin/wov-push-containers b/bin/wov-push-containers
--- a/bin/wov-push-containers
+++ b/bin/wov-push-containers
@@ -4,6 +4,10 @@
 # --------------------------------------------------------------------- 
 # Import Env 
 # --------------------------------------------------------------------- 
+if [ ! -z ${WOV_stagemod+x} ]; then
+  printf "\nERROR: Can't have WOV_stagemod set when pushing content.\n\n"
+  exit 1
+fi
 pushcontainersargs=( "$@" )
 set ""
 . wov-env
@@ -37,9 +41,12 @@ function fDisplayOptions()
   cat <<EOF | fold -w ${FOLD} -s
 
 
-usage: `basename $0` [options] containers ...
+usage: `basename $0` [options] {containercode ...}
 
 Runs the recipe scripts and if there is a change, build the containers.
+
+ex. `basename $0` -f ggg hhh  
+    -> for project iii,  forces the building of containers iiiggg and iiihhh
 
   --key X : ssh key to add ex. ${HOME}/.ssh/id_rsa
   -h : this help
diff --git a/bin/wov-pushcontainer-check b/bin/wov-pushcontainer-check
--- a/bin/wov-pushcontainer-check
+++ b/bin/wov-pushcontainer-check
@@ -8,6 +8,10 @@ LASTCHECKFORREMOTEIMAGE=-1
 # ---------------------------------------------------------------------
 # Import Env
 # ---------------------------------------------------------------------
+if [ ! -z ${WOV_stagemod+x} ]; then
+  printf "\nERROR: Can't have WOV_stagemod set when pushing content.\n\n"
+  exit 1
+fi
 pushargs=( "$@" )
 set ""
 . wov-env
