Adding in ability to build the vh container. Lots of fixes.

diff --git a/bin/wov-env b/bin/wov-env
--- a/bin/wov-env
+++ b/bin/wov-env
@@ -7,10 +7,13 @@ export WOV_BASEDIR
 
 
 if [ "$WOV_BASEDIR" == "" ]; then
-  echo "ERROR: not in wovtools project."
+  echo "ERROR: not in wovtools project (no git)."
   exit 1
 elif [ ! -e "$WOV_BASEDIR/wovtools" ]; then
-  echo "ERROR: not in wovtools project."
+  echo "ERROR: not in wovtools project (no wovtools directory)."
+  exit 1
+elif [ ! -e "${WOV_BASEDIR}/wovtools/config.json" ]; then
+  echo "ERROR: not in wovtools project (no wovtools/config.json file)."
   exit 1
 fi
 
@@ -70,61 +73,58 @@ WOV_DEVMODE=
 
 #set -x 
 # vars from git, if in project directory
-if [ -e "${WOV_BASEDIR}/wovtools/config.json" ]; then
-  RANGIT=1
-  WOV_PVER=$(git rev-list --count $(git rev-parse --abbrev-ref HEAD))
-  WOV_SVER=$(cd ${WOV_BASEDIR}/wovtools/secrets && git rev-list --count $(git rev-parse --abbrev-ref HEAD))
-  # WOV_USER=$(git config user.email | cut -d@ -f1)
-  WOV_USERNAME=$(git config user.name)
-  WOV_USEREMAIL=$(git config user.email)
-  export WOV_PVER
-  export WOV_SVER
+WOV_PVER=$(git rev-list --count $(git rev-parse --abbrev-ref HEAD))
+WOV_SVER=$(cd ${WOV_BASEDIR}/wovtools/secrets && git rev-list --count $(git rev-parse --abbrev-ref HEAD))
+# WOV_USER=$(git config user.email | cut -d@ -f1)
+WOV_USERNAME=$(git config user.name)
+WOV_USEREMAIL=$(git config user.email)
+export WOV_PVER
+export WOV_SVER
 #  export WOV_USER
-  export WOV_USERNAME
-  export WOV_USEREMAIL
+export WOV_USERNAME
+export WOV_USEREMAIL
 
-  # TODO:  optimize the jq calls into one, returning an array
-  #A=( `jq -r ". | ( .rootdir, .srcdir, .secretsdir, .compileddir, .containerdir, .registry, .wovtools )" ${dir_wovtools_rc}/.wovtools.json` )
-  #echo "A:${A[*]}:A"
-  #dir_root="${A[0]}"
+# TODO:  optimize the jq calls into one, returning an array
+#A=( `jq -r ". | ( .rootdir, .srcdir, .secretsdir, .compileddir, .containerdir, .registry, .wovtools )" ${dir_wovtools_rc}/.wovtools.json` )
+#echo "A:${A[*]}:A"
+#dir_root="${A[0]}"
 
-  WOV_PVERSION=$(cat ${WOV_BASEDIR}/wovtools/config.json | jq -r '.ver')
-  if [ "${WOV_PVERSION}" != "${WOV_VERSION}" ] && [ "${WOV_PVERSION}" != "initing" ] ; then
-    printf "\n\nERROR: Your project version '${WOV_PVERSION}', does not match to the WovTools version '${WOV_VERSION}'.\n\n"
-    exit 1
-  fi
-
-  WOV_WPROJECT=$(cat ${WOV_BASEDIR}/wovtools/config.json | jq -r '.project.project') 
-  WOV_PROJECTTYPE=$(cat ${WOV_BASEDIR}/wovtools/config.json | jq -r '.project.type') 
-  WOV_PROJECTTITLE=$(cat ${WOV_BASEDIR}/wovtools/config.json | jq -r '.project.title') 
-  WOV_PROJECTDESCRIPTION=$(cat ${WOV_BASEDIR}/wovtools/config.json | jq -r '.project.description') 
-  export WOV_WPROJECT
-  export WOV_PROJECTTYPE
-  export WOV_PROJECTTITLE
-  export WOV_PROJECTDESCRIPTION
-
-  WOV_ARCHIVEREPOSITORY=$(cat ${WOV_BASEDIR}/wovtools/config.json | jq -r '.archive.repository') 
-  WOV_ARCHIVEENV=$(cat ${WOV_BASEDIR}/wovtools/config.json | jq -r '.archive.env') 
-  export WOV_ARCHIVEREPOSITORY
-  export WOV_ARCHIVEENV
-
-  WOV_GSTAGE=$(git rev-parse --abbrev-ref HEAD)
-  WOV_STAGE=$WOV_GSTAGE
-    # GSTAGE has priority since it can represent <initials>-local, for local namespaces.
-  export WOV_GSTAGE
-  export WOV_STAGE
-
-  # Set DEVMODE 
-  if [[ ${WOV_GSTAGE} == "${WOV_KSTAGE}-l" ]]; then
-    WOV_DEVMODE=local
-  elif [[ ${WOV_GSTAGE} == "${WOV_KSTAGE}-v" ]]; then
-    WOV_DEVMODE=virtual
-  fi
-  export WOV_DEVMODE
-
-  WOV_PROJECT=${WOV_WPROJECT}
-  export WOV_PROJECT
+WOV_PVERSION=$(cat ${WOV_BASEDIR}/wovtools/config.json | jq -r '.ver')
+if [ "${WOV_PVERSION}" != "${WOV_VERSION}" ] && [ "${WOV_PVERSION}" != "initing" ] ; then
+  printf "\n\nERROR: Your project version '${WOV_PVERSION}', does not match to the WovTools version '${WOV_VERSION}'.\n\n"
+  exit 1
 fi
+
+WOV_WPROJECT=$(cat ${WOV_BASEDIR}/wovtools/config.json | jq -r '.project.project') 
+WOV_PROJECTTYPE=$(cat ${WOV_BASEDIR}/wovtools/config.json | jq -r '.project.type') 
+WOV_PROJECTTITLE=$(cat ${WOV_BASEDIR}/wovtools/config.json | jq -r '.project.title') 
+WOV_PROJECTDESCRIPTION=$(cat ${WOV_BASEDIR}/wovtools/config.json | jq -r '.project.description') 
+export WOV_WPROJECT
+export WOV_PROJECTTYPE
+export WOV_PROJECTTITLE
+export WOV_PROJECTDESCRIPTION
+
+WOV_ARCHIVEREPOSITORY=$(cat ${WOV_BASEDIR}/wovtools/config.json | jq -r '.archive.repository') 
+WOV_ARCHIVEENV=$(cat ${WOV_BASEDIR}/wovtools/config.json | jq -r '.archive.env') 
+export WOV_ARCHIVEREPOSITORY
+export WOV_ARCHIVEENV
+
+WOV_GSTAGE=$(git rev-parse --abbrev-ref HEAD)
+WOV_STAGE=$WOV_GSTAGE
+  # GSTAGE has priority since it can represent <initials>-local, for local namespaces.
+export WOV_GSTAGE
+export WOV_STAGE
+
+# Set DEVMODE 
+if [[ ${WOV_GSTAGE} == "${WOV_KSTAGE}-l" ]]; then
+  WOV_DEVMODE=local
+elif [[ ${WOV_GSTAGE} == "${WOV_KSTAGE}-v" ]]; then
+  WOV_DEVMODE=virtual
+fi
+export WOV_DEVMODE
+
+WOV_PROJECT=${WOV_WPROJECT}
+export WOV_PROJECT
 
 export K8S_CONTEXT
 export WOV_CLUSTER
@@ -155,28 +155,25 @@ function fDoEcho()
   echo WOV_FLAVOR="$WOV_FLAVOR"
   echo WOV_PROJECT="$WOV_PROJECT"
   echo WOV_KSTAGE="$WOV_KSTAGE"
-  if [ "$RANGIT" == "1" ]; then
-    echo WOV_GSTAGE="$WOV_GSTAGE"
-    echo WOV_STAGE="$WOV_STAGE"
-  fi
+  echo WOV_GSTAGE="$WOV_GSTAGE"
+  echo WOV_STAGE="$WOV_STAGE"
   echo WOV_DEVMODE="${WOV_DEVMODE}"
   if [ "$RANCLUSTER" == "1" ]; then
     echo CL_REGION="$CL_REGION"
     echo CL_ZONES="${CL_ZONES}"
   fi
-  if [ "$RANGIT" == "1" ]; then
-    echo WOV_PVER="$WOV_PVER"
-    echo WOV_SVER="$WOV_SVER"
+
+  echo WOV_PVER="$WOV_PVER"
+  echo WOV_SVER="$WOV_SVER"
 #    echo WOV_USER="$WOV_USER"
-    echo WOV_USERNAME="$WOV_USERNAME"
-    echo WOV_USEREMAIL="$WOV_USEREMAIL"
-    echo WOV_PROJECT="$WOV_PROJECT"
-    echo WOV_PROJECTTYPE="$WOV_PROJECTTYPE"
-    echo WOV_PROJECTTITLE="$WOV_PROJECTTITLE"
-    echo WOV_PROJECTDESCRIPTION="$WOV_PROJECTDESCRIPTION"
-    echo WOV_KPROJECT="$WOV_KPROJECT"
-    echo WOV_WPROJECT="$WOV_WPROJECT"
-  fi
+  echo WOV_USERNAME="$WOV_USERNAME"
+  echo WOV_USEREMAIL="$WOV_USEREMAIL"
+  echo WOV_PROJECT="$WOV_PROJECT"
+  echo WOV_PROJECTTYPE="$WOV_PROJECTTYPE"
+  echo WOV_PROJECTTITLE="$WOV_PROJECTTITLE"
+  echo WOV_PROJECTDESCRIPTION="$WOV_PROJECTDESCRIPTION"
+  echo WOV_KPROJECT="$WOV_KPROJECT"
+  echo WOV_WPROJECT="$WOV_WPROJECT"
 }
 
 # TODO: fill this function in, and remove from WIAAS
diff --git a/bin/wov-service b/bin/wov-service
--- a/bin/wov-service
+++ b/bin/wov-service
@@ -2,6 +2,7 @@
 
 DOECHO=1
 DOFORCE=0
+DIDRUN=0
 FOLD=100
 CURSERVICE=""
 RETVAL=0
@@ -17,7 +18,7 @@ set ""
 set -- "${pushenvargs[@]}"
 
 
-#set -x
+# set -x
 
 
 # ---------------------------------------------------------------------
@@ -31,11 +32,11 @@ usage: `basename $0` [options]
 
 Runs, tests or kills a local running service for this project. These commands are run in order.
 
-  -s service : Sets the name of the service (look for in wovtools/services/SERVICE.sh)
+  -s service : Sets the name of the service (look for in wovtools/services/SERVICE)
   -r : run the service if test fails 
   -R : run without testing
-  -t : test the service (if error code returned, fails) (./wovtools/services/SERVICE-test.sh)
-  -k : kill the service (./wovtools/services/SERVICE-kill.sh)
+  -t : test the service (if error code returned, fails) (./wovtools/services/SERVICE-test)
+  -k : kill the service (./wovtools/services/SERVICE-kill)
   -h : this help
   -q/-v : quiet/verbose
 
@@ -45,9 +46,11 @@ EOF
 function doTest()
 {
   if [ ${DOECHO} -ge 2 ]; then echo "...test"; fi
-  if [ -e ${WOV_BASEDIR}/wovtools/services/${DOSERVICE}-test.sh ]; then
-    OUTIS=$(${WOV_BASEDIR}/wovtools/services/${DOSERVICE}-test.sh)
+  if [ -e ${WOV_BASEDIR}/wovtools/services/${DOSERVICE}-test ]; then
+    echo 1
+    OUTIS=$(${WOV_BASEDIR}/wovtools/services/${DOSERVICE}-test)
     RETVAL=$?
+    echo 2
   else
     if [ ${DOECHO} -ge 2 ]; then echo "  ...no test script for '${DOSERVICE}'"; fi
     OUTIS=""
@@ -59,19 +62,22 @@ function doTest()
     echo "ERROR: failed test '${DOSERVICE}'."
     echo
   fi
+  DIDRUN=1
 }
 
 function doRun()
 {
   if [ ${DOECHO} -ge 2 ]; then echo "...run"; fi
-  ${WOV_BASEDIR}/wovtools/services/${DOSERVICE}.sh
+  ${WOV_BASEDIR}/wovtools/services/${DOSERVICE}
+  DIDRUN=1
   RETVAL=$?
 }
 
 function doKill()
 {
   if [ ${DOECHO} -ge 2 ]; then echo "...kill"; fi
-  ${WOV_BASEDIR}/wovtools/services/${DOSERVICE}-kill.sh
+  ${WOV_BASEDIR}/wovtools/services/${DOSERVICE}-kill
+  DIDRUN=1
   RETVAL=$?
 }
 
@@ -97,10 +103,14 @@ while [[ $1 =~ ^- ]]; do
   elif [ "$1" == "-R" ]; then
     shift
     DOFORCE=1
+    DOSERVICE="$1"
+    shift
     doRun
     DOFORCE=0
 
   elif [ "$1" == "-r" ]; then
+    shift
+    DOSERVICE="$1"
     shift
     doTest
     if [ "${RETVAL}" != "0" ]; then doRun; fi
@@ -125,6 +135,12 @@ while [[ $1 =~ ^- ]]; do
     exit 1
   fi
 done
+
+if [ "${DIDRUN}" == "0" ]; then
+  printf "\n\nERROR: you did not call any services.\n"
+  fDisplayOptions
+  exit 1
+fi
 
 exit ${RETVAL}
 
