Bit better error messages, resource naming error catching and added EUndef for printing undefined when no data present.

diff --git a/bin/wov-env b/bin/wov-env
--- a/bin/wov-env
+++ b/bin/wov-env
@@ -420,7 +420,7 @@ function fConfGeneration()
       R=( $(node -e "console.log((new (require('${MSCFILE}'))())._genK8SSecrets())") )
       RR=$?
     fi
-    if [ "${RR}" != "0" ]; then echo "ERROR: failed to generate '${1}' config from NodeJS source code."; exit 1 ; fi
+    if [ "${RR}" != "0" ]; then echo "ERROR: failed to generate '${1}' config from NodeJS source code: ${MSCFILE}"; exit 1 ; fi
 
   elif [ -e "${WOV_BASEDIR}/src/${1}config.js" ]; then
     MSCFILE="${WOV_BASEDIR}/src/${1}config.js"
@@ -431,22 +431,22 @@ function fConfGeneration()
       R=( $(node -e "console.log((new (require('${MSCFILE}'))())._genK8SSecrets())") ) 
       RR=$?
     fi
-    if [ "${RR}" != "0" ]; then echo "ERROR: failed to generate '${1}' config from NodeJS source code."; exit 1 ; fi
+    if [ "${RR}" != "0" ]; then echo "ERROR: failed to generate '${1}' config from NodeJS source code: ${MSCFILE}"; exit 1 ; fi
 
   elif [ -e "${WOV_BASEDIR}/${1}/src/${1}config.sh" ]; then
     MSCFILE="${WOV_BASEDIR}/${1}/src/${1}config.sh"
     R=( $(${MSCFILE} $2) )
     RR=$?
-    if [ "${RR}" != "0" ]; then echo "ERROR: failed to generate '${1}' config from NodeJS source code."; exit 1 ; fi
+    if [ "${RR}" != "0" ]; then echo "ERROR: failed to generate '${1}' config from NodeJS source code: ${MSCFILE}"; exit 1 ; fi
 
   elif [ -e "${WOV_BASEDIR}/src/${1}config.sh" ]; then
     MSCFILE="${WOV_BASEDIR}/src/${1}config.sh"
     R=( $(${MSCFILE} $2) )
     RR=$?
-    if [ "${RR}" != "0" ]; then echo "ERROR: failed to generate '${1}' config from NodeJS source code."; exit 1 ; fi
+    if [ "${RR}" != "0" ]; then echo "ERROR: failed to generate '${1}' config from NodeJS source code: ${MSCFILE}"; exit 1 ; fi
 
   else
-    (>&2 printf "\nERROR: could not find '${1}config.js'. Should be in ./src or ./${1}/src.\n\n")
+    (>&2 printf "\nERROR: could not find '${1}config.(js|sh)'. Should be in ./src or ./${1}/src.\n\n")
     exit 1
   fi
 
